### ISSUE TITLE
DB exception occur after detach and attach DID repeatedly

### ISSUE THREAD

**Issue by ghost** [rucio/rucio#1004]
Motivation
----------
After detach, an entry will add into table contents_history. If one attach and detach it again, a same entry can not add into table because of primary key constrain. As a result, the DID can never be detached .

Modification
------------

**Comment by bari12** [comment]
This should probably be fixed by doing a MERGE INSERT into the history table. That should solve the issue. It's not high priority though 😄 
Thanks for the report.
