### ISSUE TITLE
flake8 package update to 3.5.0

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#1012]
Motivation
----------
Update to the latest version of flake8(3.5.0) but with it, we have:

```
$ flake8 lib/|wc
     181    1262   12472
```
Mostly  `E722 do not use bare except`. If we ignore this error, we are let with:

```
lib/rucio/tests/test_did.py:385:9: E741 ambiguous variable name 'l'
lib/rucio/client/dq2client.py:1445:13: E741 ambiguous variable name 'l'
lib/rucio/client/dq2client.py:1446:16: E741 ambiguous variable name 'l'
```
Modifcation
------------
- Ignore  E722 in `.flake8` for now
- Fix E741

**Comment by bari12** [comment]
This is a duplicate of #195

**Comment by bari12** [comment]
Perhaps we should create a second issue so we fix the E722 eventually and don't completely forget about them.

**Comment by vingar** [comment]
yes +1
