### ISSUE TITLE
kill download/upload after expiration of transfer timeout

### ISSUE THREAD

**Issue by nikmagini** [rucio/rucio#1055]
Motivation
----------
rucio download/upload support the option --transfer-timeout (see issue #27 ) but this is not implemented in all protocols; and even for supported protocols (e.g. gfal) the underlying process can get stuck

Modification
------------
For all protocols implement a watcher process in the rucio downloadclient/uploadclient libraries that kills the transfer after the transfer_timeout expiration.

**Comment by nikmagini** [comment]
See https://github.com/PanDAWMS/pilot/blob/master/TimerCommand.py for an example implementation of a timeout wrapper

**Comment by bari12** [comment]
As discussed in the development meeting on [2019-01-10](https://indico.cern.ch/event/778899/) - Investigate if it is a possibility to kill e.g. gfal threads via a watcher thread.

**Comment by TWAtGH** [comment]
Maybe its worth to check if you can use the gfal context object in a watcher thread to abort the download.
The Gfal2Context object has a method called cancel that 'cancels running operations'. 
```
>>> import gfal2
>>> gfal2.Gfal2Context.cancel
<unbound method Gfal2Context.cancel>
```

**Comment by bari12** [comment]
Is there any update on this? It's quite high priority as that happens quite often on the grid.

**Comment by nikmagini** [comment]
> 
> 
> Maybe its worth to check if you can use the gfal context object in a watcher thread to abort the download.
> The Gfal2Context object has a method called cancel that 'cancels running operations'.
> 
> ```
> >>> import gfal2
> >>> gfal2.Gfal2Context.cancel
> <unbound method Gfal2Context.cancel>
> ```

Thanks for the tip - unfortunately, I Tried gfal2.Gfal2Context.cancel (on a root:// --> file:// transfer from EOS) but it blocks until the transfer is completed so it looks useless for cancelling a stuck transfer in general...

From what I see, async cancel is implemented only for gridftp  - I'll double-check with gfal devs

**Comment by nikmagini** [comment]
> From what I see, async cancel is implemented only for gridftp - I'll double-check with gfal devs

On the other hand, gfal cancel worked fine on gridftp and http transfers in my tests. Checking with gfal devs what's wrong with xrootd cancel.

**Comment by bari12** [comment]
Thanks Nikolo! Let's check with gfal devs about it, but unless we cannot cancel consistently all (or the at least the major) protocols, I think we have to look for another way. Let's discuss this in the dev meeting tomorrow.

**Comment by nikmagini** [comment]
Andrea Manzi commented that it looks like a gfal issue with xrootd cancel. Anyway for the other protocols it seems to work, for now I've submitted a pull request to implement it 

(note - currently it won't do anything due to a bug in propagation of transfer_timeout in the client- submitting a separate bug report)
