### ISSUE TITLE
Client : rucio list-file-replicas doesn't work for RSE expression

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1056]
Motivation
----------
rucio list-file-replicas --rse <RSE EXPRESSION> doesn't return anything whereas specifying explicitly the RSE vname works

Modification
------------
Fix list-file-replicas to support RSE expression

**Comment by nikmagini** [comment]
Hi @cserf 

rucio list-file-replicas already has the --expression option to pass RSE expressions - does it do what you need?

Cheers
N.

**Comment by cserf** [comment]
Yes, that's it. Closing the ticket.
