### ISSUE TITLE
documention: add link on AUTHORS from CONTRIBUTING.rst

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#106]

**Comment by gumond** [comment]
Hi, 

I just tried the "AUTHORS" link from:
 http://rucio.readthedocs.io/en/latest/contributing.html#

and it took me here: 
http://rucio.readthedocs.io/en/latest/AUTHORS.rst

Saying that the page does not exist. Should:
_\`AUTHORS \<AUTHORS.rst \>\`_
become something like : 
_\`AUTHORS \<https://github.com/rucio/rucio/blob/master/AUTHORS.rst \> \`_
or
_\`AUTHORS \<../AUTHORS.rst \>\`_

?
Cheers, 
Jaroslav

**Comment by mlassnig** [comment]
It should point to `https://rucio.readthedocs.io/en/latest/authors.html`
