### ISSUE TITLE
list-rules CLI should give a warning if it does not find a rule but looks on content of a container/DS

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1077]
Motivation
----------
If list-rules does not find a rule for a DID it automatically looks for rule on the content of a DID. The CLI should at least give a warning when it does this.

**Comment by MaisamMD** [comment]
Hi,

I am not completely sure my problem belongs to this issue. For some files on the data lake when I use 
`$rucio list-rules
`
the output does not have any information (only the title of the columns). I do not know where does the problem come from. Is there any idea about that?

Cheers,
Maisam
