### ISSUE TITLE
Error message for unregistered users in webui is ATLAS specific

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#1109]
Motivation
----------
The error message shown to unregistered users in the webui always points to ATLAS voms.

Modification
------------
Make the message configurable.

**Comment by deutranium** [comment]
Hi @tbeerman can I take this up?

**Comment by DhruvSondhi** [comment]
Hello @tbeerman, I had a small query about the configuration of the message. What type of attributes or fields may be required in the message so as to make it modified for a particular user? & what may be the intended output for the same? I do understand that we don't wish to direct the user to the ATLAS Vom directly, but I failed to understand the configurational side of the issue 😶

**Comment by bari12** [comment]
Hi,
I think it would be best if the entire message is configurable. I mean this part:
```
First, please make sure it is correctly registered in <a href=\"https://voms2.cern.ch:8443/voms/atlas\">VOMS</a> and be patient until it has been fully propagated through the system.
```
So not only the URL, just the entire message.

**Comment by DhruvSondhi** [comment]
Hello @bari12, What does Configurable means in this context? I am failing to understand the meaning. I do understand where the change is needed but I am not able to understand what outcome is being expected from the same? Is it in relation to how we need the user to be redirected somewhere else? or Is it something else altogether? 🤔

**Comment by bari12** [comment]
Configurable in a sense that the message is read from a config file (The WebUI does this in other places) and it can be changed there. The reason is that different institutions run their own Rucio instances, but the message (hardcoded) points them to `https://voms2.cern.ch:8443/voms/atlas` - which will only work for ATLAS.

**Comment by rak108** [comment]
@bari12 shouldnt the line after also be configurable? the DDM support email given is specifically for ATLAS right?

**Comment by DhruvSondhi** [comment]
@rak108 I have made that configurable too ... I was thinking of making it very much configurable that based on the id the relevant email id can be called upon for the same organisation

**Comment by rak108** [comment]
@DhruvSondhi but it has to be read from the config file right

**Comment by DhruvSondhi** [comment]
Doesn't matter ... It can be directly be specified by the organisation ... I was trying to make its organisation specific ... simple inputs  can be changed according to the organisation to let have it accordingly
