### ISSUE TITLE
exit quickly on dependency problem

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#112]
If we fail on importing necessary dependencies like gfal, we end up in very long timeouts later in the workflow. We should exit quickly if dependencies are not available.

**Comment by bari12** [comment]
Needs to be discussed with Paul

**Comment by mlassnig** [comment]
Try to figure out where the earliest possible exit in the codepath is.

**Comment by TWAtGH** [comment]
For the upload one of the first things we do is query the rse information:
https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L111
So directly afterwards we could check if any protocol implementation is available
