### ISSUE TITLE
lifetime field for rule creation should be pre-filled with 180 days

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1127]
Motivation
----------
Right now the lifetime field default is empty, thus resulting in infinite rules (Except for SCRATCHDISK rules where it is 15 days). This should be changed to 180 days per default (except for SCRATCHDISK, where it should stay with 15)

**Comment by afortiorama** [comment]
When is this going in production? UI is still on 1.16.0. I thought this would be quicker.

**Comment by bari12** [comment]
The usual release cycle is 2 weeks. However, we did not deploy 1.16.1 due to a problem, thus we are still on 1.16.0
1.16.2 will be deployed tomorrow.
