### ISSUE TITLE
Raise an exception in case of server timeout

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1152]
Motivation
----------
It looks like when the server times out, no exception is raised to the client

Modification
------------
Raise a new TimeOut exception

**Comment by cserf** [comment]
Up

**Comment by hahahannes** [comment]
Some observations I made with a simluated timeout in the API:

1. Using a 60s TimeOut:
Apache times out after 60s and returns a 502 Proxy error. 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head>
        <title>502 Proxy Error</title>
    </head>
    <body>
        <h1>Proxy Error</h1>
        <p>The proxy server received an invalid
response from an upstream server.
            <br />
The proxy server could not handle the request
            <em>
                <a href="/proxy/rses/MOCK5">GET&nbsp;/proxy/rses/MOCK5</a>
            </em>.
            <p>
Reason: 
                <strong>Error reading from remote server</strong>
            </p>
        </p>
    </body>
</html>
```
Strangely this occurred only with postman in my test but not with the client. The client received the correct response.

2. Using a 600s TimeOut: 
The default timeout in the base client is 600s. The client raises a requests TimeOut exception which does not get catched. 

I think it would make sense to change the default timeout in the base client to 60s and to catch the TimeOut exception to then raise an own TimeOut exception ?
But I could not reproduce a case where the client interprets a request successfully when there was a timeout.

**Comment by bari12** [comment]
Just to follow up on this in the github-a-thon. Could you maybe try to generate a case where HTTP streaming is used?
I could imagine a workflow where:
- Client and server communicate via python requests with the streaming parameter.
- As the header (of a stream) is sent first, it might be a HTTP 200
- During the stream (even if is just one line) an exception might occur and actually kill the DB session.
- This could still be interpreted as a HTTP 200, as this was sent in the header first.
Now, most POST calls where a timeout matters do not really stream much, but we should check if this can still happen if it is requested via python requests.

**Comment by bari12** [comment]
@mlassnig @TomasJavurek please have a look if we can still do anything with this one. If you thik it's not relevant anymore, please close

**Comment by mlassnig** [comment]
Needs some real-world observables, now with things on Flask
