### ISSUE TITLE
Resurrect method should remove expiration date of dataset if it is not deleted yet

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#116]
Motivation
----------
Sometimes datasets are resurrected which are already expired but not deleted yet. In this case the call does not do anything, and the dataset will be deleted at a later point in time.

Modification
------------
Change resurrect method to remove expiration date of dataset.

**Comment by vingar** [comment]
Raising UnsupportedOperation looks also a good option if the expiration date < now

**Comment by bari12** [comment]
Right now, DataidentifierNotFound is raised in these cases, and I think we can keep it the same. This is really only for the case where a dataset is not deleted yet, but logically, it already should be.
