### ISSUE TITLE
Allow upload of replicas to non-det RSEs by users

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1172]
Motivation
----------

The functionality we have for event-service in rucio upload --pfn requires --no-register. For non-det RSEs we can relax this restriction and allow users to directly rucio upload there.

**Comment by TomasJavurek** [comment]
I discussed this a bit with Tobi already yesterday, can I have a look?

**Comment by bari12** [comment]
Yes! Thanks a lot @TomasJavurek
