### ISSUE TITLE
FTS3 transfertool: proxy delegation function

### ISSUE THREAD

**Issue by dciangot** [rucio/rucio#1177]
Motivation
----------
Avoid using cronjobs for periodically delegating proxy to FTS3 and, more generally, make delegation function available within the daemons. 

Modification
------------
Include fts3 proxy delegation function in fts3 transfertool using fts3 python bindings.

**Comment by rcarpa** [comment]
Should we re-open this one ?

**Comment by rcarpa** [comment]
@dchristidis
