### ISSUE TITLE
RSE manager: remove .part from filename if adler32 is set and ignore_checksum is true

### ISSUE THREAD

**Issue by TWAtGH** [rucio/rucio#1185]
Motivation
----------
rsemanager.download, downloads the file as <filename>.part if an adler32 checksum is given.
If ignore_checksum is set to True the file will not be renamed thus the .part will not be removed from the file name.

Modification
------------
Make the  os.rename call independent of ignore_checksum

**Comment by bari12** [comment]
@berghaus You recently did some changes in this code I think. Can you maybe have a look on this issue? 😃
