### ISSUE TITLE
Core: track account of usage and interests per DID (dataset) and account

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#121]
Motivation
----------
For the lifetime model, it would be good to expose simply who(account) uses a dataset(did) and the last time of access.
Another requirement is to provide a way for users to express their interest for DIDs and  use it wrt to the lifetime model and the list of future deleted data.

Modification
------------

Extend models with two tables.

consumers/leechers:
scope, name, account, created_at_ updated_at, hits

to keep track of the number of access, the first access and last access for an account to a specific dataset. Populated from the traces. core only needed.

followers:
scope, name, account, created_at_ updated_at, expired_at

to keep track of people interest for a dataset. This will need clients, rest, core.

**Comment by bari12** [comment]
Lets discuss in the next dev meeting. The interest part sounds a bit redundant to the lifetime exceptions to me.

**Comment by bari12** [comment]
Just to note what we discussed in the meeting. We decided to follow up with DAST what they think of the idea and then move from there.

**Comment by bari12** [comment]
Lets try to discuss with them in Hamburg

**Comment by bari12** [comment]
Decided to keep it; Possibly a student project.

**Comment by pujanm** [comment]
Can I work on solving this issue?

**Comment by bari12** [comment]
Hi @pujanm 
Yes, this can be (part) of your gsoc project. Let's discuss this on Slack, so you can put together a proposal.

**Comment by bari12** [comment]
Duplicate #2304
