### ISSUE TITLE
ignore_availabilty parameter in list_replicas is not working

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1213]
Motivation
----------
The recovery doesn't take into account the replicas on sites blacklisted for read. If a file is declared bad, and is not recoverable because the only remaining site where it is located is blacklisted for read, the necromancer should declare the file as recoverable and not as definitely lost.

**Comment by cserf** [comment]
After checking the code, the necromancer do it the proper way. The problem is actually due to the fact that the ignore_availabilty flag that is in the signature of the list_replicas method is not working, so reassign the ticket to core.

**Comment by leoank** [comment]
Hi,
~I am looking for an issue to work on for GSoC. Can I start working on this one?~
Ignore this. Just read your msg on the slack channel. I'll start working on it now.

**Comment by leoank** [comment]
Also, do we have any failing tests for this specific issue or a reproducible example?

**Comment by bziemons** [comment]
I don't think so, no. Please create one, if possible.
