### ISSUE TITLE
New option for rucio list-rse-usage to list usage per account

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1218]
Motivation
----------
rucio list-rse-usage returns the RSE usage from different sources (Rucio, storage, expired). It would be good to have an option to list the usage per account.

**Comment by bari12** [comment]
So basically list-account-usage, but instead of per-user account per-rse?

**Comment by cserf** [comment]
Yes

**Comment by jegarcian** [comment]
Hi,
is it available in lxplus? how can I use it? Thanks,

Best,
  Jose

**Comment by bari12** [comment]
It is as TESTING, so you have to install the testing release with lsetup
There is a new option for list-rse-usage: --show-accounts

**Comment by jegarcian** [comment]
> It is as TESTING, so you have to install the testing release with lsetup
> There is a new option for list-rse-usage: --show-accounts

Great!! Thanks! Just a detail, is there a way to get the response in a different format? Thanks again,
Jose

**Comment by bari12** [comment]
I am sure we can change the formatting a bit. What would be your suggestion?

**Comment by jegarcian** [comment]
> I am sure we can change the formatting a bit. What would be your suggestion?

I was just thinking about a line per user instead. I can parse the current output easily but just wondering if that was possible. Thanks again,

**Comment by bari12** [comment]
Oh, I thought it is already 1 line per account, but I just tried it and saw that it is multiple lines. We will fix that and make it one line per account. Will be fixed in #1672
