### ISSUE TITLE
wrong error message in clients

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1223]
Motivation
----------
From @sartiran

`[root@c79d3ace2f51 /]# rucio ping`
`2018-06-03 21:02:40,634 ERROR   Cannot authenticate.`
`Details: HTTPSConnectionPool(host='rucio-cms.grid.uchicago.edu', port=443): Max retries exceeded with url: /auth/x509_proxy (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_CERTIFICATE_EXPIRED] sslv3 alert certificate expired (_ssl.c:579)'),))`
`2018-06-03 21:02:40,635 ERROR   Please verify that your proxy is still valid and renew it if needed.`
`[root@c79d3ace2f51 /]#`

Modification
------------
This error has nothing to do with the client proxy, it's the server certificate that expired.

**Comment by bari12** [comment]
Pinging @hahahannes
