### ISSUE TITLE
add kubernetes config to repo

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#1226]
Motivation
----------
Make the current kubernetes config publicly available

Modification
------------

**Comment by lukasheinrich** [comment]
Hi -- 

can you also add a chart / manifest to show how to configure the client using the rucio/rucio-client image. I tried and failed by 

* bind mounting a `rucio.cfg`
* copying the ca.crt from ATLAS (`/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/rucio-clients/1.16.3/etc/ca.crt`) into `RUCIO_HOME/etc/ca.crt`
* setting a providing a proxy file and setting X509_USER_PROXY, RUCIO_AUTH_TYPE and RUCIO_ACCOUNT env vars 

```
$> tree
.
├── etc
│   ├── ca.crt
│   └── rucio.cfg
└── x509up_u36923
$> docker run --rm -it -v $PWD:/tmp -e X509_USER_PROXY=/tmp/x509up_u36923 -e RUCIO_AUTH_TYPE=x509_proxy -e RUCIO_ACCOUNT=lheinric rucio/rucio-clients:latest bash
```

some files get downloaded but I also see some issues like

```
2018-06-12 22:24:59,842	INFO	Thread 1/2 : File group.phys-exotics:group.phys-exotics.14267504.XAMPP._000001.root trying from CA-WATERLOO-T2_SCRATCHDISK
2018-06-12 22:25:01,268	WARNING	The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Could not open source: Failure (Neon): Server certificate verification failed: issuer is not trusted after 1 attempts
```

**Comment by vingar** [comment]
The last error is more a storage issue. If you get `rucio ping` working it's most likely fine.

Otherwise, there is the image rucio-clients-atlas:

     https://hub.docker.com/r/rucio/rucio-clients-atlas/

If you are willing to test it, we can update it and update the instructions on dockerhub as well

**Comment by lukasheinrich** [comment]
Hi @vingar,

yes, I'm very happy to test an ATLAS use-case. For the ATLAS image, would you be willing to also add the X509 auth (e.g. `voms-proxy-init` etc such that inside the container one could do 

```
$> voms-proxy init --voms atlas
$> rucio download ...
```

In Kubernetes this could then be run as part of a `initContainer`

**Comment by vingar** [comment]
yes, that's doable. But to do `voms-proxy init --voms atlas` one should mount the .globus directory as well or the variables X509_USER_CERT X509_USER_KEY.

**Comment by lukasheinrich** [comment]
yes, my idea was to mount this via secrets. e.g. 

```
apiVersion: v1
kind: Secret
type: Opaque
data:
  gridpw: ...
  host.cert: ...
  privkey.pem: ...
metadata:
  name: atlas-auth
  namespace: default
```
