### ISSUE TITLE
rucio-admin  replicas declare-bad

### ISSUE THREAD

**Issue by afortiorama** [rucio/rucio#1245]
Motivation
----------
when I declare bad a huge amount of files ( for example when a machine cannot be recovered) it takes several hours and it is not possible to understand at what stage the declaration is. On occasion not all the files get declared as it has happened with Glasgow. Files were declared lost in December but some of them were still there yesterday and deletion failed and I had to reduclare lost >240,000 files.

https://ggus.eu/index.php?mode=ticket_info&ticket_id=135621

Modification
------------

It would be useful if this tool left wrote a log file with the number of files declared if the admin wants to or wrote to the output as part of the verbose when it does a commit. So if it declares lost 1000 files at the time it writes it has done those and if something fails it logs that too. So that it is possible to rerun only on the missing files instead of going through the whole lot. A summary at the end would also be useful.  For example as I imagine yesterday went from the output

241000 processed
233000 uknown replicas
3000 already declared
5000 declared bad

**Comment by bari12** [comment]
Hi Alessandra, I think that's possible, but maybe @cserf or @TomasJavurek can comment.

**Comment by afortiorama** [comment]
Hi,

any answer here? It seems that after declaring those 300k files lost 3 times, rucio still thinks it has them [1]. Unfortunately more than keeping on declaring all of them I cannot do in these conditions.

thanks

[1] https://its.cern.ch/jira/browse/ATLDDMOPS-5414?focusedCommentId=2135911&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2135911

**Comment by cserf** [comment]
Hi,

That's possible. I'll try to implement it next week.

Cheers,
Cedric

**Comment by cserf** [comment]
Cleaning old tickets. I think some of the suggestions were addressed. In addition, since we moved to asynchronous declaration, declaring large number of files should be much faster (@dchristidis can confirm).
There is one recent ticket that was opened to propose further optimization https://github.com/rucio/rucio/issues/3235 . I would propose to use it and close this one.
