### ISSUE TITLE
Possibility to filter collection on empty state

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1273]
Motivation
----------
Some users would be interested to filter out empty containers in list-dids, e.g. :
`rucio list-dids user.blah:blahblah --filter type=CONTAINER,empty=False`

**Comment by bari12** [comment]
We should really think about the syntax in `--filter`
In the meanwhile we could add a `--exclude-empty`

**Comment by alexarmstrongvi** [comment]
Has there been progress on this?

**Comment by bari12** [comment]
Hi Alex, no news on this. These days development time is thin as many people are on vacation and there were also some conferences and meetings in the last weeks. We will keep you posted in this ticket, but I don't have a specific ETA yet.

**Comment by alexarmstrongvi** [comment]
Understandable. Thanks for the reply.

**Comment by hahahannes** [comment]
Maybe it would be useful to implement the possibility to filter more generally. For example size.gt to filter out containers with a size greater than 0. And of course size.lt for less than.
```shell
rucio list-dids user:bla --filter size.gt=0,type=CONTAINER
```
