### ISSUE TITLE
Add top-level attribute EVENT_TYPE to messages

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1281]
Motivation
----------
Idea is to be able to make filters on the broker based on the EVENT_TYPE.

**Comment by vingar** [comment]
+ scope ?

**Comment by mlassnig** [comment]
`Scope` might make sense, I'll have a look.

**Comment by cserf** [comment]
Up

**Comment by cserf** [comment]
Can we increase the priority of this ticket ? It's mainly for AMI
