### ISSUE TITLE
dependencies: geoip2 forces requests>=2.9

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1302]
Motivation
----------
We have to default to requests>=2.6 because of the default yum-provided package. However, geoip2 forces requests>=2.9 breaking the install.

We could either downgrade geoip2, temporarily disable it, or switch to a different type of installation (venv, ...)

**Comment by bari12** [comment]
How far do we have to downgrade so it doesn't ask for the specific requests version?

**Comment by mlassnig** [comment]
Just the previous versoin (which is from 2015), but it's not on PyPI anymore. This is starting to get tricky.
