### ISSUE TITLE
upload doesn't add a new rule for a new replica if DID already exists

### ISSUE THREAD

**Issue by TWAtGH** [rucio/rucio#1304]
Motivation
----------
If the UploadClient is used to upload a new replica of a file DID (no dataset given) that is already registered, no rule will be updated or added.

Modification
------------

**Comment by TWAtGH** [comment]
We discussed this couple of times and it's still not clear if this is a bug or not. Can we discuss this on Thursday @cserf @TomasJavurek @bari12 ?

**Comment by bari12** [comment]
Could be an upload of a replica on a different rse (did exists) - This should add a rule on the RSEx

**Comment by bari12** [comment]
I am closing this now. I don't think there was any conclusion here, if needed we can reopen the ticket.
