### ISSUE TITLE
Incorrect configuration of rucio demo?

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#1334]
Motivation
----------
If I try to access the demo web ui, running with docker-compose on https://localhost/ui/, I get a 500 Internal Server error with the following error message from the error log:
```shell
[Wed Jul 11 11:48:51.199437 2018] [:error] [pid 9] [client 172.18.0.1:58702] Traceback (most recent call last):
[Wed Jul 11 11:48:51.199458 2018] [:error] [pid 9] [client 172.18.0.1:58702]   File "/usr/lib/python2.7/site-packages/rucio/web/ui/main.py", line 69, in <module>
[Wed Jul 11 11:48:51.199640 2018] [:error] [pid 9] [client 172.18.0.1:58702]     POLICY = config_get('policy', 'permission')
[Wed Jul 11 11:48:51.199657 2018] [:error] [pid 9] [client 172.18.0.1:58702]   File "/usr/lib/python2.7/site-packages/rucio/common/config.py", line 57, in config_get
[Wed Jul 11 11:48:51.199747 2018] [:error] [pid 9] [client 172.18.0.1:58702]     raise err
[Wed Jul 11 11:48:51.199782 2018] [:error] [pid 9] [client 172.18.0.1:58702] NoSectionError: No section: 'policy'
````
Modification
------------
It could be fixed by changing the etc/docker/demo/rucio.cfg file from:
```shell
[permission]
policy=demo
```
to
```shell
[policy]
permission=demo
``` 
But I am not sure, if this configuration is needed somewhere else or if the config reader in lib/rucio/web/ui/main.py should be changed instead.

**Comment by tbeerman** [comment]
The order of this configuration was changed some time in the past. So, what's currently in the demo rucio.cfg is wrong. Changing the config as file as you proposed will fix it. No need to fix the config reader.
