### ISSUE TITLE
fix uploading of ROOT files from docker client image 

### ISSUE THREAD

**Issue by lukasheinrich** [rucio/rucio#1351]
Motivation
----------

the rucio/rucio-atlas docker images are excellent to do basic get/put operations within a minimal environment. However uploading ROOT files fails because the pool_extractFileIdentifier is not found. I'm cross-referencing an issue on the ATLAS JIRA were I asked whether we can provide a statically linked version of it: 

https://its.cern.ch/jira/browse/ATLINFR-2530

Modification
------------

If we can get a statically linked binary presumably one could just add it to the image.

**Comment by lukasheinrich** [comment]
We looked at this and it looks like a pure statically linked binary is not possible, but perhaps we can provide a stripped down RPM that installs this binary.

Note though that this will require some additional dependencies (ROOT's libCore, boost, etc)

**Comment by lukasheinrich** [comment]
another option would be to add a configuration option that lists the extensions for which GUIDs are extracted. the default could be 

```
extractGUID_extensions: ["*.root"]
```

which could be set to 


```
extractGUID_extensions: []
```

**Comment by bari12** [comment]
This is a quite old ticket, but now with the ATLAS specific rucio docker clients, it's maybe worth to look into this again? @tbeerman ?

**Comment by rcarpa** [comment]
Hi @lukasheinrich , to celebrate the 3rd anniversary of this ticket, I'm giving it a look and try to decide on how to best solve the issue. 

I initially intended to substitute the call to the external executable with reading the File ID directly from the *.root files using uproot. Unfortunately, uproot relies on numpy as mandatory dependency. It doesn't seem right to add such a large dependency into rucio for an use-case serving only the high-energy-physics community.

You mention adding an option to the client which would allow to disable extracting the FID and, instead, generate a random one. Wouldn't it be problematic if somebody uploads root file with inconsistent ID to prod? 

A completely different possible solution is to maintain the current rucio code and create a small drop-in replacement for `pool_extractFileIdentifier` executable. Either using Golang (https://pkg.go.dev/go-hep.org/x/hep@v0.28.2/groot#section-sourcefiles) or a self-contained python pex (using uproot + numpy). And deploy this executable to the client container.

**Comment by bari12** [comment]
For uproot + numpy, I just meant I wouldn't want to include this to the default rucio package, but make it an extra. (`pip install rucio[uproot]`) For the atlas clients images we could add it like this.
But your other solution would off course work too.

**Comment by rcarpa** [comment]
I don't think there is any technical difficulty. Mostly a choice to me made. I would vote for the uproot solution; and only install uproot when needed

**Comment by bari12** [comment]
@lukasheinrich any opinions on this? 😄

**Comment by rcarpa** [comment]
Is a fix to this issue still needed ? Nobody answers anything

**Comment by bari12** [comment]
Let's close it, we can always reopen.
