### ISSUE TITLE
client_extract=True replicas need to be extracted from the zip file

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1354]
Motivation
----------
The client needs to check for replicas with client_extract=True and extract them.

**Comment by TWAtGH** [comment]
I'm going to disable multi threaded download in case that multiple files should be downloaded from the same archive (guess it's not too unlikely for datasets?)

How shall we handle the archive file? I have different approaches in mind:
A
1. download archive
2. extract file
3. go to 1. for next file

B
1. download archive
2. extract file
3. delete archive
4. go to 1. for next file

C
1. download archive if it doesn't exist
2. extract file
3. go to 1. for next file
4. delete all archives

Or any of these approaches with downloading archives into /tmp/...

**Comment by bbockelm** [comment]
How about never downloading the archives into `/tmp`?

1.  Sort all files needed by archive name.  This way, you only download each archive once.
2.
   *  If gfal2 module is present: For each archive needed, read the last 1MB of the archive, parse out the central directory of the zipfile, then read out only the bytes corresponding to files you need.
   *  If gfal2 module is not present: download whole archive to the output directory, then open with python, unlink the file, and start extracting the files needed.

Should be relatively straightforward to avoid downloading the whole archive in the end...

**Comment by TWAtGH** [comment]
Do I have the archive name?
This ticket should only handle the case when the protocol cannot stream the single file from an archive. I was told to use an external program like unzip in this case. ( @bari12 )

**Comment by TWAtGH** [comment]
Even if I had the archive name sorting would not be that easy because this would probably break the PFN order

**Comment by bari12** [comment]
Yes, only the actual local extract case should be handled here, streaming the content of the (uncompressed) zip is already handled in list_replicas.
The result of list_replicas (be it metalink or not) has the PFN of the archive.
Right now the loop is going logical file by file and then do the actual physical download. What you can do (Basically Brians suggestion) is to take the ones which only have replicas saying `client_extract=True` out, remove the duplicates from this list and only download these replicas. Afterwards you extract the files wanted (re-adding the logical files whose duplicate replicas you removed). I know this breaks the current simple "one loop solves it all" concept, but it shouldn't be all too complicated to add.

**Comment by TWAtGH** [comment]
Can't list_replicas return a file that has some PFNs with client_extract=True and some with False?
So if its always either True or False per file it should make things easier. But in this case client_extract should be a file attribute

**Comment by TWAtGH** [comment]
Otherwise I would be afraid of cases like:
```
<metalink>
  <file1>
    <url client_extract=True prio=1>same_archive_pfn</url>
    <url client_extract=False prio=2>pfn1</url>
  </file>
  <file2>
    <url client_extract=False prio=1>pfn2</url>
    <url client_extract=True prio=2>same_archive_pfn</url>
  </file>
</metalink>
```
You say in such cases I should skip the prio 1 pfn of file2 ?

**Comment by mlassnig** [comment]
@TWAtGH right now, client_extract is set per file (current decision is based purely on if protocol==root)

**Comment by bari12** [comment]
It should be set per replica. It's a valid case to have a file which has "normal" replicas but is also a constituent of an archive. Thus some replicas of this file would have client_extract=True some would not.
