### ISSUE TITLE
Fix activity in BB8

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1361]
Motivation
----------

BB8 uses activity `Data Rebalancing` but the activity defined in ATLAS schema is `Data rebalancing`. We should use the same activity everywhere, and it should be consistent with the share defined in FTS

**Comment by TomasJavurek** [comment]
This doesn't seem to be my fault:
with python 2.7:

CannotAuthenticate: Cannot authenticate.

**Comment by TomasJavurek** [comment]
Although it can be, that certain activities can be processed only by certain accounts, and travis had not the rights to run this activity?
