### ISSUE TITLE
rest/replica controllers do metalink inconsistently

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1382]
Motivation
----------
The Replicas controller creates the metalink output differently than the ListReplicas controller.

**Comment by mlassnig** [comment]
Replicas controller (== GET calls) is unused by the Rucio clients. We should deprecate it in the next feature release.

**Comment by mlassnig** [comment]
It's actually used by the ARC clients, cannot deprecate. Still needs deep-check if there are functionality differences between GET and POST

**Comment by bari12** [comment]
We keep it as it is, but should put comment in code.
