### ISSUE TITLE
extend download/upload for cloud checksums

### ISSUE THREAD

**Issue by berghaus** [rucio/rucio#140]
Motivation
----------
Cloud storage solutions have opted to use MD5 to verify file integrity. To support cloud storage and ensuring file integrity the MD5 digests of files added to the data catalogue should be computed.

Modification
------------
 - [x] Client computes md5 checksum on file upload and adds this to the file metadata
 - [x] Client download checks the file adler32 or md5 against the metadata - preference of adler32

Expected behavior
-----------------
The MD5 field of the file metadata in the Rucio database will be filled with the MD5 digest of the file for new files.

**Comment by mlassnig** [comment]
+1

**Comment by bari12** [comment]
Hi Frank, just to confirm (as nobody is assigned to this ticket): You are planning to implement this, right? 😃

**Comment by berghaus** [comment]
There is no one assigned to the ticket because I can't assign anyone. I am planning to implement this. Sorry about the long delay, I got absorbed by something else for a moment. Back at it now - starting with dealing with the repo reset ;-)

**Comment by bari12** [comment]
I just added you as collaborator for the repo :) You should be able to assign now.

**Comment by berghaus** [comment]
That worked, thanks!

**Comment by berghaus** [comment]
Going to work on #322 first to set up my dev environment (if you guys like the suggestions that is).
