### ISSUE TITLE
Add a --allow-tape option in rucio download

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1404]
Motivation
----------
`rucio download` does a check at the beginning to see if the account is an admin one in case the replica is on tape. It puts unneeded load on the servers.

Modification
------------
Propose to forbid any access to replicas on TAPE by defaut and add a `--alllowtape` option. If this option is set to True, then the admin check is done

**Comment by mlassnig** [comment]
suggestion: "--allow-tape" :-)
