### ISSUE TITLE
postgres requires ::text conversion of uuid for md5

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1446]
Motivation
----------

It seems that some PSQL instances do not autoconvert uuid to text when calling md5(). We can force the conversion, e.g., this line:
               `query = query.filter(text('mod(abs((\'x\'||md5(id))::bit(32)::int), %s) = %s' % (total_workers + 1, worker_number)))`
should actually be:
               `query = query.filter(text('mod(abs((\'x\'||md5(id::text))::bit(32)::int), %s) = %s' % (total_workers + 1, worker_number)))`

**Comment by illingwo** [comment]
I think I've found them all. rucio/core/account_counter.py also uses md5() on a uuid, but the concat function coerces its arguments to text anyway, so that one should be okay.
