### ISSUE TITLE
python3 pip install rucio-clients fails

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#1476]
After today's TCB talk I tried to install rucio clients in a python3 virtualenv, but it fails to find the "futures" dependency:

```
$ python --version
Python 3.6.5

$ pip install rucio-clients
Collecting rucio-clients
 [...]
Collecting futures>=3.2.0 (from rucio-clients)
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement futures>=3.2.0 (from rucio-clients) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures>=3.2.0 (from rucio-clients)
```
From what I can see this package is a python2 backport of a python3 native package so shouldn't be installed in python3.

**Comment by bari12** [comment]
I have updated #819 and will close this ticket. Right now the clients are compatible with Python 3.5 but fail with 3.6+.

**Comment by bari12** [comment]
Duplicate of #819
