### ISSUE TITLE
improve connection handling to broker

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1479]
Motivation
----------

This touches all modules using stomp.

- Replace dns.resolver with socket.getaddrinfo
- Remove obsolete TLS session parameter

**Comment by mlassnig** [comment]
- add vhost support

**Comment by illingwo** [comment]
I would probably be able to provide a pull request for this (although my ability to test anything is limited since I'm still trying to get it working at all).

**Comment by bari12** [comment]
We can test and confirm it. So if you want to provide the PR, please go ahead.

**Comment by illingwo** [comment]
I have this working (at least for the hermes and cache daemons, which are the only ones I'm currently using). But I have a question about IPv6 - the existing implementation doesn't use it since it only looked up the DNS A record. But getaddrinfo will return both unless instructed otherwise. For the time being I've forced IPv4 to keep the behaviour consistent, but that's not very future proof. Would it be better to use the v6 addresses if available? (I see atlas-mb.cern.ch does have them.)

**Comment by bbockelm** [comment]
I think there's standard policy and procedure we can follow:
- Use V6 if that's available.
- If not, use V4
- (Extra credit) If both V6 and V4 are available, then, after waiting for 150ms for the V6 connection to finish, opportunistically try a V4 connection as well.  Take the first one to successfully connect.
   - I think I've only seen this recommendation executed in big codebases, such as browsers.

I saw at the GDB today that 23% of LHC data is transported using IPv6; this suggests the simple case of "use first record available" is probably fine for most R&D networks.

**Comment by mlassnig** [comment]
After having so much trouble with IPv6 on the CERN network I consider the extra credit option as mandatory unfortunately.

**Comment by illingwo** [comment]
One problem in this case is with the multiple responses to the name lookup I don't think it's possible to match the 6 and 4 addresses for the same host. So you could easily end up connecting twice to the same broker, which doesn't seem like a good idea.

How about a disable IPv6 option? - it'd be simpler to implement.

**Comment by mlassnig** [comment]
That's perfectly viable. If we feel the need to support IPv6 properly down the line we can always do it.

**Comment by mlassnig** [comment]
@illingwo did you manage to progress on this? if you already have some lines of code written I can integrate them during our coding-camp next week

**Comment by illingwo** [comment]
I never got around to doing the IPv6 part. I can turn what I do have - IPv4 only with the system resolver - into a pull request.

**Comment by mlassnig** [comment]
Ok, cool! I'll take care of the ipv6 part then later on. Thanks!
