### ISSUE TITLE
parse_json not python3 compatible

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1490]
Motivation
----------

String responses cannot be decoded into UTF-8 in Python 3, since they're already UTF-8 by default. The function has been removed from the language.

Modification
------------

provided by @XeBoris

```
def parse_response(data):
   """ JSON render function
   """
   ret_obj = None
   try:
       ret_obj = data.decode('utf-8')
   except AttributeError:
       ret_obj = data
   
   return json.loads(ret_obj)
```

**Comment by bari12** [comment]
We should check if there is a common implementation to do this.
