### ISSUE TITLE
RSEManager functions give returns in different types

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1494]
Motivation
----------
E.g. the rsemanager.upload gives different returns if it is a bulk or a single upload, which crashes the uploadclient. See #1487 
This needs to be reworked there should be a single return type independent of the method being called in bulk or single upload/download/delete etc.

**Comment by TWAtGH** [comment]
The PR for `rsemgr.upload` was merged #1509 
`rsemgr.download` will be removed since it isn't used anymore.

**Comment by bari12** [comment]
Ok, Closing with reference to #1378
