### ISSUE TITLE
Mark replicas as temporarily unavailable

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1550]
Motivation
----------

> This comes up again for LRZ as we have a broken server. What is possible now, if we have a list of files to be marked temporarily unavailable? I am no longer pushing for rucio to know the pool info - a list produced by the site is fine, if it can be handled in bulk.
> Files marked unavailable would
> - not show up in list-replicas, also in --deep dataset replica lookup used by panda
> - mark complete datasets as not complete (panda uses complete replicas, to avoid file replica lookup)
> - not trigger recovery from other replicas

The critical part here is what happens with the replication rules touching these replicas. The state-consistent workflow would be, to set them to STUCK, but this would issue an immediate recovery of these replicas. Leaving the rules in OK state breaks somewhat the consistency of the state-machine and could lead to problems if admins forget to set these replicas back to AVAILABLE again. 

Modification
------------
- [ ] CLI command needed to operate over a list of replicas supplied in a txt file
- [ ] Replicas are marked as UNAVAILABLE
- [ ] Collection Replicas are updated respectively
- [ ] Reverse CLI command needed to make replicas and collection replicas AVAILABLE again

**Comment by cserf** [comment]
Not so simple. Imagine a file is marked as temporarily `UNAVAILABLE` and there is only one other copy of this file that is declared `BAD` to Rucio in the meantime. In that case, the necromancer won't see any `AVAILABLE` copy of the file and will set a Epoch tombstone on all the `UNAVAILABLE` replicas.

**Comment by bari12** [comment]
Yes, it's a quite heavy change touching all systems. That's why I think it would have to be a new `TEMPORARYUNAVAILABLE` state, so it is obvious to other daemons that this is not a normal `UNAVAILABLE` replica.
