### ISSUE TITLE
Resolve archives per default in clients

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1560]
Motivation
----------

Should be default true everywhere and also work for datasets, not only files.

**Comment by bari12** [comment]
I think we should just change the switch to --no-resolve-archives. If not set resolving is true by default.

**Comment by mlassnig** [comment]
maybe shorter just `--no-archives` ?

**Comment by bari12** [comment]
Hmm, it might be a bit confusing as one could assume that `--no-archives` means there are not archive replicas in the result. Although, to some extend `--no-resolve-archives` could be interpreted the same...
