### ISSUE TITLE
Client fails if auth type is x509_proxy and X509_USER_PROXY is not set

### ISSUE THREAD

**Issue by illingwo** [rucio/rucio#1579]
The client fails if the authentication type is x509_proxy and the X509_USER_PROXY environment variable is not set with a very confusing error message:
```
$ rucio whoami
2018-09-27 09:22:57,749	ERROR	coercing to Unicode: need string or buffer, module found
```

**Comment by bari12** [comment]
@hahahannes can you please have a look on this. I expect it should be an easy fix.

**Comment by illingwo** [comment]
It is - I was just doing a pull request

**Comment by mlassnig** [comment]
i just tried this in various ways and can't reproduce it.

`
$ rucio -v whoami
given client cert (/data/rucio/$X509_USER_PROXY) doesn't exist
2018-09-27 16:26:31,717 ERROR   Cannot authenticate.
Details: x509 authentication failed
`

respectively:
`Details: Cannot find a valid X509 proxy; not in /tmp/x509up_u23311, $X509_USER_PROXY not set, and 'x509_proxy' not set in the configuration file.`

or:
`2018-09-27 16:28:21,172 ERROR   [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'PEM lib')]`


really interested in that pull-request ;-)

**Comment by bari12** [comment]
Ahh, sorry 😄 Thanks a lot!
