### ISSUE TITLE
Download client should report suspicious files properly

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1593]
Motivation
----------

The download client only reports suspicious files if there is a checksum mismatch. In case the download fails because of missing files, it doesn't report anything. The client should parse the error reported by `protocol.get` and if it matches some pattern, report.

Modification
------------
Fix it

**Comment by bari12** [comment]
Link to #1623 as only one of them has to be implemented.

**Comment by cserf** [comment]
#1623 has been implemented and merged. Therefore all downloads with eventType `get_sm` or `get_sm_a` shouldn't report any suspicious files
