### ISSUE TITLE
Option to register replica only after upload

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1599]
Motivation
----------

The current workflow when uploading a file is to register the replica as `UNAVAILABLE` first; Process the upload; Switch the replica to `AVAILABLE`. When the upload fails, the command can just be re-executed, however it is verified that a file with a similar checksum is uploaded.
We recently were told about official workflows where the re-upload, after a failure, would be done with a different file; Thus same filename but different checksum, which does not work in this workflow. The proposed solution is to offer a switch `--register-after-upload` (or something similar) where the client uploads first and registers the replica only as `AVAILABLE` when successful. Thus the pre-registration as `UNAVAILABLE` is skipped. In this case however, if the upload is repeated, the destination file always has to be over-written, as it could always be a new file being uploaded, as long as it is not registered in the catalog yet.

**Comment by cserf** [comment]
Priority increased
