### ISSUE TITLE
zip extraction to wrong scope

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1622]
Motivation
----------

> Hi,
>  Download of data16_13TeV:DRAW_RPVLL.11106701._000026.pool.root.1
> 
> produces the file
> 
> data16_valid/DRAW_RPVLL.11106701._000026.pool.root.1
> 
> This is the scope of the zip file containing it, but should be the scope of the constituent.
> 
> This is not a problem until it is - I think in general the scopes will be the same.
> 
> However, I don`t think there is a requirement that this be the case, so this should probably be fixed.
> 
> Please also check that the file(s) end up in the correct directories in the case where the whole zip is downloaded.
> 
> Cheers,
> Rod.

**Comment by TWAtGH** [comment]
```
(.venv) [11:35][twegner@twegner-dev rucio]$ rucio -v get --rse NIKHEF-ELPROD_DATADISK data16_13TeV:DRAW_RPVLL.11106701._000026.pool.root.1
...
2018-10-09 11:36:40,191	DEBUG	Executing: xrdcp -vf root://tbn18.nikhef.nl:1094//dpm/nikhef.nl/home/atlas/atlasdatadisk/rucio/data16_13TeV/fd/f5/DRAW_RPVLL.14552406._000001.zip.1?xrdcl.unzip=DRAW_RPVLL.11106701._000026.pool.root.1 -z DRAW_RPVLL.11106701._000026.pool.root.1 file:///data/rucio/data16_13TeV/DRAW_RPVLL.11106701._000026.pool.root.1.part
2018-10-09 11:36:53,080	DEBUG	renaming '/data/rucio/data16_13TeV/DRAW_RPVLL.11106701._000026.pool.root.1.part' to '/data/rucio/data16_13TeV/DRAW_RPVLL.11106701._000026.pool.root.1'
...
----------------------------------
Download summary
----------------------------------------
DID data16_13TeV:DRAW_RPVLL.11106701._000026.pool.root.1
Total files :                                 1
Downloaded files :                            1
Files already found locally :                 0
Files that cannot be downloaded :             0
Completed in 12.9494 sec.
(.venv) [11:37][twegner@twegner-dev rucio]$ ls data16_13TeV/
total 227380
-rw-r--r--. 1 twegner zp 232834160 Oct  9 11:36 DRAW_RPVLL.11106701._000026.pool.root.1
```
Maybe not the newest client?

**Comment by bari12** [comment]
I think this is dependent on #1613

**Comment by bari12** [comment]
#1613 is merged now. I think this bug should be fixed by that, but please check.

**Comment by TWAtGH** [comment]
It gets downloaded correctly using the current master and #1956 .
It's also done correctly in case the whole zip is downloaded.
