### ISSUE TITLE
add_files_to_dataset without SRM

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1636]
Motivation
----------

Email discussion with ATLAS T0:

"""btw, the double-slash is always necessary for root.

it works for add_replica, so there must be something different in the method add_files_to_dataset()

On 9/14/18 3:52 PM, Tomas Javurek wrote:
> Trying to register with add add_files_to_dataset that Luc is using:
> RSE does not support requested protocol.
>
> while when I set the protocol, it works fine. So, we need to keep it there for now. *However, please keep it with srm* for now, because it did work for me only with srm, when I tried with root protocol, it failed with the same error. And I tried both:
>
> 'root://sedoor1.bfg.uni-freiburg.de:1094/pnfs/bfg.uni-freiburg.de/data/atlasdatadisk/rucio/user/ddmadmin/‘
> 'root://sedoor1.bfg.uni-freiburg.de:1094//pnfs/bfg.uni-freiburg.de/data/atlasdatadisk/rucio/user/ddmadmin/'
>
>
>
>> On 14 Sep 2018, at 15:21, Tomas Javurek <Tomas.Javurek@cern.ch <mailto:Tomas.Javurek@cern.ch>> wrote:
>>
>> I couldn’t find the place where we subtract the protocol part from path when registering to replicas. But I’ll try brute-force. Just preparing a script that would imitate Lucs needs, and see whether I can register without protocol part.
"""

**Comment by cserf** [comment]
I'm not sure what the problem is here (maybe related to the double `/` in xrootd path). But `add_files_to_dataset` definitely works without SRM. We tried with `gsiftp` at T0 and it works fine.
