### ISSUE TITLE
Migrate Nagios probes to a separate repository

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1638]
Motivation
----------
Right now the Nagios probes are part of the core repository, but they should not be. We should move them to a separate atlas-rucio-probes repository (or similar). Over time this can also converge to a common probe repository, as CMS most likely will also use a large fraction of these probes.

**Comment by bari12** [comment]
This was discussed in the [dev meeting on 2018-10-11](https://indico.cern.ch/event/760955/)

**Comment by cserf** [comment]
New repository : https://github.com/rucio/probes
The probes will be migrated
