### ISSUE TITLE
ATLAS: Improvements for check_sync_rses_with_agis probe

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1648]
Motivation
----------
The probe doesn't set properly the `RSE_TYPE` (need first to implement #1647). Moreover it should set a default distance for all the new RSEs.

**Comment by bari12** [comment]
Should not be an issue with #716

**Comment by dchristidis** [comment]
I think not populating the RSE distance matrix is a Feature™ that we still want to keep for operational reasons.

With `core.rse.add_rse()` and the probe modified, I am closing this issue.
