### ISSUE TITLE
setup.py is needed for readthedocs

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#165]
Motivation
----------
setup.py file is needed in the repo for readthedocs.

Modification
------------
Copy the setup_rucio.py to setup.py and have both (as duplicates)

**Comment by mlassnig** [comment]
Git can handle symlinks alright, so no need to duplicate the file, right?

**Comment by vingar** [comment]
yes, git can but the issue is more with the release procedure as this file is changed several times and how readthedocs accesses it

**Comment by bari12** [comment]
True good point!

**Comment by bari12** [comment]
For the release procedure it is fine, it is just overwriting the symlink, but never commiting back the code. If readthedocs can handle the symlink it is fine for the release procedure.

**Comment by vingar** [comment]
try the symbolic link then
