### ISSUE TITLE
Registration in uploadclient

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#1669]
Motivation
----------
it can happen in uploadclient, that registration fails, but file proceeds with an upload. Such a data is most probably deleted by dark-reaper soon. The case when registration fails, should be mentioned in the trace['stateReason'].

Modification
------------
introduce return codes in _register_file method and populate the trace.

**Comment by TWAtGH** [comment]
How?

**Comment by bari12** [comment]
Needs to be checked.

**Comment by TWAtGH** [comment]
We can check again but I think the registration is working fine now
