### ISSUE TITLE
Implement missing update_account method

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1685]
Motivation
----------
There is a `set_account_status` to update the status of an account, but there is no `update_account` method to update the account email for instance. Proposal is to get rid of  `set_account_status` and replace it by `update_account(account, key, value)`. Change is needed at all levels (core, API, REST, CLI)

**Comment by hahahannes** [comment]
Maybe `set_account_property`, `set_account_parameter` or something similar instead? So that it is aligned with the attribute functions `del_account_attribute`, `add_account_attribute`. 
Then I would also replace the `get_account_status` with `get_account_property`.

**Comment by hahahannes** [comment]
Also I am not sure how I shall handle the permissions. For example [here](https://github.com/rucio/rucio/blob/master/lib/rucio/core/permission/atlas.py#L43). 
I think the permission for set_account_status should apply for changes on all account properties ? Then I would also update the permission files.
