### ISSUE TITLE
Problem with deleting RSE after deleting attribute

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#1689]
Motivation
----------
If you delete the RSE attribute with the same name as the RSE, you can not delete the RSE afterwards. The request will fail with status code 500 and 'Internal server error' message.
```
DELETE /rses/MOCK/attr/MOCK
DELETE /rses/MOCK
```

Modification
------------
I would create a new exception class e.g. RSEAttributeNotFound and throw it [here](https://github.com/rucio/rucio/blob/master/lib/rucio/core/rse.py#L326) if a NoResultFound exception gets raised and then respond with the corresponding error message.
Then there should be a check if the attribute to be deleted has the same name as the RSE to avoid this exception in the RSE deletion.

**Comment by cserf** [comment]
Related to RSE deletion, it might make sense to have a look at #26. If the RSE is not empty, a `RSEOperationNotSupported` should be raised.
