### ISSUE TITLE
REST API not returning full JSON

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#1730]
Motivation
----------

It seems like the Rucio REST API does not actually return true JSON. This is an e-mail from @vkuznet to me about this. The context is that CMS uses something called DAS to aggregate info across our data management system, data catalog, and other systems. It relies on REST APIs to do this in a reasonable fashion (not a client library for each system). Thoughts?

It seems Rucio APIs do not return proper JSON:

```
curl -H "X-Rucio-Auth-Token: $token" http://cms-rucio-test.cern.ch/rses/

{"rse_type": "DISK", "id": "c7ed36b8906c4808b090b35976373f88", "region_code": null, "city": null, "updated_at": "Fri, 28 Sep 2018 19:11:56 UTC", "rse": "T2_US_Nebraska_Test", "created_at": "Fri, 28 Sep 2018 19:11:56 UTC", "ISP": null, "deleted": false, "time_zone": null, "longitude": null, "availability": 7, "deterministic": true, "volatile": false, "country_name": null, "latitude": null, "deleted_at": null, "continent": null, "ASN": null, "staging_area": false}
{"rse_type": "DISK", "id": "1a8167d0f9c743749ecd3bf00d4fb04c", "region_code": null, "city": null, "updated_at": "Wed, 24 Oct 2018 12:06:07 UTC", "rse": "T3_US_NERSC", "created_at": "Wed, 24 Oct 2018 12:06:07 UTC", "ISP": null, "deleted": false, "time_zone": null, "longitude": null, "availability": 7, "deterministic": true, "volatile": false, "country_name": null, "latitude": null, "deleted_at": null, "continent": null, "ASN": null, "staging_area": false}

```

and

```

curl -H "X-Rucio-Auth-Token: $token" http://cms-rucio-test.cern.ch/accounts/
{"account": "das", "type": "USER", "email": null}
{"account": "dciangot", "type": "USER", "email": null}

```

Yes, they return JSON dicts, but it is not single JSON document, and therefore
it fails to be parsed. Here is example to prove it.

```
curl -H "X-Rucio-Auth-Token: $token" http://cms-rucio-test.cern.ch/accounts/ > account.json
python
Python 2.7.5 (default, Jul 13 2018, 13:06:57)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-28)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
import json
data = json.load(open("accounts.json"))
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
 File "/usr/lib64/python2.7/json/__init__.py", line 290, in load
   **kw)
 File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
   return _default_decoder.decode(s)
 File "/usr/lib64/python2.7/json/decoder.py", line 369, in decode
   raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 9 column 1 (char 50 - 419)

```
I also tried to use HTTP header Content-Type: application/json and results are
the same.

I don't want to crawl over strings (this is what APIs return now) and convert
them to JSON docs. Instead, I would [like]  a JSON document. For the record, the
proper JSON would be something like (based on accounts API output):

```
[
{"account": "das", "type": "USER", "email": null},
{"account": "dciangot", "type": "USER", "email": null}
]

```
It is also desired that all APIs will use the same data-type, a list of dicts,
even if one item in a list is present. This will allow to abstract parsing code
much easily and make it API independent.

Best,
Valentin.

Modification
------------

**Comment by vingar** [comment]
I guess it corresponds to answer with `Content-Type: application/x-json-stream`. To stream JSON, we used objects delimited by newlines. cf. https://rucio.readthedocs.io/en/latest/rest.html

**Comment by vkuznet** [comment]
According to JSON specs:

------- from [JSON](http://www.json.org/) specs -----
In JSON, they take on these forms:

An object is an unordered set of name/value pairs. An object begins with { (left brace) and ends with } (right brace). Each name is followed by : (colon) and the name/value pairs are separated by , (comma).

An array is an ordered collection of values. An array begins with [ (left bracket) and ends with ] (right bracket). Values are separated by , (comma).

-------- END OF QUOTE -----

Since your APIs provide an answer as a list of records (which are dicts), they need to be separated by comma and embraced with brackets.

The provided output of REST APIs, e.g.
```
curl -H "Content-Type: application/json" -H "X-Rucio-Auth-Token: $token" http://cms-rucio-test.cern.ch/accounts/
{"account": "das", "type": "USER", "email": null}
{"account": "dciangot", "type": "USER", "email": null}
``` 

does not satisfy the JSON specs. That's why the standard JSON parsers (in python or other languages) will fail to parse it. What you yield in APIs is a list of strings (even though they're represented dicts) but it is not a valid JSON document.

I provided an example of python parser flow which you can use to tests your documents
```
curl -H "Content-Type: application/json "-H "X-Rucio-Auth-Token: $token" http://cms-rucio-test.cern.ch/accounts/ > account.json
# parse docs in python
import json
data = json.load(open("accounts.json"))
```
And, it fails to parse the document obtained from the REST API. I can easily substitute a file with file descriptor which is established in network call and `json.load(fileDescriptor)` should work.

In order to stream a data in JSON format someone needs to do the following:
```
# obtain json serialized object
objectData = json.dumps(data)
# send objectData to the wire
```

**Comment by bbockelm** [comment]
@vkuznet - isn't that compatible with what Vincent said?

That is, the API returns `Content-Type: application/x-json-stream`.  A JSON stream is _not_ JSON (e.g., https://en.wikipedia.org/wiki/JSON_streaming)!

**Comment by vkuznet** [comment]
@bbockelm , according to Rucio REST API page:
```
The server answer can be one of the following content-type in the http Header:
Content-type: application/json
Content-Type: application/x-json-stream
In the last case, it corresponds to JSON objects delimited by newlines(streaming JSON for large answer),
{ "id": 1, "foo": "bar" }
{ "id": 2, "foo": "baz" }
```

The MIME media type for JSON text is application/json and it is defined by [RFC4627](http://www.ietf.org/rfc/rfc4627.txt) The data with MIME type `application/x-json-stream` is not the same as data with MIME type `application/json`. The former can be defined as JSON objects delimited by newlines and later should be strict JSON document.

Vincent is correct about `application/x-json-stream` but that is not what I was looking for. I asked about `application/json` which right now returns data in `application/x-json-stream` format.

**Comment by mlassnig** [comment]
Hi,
to explain, we stream the results from the database directly to the clients, that's why we do JSON streams (the server ignores client requests for different MIME types).

Now, if for a particular call you'd like to have a single JSON document, then we will have to add support for a client requesting MIME `application/json`. It's not really a problem, but the implications are of course that any wide-spread use of that will quickly exhaust the memory on our servers since the JSON has to be assembled there. For example, doing this for `list_replicas()` is a no go whereas for many other calls it would be ok.

**Comment by vkuznet** [comment]
Mario,
I'm not sure I understand the technical issue here. Why do you need to assemble a JSON? If you have your stream from DB, the change I would expect is to add opening bracket `[` to the response, replace newline delimiter `\n` to comma `,`, and end response with closing bracket `]`. It can be easily done by adding response wrapper (decorator) which will take whatever stream API you have and perform these three actions.

Here is a brief sketch of the program flow which does not assemble the JSON in memory but rather add additional wrapper around rucio data stream and yield proper JSON format:
```
#!/usr/bin/env python
import json

def json_stream(func):
    "JSON streamer which yield correct JSON object"
    yield "["
    for idx, doc in enumerate(func()):
        if idx:
            sdoc += ','
            yield sdoc
        sdoc = json.dumps(doc)
    yield sdoc
    yield "]"

def rucio_data():
    "Provide JSON data from Rucio server"
    doc = {'srv':'rucio'}
    for idx in range(3):
        doc['counter'] = idx
        yield doc

def main():
    print("Rucio JSON stream")
    stream = ''
    for doc in rucio_data():
        print(doc)
        stream += json.dumps(doc) + '\n'
    try:
        data = json.loads(stream)
    except ValueError:
        print("ERROR: unparseable JSON stream")
    print("\nRucio JSON object")
    stream = ''
    for doc in json_stream(rucio_data):
        print(doc)
        stream += doc
    data = json.loads(stream)
    print("parsed json object: %s" % data)

if __name__ == '__main__':
    main()
```
If you'll run it you'll get this output:
```
Rucio JSON stream
{'counter': 0, 'srv': 'rucio'}
{'counter': 1, 'srv': 'rucio'}
{'counter': 2, 'srv': 'rucio'}
ERROR: unparseable JSON stream

Rucio JSON object
[
{"counter": 0, "srv": "rucio"},
{"counter": 1, "srv": "rucio"},
{"counter": 2, "srv": "rucio"}
]
parsed json object: [{u'counter': 0, u'srv': u'rucio'}, {u'counter': 1, u'srv': u'rucio'}, {u'counter': 2, u'srv': u'rucio'}]
```

**Comment by mlassnig** [comment]
Hi Valentin,
sure. If we agree that all JSON streams can also be returned as a JSON list instead, then that is easy.

**Comment by vingar** [comment]
In your example, you are not testing the serialisation between the server and the client through the network which was our problem at that time. That's what we went with newlines which was the way to stream json. Maybe now there is some better way.

**Comment by vkuznet** [comment]
@vingar, of course I don't know the details of your code, but example clearly demonstrate the idea. I would expect that you organize the pipe between your DB layer and streaming API. You consume data on your DB part and yield it back with proposed modifications to the streaming API.

**Comment by vkuznet** [comment]
@mlassnig , Mario, you can leave JSON stream as is and they can be returned with `application/x-json-stream` type, but my request was to fix the data when client requests `application/json`.

**Comment by vingar** [comment]
@vkuznet we started by what you proposed but got issue with the http client libraries(httplib, requests, etc) not being able to consume the streamed entries.

**Comment by bbockelm** [comment]
Valentin - you mentioned you used Content-Type. Shouldn’t that be Accept?

**Comment by bbockelm** [comment]
@vingar - indeed, it's probably easier for the client side to consume the JSON streaming format (not to mention things like handling HTTP chunk-encoding better!), but if the client explicitly asks for JSON instead, I guess we have to assume they know what they are doing!

**Comment by vingar** [comment]
yes, good points. Feel free to post pull requests ;)

**Comment by mlassnig** [comment]
Ok, I guess I figured out why Valentin expected that he could request a JSON with Accept, since the statement in the doc is ambiguous:

"...The server answer can be one of the following content-type in the http Header..." However, this doesn't mean that the client has a choice ;-)

Anyway, adding an "Accept" parser to the REST frontend is easy.

**Comment by vingar** [comment]
When the HTTP Header `Accept: application/json` is there, proper json should be returned.
One caveat is to check the rucio clients regarding this...

BTW, listing accounts is not the most memory usage critical operation and do no need streaming imo.

**Comment by vkuznet** [comment]
Indeed, the proper request header should be `Accept`, sorry for confusion.

**Comment by vkuznet** [comment]
Yet, another issue with ambiguity of documents returned by server. Imaging that one query will return a single record. Using x-json-stream we have (I took record as an example):
```
{"accessed_at": null, "name": "/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#49a747ac-3736-11e8-91bf-ac1f6b05ea26", "rse": "T3_US_NERSC", "created_at": "Wed, 24 Oct 2018 12:45:12 UTC", "bytes": 0, "state": "UNAVAILABLE", "updated_at": "Wed, 24 Oct 2018 12:45:12 UTC", "available_length": 0, "length": 0, "scope": "cms", "available_bytes": 0}
```
By parsing this doc we'll get a Python dictionary data-type. While if server return multiple records, e.g.
```
{"accessed_at": null, "name": "/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#49a747ac-3736-11e8-91bf-ac1f6b05ea26", "rse": "T3_US_NERSC", "created_at": "Wed, 24 Oct 2018 12:45:12 UTC", "bytes": 0, "state": "UNAVAILABLE", "updated_at": "Wed, 24 Oct 2018 12:45:12 UTC", "available_length": 0, "length": 0, "scope": "cms", "available_bytes": 0}
{"accessed_at": null, "name": "/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#cd7def92-37b6-11e8-a513-02163e018570", "rse": "T3_US_NERSC", "created_at": "Tue, 30 Oct 2018 19:25:25 UTC", "bytes": 0, "state": "UNAVAILABLE", "updated_at": "Tue, 30 Oct 2018 19:25:25 UTC", "available_length": 0, "length": 0, "scope": "cms", "available_bytes": 0}
```
it will be converted (assuming parser can do it) into a list data-type. As you can see a single API can produce different data-type using this format. Without `application/json` we end-up with ambiguity of data-type from APIs. I hope you can take care of this ambiguity at a server level and return data such that they can be decoded into consistent data-type.

**Comment by bari12** [comment]
For me the main issue here is that the documentation is a bit ambiguous and the server handling of the requested Content-Type is not strict enough.
If the application requests `Content-Type: application/json` (or any other content type that is) and the server cannot supply it, it should raise a `HTTP 406 Not Acceptable` (See [link](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.7)) instead of just replying with whatever it thinks is useful.

For me the handling is fine: If no specific type is requested we return `application/x-json-stream` - By keeping it like this we also ensure possible back-compatibility issues with (old) clients.
What we should change is, if a different type is requested (e.g. `application/xml`, `application/pdf`, ...) we should raise a 406
And we can also add the `application/json` handling, as asked by Valentin, it shouldn't be too hard to add.
Let's discuss this at the Dev Meeting on Thursday and then create the respective issues.

**Comment by bari12** [comment]
This was discussed in the development meeting from [2018-11-08](https://indico.cern.ch/event/766990/)
Essentially we decided that if a content type is requested, which the server cannot reply, we will raise HTTP 406. However, we will try to add `application/json` type additionally to `application/x-json-stream`.

**Comment by vkuznet** [comment]
How do we stand on this issue?

I found yet another problem with records using default `application/x-json-stream` mime type. It does not provide newline `\n` for the last record, i.e. if we have multiple records in response they are separated by `\n` except last one. Response with single record does not have `\n` either. This requires to properly write a parser for x-json-stream which should separate record based on newline and collect last output till the end of the stream. According to https://www.wikiwand.com/en/JSON_streaming#/Line-delimited_JSON the line-delimited JSON should have `\n` for every record, but it is unclear from the description if last record should have the delimiter or not.

**Comment by bari12** [comment]
It's still in the plan, but as this is non-blocking, it doesn't have the highest priority.
@hahahannes Can you please look into the raising a `406` in case of non-supported content-type. We can discuss this on Monday. To also allow `application/json` for certain queries should be not difficult.

For the `\n` for the last record. Just quickly looking into it I couldn't find a definitive answer on this. For [JSON Lines](http://jsonlines.org) (Which is  part of the Line delimited JSON) it says:
> The last character in the file **may** be a line separator, and it will be treated the same as if there was no line separator present.
