### ISSUE TITLE
Scope name validation regex allows single quotes

### ISSUE THREAD

**Issue by illingwo** [rucio/rucio#1739]
The scope validation regex for atlas/generic/icecube (but not cms) allows single quotes, which seems like a bad idea.

`"^[a-zA-Z'_'-.0-9]{1,%s}$" % SCOPE_LENGTH` looks wrong, and I'm guessing it ought to be `"^[a-zA-Z_\\-.0-9]{1,%s}$" % SCOPE_LENGTH`. Unless someone really does have this requirement?

**Comment by illingwo** [comment]
@briedel is this an icecube requirement? Because if not then it's almost certainly a mistake.

**Comment by bbockelm** [comment]
Per @briedel in Slack, there's no need to allow single quotes.  Probably an error.

@illingwo - any chance you want to put in a PR?
