### ISSUE TITLE
Primary Key for replicas table is in wrong order in models.py

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1749]
Motivation
----------
https://github.com/rucio/rucio/blob/a7b6fef66687f4a673b705eb738dd4d88113edac/lib/rucio/db/sqla/models.py#L736
The PK for the replicas table is in `order rse_id, scope, name` while it actually should be in order `scope, name, rse_id`
This needs to be changed and we need a proper upgrade script so this can be adapted at all installations.

**Comment by mlassnig** [comment]
This is potentially tricky. Changing the primary key is easily possible, however, this won't move the data already on the tablespace, it will just check that the new primary key constraint is still valid. What we actually want is for the data to be moved. So this will need an intermediate tmp_replicas table and thus some downtime as the DBA manually shovels data around. Changing the primary key can be done with the alembic upgrades, but shoveling the data can only be done manually if we don't want tmp_replicas to pollute our models.py

**Comment by mlassnig** [comment]
We can do the primary key change anyway though. And we could provide a script for all databases to do it offline. Then it's the instance admins choice when/how they apply it (if they want to do it)

**Comment by bari12** [comment]
It is fine to do it offline, but we need to document it somehow. I am surprised that this never showed up, but in smaller installations the queries will just be quick enough without going against the PK. And from a uniqueness point of view this PK is correct as well.
