### ISSUE TITLE
How to find block replica info

### ISSUE THREAD

**Issue by vkuznet** [rucio/rucio#1758]
Motivation
----------

In CMS we get use to these concepts: a dataset is collection of blocks, a block is collection of files.
I understand that in ATLAS a dataset is a container, etc. But apart from naming convention differences I need to find block replicas (in CMS terminology).

If we call a dataset as /a/b/c pattern, a block as /a/b/c#123xys pattern and file is /file.root one. The `/replicas/scope/name` can take either dataset or block patterns and return list of files. How I can find list of block (/a/b/c#123xys pattern) replicas? Is it issue with /replicas/scope/name/datasets API in this https://github.com/rucio/rucio/issues/1746 ticket or there is no such API?

CC'ing Eric (@ericvaandering) to follow up with this issue.

**Comment by ericvaandering** [comment]
In Rucio, what we call a block is going to be called a dataset. Beyond that, I'm having kind of a hard time understanding what you're looking for. 

Rucio itself does not require that datasets (Rucio definition) live all at one site, they can be scattered file by file. We don't plan to do this in CMS, though.

**Comment by mlassnig** [comment]
The dataset replicas API is `GET /replicas/<scope>/<name>/datasets`, that's correct. We don't have an API for dataset replicas for only a single RSE. Should be trivial to implement though.

**Comment by vkuznet** [comment]
Eric,
we use the following query in DAS:
block dataset=/a/b/c site=XYZ
where block is /a/b/c#123 patterns. So I must pass to API /a/b/c and get back
/a/b/c#123 (whatever you call them). The site is part of response so we can
filter, but it would be nice to add it as a parameter to the query. The later
can be problematic due to REST logic. I can imaging this
`/replicas/cms/<rse>/<name>` where we can supply both rse and dataset/block
names or `/replicas/cms/<name>/<rse>` but it may be hard to implement since
API path should be parsed properly. REST goes well with a single argument which
is appended to the path of API, but handling multiple parameters in REST
is harder, and solution may require fallback to URL parameters, e.g.
/path?arg1=val1&arg2=val2, etc.
Valentin.

**Comment by ericvaandering** [comment]
The first should give you the mapping you want. I don't know what the client is doing internally in the second call, if its one REST API call or a dozen.

```
[root@client-6c4466d746-76ldc /]# rucio list-content cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD
+------------------------------------------------------------------------------------+--------------+
| SCOPE:NAME                                                                         | [DID TYPE]   |
|------------------------------------------------------------------------------------+--------------|
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#49a747ac-3736-11e8-91bf-ac1f6b05ea26 | DATASET      |
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#56f1f7ec-3789-11e8-a513-02163e018570 | DATASET      |
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#642e11e4-375b-11e8-91bf-ac1f6b05ea26 | DATASET      |
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#8ca7b000-374f-11e8-a5e2-ac1f6b05e848 | DATASET      |
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#b171c1de-3748-11e8-a5e2-ac1f6b05e848 | DATASET      |
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#c6454d7a-3715-11e8-bf17-ac1f6b05ec6a | DATASET      |
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#cd7def92-37b6-11e8-a513-02163e018570 | DATASET      |
| cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#f8910b72-3704-11e8-bf17-ac1f6b05ec6a | DATASET      |
+------------------------------------------------------------------------------------+--------------+
[root@client-6c4466d746-76ldc /]# rucio list-dataset-replicas cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#b171c1de-3748-11e8-a5e2-ac1f6b05e848
+---------------------+---------+---------+
| RSE                 |   FOUND |   TOTAL |
|---------------------+---------+---------|
| T3_US_NERSC         |       0 |       0 |
| T2_US_Nebraska_Test |       0 |       0 |
+---------------------+---------+---------+

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#cd7def92-37b6-11e8-a513-02163e018570
+-------------+---------+---------+
| RSE         |   FOUND |   TOTAL |
|-------------+---------+---------|
| T3_US_NERSC |       0 |       0 |
+-------------+---------+---------+

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#f8910b72-3704-11e8-bf17-ac1f6b05ec6a
+-------------+---------+---------+
| RSE         |   FOUND |   TOTAL |
|-------------+---------+---------|
| T3_US_NERSC |       0 |       0 |
+-------------+---------+---------+

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#8ca7b000-374f-11e8-a5e2-ac1f6b05e848
+---------------------+---------+---------+
| RSE                 |   FOUND |   TOTAL |
|---------------------+---------+---------|
| T2_US_Nebraska_Test |       0 |       0 |
+---------------------+---------+---------+

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#c6454d7a-3715-11e8-bf17-ac1f6b05ec6a
+-------------+---------+---------+
| RSE         |   FOUND |   TOTAL |
|-------------+---------+---------|
| T3_US_NERSC |       0 |       0 |
+-------------+---------+---------+

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#56f1f7ec-3789-11e8-a513-02163e018570
+-------------+---------+---------+
| RSE         |   FOUND |   TOTAL |
|-------------+---------+---------|
| T3_US_NERSC |       0 |       0 |
+-------------+---------+---------+

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#49a747ac-3736-11e8-91bf-ac1f6b05ea26
+-------------+---------+---------+
| RSE         |   FOUND |   TOTAL |
|-------------+---------+---------|
| T3_US_NERSC |       0 |       0 |
+-------------+---------+---------+

DATASET: cms:/Charmonium/Run2017D-31Mar2018-v1/MINIAOD#642e11e4-375b-11e8-91bf-ac1f6b05ea26
+-------------+---------+---------+
| RSE         |   FOUND |   TOTAL |
|-------------+---------+---------|
| T3_US_NERSC |       0 |       0 |
+-------------+---------+---------+
```

**Comment by vkuznet** [comment]
Can we translate this into REST API calls?

My understanding that it is
/replicas/cms/Charmonium/Run2017D-31Mar2018-v1/MINIAOD/datasets
which produces nothing. It aligns with your output which shows 0 found results.
Then the question is why we see files on these sites but not blocks (in CMS
terminology) or DATASET (in Rucio one). Is it artefact or something else?

**Comment by bari12** [comment]
This is still an outstanding issue. The dataset replicas are currently updated only by an PL/SQL procedure on the Oracle database. This PL/SQL I believe is not run on the CMS instance, hence the dataset replica counters not being updated...

**Comment by ericvaandering** [comment]
@vkuznet that's why I have suggested a couple of times that you install the rucio client and instrument it to see which REST calls are being made. It's a fool-proof way. Relying on me or others to read the code is time consuming and error prone.

**Comment by bari12** [comment]
With #524 the daemon to update the collection replicas has been added. (It's in 1.18.9 release)
Thus with this one or the PL/SQL procedure it will update the collection_replicas to the correct stats.
