### ISSUE TITLE
Database Exceptions MariaDB: Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by astroclark** [rucio/rucio#1759]
Motivation
----------
I've recently started seeing various mysql exceptions.

First, listing file replicas in a dataset gives a database exception message in the client:
```
(ligo-rucio) ➜  ~ rucio list-file-replicas O1:L-L1_R-11266
2018-11-06 14:16:35,616	ERROR	Database exception.
Details: (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'SELECT rses.id AS rses_id, rses.rse AS rses_rse, rses.rse_type AS rses_rse_type, rses.`deterministic` AS rses_deterministic, rses.volatile AS rses_volatile, rses.staging_area AS rses_staging_area, rses.city AS rses_city, rses.region_code AS rses_region_code, rses.country_name AS rses_country_name, rses.continent AS rses_continent, rses.time_zone AS rses_time_zone, rses.`ISP` AS `rses_ISP`, rses.`ASN` AS `rses_ASN`, rses.longitude AS rses_longitude, rses.latitude AS rses_latitude, rses.availability AS rses_availability, rses.updated_at AS rses_updated_at, rses.created_at AS rses_created_at, rses.deleted AS rses_deleted, rses.deleted_at AS rses_deleted_at \nFROM rses \nWHERE rses.deleted = false AND rses.rse = %s'] [parameters: ('LIGO-WA',)] (Background on this error at: http://sqlalche.me/e/f405)
```

Next, the judge-cleaner log shows the following message several times a second:
```
2018-11-06 11:20:17,659 3158    DEBUG   rule_cleaner[0/0] index query time 0.002273 fetch size is 1
2018-11-06 11:20:17,660 3158    INFO    rule_cleaner[0/0]: Deleting rule eb8794198a854dcd88846ca95998385c with expression UNL
2018-11-06 11:20:17,703 3158    DEBUG   Deleting lock O1:H-H1_R-1126621184-64.gwf for rule eb8794198a854dcd88846ca95998385c
Exception _mysql_exceptions.InterfaceError: (0, '') in <bound method SSCursor.__del__ of <MySQLdb.cursors.SSCursor object at 0x7f8c531e8950>> ignored
(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s'] [parameters: ('O1', 'H-H1_R-1126621184-64.gwf', '\xeb\x87\x94\x19\x8a\x85M\xcd\x88\x84l\xa9Y\x988\\', 'NI\t\xdc\xf5\x13I\xb0\x93\xb0\x1a\xf41\xb6\xf5\xc6')] (Background on this error at: http://sqlalche.me/e/f405)
2018-11-06 11:20:17,710 3158    ERROR   Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/judge/cleaner.py", line 104, in rule_cleaner
    delete_rule(rule_id=rule_id, nowait=True)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 360, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s'] [parameters: ('O1', 'H-H1_R-1126621184-64.gwf', '\xeb\x87\x94\x19\x8a\x85M\xcd\x88\x84l\xa9Y\x988\\', 'NI\t\xdc\xf5\x13I\xb0\x93\xb0\x1a\xf41\xb6\xf5\xc6')] (Background on this error at: http://sqlalche.me/e/f405)
```

Finally, the reaper log shows the following message which may or may not be related:
```
2018-11-02 13:59:22,418 2582    INFO    Reaper 0-1: Running on RSE LIGO-CIT-ARCHIVE None
2018-11-02 13:59:22,441 2582    DEBUG   Reaper 0-1: list_unlocked_replicas on LIGO-CIT-ARCHIVE for None bytes in 0.0183210372925 seconds: 1 replicas
2018-11-02 13:59:22,442 2582    CRITICAL        Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/reaper/reaper.py", line 215, in reaper
    prot = rsemgr.create_protocol(rse_info, 'delete', scheme=scheme)
  File "/usr/lib/python2.7/site-packages/rucio/rse/rsemanager.py", line 171, in create_protocol
    protocol_attr = select_protocol(rse_settings, operation, scheme, domain)
  File "/usr/lib/python2.7/site-packages/rucio/rse/rsemanager.py", line 146, in select_protocol
    candidates = _get_possible_protocols(rse_settings, operation, scheme, domain)
  File "/usr/lib/python2.7/site-packages/rucio/rse/rsemanager.py", line 122, in _get_possible_protocols
    ' found : %s.' % str(rse_settings))
RSEProtocolNotSupported: RSE does not support requested protocol.
Details: No protocol for provided settings found : {'third_party_copy_protocol': 1, 'rse_type': 'DISK', 'domain': ['lan', 'wan'], 'availability_delete': True, 'delete_protocol': 1, 'rse': u'LIGO-CIT-ARCHIVE', 'deterministic': True, 'write_protocol': 1, 'read_protocol': 1, 'staging_area': False, 'lfn2pfn_algorithm': 'ligo', 'availability_write': True, 'volatile': False, 'availability_read': True, 'credentials': None, 'verify_checksum': True, 'id': '65b733dd9afb4ec3beee2ac5c0fbc5c6', 'protocols': [{'extended_attributes': None, 'hostname': u'ldas-pcdev5.ligo.caltech.edu', 'prefix': u'/hdfs/frames', 'domains': {'wan': {'read': 1L, 'write': 0L, 'third_party_copy': 1L, 'delete': 0L}, 'lan': {'read': 0L, 'write': 0L, 'delete': 0L}}, 'scheme': u'gsiftp', 'port': 2811L, 'impl': u'rucio.rse.protocols.gfalv2.Default'}]}.
```

Note that these errors only seem to be affecting deletion of rules and replicas; actual transfer operations appear to be unaffected.

Modification
------------

**Comment by mlassnig** [comment]
Happens on
```
Name        : MariaDB-server
Arch        : x86_64
Version     : 10.2.18
```
with `MySQL-python 1.2.5`

Will have to try to reproduce this.

**Comment by mlassnig** [comment]
Still not able to reproduce. Abandon?

**Comment by mlassnig** [comment]
ping @astroclark

**Comment by mlassnig** [comment]
Closing.

**Comment by jlstephen** [comment]
We're also seeing similar behavior with MariaDB 10.3.15 and MySQL-python 1.2.5

In judge-cleaner.log:
```
2019-07-05 08:51:04,856      490     DEBUG   Deleting lock x1t_SR001_170320_1116_tpc:records-943c2b3857b2a913583557452451b5049362ecbd-000000 for rule 2da476bb1d854febbf28b76deddc78a6
(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s'] [parameters: ('x1t_SR001_170320_1116_tpc', 'records-943c2b3857b2a913583557452451b5049362ecbd-000000', '-\xa4v\xbb\x1d\x85O\xeb\xbf(\xb7m\xed\xdcx\xa6', 'jM\x10)+\xd2J\xf5\xb0\x05\x96,\xafo\x99\x84')] (Background on this error at: http://sqlalche.me/e/f405)
2019-07-05 08:51:04,861 490     ERROR   Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/judge/cleaner.py", line 107, in rule_cleaner
    delete_rule(rule_id=rule_id, nowait=True)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 365, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s'] [parameters: ('x1t_SR001_170320_1116_tpc', 'records-943c2b3857b2a913583557452451b5049362ecbd-000000', '-\xa4v\xbb\x1d\x85O\xeb\xbf(\xb7m\xed\xdcx\xa6', 'jM\x10)+\xd2J\xf5\xb0\x05\x96,\xafo\x99\x84')] (Background on this error at: http://sqlalche.me/e/f405)
```
In undertaker.log:
```2019-07-05 08:50:09,628      488     INFO    Undertaker(1): Receive 1 dids to delete
2019-07-05 08:50:09,628 488     INFO    Removing did x1t_SR001_170319_1011_tpc:raw_records-58340a130a541c95997fd1c442930427b04eac30 (DATASET)
Data identifier not found.
Details: Data identifier 'archive:raw_records-58340a130a541c95997fd1c442930427b04eac30' not found
2019-07-05 08:50:09,646 488     DEBUG   Removing rule d0b05b80dee24094b2a9f7b146412c97 for did x1t_SR001_170319_1011_tpc:raw_records-58340a130a541c95997fd1c442930427b04eac30 on RSE-Expression UC_OSG_USERDISK
2019-07-05 08:50:09,671 488     DEBUG   Deleting lock x1t_SR001_170319_1011_tpc:raw_records-58340a130a541c95997fd1c442930427b04eac30-000000 for rule d0b05b80dee24094b2a9f7b146412c97
(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s'] [parameters: ('x1t_SR001_170319_1011_tpc', 'raw_records-58340a130a541c95997fd1c442930427b04eac30-000000', '\xd0\xb0[\x80\xde\xe2@\x94\xb2\xa9\xf7\xb1FA,\x97', 'jM\x10)+\xd2J\xf5\xb0\x05\x96,\xafo\x99\x84')] (Background on this error at: http://sqlalche.me/e/f405)
2019-07-05 08:50:09,678 488     CRITICAL        Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/undertaker/undertaker.py", line 109, in undertaker
    logging.error('Undertaker(%s): Got database error %s.', worker_number, str(error))
UnboundLocalError: local variable 'error' referenced before assignment
```

**Comment by mlassnig** [comment]
@bari12 can we come up with a reproducable test for this?

**Comment by bari12** [comment]
I haven't looked into this personally. It would be good to understand under which conditions this shows up. Running the daemons with multiple threads, or also one thread etc. @astroclark @jlstephen 
Then we could try to reproduce this condition.

**Comment by bari12** [comment]
From Handson:
> Hi rucio-team,
> I’m DDM admin from ASGC(Taiwan site)
> We have a rucio server to manger out data.
> Here is our version information
> Rucio 1.13.3
> MariaDB 10.1.37
> Python package SQLAlchemy-1.1.13
> 
> When I run rucio-judge-cleaner, I got error like:
> 
> 2019-10-17 10:37:52,738 3265    INFO    rule_cleaner[0/0]: Deleting rule bb60ed7f80ad43059984e5a8663f5c29 with expression TW-EOS02_AMS02SCRATCHDISK
> 2019-10-17 10:38:53,390 3265    DEBUG   Deleting lock ams-user-felixlee:amsoutput2taiwan.873005283.pr.pl1.flux.l1o9.2016000.job.log.tgz for rule bb60ed7f80ad43059984e5a8663f5c29
> Exception _mysql_exceptions.InterfaceError: (0, '') in <bound method SSCursor.__del__ of <MySQLdb.cursors.SSCursor object at 0x31a5c50>> ignored
> (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s'] [parameters: ('ams-user-felixlee', 'amsoutput2taiwan.873005283.pr.pl1.flux.l1o9.2016000.job.log.tgz', '\xbb`\xed\x7f\x80\xadC\x05\x99\x84\xe5\xa8f?\\)', 'b?\xc5q\xb4\xbfA\xbf\x94\x93\xe4)\x86\x92\xed\x1a')]
> 
> 2019-10-17 10:38:53,397 3265    ERROR   Traceback (most recent call last):
>   File "/opt/rucio/lib/rucio/daemons/judge/cleaner.py", line 93, in rule_cleaner
>     delete_rule(rule_id=rule_id, nowait=True)
>   File "/opt/rucio/lib/rucio/db/sqla/session.py", line 358, in new_funct
>     raise DatabaseException(str(error))
> DatabaseException: Database exception.
> Details: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now") [SQL: u'DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s'] [parameters: ('ams-user-felixlee', 'amsoutput2taiwan.873005283.pr.pl1.flux.l1o9.2016000.job.log.tgz', '\xbb`\xed\x7f\x80\xadC\x05\x99\x84\xe5\xa8f?\\)', 'b?\xc5q\xb4\xbfA\xbf\x94\x93\xe4)\x86\x92\xed\x1a')]
> 
> I google it and found this issue https://github.com/rucio/rucio/issues/1759
> I do some test and found in the rucio/lib/core/rule.py  line 823(I use the Rucio 1.13.3 on git hub to be the stander of line number)
> locks = session.query(models.ReplicaLock).filter(models.ReplicaLock.rule_id == rule_id).with_for_update(nowait=nowait).yield_per(100)
> If there was a rule that contain over 100 locks (which the number is the same with yield_per input), then the error will show up.
> I guess the session query ReplicaLock table get over 100 row, but function yield_per only return 100 for once and the rows which satisfy ReplicaLock.rule_id == rule_id are still lock by function with_for_update.
> So on the rucio/lib/core/rule.py  line 830
> if __delete_lock_and_update_replica(lock=lock, purge_replicas=rule.purge_replicas, nowait=nowait, session=session):
> rucio/lib/core/rule.py  line 2711
> lock.delete(session=session, flush=False)
> 
> it failed to delete the row on the ReplicaLock table.
> I’m not sure my guess is right or not.
> Increase the number of yield_per input can fix the problem temporarily.
> But I think that is not a good way.
> Is there a better way to fix it?
> 
> Best regards,
> Handson Peng

**Comment by bari12** [comment]
To my understanding, the most likely reason why this is happening is that due to the `yield_per` parameter, the query is actually still running and the delete call (line 2711) changes the table thus somewhat conflicting the query (since it is still running). This is not an issue on Oracle, but it appears this brings MySQL into troubles.

When you are changing the `yield_per` to something bigger than the amount of locks, this is not an issue as the query already ended at the moment we start deleting the locks.

The only solution I see is to change the `yield_per(...)` to an `all()`, so the query finishes at the beginning of the loop. The downside of this is that the entire result has to be loaded into memory, which for big rules might be an issue. Maybe we can do this conditional to the DB implementation.

**Comment by Handson-peng** [comment]
The problem solved by changing the yield_per(...) to an all().

The rule stuck before is around 60K locks with the same rule_id. And there is no other problems.
So I still don't know the limit of rule size.

**Comment by bari12** [comment]
There is no principal limit of the rule size, however, the repairer might load the entire rule into memory, which for bigger rules requires a bit more. Thus if you run the repairer with a lot of threads in this uses all memory already under normal conditions, these large rule peaks might bring it over the limit.

**Comment by blinkdog** [comment]
WIPAC was bitten by this bug when we fired a one-off run of `rucio-judge-cleaner` to delete a rule:

```text
bash-4.2# rucio-judge-cleaner --run-once
/usr/lib64/python2.7/site-packages/sqlalchemy/engine/default.py:552: Warning: Truncated incorrect DOUBLE value: 'fe946249600df76ab57e5331127514f2'
  cursor.execute(statement, parameters)
2020-04-17 16:43:47,845	21475	INFO	rule_cleaner[0/0]: Deleting rule 4472de8c65214c3991028b91ed2097ff with expression NERSC-LTA
Exception _mysql_exceptions.InterfaceError: (0, '') in <bound method SSCursor.__del__ of <MySQLdb.cursors.SSCursor object at 0x7f98709a5510>> ignored
(raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
[SQL: DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s]
[parameters: ('lta', '00757c0a62d211eabaa642cd496541f0.zip', 'Dr\xde\x8ce!L9\x91\x02\x8b\x91\xed \x97\xff', '\r\xb4\x1d\x9c\xd2\xc0D$\xbb\x0e\xfb"\xad\x99\xca\'')]
(Background on this error at: http://sqlalche.me/e/f405)
2020-04-17 16:43:47,888	21475	ERROR	Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rucio/daemons/judge/cleaner.py", line 107, in rule_cleaner
    delete_rule(rule_id=rule_id, nowait=True)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 365, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely)
(_mysql_exceptions.ProgrammingError) (2014, "Commands out of sync; you can't run this command now")
[SQL: DELETE FROM locks WHERE locks.scope = %s AND locks.name = %s AND locks.rule_id = %s AND locks.rse_id = %s]
[parameters: ('lta', '00757c0a62d211eabaa642cd496541f0.zip', 'Dr\xde\x8ce!L9\x91\x02\x8b\x91\xed \x97\xff', '\r\xb4\x1d\x9c\xd2\xc0D$\xbb\x0e\xfb"\xad\x99\xca\'')]
(Background on this error at: http://sqlalche.me/e/f405)
```

Running Rucio 1.20.1.post1:
```text
bash-4.2# rucio --version
rucio 1.20.1.post1
```

And MariaDB 10.3.22:
```text
mysql Ver 15.1 Distrib 10.3.22-MariaDB, for Linux (x86_64) using readline 5.1
```

We are looking into using MariaDB 10.4, per [the suggestion in #support on Slack](https://rucio.slack.com/archives/C7P5AG01F/p1587148652205900). Will follow up with any results on this issue.

**Comment by bari12** [comment]
hi @blinkdog, I know it is some time, but was this possible solved with MariaDB 10.4? Would be good to follow-up on this issue. Thanks!

**Comment by mlassnig** [comment]
Related: https://github.com/rucio/rucio/issues/4945

**Comment by mlassnig** [comment]
Closing (impossible to reproduce, session handling #4945 )
