### ISSUE TITLE
sorting of column of type datetime in datatable broken

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1771]
Motivation
----------

Sorting of column of type datetime is broken datatable. The sorting is done alphabetically and not based on the date

**Comment by cserf** [comment]
For reference : https://datatables.net/forums/discussion/43603/datatables-1-10-15-broke-date-sorting

**Comment by davidgcameron** [comment]
Just came across the same problem, any chance it will be fixed?

**Comment by cserf** [comment]
@tbeerman , what can we do ?

**Comment by davidgcameron** [comment]
The bad replicas and suspicious replicas tables are still using the old format.
