### ISSUE TITLE
Bypass metadata extraction through configuration

### ISSUE THREAD

**Issue by lukasheinrich** [rucio/rucio#1773]
Motivation
----------

For some use-cases the default of exracting metadata for specific file extensions is undesired. E.g. to use `rucio upload` with ROOT files within an standalone container image that does not have the software of a specific experiment installed.

(partly discussed here: https://github.com/rucio/rucio/issues/1351) 

Modification
------------

allow to add configuration optiosn in the cfg file that list the file extensions for which metadata extraction should be performed. the defaults would stay as it is (extract GUID for root files) but it could be switched off

**Comment by bari12** [comment]
Any update on this? Is this still needed? #1351 was closed
