### ISSUE TITLE
Expose request details (e.g. FTS job ID) to the client

### ISSUE THREAD

**Issue by dciangot** [rucio/rucio#1786]
Motivation
----------
Clients should be able to retrieve request details (FTS jobID etc) for transfer monitoring purpose.

Modification
------------
Make results available in query_request (@api/request.py) into web/rest/request.py. 
If I have understood well the suggestion by @mlassnig .

**Comment by vingar** [comment]
@dciangot 
Which access pattern would you see to retrieve this information ?  `requestId` is very internal to Rucio and exposed at few places. Drafting the corresponding REST APIs and workflow would help.

**Comment by dciangot** [comment]
@vingar  In fact the idea is that a system using Rucio clients (e.g. CRAB for CMS user data) wants to keep track of the FTS job ID/IDs for a certain DID against a user defined RSE, only for debugging purpose at the moment.

In this sense I think the access pattern could be as complicated as it needs to be, e.g. first retrieve request ID for a DID and then to a second call to retrieve the request details.
An optimal solution instead, but probably too specific for the use case, would be that the details of the last request will be shown providing a set of (did, source_rse, destination_rse).

Does it make any sense for you?

P.S. using the MQ would be a possibilty too for this problem, but I fill like it is a general-enough problem that one may want to pass it directly through the client.

**Comment by vingar** [comment]
yes, it makes perfect sense.  I think the workflow will be from DID, RSE -> Rule -> RequestIds -> FTS jobs Ids.

Few things are already there at least in the rucio UI + rules CLIs for this purpose. It should be checked.

**Comment by dciangot** [comment]
For what I have understood the only missing part there is RequestIds -> FTS jobs, at list from CLI point of view.

So a minimal solution here is essentially the porting of  RequestIds -> FTS jobs step into CLI/python bindings from where it is already available in Rucio core. At least this is my understanding/opinion at the moment.

**Comment by vingar** [comment]
I had a look at the UI code showing the status of a rule (https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/static/rule.js) and there it calls `get_request_by_did` which corresponds to the REST call:

     https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/webpy/v1/request.py

I have the feeling that's what you need. Maybe some convenient clients and wrappers missing.

**Comment by dciangot** [comment]
Yes, I think that what we are looking for is to integrate the info of `get_request_by_did` with the info coming from `query_request` (*) in some form.

(*) https://github.com/rucio/rucio/blob/next/lib/rucio/core/request.py#L333

**Comment by dciangot** [comment]
mmm... btw, probably `get_request_by_did` it is enough alone. If I understand well the query made there. So probably it is really something minor that is missing. 
But I think that it is now more or less clear what I have to check.

**Comment by dciangot** [comment]
So, summarizing with a working plan: 
1. add a call here (*), or in another client if you prefer, like:
 ``` def get_request_by_did(self, name, rse, scope=None)```
this will use the rest call to: ```https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/webpy/v1/request.py```

2. Problem is that I have just checked that due to this (**), the request rest call is broken for CMS DIDs (containing `/`). So this is to be fixed before`1.` (that is pretty straight forward) can work.

How does it sound? Did I miss anything?

(*) https://github.com/rucio/rucio/blob/next/lib/rucio/client/didclient.py
(**) https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/webpy/v1/request.py#L38

**Comment by vingar** [comment]
About 1. 
With the current per resource logic, it should go in a new rucio/client/requestclient.py file.

2. looks fixable ;)

**Comment by dciangot** [comment]
> About 1.
> With the current per resource logic, it should go in a new rucio/client/requestclient.py file.
> 

ok then, I'll put in `rucio/client/requestclient.py`

> 2. looks fixable ;)

yeah, indeed :) do you prefer a separate issue for that?

**Comment by mlassnig** [comment]
Hi, yes, agree on a new `requestclient`. For 2 a new ticket would be helpful, thanks.

**Comment by bari12** [comment]
I think a new requestclient would be good as well. The concern I see a bit, also what Vincent said, that previously the requestId was a rather internal concept, but since we are exposing it already via the REST (For the WebUI fts-id linking), I think it is good to expose it properly via a client. Also it's a proper usecase to be able to access fts-ids for external monitoring.

**Comment by vingar** [comment]
from the described workflow, it looks not needed to interact with `requestId`

**Comment by bari12** [comment]
Yes you are right, it's not interacting, but exposing (primarily for the fts-id).
