### ISSUE TITLE
Bring S3 and Swift signature support in line with rest of code

### ISSUE THREAD

**Issue by jamesp-epcc** [rucio/rucio#1787]
Motivation
----------
Rucio has support for S3-style objectstore download and upload, using shared secrets (with boto and 's3cmd'), as well as native support for S3 signed URLs.

There are a few implications:
* Shared secrets, as the name implies, require distribution of the secrets to clients which limits its usefulness. We cannot guarantee confidentiality as shared secrets can leak easily.
* The code itself is still from early days of R&D and follows an old architecture.
* Swift is an S3-style compatible protocol, targeted to OpenStack instead of Amazon, which exists as an untested prototype.

In the meantime, URL signatures were implemented natively in Rucio, with a Google Cloud Storage signature plugin,  which are similar to S3 signatures. The first objective would be to revisit the S3 and Swift signatures and bring it in line with the remainder of the code, such that it can be used transparently by the replica core.

Modification
------------

**Comment by vingar** [comment]
One difference between the Google Cloud Storage signature plugin and S3/swift ones is the need to call an external service to generate the signed url. To no affect the performance on one of the most called APIs `list_replicas`, the signed urls operation has ben isolated in a dedicated endpoint. cf. ´lib/rucio/web/rest/objectstore.py´. For example, with the degradation of this signed url external service, the responses time can increase together with the number of simultaneous db sessions  resulting in less slots available on http frontends (snowball effect). A solution might be between the two approaches.

**Comment by mlassnig** [comment]
There's the possibility to sign S3 offline without having to contact an external service. This should work for both private S3 servers (because we control the private key) and for AWS (similar to the delegated credential loading we do for GCS).

**Comment by vingar** [comment]
Interesting. It looks new. For which S3 version ? spec ?  ceph (the most popular s3 object stores for ATLAS) is usually behind for new features unfortunately. And for swift ?

**Comment by jamesp-epcc** [comment]
I'm not sure if it's mentioned in the documentation, but my experimentation shows that the signing operations in the boto3 API work fully offline (they still work if I disable the network on my VM) but the ones in the old boto API (currently used by Rucio) don't. So it might be necessary to use boto3 if we want offline url signing, unless it can somehow be made to work with boto 2.
