### ISSUE TITLE
Support checking of tape staging status

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#1797]
Motivation
----------

Concern by CMS that data which is only on the tape buffer may not be migrated to tape before additional disk copies are deleted which could result in the loss of data.

Modification
------------

Undetermined, but as I understand it

- [ ] Add a new, optional, state "Waiting for tape check"
- [ ] FTS transfers to tape systems are put in this state when the transfer finishes
- [ ] A new daemon checks the state with the storage system, moves state to the one which can be picked up by the finisher

**Comment by bari12** [comment]
FTS is thinking about adding this to FTS; On hold until confirmation

**Comment by bari12** [comment]
Just updating tickets. FTS is implementing this at the moment. We will have to add a parameter to these jobs.
