### ISSUE TITLE
mode should be an RSE attribute

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#1804]
Motivation
----------

Right now the configuration of the reaper decides which mode of deletion is used. This causes us to run different types of reapers for no good reason. If the mode is an RSE attribute this is more flexible.

**Comment by bari12** [comment]
This is actually a change which is more relevant to #2444 since the algorithm needs to decide if to include greey RSEs or not.

**Comment by cserf** [comment]
The new reaper relies on the RSE attribute `greedyDeletion`, so I propose to close this ticket.
