### ISSUE TITLE
FTS3: align transfertool to use python bindings

### ISSUE THREAD

**Issue by dciangot** [rucio/rucio#1805]
Motivation
----------
Fix the mixture of REST call and python bindings present in the FTS3 transfer tool. 
Particular attention on testing and consistency check between REST response and binding ones. 

Modification
------------
 - Mainly integrating what was done for [user transfers](https://github.com/rucio/rucio/blob/next/lib/rucio/transfertool/fts3_myproxy.py) in the default tool
 - check for response equivalence w.r.t. REST response
 - mock_fts3 may be needed for a proper testing

**Comment by dciangot** [comment]
Issue to be solved with FTS people:
- the submission python api is missing the following file attributes:
  - `selection_strategy`
- and the following job attribute:
  - `s3alternate`

Opening a ticket to FTS support: [FTS Jira ticket](https://its.cern.ch/jira/browse/FTS-1339)

**Comment by dciangot** [comment]
Also, made a pull request to allow bulk status requests from the client (https://gitlab.cern.ch/fts/fts-rest/merge_requests/17)

**Comment by dciangot** [comment]
Requiring also to implement the following function in the FTS bindings:
- update priority
- query_latest
- set se status
- version

Needed before completing the migration

**Comment by bari12** [comment]
This is superseded by #2518 Closing
