### ISSUE TITLE
FTS3: proxy delegation at job submission

### ISSUE THREAD

**Issue by dciangot** [rucio/rucio#1806]
Motivation
----------
The default transfer submission flow is based on the assumption that the proxy has already been delegated by an external script.

For user transfers an integrated delegation is already in like [this](https://github.com/rucio/rucio/blob/next/lib/rucio/transfertool/fts3_myproxy.py#L345). And a standalone method in the transfertool is already available [here](https://github.com/rucio/rucio/blob/next/lib/rucio/transfertool/fts3.py#L89). 

A similar solution can be implemented also for the default submission [flow](https://github.com/rucio/rucio/blob/next/lib/rucio/core/transfer.py#L82) avoiding to keep a cron/script doing the delegation externally. This new behavior must be optional and available through a configuration parameter.

Modification
------------
2 steps needed here:
- align the fts transfertool code to use python bindings. Followed on #1805
  - check for response equivalence w.r.t. REST response
  - mock_fts3 may be needed for a proper testing
- do FTS job submission with the integrated delegation check available by a configuration parameter

**Comment by bari12** [comment]
Not relevant anymore :-)
