### ISSUE TITLE
add validator for traces

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#1834]
Motivation
----------

The tracer server accepts any kind of json send to it and expects clients to send the information using the correct schema. Sometimes a bug in a client can lead to an invalid trace that then can break any of the systems using the traces (monitoring, Kronos, etc.)

Modification
------------

Add a validator that listens on the ActiveMQ topic and constantly checks that necessary fields are set correctly or set at all. If something doesn't match the schema send out notifications.

**Comment by bari12** [comment]
Still something we should do. Might be something to look into together with @davidpob99 😄
