### ISSUE TITLE
Extend throttler to be able to throttle over ALL activities for a destination

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1836]
Motivation
----------
Right now throtteling is possible per `(activity, destination_rse)` tuple. However, it would be good for the tape carousel to be able to throttle per destination over all activities.

**Comment by cserf** [comment]
destination or source ?

**Comment by bari12** [comment]
Destination

**Comment by cserf** [comment]
See also #53

**Comment by hahahannes** [comment]
How would you change the behaviour? By a value in the config table ?

**Comment by hahahannes** [comment]
I think this can be handled after #2220 because the grouped FIFO will also throttle over all activites per destination. So it will be easy add it to the current FIFO way.

**Comment by cserf** [comment]
According to #2542, this is implemented. @hahahannes, can you confirm please ?

**Comment by hahahannes** [comment]
This should be fixed by #2726 because there I add the new way of changing between all the different modes.
