### ISSUE TITLE
Inconsistency in command-line options to specify RSEs

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#1839]
Motivation
----------

It’s difficult memorising command-line options when they are named differently across commands. `delete-rule` uses `--rse_expression`, `list-file-replicas` has both `--rse` and `--expression` (with different meaning), `get` has `--rse` but it actually takes an RSE expression.

Modification
------------

First it has to be decided whether it’s worth breaking the current CLI interface to fix this.

**Comment by bari12** [comment]
This should be consolidated. I would not be too afraid of backwards-compatibility, but maybe we should still add the new parameter, leave the old one in, but if it is used display some kind of message. A few (feature) versions later we then take it out. We used this concept already for several other CLI changes.

**Comment by mlassnig** [comment]
Much of it is historical due to the API itself, but we can start changing the clients and bring the API, REST, and core slowly up to speed. At least for the RSE parameter I would suggest for conciseness to always use `--rse` but always parse RSE expressions, and get rid of the `--rse-expression` or `--expression` extra arguments.

**Comment by vingar** [comment]
As rse expression can give a back a list, i.e. `--rses` looks more appropriate imo. starting with the same name for both `rse-expression` and `expression` would be already a good step.

**Comment by bari12** [comment]
Sounds good to me:
- `--rse` if it is really only 1 RSE
- `--rses` if it is an expression. Although --rses suggests a bit that you can enumerate them, which is not really true (`RSEA|RSEB|RSEC` would work but not `RSEA,RSEB,RSEC`)

**Comment by mlassnig** [comment]
But shouldn't we handle single RSE or multiple RSEs automatically? `--rse` is a basically a subset of `--rses` and having two different parameters is confusing.

**Comment by bari12** [comment]
We would have to go through it, in most cases `--rses` is ok. But in cases where you really only want one RSE, e.g. marking a replica as bad/lost, --rses doesn't really make sense, as it suggests a list, which doesn't work.

**Comment by mlassnig** [comment]
I would do `--rse` everywhere, and in case a list comes back instead of a single RSE fail to the client and tell "hey you selected more than one", instead of having two parameters. (In a way, like SQL cursors)

**Comment by vingar** [comment]
ah but are you proposing to always resolve RSE by expression ? Most of the time the RSE expression corresponds to the RSE name. It might be worth to check the implementation as this will be the most popular call then...

**Comment by bari12** [comment]
From a performance that should be fine, the expression is cached server-side, so it's not even going to the DB too much.

**Comment by vingar** [comment]
it's worth to check that even without the caching,  it does a simple lookup first against the rse table. Not sure the caching is enabled if memcached is not there and the memoization fallback will be most likely in memory per thread/process, which won't reduce that much the query rate.
