### ISSUE TITLE
Need a new PL/SQL procedure to insert rows in ACCOUNT_USAGE_HISTORY

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1878]
Motivation
----------
The original procedure was dropped in 2017 and was forgotten 😢 
We need a new procedure similar to the current ADD_RSE_USAGE procedure.

Note: Check how this is done in #524 as well.

**Comment by hahahannes** [comment]
Actually I thought that this table gets automatically filled by sqlalchemy?

**Comment by bari12** [comment]
Nope, apparently this was a procedure as well, which we deactivated in 2017.

**Comment by cserf** [comment]
The new procedure has been implemented.
