### ISSUE TITLE
Last python3 fixes for clients

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#1888]
Motivation
----------
Fix the last small changes to make the clients python3 compatible. This closes #819 
- didclient
- fileclient
- dq2client
- downloadclient

Modification
------------

**Comment by cserf** [comment]
You can ignore dq2client. It is deprecated and will be removed in less than 6 months.

**Comment by hahahannes** [comment]
downloadclient can be ignored also, because the last python3 problem is the round() function that behaves different in python2/3 but we decided to ignore this because of the incompatibility of the fix  `from builtins import round` (see #1845 )
