### ISSUE TITLE
Detaching CMS specific methods in transfertool

### ISSUE THREAD

**Issue by dciangot** [rucio/rucio#1895]
Motivation
----------
This is needed to let the development of user data transfers code separated from the RUCIO one.

Modification
------------
Talking in particular of using `importlib` (using configuration param) [here](https://github.com/rucio/rucio/blob/master/lib/rucio/transfertool/fts3_myproxy.py), for the following methods::
- user to DN mapping
- myproxy interactions

I would go with importing just the methods, since the case of mapping a user to a DN and then retrieving the corresponding proxy may have a more general use. In any case a feedback on this is very welcome.

**Comment by bari12** [comment]
Hi @dciangot I think this is not relevant anymore as well. Please re-open if I am wrong 😄
