### ISSUE TITLE
Wrong cms RSE name pattern used when attaching dids

### ISSUE THREAD

**Issue by sartiran** [rucio/rucio#1901]
Motivation
----------
in lib/rucio/common/schema/cms.py the RSE Name pattern is 

`^T[0-3]_[A-Z]{2}((_[A-Za-z0-9]+)+)$`

while the pattern for the rse property of ATTACHMENT is

`^([A-Z0-9]+([_-][A-Z0-9]+)*)$`

as a result when we add replicas to a CMS RSE whose name is not all in capitals (e.g. T1_UK_RAL_Buffer):
  * if we use `add_replicas` and the `attach_dids` it works fine
  * if we use `attach_dids` directly it fails with `InvalidObject`

Modification
------------
Just put the same regexp for the two patterns (PR coming)

**Comment by sartiran** [comment]
Created PR #1902 
Maybe we may want to test it on the CERN server before merging.

**Comment by bari12** [comment]
Hi Andrea,
You created this PR against the next branch (Thus it is treated as a feature). This will then only go in the Rucio 1.19.0 release in February 2019. Is this fine? Otherwise please re-create as a patch.
See https://github.com/rucio/rucio/blob/master/CONTRIBUTING.rst

**Comment by sartiran** [comment]
Hi Martin, 
ok sorry. I'm recreating the PR.

**Comment by sartiran** [comment]
Created #1904

**Comment by bari12** [comment]
That's against the **hotfix** branch 😄
I'll create the two PRs for **master** and **next**.

**Comment by bari12** [comment]
Although I just saw you based your development off the **hotfix** branch (instead of master). It's not super clean to merge it like that. It would probably work fine, but we should stick to the normal workflow here.

**Comment by sartiran** [comment]
I'm really sorry.. I've read the doc too quickly and understood patches go in hotfix (I do not know how, since is clearly stated). I'll recreate 2 PR one for next and one for master (both from a branch based on master, if I understand correctly)

**Comment by bari12** [comment]
Hi Andrea, no worries. The workflow we have is sadly not very simple for somebody new, since it is somewhat different than most projects do it, so I can understand the confusion. Just ping me on Slack if you have any question about the setup. 😄
