### ISSUE TITLE
Undertaker handling of very larger rules

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#1909]
Motivation
----------
For very large rules, the undertaker is blocked a long time to delete them which leads to long backlogs.

Modification
------------
Instead, for rules > 10k files it could just flag the rule for expiration and set the timeout of the dataset 1 day in the future. Doing this, the judge-cleaner will take care of the rule deletion and thus free up the undertaker to do its job.

**Comment by cserf** [comment]
Adding high priority flag cause this is causing major pain now
