### ISSUE TITLE
rucio list-account-usage does not return output

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#191]
Motivation
----------
The CLI command rucio list-account-usage does not return any output.

**Comment by cserf** [comment]
Cannot reproduce : 
`
rucio list-account-usage
usage: rucio list-account-usage [-h] [--rse RSE] usage_account
rucio list-account-usage: error: too few arguments

rucio list-account-usage xyz
+------------------------------+------------+---------+--------------+
| RSE                          | USAGE      | LIMIT   | QUOTA LEFT   |
|------------------------------+------------+---------+--------------|
| xxx      | 25.254 GB  | 0.000 B | 0.000 B      |
| yyy         | 2.564 GB   | 0.000 B | 0.000 B      |
| zzz | 144.282 GB | 0.000 B | 0.000 B      |
+------------------------------+------------+---------+--------------+
`

**Comment by bari12** [comment]
Weird, I don't know what I did then. Can be closed I guess.
