### ISSUE TITLE
Rucio missing kerberos dep

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#1910]
Motivation
----------
I'd expect Rucio to install on a fairly plain RHEL7 box with the following:

```
virtualenv-2 rucio-doma
cd rucio-doma
. bin/activate
pip install rucio-clients
```

However, when I do this locally, I get:

```
$ rucio
Traceback (most recent call last):
  File "/home/cse496/bbockelm/software/rucio-doma/bin/rucio", line 61, in <module>
    from rucio.client.client import Client
  File "/home/cse496/bbockelm/projects/rucio/lib/rucio/client/__init__.py", line 9, in <module>
    from rucio.client.client import *  # NOQA pylint: disable=wildcard-import
  File "/home/cse496/bbockelm/projects/rucio/lib/rucio/client/client.py", line 17, in <module>
    from rucio.client.accountclient import AccountClient
  File "/home/cse496/bbockelm/projects/rucio/lib/rucio/client/accountclient.py", line 21, in <module>
    from rucio.client.baseclient import BaseClient
  File "/home/cse496/bbockelm/projects/rucio/lib/rucio/client/baseclient.py", line 39, in <module>
    from requests_kerberos import HTTPKerberosAuth
ImportError: No module named requests_kerberos
```

That is, the `requests_kerberos` dep appears missing.  Note this is with version 1.18.7.

Modification
------------
Either the base client should silently ignore the missing kerberos client (until someone tries to use it) or it should be added to `setup.py`.

A simple `pip install requests_kerberos` seems to fix the problem.

**Comment by bari12** [comment]
Kerberos is handled as an extra in setup.py so you would have to do a `pip install rucio[kerberos]` which installs `['kerberos>=1.2.5', 'pykerberos>=1.1.14', 'requests-kerberos>=0.11.0']`
I am not sure why it trys to load kerberos modules, in the baseclient it basically checks if `requests_kerberos` is available and if yes, loads HTTPKerberosAuth. Might be some issue with a very old requests_kerberos version?

**Comment by bbockelm** [comment]
Ah-ha!

Looks like an old client has snuck into `PYTHONPATH`.  Line numbers above don't match with the current code.
