### ISSUE TITLE
Improvements in the Lifetime Model pages

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1923]
Motivation
----------
- Wrong title in lifetime_exception should be fixed
- Need a button to bulk update the WAITING requests

**Comment by bari12** [comment]
@dchristidis Are you using the WebUI to approve Lifetime exceptions? @cserf and I are thinking if we need the Bulk update, which would also require a new rest call.

**Comment by dchristidis** [comment]
No, I am not using the Web UI for managing the Lifetime Model.

**Comment by bari12** [comment]
Ok, then just the title change is sufficient. ✅
