### ISSUE TITLE
Injector can crash when split_container option is enabled

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#1976]
Motivation
----------
The `split_container` option is enabled when requests on containers are done via R2D2. It creates rules on the constituent datasets of the container instead of a single rule on the container. 
- It can trigger `IntegrityError` in the case a rule for scope, name, account, rse_expression already exists. 
- Similarly the same error can be raised if 2 constituents contain the same datasets.

Modification
------------
To handle the first issue, the injector must check if a rule on scope, name, account, rse_expression already exists. To handle the second one, it should make a set from the list returned by `list_child_datasets`.

**Comment by bari12** [comment]
The check if a rule exists (uniqueness) is already done. The missing part is the uniqueness of list_child_datasets
