### ISSUE TITLE
Remove DownloadClient.download_file_from_archive and rsemanager.download

### ISSUE THREAD

**Issue by TWAtGH** [rucio/rucio#2021]
Motivation
----------

Modification
------------

**Comment by bari12** [comment]
Would be good to remove this and get it into the 1.20 release, as it creates some confusion.
There is some inconsistency there though, as we remove `rsemanager.download` (moved to downloadclient) but still use `rsemanager.upload` -> Should make a plan to remove it there too.

**Comment by TomasJavurek** [comment]
I think, we can just remove it without touching any other part of the code.

**Comment by TWAtGH** [comment]
Maybe but please check bin/rucio for something like `--archive-file` option

**Comment by TomasJavurek** [comment]
right:
https://github.com/rucio/rucio/blob/master/bin/rucio#L988

**Comment by bari12** [comment]
`download_file_from_archive` has been removed. `rsemanager.download` is still there, needs to be removed later.
