### ISSUE TITLE
Incomplete XML returned when calling list_replicas with metalink option

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#2029]
Motivation
----------
Assuming that the DID exists, this command returns a broken XML where the closing tag is missing.
It is caused by using a RSE expression that returns no RSEs
```shell
ReplicaClient().list_replicas([{'name': 'file_LMXZHCXRHS', 'scope': 'data13_hip'}], rse_expression='test=True', metalink=True)

<?xml version="1.0" encoding="UTF-8"?>\n<metalink xmlns="urn:ietf:params:xml:ns:metalink">\n
```

Modification
------------

**Comment by bari12** [comment]
@mlassnig please have a look if this is still relevant; Close if not.

**Comment by bziemons** [comment]
@bari12 it is still relevant, can I take it?

**Comment by bari12** [comment]
Yes please, I think it is still relevant.
