### ISSUE TITLE
Reaper silently excludes RSEs based on soon-to-be-deprecated RSEUsage counters

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#2030]
Motivation
----------

[`core.rucio.rse.sort_rses()`](https://github.com/rucio/rucio/blob/master/lib/rucio/core/rse.py#L146) will silently excludes RSEs that don’t have either an `srm` or a `gsiftp` counter. The former might not exist in the future as sites move away from SRM and the latter was renamed to `json`. Additionally, the long-term plan is to drop the individual counters and solely use the new `storage` one.

This was investigated and reported by @cserf.

Modification
------------

Modify the query so that it only filters against the `storage` counter.

**Comment by bari12** [comment]
Could you maybe have a look on #1917 as well? It sounds quite related.

**Comment by dchristidis** [comment]
Duplicate of #1729.
