### ISSUE TITLE
Conveyor sometimes submit transfers without space token for SRM protocol

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2045]
Motivation
----------
Some sites reported that some 3rd party copy to their SRM are failing because no destination space token was specified despite the fact that the space token is properly defined in the extended attributes of the protocol. The problem is not systematic and only happens from time to time. It affects both single and multi-sources transfers.
This needs to be fixed.

**Comment by bari12** [comment]
I had a quick look on this (without conclusion) and think this has something to do with the protocol (scheme) caching in the conveyor. The spacetoken is part of the extended attribute, it might be that (for some reason) it gets cached without one and recalled later (expecting one) - to be confirmed.

**Comment by cserf** [comment]
Due to session reuse in FTS. Not a Rucio bug :-)
