### ISSUE TITLE
Change primary key order for the replicas table

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#2102]
Motivation
----------

Cf. 
https://github.com/rucio/rucio/blob/master/lib/rucio/db/sqla/models.py

`_table_args = (PrimaryKeyConstraint('rse_id', 'scope', 'name', name='REPLICAS_PK'),`

Modification
------------

`_table_args = (PrimaryKeyConstraint('scope', 'name', 'rse_id'; name='REPLICAS_PK'),`

**Comment by bari12** [comment]
This is a duplicate of #1749 - it's already merged. 😄
