### ISSUE TITLE
Add eventType and usrDN parameters to CLI up/download

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#211]
Motivation
----------

When the pilot uses the rucio mover the traces are sent out as type 'download' and with the account 'pilot'. This messes up the monitoring in the as they will show up as 'CLI download' in the Dashboard and we are also losing the user information.

Modification
------------

Add two new paramters the rucio download cli command: `--usrdn` and `--eventType` which will then be propagated to the traces.

Expected behavior
-----------------

**Comment by mlassnig** [comment]
Proposal for consistency:

--trace-user
--trace-event-type
