### ISSUE TITLE
Email missing from list identities

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#2142]
Motivation
----------
Looking at the output from list_identities in the account client, it does not return the e-mail address for the identity. However, the set identity takes this parameter and the field exists in the database.  Is this an oversight or is it intentional?

The underlying motivation for this is that I'm trying to migrate the accounts and identities from one server to another.

Modification
------------

**Comment by bari12** [comment]
@hahahannes can you please have a look on this.
In https://github.com/rucio/rucio/blob/ca3166ff5e63b7f24b61236646c2aa747f8aa40b/lib/rucio/core/account.py#L180
we probably need to join models.IdentityAccountAssociation with models.Identitiy to add the email there.
