### ISSUE TITLE
Test reaper console script

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#2149]
Motivation
----------

The reaper console script `rucio-reaper` is not tested in the testsuite.

Modification
------------
- Add test for the reaper console script.
- Install the environnement with `python setup.py develop` in the docker env to have the generated console scripts available in the docker.
- Extend the reaper argparse method and the reaper tests to validate the argparse main method and console script.

**Comment by bari12** [comment]
Before you go through the effort, we should decide if we want to move all the bin/ scripts to console scripts, or everything back to bin/
Is there any major added benefit of the console_scripts? We had one issue where a dependency conflict was only affecting the console_scripts, not the bin/ scripts. So we should get this consistent in one way or the other.
