### ISSUE TITLE
Symlink as a new storm protocol

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#2160]
Motivation
----------
StoRM sites have an effective way of getting a file from their shared FS. In such case, rucio shouldn't try to do direct copy for local reads. 

Modification
------------
introduce a new protocol imitation, that will create a symlink in place of communicating and copying a file from a storage.

**Comment by mlassnig** [comment]
I don't think this can be made generic, but I'm happy to be proven wrong ;-) The symlinking itself is simple enough, but for StoRM you'll need the additional webdav/etag lookup.

So, something like `storm://` should be perfectly reasonable (unless you can find a nice way to make it generic, then it would be something like `ln://`)
