### ISSUE TITLE
fts-source-strategy configurable by activity

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2161]
Motivation
----------
The conveyor supports `--fts-source-strategy` option to specify which option should be chosen for the sources. This option is the same for all the transfers processed by a given conveyor instance. It would be better to be able to specify different options for different activities.

Modification
------------
Introduce a default `default-fts-source-strategy` in the configuration table as well a `activity-fts-source-strategy`, so that every activities can use a different strategy.

**Comment by bari12** [comment]
I wonder if we should make this configurable via the config table?

**Comment by mlassnig** [comment]
> I wonder if we should make this configurable via the config table?

We should. IMHO all configuration that is not absolutely necessary to make a connection to the rucio server (client side), and to make the database connection (daemon, server side), should be moved into the config tables. New configs should not go into the .cfg

**Comment by bari12** [comment]
The `--fts-source-strategy` makes sense as an override, but per default I think it just should come from the config table. But re-reading the ticket, I guess that's what @cserf meant anyway.

**Comment by cserf** [comment]
I was thinking about completely getting rid of the `--fts-source-strategy` and just use the config table. If one has 2 ways to specify the source strategy, that's not obivious which one has the precedence on the other.

**Comment by bari12** [comment]
It might make sense to have both ways, if we just want to test a strategy at one conveyor, without impacting all of them. (Thus command line has precedence) - But I am not really sure if it is needed for the source selection strategy.
