### ISSUE TITLE
We need more verbosity of logger in rsemgr and protocols

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#2168]
Summary
-------------

we observed following behaviour:

2019-02-08 06:21:34| 23631|FileHandling| Ski2019-02-08 05:22:59| 24559|rucio_sitemo| StageOut, attempt 1/2
2019-02-08 05:22:59| 24559|rucio_sitemo| _stageOutApi: {'no_register': True, 'path': 'panda.um.group.phys-exotics.16728385.XAMPP._000681.root', 'guid': '7dee6f62-e341-4ddd-9a7f-2952a32ebafb', 'did_scope': 'panda', 'rse': 'IN2P3-LAPP_SCRATCHDISK'}
2019-02-08 05:23:00| 24559|rucio_sitemo| Preparing upload for file panda.um.group.phys-exotics.16728385.XAMPP._000681.root
2019-02-08 05:53:00| 24559|rucio_sitemo| StageOut, attempt 2/2
where the logger message between the two attempts is not sufficient to understand the problem. As a consequence, pilot fails later with:

PilotException: PilotException: 1220: stageOut with API failed:  The requested service is not available at the moment.
Details: An unknown exception occurred
Code details
-----------------

the message starting with ‘Preparing upload …’ originates from Rucio’s upload client: https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L133
it didn’t reach the next logger message that is on line: https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L193

But on 60 lines between, we are calling rsemgr and protocols, which I suspect from failing somewhere without proper raise or logger message. The logger level is set to ‘DEBUG’. Note that srm protocol is the first priority one for the w_lan activity.

Writing a job log into the same destination from the same job passed with no problems, thus most probably, there was a problem with the file itself.

Solution
-----------

we should expand logger messages in upload client on these lines at the first place. Secondly, we should investigate rsemgr and protocols for raising exceptions and let them provide more info to logger if possible.

**Comment by TWAtGH** [comment]
The upload client part will be improved with #3084 
The rsemgr/protocol part will be improved with the rsemgr overhaul.
So I close this one
