### ISSUE TITLE
PostgreSQL alembic upgrade problems

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2212]
Motivation
----------

(1)

Example:
```
sqlalchemy.exc.DataError: (psycopg2.DataError) invalid input value for enum "BAD_REPLICAS_STATE_CHK": "T"

 [SQL: 'ALTER TABLE bad_replicas ADD CONSTRAINT "BAD_REPLICAS_STATE_CHK" CHECK (state in (\'B\', \'D\', \'L\', \'R\', \'S\', \'T\'))']
```

In PSQL we cannot drop the constraint and create it anew, instead we have to alter the enum of the constraint:

```
ALTER TYPE "BAD_REPLICAS_STATE_CHK" ADD VALUE 'T' AFTER 'S';
ALTER TYPE "RULES_NOTIFICATION_CHK" ADD VALUE 'P' AFTER 'C';
```

(2)

Foreign keys are a hard dependency in PSQL, we cannot simply drop an index. This is now a problem with:
```
SOURCES_REPLICA_FK
```

To fix the replicas primary key migration:
```alter table sources drop constraint "SOURCES_REPLICA_FK";```
```alter table replicas drop constraint "REPLICAS_PK";```
```alter table replicas add primary key (scope,name,rse_id);```
```alter table sources add constraint "SOURCES_REPLICA_FK" FOREIGN KEY (scope, name, rse_id) REFERENCES replicas(scope, name, rse_id);```

**Comment by illingwo** [comment]
This still isn't quite right:

```
dune_rucio_prod=> ALTER TYPE 'BAD_REPLICAS_STATE_CHK' RENAME TO 'BAD_REPLICAS_STATE_CHK_OLD';
ERROR:  syntax error at or near "'BAD_REPLICAS_STATE_CHK'"
LINE 1: ALTER TYPE 'BAD_REPLICAS_STATE_CHK' RENAME TO 'BAD_REPLICAS_...
                   ^
```

Those need to be double quotes, not single (or omitted entirely).

**Comment by illingwo** [comment]
It's worse than that. This won't work at all:

```
ALTER TYPE "BAD_REPLICAS_STATE_CHK" RENAME TO "BAD_REPLICAS_STATE_CHK_OLD";

ALTER TABLE bad_replicas ADD CONSTRAINT "BAD_REPLICAS_STATE_CHK" CHECK (state in ('B', 'D', 'L', 'R', 'S', 'T'));

ALTER TABLE bad_replicas ALTER COLUMN state TYPE 'BAD_REPLICAS_STATE_CHK';

DROP TYPE 'BAD_REPLICAS_STATE_CHK_OLD';

```

It renames the enum, tries to add a check constraint to the column, which fails because the column type is still the enum, then it would try to change the column type to a non-existent type, which would fail if it ever got that far.

**Comment by illingwo** [comment]
I think this works:

```
        if context.get_context().dialect.name == 'postgresql': 
            # For Postgres the ENUM Type needs to be changed to the new one and the old one needs to be dropped 
            op.execute('ALTER TYPE "BAD_REPLICAS_STATE_CHK" RENAME TO "BAD_REPLICAS_STATE_CHK_OLD"')  # pylint: disable=no-member 
            new_type = sa.Enum('B', 'D', 'L', 'R', 'S', 'T', name='BAD_REPLICAS_STATE_CHK') 
            new_type.create(op.get_bind()) 
            op.execute('ALTER TABLE bad_replicas ALTER COLUMN state TYPE "BAD_REPLICAS_STATE_CHK" USING state::text::"BAD_REPLICAS_STATE_CHK"')  # pylint: disable=no-member 
            op.execute('DROP TYPE "BAD_REPLICAS_STATE_CHK_OLD"')  # pylint: disable=no-member 
        else: 
            drop_constraint('BAD_REPLICAS_STATE_CHK', 'bad_replicas', type_='check') 
            create_check_constraint(name='BAD_REPLICAS_STATE_CHK', source='bad_replicas', condition="state in ('B', 'D', 'L', 'R', 'S', 'T')") 
```

**Comment by mlassnig** [comment]
Thanks @illingwo! I'm currently rewriting all the alembic migrate scripts (now properly, via https://github.com/rucio/rucio/issues/2257) and was stumped by this as well.
