### ISSUE TITLE
Exception when calling core.replica.list_replicas() with a lengthy list of dids

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#2216]
Motivation
----------

```
>>> from rucio.daemons.auditor import process_output
>>> process_output('…')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rucio/daemons/auditor/__init__.py", line 188, in process_output
    lost_pfns = [r['rses'][rse][0] for r in list_replicas(lost_replicas)
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 327, in new_funct
    raise DatabaseException(str(error))
DatabaseException: Database exception.
Details: (cx_Oracle.DatabaseError) ORA-00600: internal error code, arguments: [qcscbndv1], [65535], [], [], [], [], [], [], [], [], [], []
 [SQL: u'SELECT /*+ INDEX(DIDS DIDS_PK) */ atlas_rucio.dids.scope AS atlas_rucio_dids_scope, …
```

Note that this is not an ordinary case. The file used in this example has about 41k lost files.

Originally I was chunking on the Auditor’s side, but I was recommended against that.

Modification
------------

**Comment by bari12** [comment]
How many files is this list long?

**Comment by bari12** [comment]
Just following up on old tickets: The chunking should be done on the auditor side. The list_replicas method here is a core function, which should not need protection from other core/daemon calls - only on the API level. Thus please chunk this in the daemon itself.
