### ISSUE TITLE
Throttler mechanic to release transfers based on a strategy (FIFO)

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2220]
Motivation
----------
Right now, the throttler releases transfers simply based on time. FIFO. For the Tape Carousel activity, it is necessary to release them in a smarter way: Grouped FIFO. This essentially means, if a transfer is being released, it should also release all the transfers of the same dataset, so they are submitted to FTS in the same time-window to allow subsequent grouping on FTS side, and thus on the tape system.

**Comment by mlassnig** [comment]
(1) I wonder if we also need something in the submitter, since the decision should be on the tuple (src,dst,dataset). Right now, I don't see it, but we should keep it in mind.

(2) The "deadline" until datasets from tape are to be released should be configurable via core.config, with a default of 1 hour.

**Comment by mlassnig** [comment]
Oh, the deadline can be different per RSE.

**Comment by hahahannes** [comment]
How should the chosen strategy be configured? In the cfg file or config table or as daemon argument?

**Comment by hahahannes** [comment]
Seems like MySQL has problems with the original version of core/request:release_waiting_requests as well my new query for grouped FIFO. 

### LIMIT and IN not supported together
- `This version of MySQL doesn't yet support 'LIMIT & IN/ALL/ANY/SOME subquery'`
- It seems like mysql never supported the query for core/request:release_waiting_requests
`UPDATE requests SET state=%s, updated_at=%s WHERE requests.id IN (SELECT requests.id AS requests_id \nFROM requests \nWHERE requests.dest_rse_id = %s AND requests.state = %s ORDER BY requests.requested_at ASC \n LIMIT %s FOR UPDATE)`
- this means that the throttler is not working with mysql

### Updating table while selecting from it
- `You can't specify target table 'requests' for update in FROM clause`
