### ISSUE TITLE
Downloadclient should skip non-root protocols when download zips

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2226]
Motivation
----------

If root protocol is available according to the list_replicas reply, skip all non-root protocols to minimise the effect of download+extract.

**Comment by bari12** [comment]
This is no longer needed due to #2313 ?

**Comment by TWAtGH** [comment]
In the current implementation the download priories the root download (no explicit extraction) if:
1. the file is not in a zip that will be downloaded anyway (e.g., zip is prio 1 for another file)
2. the file is not in a zip with at least 10 other files that are needed

This decision is made there:
https://github.com/rucio/rucio/blob/master/lib/rucio/client/downloadclient.py#L1337
