### ISSUE TITLE
RSE Abacus needs to fill rse_usage_history

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2253]
Motivation
----------

For installations without Oracle we need a flag such that the RSE abacus reports the RSE usage every hour into the rse_usage_history table.  (e.g., --enable-history)

**Comment by hahahannes** [comment]
Should I also add it to the account abacus ?

**Comment by bari12** [comment]
Yes please, if we do it for one we might as well do it for both. 😄

**Comment by hahahannes** [comment]
Should I add the history table to models.py or use `models.RSEUsage.__history_mapper__.class_` to access the history table? I think, adding it to models.py is better as we are not using the sqlalchemy versioned table?

**Comment by bari12** [comment]
The plan was to change all of these tables with #2063 anyway.
However I think we should change them explicitly in this separate PR and not intermix them, just get's easier to track. So for now, keep using the history mapper.
