### ISSUE TITLE
Docker: Remove reference for CERN services in the demo image

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2264]
Motivation
----------
The demo image contains reference to service hosted at CERN. Need to be removed

**Comment by rak108** [comment]
can i take this up?

**Comment by mlassnig** [comment]
Sure, but best check with @tbeerman how this should be done

**Comment by DhruvSondhi** [comment]
If it's not a problem can I work on it?

**Comment by tbeerman** [comment]
I think we can close this ticket. There is no demo image anymore. But maybe @cserf can comment, since he opened this issue.

**Comment by bari12** [comment]
Closing it :-)
