### ISSUE TITLE
Declare lost suspicious log files

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2282]
Motivation
----------
The log files that have been declared suspicious a lot of times can be safely declared `BAD`. For now, this is done as a probe, but eventually it must be done by a dedicated daemon that apply different policies based on the project/datatype/nb_replicas.

**Comment by dchristidis** [comment]
I am guessing that this can be addressed by Christoph’s QT. Do we want to keep this issue open?

**Comment by cserf** [comment]
Agree to have a more generic issue that will be addressed by Christoph's QT
