### ISSUE TITLE
Collection following mechanism

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2304]
Motivation
----------
Many operations can affect a collection (dataset/container) or its rules that can have effects on the end-users:
- File loss : The files that are lost or corrupted are removed from the datasets which change the content of the dataset. Often these events has unnoticed but can have bad consequences  on physics analyses (e.g. less statistics)
- Dataset erased : The dataset is erased because it was buggy or superseded  by a new version
- Lifetime expiration : All the datasets have finite lifetime. In case the lifetime of a dataset expires, the users can ask for an extension of the lifetime.
All these operations are run without notifying the users, or when a notification happens it is via the use of generic mailing list that might not reach the users really interested in these events. 

Modification
------------
We propose here a new mechanism where users can "follow" the events affecting a dataset or container. Any event mentioned above affecting one the the dataset followed, will trigger a notification to the user (e.g. daily email summarizing all the events)

**Comment by viveknigam3003** [comment]
I'll try to tackle this one.
