### ISSUE TITLE
Functional download/upload tests with xrootd containers

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2311]
Motivation
----------
At the moment we only have very limited upload/download tests either using mock calls or direct posix protocols. One possibility to expand these to actualy functional tests would be to use xrootd docker containers and start up two xrootd storages in the test environment. This would allow us to test upload/download also with different protocols, such as gfal, which would also help enormously to validate gfal for python 3.6.

**Comment by rcarpa** [comment]
I'm working on increasing the coverage of the tests in test_download.py. I need better tests to be able to work more confidently on #4153 . Let me know if I risk to do duplicate work.
