### ISSUE TITLE
Global account qutoas

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2315]
Motivation
----------
Currently Rucio only supports local quotas. E.g. an account_limit for an account on a specific RSE. The idea of this feature would be to allow quotas on a set of RSEs. E.g. an aggregated limit for an account on all RSEs in the UK (`country=uk`)

Modification
------------
This requires changes in the replication rules quota checking and a whole system around calculating/managing these global quotas in an efficient way.

**Comment by hahahannes** [comment]
As discussed, the RSE selector in core/rse_selector.py needs to updated to first check local quotas and then global quotas. If a RSE does not have quota left from either local or globa quotal, it will get removed from the list of possible destination RSEs.

It still needs to be discussed how the free space should be calculated/displayed to the user.

**Comment by hahahannes** [comment]
How should I modify the CLI commands to display the limits and usage?
```
rucio list-account-usage root
+-------+---------+---------+--------------+
| RSE   | USAGE   | LIMIT   | QUOTA LEFT   |
|-------+---------+---------+--------------|

rucio list-account-limits root
+-------+---------+
| RSE   | LIMIT   |
|-------+---------|
```
Should I just leave it as it is and only show local quota because it might be confusing to mix it with global quotas? On the other side, it might be weird to see a rule failing but to also have enough (local) quota

**Comment by bari12** [comment]
We could add the rse-expressions of the global quotas there as well (similar rows like the others) but this might be confusing. It might be better to separate this completely and have, essentially two tables.

**Comment by hahahannes** [comment]
Yes, I was thinking the same. It is too messy in one table, also because the global quota is independent from one specific RSE
