### ISSUE TITLE
Extend Kronos to update # of accesses of files

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#236]
Motivation
----------
Kronos already updates the accessed_at of each file. Additionally it should also update the # of accesses.

**Comment by cserf** [comment]
@tbeerman , I can see the access_cnt is not null for certain DIDs. So I guess it has been implemented. Can you confirm please ?

**Comment by tbeerman** [comment]
Yes, it's implemented but I used the wrong issue number on the PR so it's not linked here. But the issue can be closed.
