### ISSUE TITLE
Using subprocess instead of commands module in submit-pull-request

### ISSUE THREAD

**Issue by kaustubhhiware** [rucio/rucio#2378]
Motivation
----------
I recently submitted a PR during which I ran into an error while executing 

```
$ ./tools/submit-pull-request
```
as mentioned in the [Contribution guide](https://rucio.readthedocs.io/en/latest/contributing.html). The error was 

```
Traceback (most recent call last):
  File "./tools/submit-pull-request", line 14, in <module>
    import commands
ModuleNotFoundError: No module named 'commands'
```

I use Arch linux, where the default python version is 3.x. A quick google search led me [to Arch's subforum](https://bbs.archlinux.org/viewtopic.php?id=125971), according to which the `commands` module is unavailable in python3, thus for submitting a PR what actually worked was

```
python2 ./tools/submit-pull-request
```

Since Python2 will not be maintained post [2020](https://pythonclock.org/), I would suggest changing the default implementation for python3 compatibility, in the longer run that would be required anyway.

Modification
------------

Using `subprocess` module instead of `commands` in [`./tools/submit-pull-request`](https://github.com/rucio/rucio/blob/master/tools/submit-pull-request)

**Comment by kaustubhhiware** [comment]
Please let me know if I can begin working upon this, if the contributors feel this is a worthy change.

**Comment by bari12** [comment]
Yes, please go ahead 😉
