### ISSUE TITLE
Recreate archived dataset

### ISSUE THREAD

**Issue by rodwalker** [rucio/rucio#2393]
Motivation
----------
It might be desirable to recreate the original dataset from the zip files, or at least amusing in a low-priority kind of way. All the metadata for constituent files and dataset exists.

Modification
------------
rucio client pulls the zip file, unpacks, verifies and then stores the constituent replicas. It would take the constituent dataset as the argument and cycle over the zip files so as to not use too much disk space. It should be recursive, so only recovering the files without a replica.
To do this at scale would need some prodsys development, but I am not sure we will ever need that. Some way to do it manually might come in handy though.

Cheers,
Rod

**Comment by bari12** [comment]
Hi Rod,
At one point we were discussing of looking into third_party_copy support of zip constituents. xroot/FTS would obviously have to support that. But if this is the case, we could essentially create the replicas via transfer requests and just nee some logic around that.
The timescale of this is a different question though.

**Comment by bari12** [comment]
Is this still something which should be considered? It didn't happen in 2+ years now and I am rather tempted to close this.

**Comment by rodwalker** [comment]
Hi,
I can`t see it happening and is not completely necessary. We can read the
replica from zip, so it is more important that this is a first class
replica, e.g. not a lost file if there is still an archive copy.
The download, unzip, upload method is easy to do if we really need the
original files. Dimitrios already did this semi-manually for some data16.

Cheers,
Rod.
