### ISSUE TITLE
checksum after download

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#2399]
Motivation
----------
the checksum is not yet checked after downloading a file. This is especially important for pilot.

Modification
------------
make it False by default:
https://github.com/rucio/rucio/blob/master/lib/rucio/client/downloadclient.py#L289

**Comment by TWAtGH** [comment]
The PFN download doesn't query the Rucio server for PFN's so it doesn't have the checksums. Thats why `ignore_checksum=True` by default. And in my opinion it should stay like this.

**Comment by TomasJavurek** [comment]
I would like to see chacksum after any download, no matter on download method. But I agree, that we don't want to add another query to Rucio DB. So, only option would be to make it optional, and pass the checksum from pilot, user etc. Pilot should have the src checksum stored in fspec object.
