### ISSUE TITLE
More verbositiy from portocols for downloads/uploads

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#2408]
Motivation
----------
We see in many cases in traces just following on the output:
stageIn with API failed: None of the requested files have been downloaded.
which is not explanatroy enough.

Modification
------------
Pilot propagates to traces an exception from Rucio. Fristly, we need to know whether this happens only for xrootd protocols and how to increase the verbosity.

**Comment by bari12** [comment]
Isn't this a duplicate from #2168 ?

**Comment by TomasJavurek** [comment]
Might be. Not sure yet. This is in traces, while the information can be still somewhere in the logs. It even might be, that this is actually more ticket to pilot than Rucio.

**Comment by TomasJavurek** [comment]
But thx for pointing to the other ticket here. Can we link them together somehow?

**Comment by TWAtGH** [comment]
#2168 is about the logging messages while this one aims for more details in the traces.
We could maybe do a single issue for this. I think the complete error handling in the download and upload client should be overhauled.

**Comment by TWAtGH** [comment]
#2953 
Can we close this? Log verbosity should actually be fine.
