### ISSUE TITLE
Fixes to atlas config template

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#2414]
Motivation
----------

The current configuration template for atlas at `etc/rucio.cfg.atlas.client.template` doesn't work out of the box.

Modification
------------

A working template (client section only):

```
[client]
rucio_host = https://voatlasrucio-server-prod.cern.ch:443
auth_host = https://voatlasrucio-auth-prod.cern.ch:443
ca_cert =
client_cert = $X509_USER_PROXY
client_key = $X509_USER_PROXY
client_x509_proxy = $X509_USER_PROXY
request_retries = 3
auth_type = x509
```

It would also be good to explain the configuration in the docs, I couldn't find anything about it there.

**Comment by TomasJavurek** [comment]
Config file was changed according to David's proposal. Documentation needs to be done still.
