### ISSUE TITLE
Read the docs out of date

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#242]
Motivation
----------
The CLI examples here no longer match the rucio client https://rucio.readthedocs.io/cli_examples.html

Modification
------------

So far I've found that "add" and "list" are no longer available, replaced by more specific commands,

Expected behavior
-----------------

**Comment by bari12** [comment]
Thanks for the report @ericvaandering, we are currently rebuilding the entire documentation to get rid of errors like this.

**Comment by bari12** [comment]
This is a duplicate now of #572 
Closing this ticket as we use the other one to track the changes.
