### ISSUE TITLE
problems upgrading to latest mysql/mariadb version

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#2421]
Motivation
----------
I am trying to use the latest mysql version 8 which results in multiple erros when trying to setup the schema via running the tests in the docker dev environment.
This is needed for #2220.

Modification
------------
### problem with loading the authentication plugin
- `Unable to load authentication plugin 'caching_sha2_password'.`
- solved by `--default-authentication-plugin=mysql_native_password`

### too long primary keys
- `Specified key was too long; max key length is 3072 bytes`
- solved by `--character-set-server=latin1`

### syntax error in setting up the rules table
- `You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IS NOT NULL`
- solved by escaping 

### missing index while applying upgrade 22d887e4ec0a
- `Failed to add the foreign key constraint. Missing index for constraint 'SOURCES_REPLICA_FK' in the referenced table 'replicas'") [SQL: u'ALTER TABLE sources ADD CONSTRAINT SOURCES_REPLICA_FK FOREIGN KEY(scope, name, rse_id) REFERENCES replicas (scope, name, rse_id)']`
- solved by changing the primary key while upgrading the replicas table

**Comment by mlassnig** [comment]
had to revisit this, mysql5 support must not be lost ;-)
