### ISSUE TITLE
Removing reference to  https://its.cern.ch/jira/browse/RUCIO in rucio clis

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#243]
Motivation
----------
We should replace https://its.cern.ch/jira/browse/RUCIO by the github issue link in the client code

2017-11-30 16:01:50,357 ERROR [Rucio exited with an unexpected/unknown error. Please rerun the last command with the '-v' option and submit a ticket with all the necessary information at https://its.cern.ch/jira/browse/RUCIO]

**Comment by bari12** [comment]
I wonder if we should have something VO specific here, configurable in rucio.cfg.

**Comment by mlassnig** [comment]
Rucio support URL and Experiment support URL. Makes sense to me.

**Comment by vingar** [comment]
maybe some rucio yaml/ini/etc file to provide some string substitution/variable based on the named policy

**Comment by bari12** [comment]
Yes.
A lot of these errors could be VO specific, so it is not bad to have the first-line VO support "filter" before it goes to the Rucio github. And secondly some errors might include partially (?) confidential information where we might not want to encourage posting them on a public issue tracker.
