### ISSUE TITLE
ChangeLog seems to be a COPYRIGHT file?

### ISSUE THREAD

**Issue by StewMH** [rucio/rucio#2434]
Motivation
----------

The ChangeLog seems to be more of a COPYRIGHT file.

Modification
------------
Remove or rename ChangeLog.

**Comment by bari12** [comment]
The original point was to have a ChangeLog there, the copyright is just put to the header of each file. But since we are not using the ChangeLog, I agree, we should remove it.

**Comment by vingar** [comment]
maybe keep it and mention in it that the changes are described in https://github.com/rucio/rucio/tree/master/doc/source/releasenotes instead.

**Comment by StewMH** [comment]
OK I can do this (@vingar's suggestion)

**Comment by bari12** [comment]
Great, thanks! 👍
