### ISSUE TITLE
Support bulk requests in the list_dataset_replicas CLI API

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#2459]
Motivation
----------
Given that a Rucio dataset corresponds to a CMS block, it would be extremely helpful if the rucio-clients `list_dataset_replicas` API would accept a list of dataset names, such that we can fetch all CMS block replicas that belong to a CMS dataset in a single call (thus having a better performance at multiple layers).

For the record, I've placed the same issue under the CMSRucio project:
https://github.com/dmwm/CMSRucio/issues/41

FYI @ericvaandering 

Modification
------------

Support a list of datasets in the `list_dataset_replicas` API, from the rucio-clients package.

**Comment by ericvaandering** [comment]
Is this a possibility?

**Comment by bari12** [comment]
Yes, this shouldn't be too complicated to do for the `deep=False` case. For the `deep=True` case it is a bit more complicated, as several tables are joined here, but I assume that this one is not relevant for you anyway.

I think we can extend the API with giving a list of scope/names, or add a new call - but it wouldn't allow the `deep=True` case.

**Comment by amaltaro** [comment]
And what's the difference between deep=True and deep=False?

**Comment by bari12** [comment]
There is a table storing all dataset replicas (called `collection_replicas`) which is queried when doing the query with `deep=False` - this is a very efficient query (just a PK lookup)
With `deep=True` this is not resolved via the collection_replica table, but the result is generated based on the location of every single file replica in the dataset. This is an expensive query, which is not needed in general, as mostly you create replication rules on the datasets you are querying for. But there are certain workflows which do not result in a collection replica being created for the dataset (as no rule was created for the dataset) in this case `deep=True` must be used.

Just to illustrate a case where this might be necessary. 
You have a dataset `A`. 50% of the files of dataset `A` are in dataset `B` and 50% in dataset `C`. If you don't create a replication rule for dataset `A`, but only for `B` and `C`, no collection replica was created for dataset `A`. For the simple query (`deep=False`), it will look like that the dataset has no full replica there, although all files actually have a replica. In that case the deep query needs to be used.

**Comment by amaltaro** [comment]
I see, thanks for this explanation. Indeed I believe we won't have need for using deep=True, but Eric knows those use cases better than me.

**Comment by ericvaandering** [comment]
@bari12 Something on our setup is not working correctly, I think. Even making a rule directly on a dataset, we don't really get replicas without the deep flag. From the CLI

```
# rucio list-dataset-replicas "cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396"

DATASET: cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396
+----------------------+---------+---------+
| RSE                  |   FOUND |   TOTAL |
|----------------------+---------+---------|
| T2_US_Wisconsin_Test |       0 |       0 |
| T2_DE_DESY           |       0 |       0 |
| T2_US_Nebraska_Test  |       0 |       0 |
+----------------------+---------+---------+
# rucio list-dataset-replicas --deep "cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396"

DATASET: cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396
+----------------------+---------+---------+
| RSE                  |   FOUND |   TOTAL |
|----------------------+---------+---------|
| T2_US_Wisconsin_Test |      20 |      20 |
| T2_DE_DESY           |      20 |      20 |
| T2_US_Nebraska_Test  |      20 |      20 |
+----------------------+---------+---------+
```

While the rules are on the dataset:

```
# rucio list-rules "cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396"
ID                                ACCOUNT          SCOPE:NAME                                                                              STATE[OK/REPL/STUCK]    RSE_EXPRESSION          COPIES  EXPIRES (UTC)    CREATED (UTC)
--------------------------------  ---------------  --------------------------------------------------------------------------------------  ----------------------  --------------------  --------  ---------------  -------------------
d0d3e85fc1954b51b5b623e4fadea08b  root             cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396  OK[20/0/0]              T2_US_Nebraska_Test          1                   2019-04-25 21:17:13
18548137e8a745a09262c227a842c655  root             cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396  OK[20/0/0]              T2_US_Wisconsin_Test         1                   2019-04-25 20:37:59
1ba5e5caf72a46b4bc8b7ea5b17ae40a  sync_t2_de_desy  cms:/SingleElectron/Run2017F-17Nov2017-v1/MINIAOD#f924e248-e029-11e7-aa2a-02163e01b396  OK[20/0/0]              rse=T2_DE_DESY               1                   2019-04-18 09:02:49
```

Are we missing a trigger or procedure in Oracle that is supposed to fill in the collection_replicas table?

**Comment by bari12** [comment]
Yes, there is the `COLL_UPDATED_REPLICAS` procedure in https://github.com/rucio/rucio/blob/master/etc/sql/oracle/procedures.sql
But this works with virtual scopes which Gancho set up (Basically there is a virtual scope for MC, one for DATA, one for Panda and one for everything else. (Would need to check with Gancho how to exactly setup these virtual scopes in oracle)

But alternatively you can also use the `abacus-collection-replica` daemon https://github.com/rucio/rucio/blob/master/bin/rucio-abacus-collection-replica
This one does the same as the oracle procedure.

**Comment by ericvaandering** [comment]
After I tried posted this, I found that daemon. Running it "does not work" in that this line https://github.com/rucio/rucio/blob/5c0258ba5064029f796c5c3d79681826dbae1778/lib/rucio/core/replica.py#L2371 basically takes minutes and consumes >2.5 GB of RAM and causes not just my pod but my k8s node to crash.

Maybe because this is because we've got a lot built up there and have never done this? Is there an easy way to limit it?

**Comment by bari12** [comment]
Yes, the daemon really seems to rely on the table being small.
Possibly easiest would be to do a cleanup with the PL/SQL first. I have a version without the virtual scopes, which you could just execute once. Let me check

**Comment by amaltaro** [comment]
Hi @bari12 , getting back to the original issue. In case you don't need any further information from my side, would you have a rough ETA for considering this ticket? Even by the end of 2019 would be helpful ;)

**Comment by bari12** [comment]
Hi @amaltaro 
I can't give you an exact ETA, but it should be before the end of 2019 :-)
This is not a difficult development, I just need to find time for it, or find someone who has time to do it 😄

**Comment by belforte** [comment]
Hi @bari12 , was this ever solved ?
We are starting to use Rucio for good to resolve location of yourdatesets-myblocks. I noticed that still location are retrieve one dataset at a time. Typical CRAB submissions require looking up for O(many 10's~few100s) datasets and while each call is indeed fast, I am worried by the sheer number of calls we make, possibly from several processes as same time (our users find it useful to submit requests for many similarly named mydatasets-yourcontainers  in tight CRAB Client loops).  We worry that many calls for little data each can create a bottleneck, also it seems a very poor use of Oracle.
Would be good IMHO to optimize this before we see an actual impact on peformance. At the momento only a fraction of CMS data get thier location resolved via Rucio, and those are smallish containers (not many datasets in it) (using Rucio naming here).
Can you somehow pop up the priority ?

**Comment by bari12** [comment]
Hi @belforte
Unfortunately I don't have time to work on this personally at the moment. @bziemons can you have a look on this issue, it should be rather simple to solve with the usual "chunked" queries for input lists. I can give you more info on Slack.

**Comment by belforte** [comment]
thanks @bari12 for quickl reply. There are many old issue in your GH with labels similat to this, is there something you can do to give it some kind of visible timeline ? Sorry if I ask, but last word was "by the end of 2019" changing that to "end of 2020" would not feel reassuring.

**Comment by bari12** [comment]
Hi Stefano,
The "by the end of 2019" was, in retrospective, not a good estimate ;-) Sorry for that. If there is no major complications, @bziemons can probably have this ready for the 1.23 release (Early July). Prioritising issues like this, which are only requested by a single community, is always a bit of a tricky thing. Don't get me wrong, I am very happy to do this, but all Rucio developers (including myself) are also guided by the priorities of our own communities/experiments, so things like this are more easily put on back of the queue, especially if only a single community requests it.

**Comment by amaltaro** [comment]
@bari12 Martin, sorry for reviving this issue. I've been trying to play with this new bulk API, using client 1.23.0, but I don't manage to get it working and the server hits a 500 Internal Server Error.
I checked this new feature implemented by @bziemons and I fail to see any problems as well (besides the docstring :)). I tried with plain dataset names (cms blocks) and with their names quote'd, and none of them work.
This is an example of what I ran from the python client side:
```
>>> pprint(dids)
[{'name': '/Cosmics/Commissioning2015-PromptReco-v1/RECO#77f9d258-b5d6-11e4-8732-02163e00d625',
  'scope': 'cms'},
 {'name': '/Cosmics/Commissioning2015-PromptReco-v1/RECO#0531324a-b6c9-11e4-8732-02163e00d625',
  'scope': 'cms'}]
>>> client.list_dataset_replicas_bulk(dids)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/srv/wmagent/v1.3.6.patch4/sw/slc7_amd64_gcc630/external/py2-rucio-clients/1.23.0/lib/python2.7/site-packages/rucio/client/replicaclient.py", line 299, in list_dataset_replicas_bulk
    raise exc_cls(exc_msg)
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
>>> 
```

and on the server side, there is only one line in the http-error-log (I'm still learning the ropes on the server logging) saying something like `core:error ... Premature end of script headers: replica.py`.

Would you see any mistake on my side? Perhaps it's also broken on the Atlas server? If that's the case, I'm happy to file a new GH issue.
Thank you in advance!

**Comment by bari12** [comment]
I think this one was resolved by adding the did_type to the query, due to the CMS specific schema, correct?

**Comment by amaltaro** [comment]
Yes, Martin. Adding "type": "DATASET" to the input parameters does the trick.

**Comment by bari12** [comment]
👍 Thanks

I already mentioned it in the chat.
I think we have to change this so that community-specific schemas do not "overwrite" the required parameters for a lookup query - these schemas are aimed on data-input but they do not make sense for query-parameters really. But for now the schemas are not prepared to distinguish this. Unfortunately changing this is quite a big task, so we have to address that a later point.

**Comment by ericvaandering** [comment]
The reason CMS is doing this is so that we can validate the three types of DIDs against their own REGEX. File has one, dataset a second, and container a third. I know this is somewhat against the spirit of Rucio and I'm willing to live with occasional snafus.
