### ISSUE TITLE
Missing created_at and updated_at columns in did_meta table

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#2462]
Motivation
----------
Somehow the columns `created_at` and `updated_at` dont get automatically created on the table `did_meta` while using the `models.py`. 
(Found in #2449)

Modification
------------

**Comment by arisfkiaras** [comment]
Just did some testing.
The database is initialized with did_meta having the columns `created_at` and `updated_at` but then the following migration is applied and the fields are missing.
https://github.com/rucio/rucio/blob/master/lib/rucio/db/sqla/migrate_repo/versions/688ef1840840_adding_did_meta_table.py

My suggestion would be to explicitly add the fields on the DIDMeta model and create a new migration.

**Comment by bari12** [comment]
But in that case, it is enough to just add a new migration to "fix" it, since the columns are created from the models.py correctly (But dropped/added wrongly by the migration)

**Comment by arisfkiaras** [comment]
So, I have fixed it in my own branch and also re-enabled the tests that were set to always pass.
I could open a pull request for review or do a combined one when I have https://github.com/rucio/rucio/issues/2840 ready.
