### ISSUE TITLE
list_replicas should raise DID not found

### ISSUE THREAD

**Issue by TWAtGH** [rucio/rucio#2468]
Motivation
----------
```
>>> from rucio.client.client import Client
>>> c = Client()
>>> print(c.list_replicas([{'scope':'user.mlassnig', 'name':'afasf'}], metalink=True))
</metalink>
```

Modification
------------

**Comment by mlassnig** [comment]
@TWAtGH this will still need an extension in the downloadclient. list_replicas replies with `['']` in the json case (already now), and (after this patch) with `'<?xml version="1.0" encoding="UTF-8"?><metalink xmlns="urn:ietf:params:xml:ns:metalink"></metalink>'` in the metalink case.
