### ISSUE TITLE
Compiling issues with Python 3 (3.6.8) and hash sum calculation

### ISSUE THREAD

**Issue by XeBoris** [rucio/rucio#2480]
Motivation
----------
  - There are several compiling issues observed when installing Rucio in Python 3.6.8. These errors are coming mainly from Py2->Py3 translations so far.
  - An error in the encoding (utf8) is observed when calculating the hash for determination of the final file path.

Modification
------------
  - Modifications are necessary in storm.py and protocol.py are necessary.

**Comment by hahahannes** [comment]
@bari12  Maybe we should change the python3 test to check all changed files now instead of only files with the py3 header
