### ISSUE TITLE
Per-RSE checksum specification

### ISSUE THREAD

**Issue by gabrielefronze** [rucio/rucio#2498]
Motivation
----------
Standard gridftp do not support multiple checksum algorithms without the installation of additional plugins.
This caused some hassle when configuring Rucio to operate in a context in which:
- vanilla gridftp offered only `md5`
- StoRM gridftp offered only `adler32`, but required VOMS auth

where provided.

The problem was related to the fact that the Rucio client writes to the DB entry both checksums (`md5` and `adler32`), hence any following operation on the data tried to check both checksums, failing alternatively depending on which gridftp was used.

Possible modification
------------
Several option have been partially discussed:

- Modify the Rucio Client in order to avoid the upload in the DB of unsupported checksums (e.g. adding support for a runtime flag such `--checksums md5,adler32`). This solution is weak and fast to implement, but delegates the handling of the RSE-checksum compatibility to the uploader (being it human or automatic);
- Insert in `rucio.cfg` a global list of supported checksums. This solution is more elegant and the setup is explicit, but making such selection global might be an issue in case of orthogonal compatibilities;
- Add to the DB an RSE field able to record a per-RSE checksum compatibility list. Such information can then be used in the Rucio demons to avoid unsupported checks.

Discussion
------------

This issue is aimed at triggering some discussion prior to the implementation of one of such solutions.

**Comment by bbockelm** [comment]
It's not particularly relevant to the question but ...

> Standard gridftp do not support multiple checksum algorithms without the installation of additional plugins

This statement is incorrect.  Adler32 support was added in 2016 (see https://github.com/gridcf/gct/commit/e0cd71abf9bc491f75933044fb4401c5ef06662f#diff-2c3c5b72076f8c6e8b30031f83bee8b2).  Older GridFTP servers were also quite annoying in that they would provide the md5 sum regardless of what algorithm you requested.

(It's still good to handle multiple checksum algorithms better in Rucio for other reasons...)

**Comment by bari12** [comment]
To me it feels logical to add the possibility to specify the checksum algorithm(s) to be used for a destination RSE. This could just be an RSE attribute with an enumerated list. Right now Rucio only supports adler32 and md5 and basically prefers adler32 over md5, but it is more flexible to make this decision per RSE. This somewhat overlaps with the discussion we had in #2410 where we discussed to basically offer arbitrary checksum support, if communities want to import their historic crc checksums.

**Comment by gabrielefronze** [comment]
> It's not particularly relevant to the question but ...
> 
> > Standard gridftp do not support multiple checksum algorithms without the installation of additional plugins
> 
> This statement is incorrect. Adler32 support was added in 2016 (see [gridcf/gct@e0cd71a#diff-2c3c5b72076f8c6e8b30031f83bee8b2](https://github.com/gridcf/gct/commit/e0cd71abf9bc491f75933044fb4401c5ef06662f#diff-2c3c5b72076f8c6e8b30031f83bee8b2)). Older GridFTP servers were also quite annoying in that they would provide the md5 sum regardless of what algorithm you requested.
> 
> (It's still good to handle multiple checksum algorithms better in Rucio for other reasons...)

Hi Brian,

Yeah, that's right. I have to rephrase that statement to something in the lines of "some older gridftp versions do not [...]". 👍

Thanks for the heads up!

**Comment by gabrielefronze** [comment]
Hi all,

For the records the branch I am working in to implement this functionality is here: https://github.com/gabrielefronze/rucio/tree/chksumsPR
Cheers,

Gabriele
