### ISSUE TITLE
differences in alembic up/downgrades and sqlalchemy models

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#2520]
Motivation
----------
While running the up and downgrades on the newest mysql version, I found some constraints that are missing in the models.py
- RULES_STATE_CHK
- IDENTITIES_TYPE_CHK
- REQUESTS_TYPE_CHK
- REQUESTS_STATE_CHK
- REPLICAS_STATE_CHK
- BAD_REPLICAS_STATE_CHK

Modification
------------

**Comment by bari12** [comment]
I think @mlassnig did not add these on purpose, since mysql previously did not support check constraints. If this is supported now, we should add them again.

**Comment by mlassnig** [comment]
Correct. MySQL did not support check constraints. I leave the glory of adding them to the migrate scripts to you ;-)

**Comment by mlassnig** [comment]
btw, no need to edit the old scripts, just add a new one which adds them all in one go

**Comment by bari12** [comment]
I would add them in the appropriate migrate scripts. It's more work, but this way we can roll back to a specific table version also with mysql.

**Comment by hahahannes** [comment]
Seems like they should get created automatically by sqlalchemy as they are the enum types described in the models.py. Needs to be investigated why they dont get created.
