### ISSUE TITLE
Virtual placement R&D prototype

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2528]
Motivation
----------

This is an R&D to test the virtual placement (VP) idea. Service (vpservice.cern.ch) that for 
a given dataset DID returns an ordered list of n sites where it should 
be processed (in case dataset is cache bound) or ["other"] if it 
should be processed in a regular panda way. It works responds queries in ~ 5ms.

What we wanted to do is that:

 1. when panda asks Rucio for list of sites having the dataset replica -
    Rucio in parallel to finding actual replicas also asks vpservice. If
    service returns "other", it returns to panda actual replicas. If
    service returns list of sites (eg. ["AGLT2", "MWT2"], it should
    return to panda this list and some flag eg. VP=true.
 2. When panda receives reply with VP=true, it should send job to the
    hospital queue of the first site from the list and only if that site
    is in downtime send it to the second from the list.
 3. Pilot will do correct thing since Rucio will give correct paths
    through caches.

If this works out, the virtual placement can be integrated into Rucio directly.

**Comment by mlassnig** [comment]
C/P from email:

"""
Hi,

Since this is R&D I don't like the idea of exposing this in the full API (I mean in the python replica client, server sided it's fine). Hence I like the (b) approach a bit more. Or alternatively we do not add a parameter to the method but make this configurable via a cfg parameter.

Server side it is more flexible, we can just do a wrapper around list_dataset_replicas which enhances the result with the vp query.

Cheers,
Martin
"""

**Comment by bari12** [comment]
Just to elaborate on this: If it is just something we want to try out, let's either do a separate function (like Ilija suggested) or hide the activation of this somehow. We shouldn't pollute the public API with a parameter we use for testing (Even if it defaults to something) - Especially, since nobody else can use the VP service anyway.
Once this is production ready we can decide how to integrate it.
