### ISSUE TITLE
dev docker image is broken

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#2548]
Motivation
----------
The docker image for the development instance is broken.
The build fails at step:
`RUN python setup.py develop`
with 
`python: can't open file 'setup.py': [Errno 2] No such file or directory`

Modification
------------

**Comment by vingar** [comment]
AFAIK, the repo directory should be mounted with `-v `pwd`: ` to get the setup.py file available.

**Comment by tbeerman** [comment]
You cannot mount anything during the build process. It is mounted when the container is actually started. For the setup.py to work during the build process the whole rucio directory would have to be copied into the container. It was working before without setup.py and I will revert it to that. If you need to run setup.py it can still be done after container has been started.

**Comment by vingar** [comment]
yes, I realised my confusion afterwards. `COPY . /etc/rucio` should fix it otherwise.

**Comment by vingar** [comment]
Doest it work with dockercompose: `etc/docker/dev/docker-compose.yml` ? I.e., `../../../../rucio/:/opt/rucio/`

This was how I tested and didn't see this error. `python setup develop` was also put there to deploy properly the package and dependency within the container.

**Comment by tbeerman** [comment]
No, the mounting in docker-compose doesn't work. Also the change of the RUCIOHOME from `/opt/rucio`/ to `/etc/rucio` introduces some problems, e.g. the aliases for httpd are using `/opt/rucio`. You were able to build it and get it running?

**Comment by vingar** [comment]
yes, it worked for me.  I might have changed the aliases as well. I should check the pull request.

**Comment by vingar** [comment]
After some checks, `docker-compose --file etc/docker/dev/docker-compose.yml up -d` works for me and 
```
[root@35f4df04509c rucio]# more  /opt/rucio/etc/web/aliases-py27.conf 
# Rucio REST
WSGIScriptAlias /accounts                /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/rest/account.py
...
``` points against my env.
