### ISSUE TITLE
Distance/ranking parameters in weird state for test RSE in new session

### ISSUE THREAD

**Issue by KatyEllis** [rucio/rucio#2582]
@ericvaandering 

Motivation
----------
I am using the CMS rucio-dev instance.

I have a couple of 'test' RSEs which are not controlled by any centralised scripts. The only changes to these RSEs should be manual changes. 

However, the distance/ranking values between my RSEs and others seem to be 'lost' in between sessions. I cannot view them (using _get-distance_) or add a rule making a file transfer between them, until I have used _update-distance_ to redefine the values. 

```
rucio-admin rse get-distance T1_FR_CCIN2P3_Disk_Test T3_CH_CERN_EOS_Test
%d format: a number is required, not NoneType
This means the parameter you passed has a wrong type.
```

Nevertheless the distance/ranking is still set in some form, as I cannot use _add-distance_. 

```
rucio-admin rse add-distance --distance 1 --ranking 1 T1_FR_CCIN2P3_Disk_Test T3_CH_CERN_EOS_Test

An object with the same identifier already exists.
Details: Distance from 48bd136e99a445398fe2075a8da0eb05 to f3c12eb9f9bf4a3ea5484743de0ba1a3 already exists!
This means that you are trying to add something that already exists.
```

Within the same session, these values seem to persist, but next time they need redefining again.

Modification
------------

**Comment by ericvaandering** [comment]
I think we discussed this on Slack. I'll make a patch for this

**Comment by KatyEllis** [comment]
Hi Eric, this is still an issue. Did you figure out why this is happening?

**Comment by ericvaandering** [comment]
Oh, I've complete forgotten about this. And I don't see a patch in CMSRucio for it (where the script resides). I'll at least make an issue there.

**Comment by ericvaandering** [comment]
Closing.
