### ISSUE TITLE
Protection in rucio-admin rse delete

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#26]
We need a protection for deleting a RSE. In particular, it should fail if some rules, collection replicas exist.

_Migrated from JIRA [RUCIO-2103](https://its.cern.ch/jira/browse/RUCIO-2103)_

**Comment by hahahannes** [comment]
I am not sure how to efficiently check if the rse is empty. If I understood correctly, I could either check for rules like:
```
[rule for rule in list_rules() for rse in parse_expression(rule['rse_expression']) if rse['rse'] == rse] == 0
```
But there I would have to iterate through each rule.

Or to check if there are file or collection replicas like:
```
session.query(models.CollectionReplicas).filter_by(rse_id=rse_id).count() == 0                                                                                                                                                                                                     
session.query(models.RSEFileAssociation).filter_by(rse_id=rse_id).count() == 0
```

**Comment by bari12** [comment]
Hi,

The best way would be to check against the replicas table directly, thus:

`session.query(models. RSEFileAssociation).filter_by(rse_id=rse_id).count() == 0`

This query goes against the Primary Key directly, so it should be rather fast, especially if the rse is empty.

**Comment by hahahannes** [comment]
Okay thanks, was not sure because of the big size of the RSEFileAssociation table.

**Comment by bari12** [comment]
For this it should be fine, as deleting an RSE is a really rare thing to do.
