### ISSUE TITLE
STOMP connections are not always cleanly closed

### ISSUE THREAD

**Issue by LionelCons** [rucio/rucio#2606]
The STOMP specification (https://stomp.github.io/stomp-specification-1.2.html#DISCONNECT) indicates that connections should be closed using the `DISCONNECT` frame and a receipt.

It seems that there are 4 places where STOMP connections are created but not closed explicitly using `stomp.py`'s `disconnect()`: `lib/rucio/core/trace.py`, `lib/rucio/core/nongrid_trace.py` and `lib/rucio/daemons/hermes/hermes.py`.

FWIW, `disconnect()` is used elsewhere: `bin/rucio-cache-client`, `lib/rucio/daemons/cache/consumer.py`, `lib/rucio/daemons/conveyor/receiver.py` and `lib/rucio/daemons/tracer/kronos.py`.

**Comment by bari12** [comment]
Hi Lionel,
Thanks for reporting; We will have a look!

**Comment by ericvaandering** [comment]
Reopening this issue
