### ISSUE TITLE
Upload to local machine

### ISSUE THREAD

**Issue by briedel** [rucio/rucio#261]
Motivation
----------

In the XENON case, we have an origin server from which the files are uploaded to the source RSE. The origin server and source RSE are the same server. Rather than doing a `gfal-copy` it would be better to do a `mv`/`rsync` of the data.

Modification
------------

Add a flag to `rucio upload` or check the origin hostname whether the start and endpoint are the same machine.

**Comment by mlassnig** [comment]
Can you give a concrete example how this would look like, especially how the two paths would look like for the mv command?

**Comment by bari12** [comment]
We could do this with a very specific (mv/rsync) protocol, however, the workflow in Rucio does not support something like this as that protocol would only work at one specific host.

In ATLAS there is a similar workflow where workernodes copy their output themselves (with whatever way they think is correct) to the specific path on storage and then just register the already existing data in Rucio via the python clients (didclient.py / add_did with the RSE attribute). Would this workflow be an alternative for you?

**Comment by briedel** [comment]
in the CLI it would be something like 

`rucio upload <dataset> <files> --scope <scope> --local`

internally you can pass `gfal-copy file://original/path/to/file file://RSE/path/to/file`or `rsync /original/path/to/file /RSE/path/to/file`

**Comment by hahahannes** [comment]
As discussed, I would add a --local argument like `rucio upload source_path --local destination_path` and perform a mv or rsync command in the uploadclient. 

An own protocol is not feasible, if I understood correctly?

**Comment by fushiyuan123** [comment]
Hi，
I find something about uploading to local machine in a PowerPoint that introducing rucio:
For existing files on storage
· Can be registered as-is directly into the Rucio catalogue
· File DIDs will retain their full path information as given by the client/user

This may be helpful to you.

**Comment by bari12** [comment]
There are some changes planned for this in regards to local moving protocols (storm)
