### ISSUE TITLE
Upload fails to register file if pfn provided and non-deterministic RSE

### ISSUE THREAD

**Issue by illingwo** [rucio/rucio#2620]
Motivation
----------

If the RSE is non-deterministic and a pfn is provided then the client prints `Upload with given pfn implies that no_register is True, except non-deterministic RSEs` and fails to register the replica.

**Comment by illingwo** [comment]
This test is wrong:

https://github.com/rucio/rucio/blob/48f46fe34d11b8c34eedecb57df7054efe4340b6/lib/rucio/client/uploadclient.py#L159-L161

- it should be `if pfn and is_deterministic:`. But also, is it a good idea to switch to no_register here? - this might be more confusing than just failing.

**Comment by TomasJavurek** [comment]
I think this is correct. In case of non-deterministic sites, pfn is obligatory option and only way to upload there. However, one sometimes still want to register such a dids.

**Comment by TomasJavurek** [comment]
The problem could be with the is_deterministic flag, how it was set for given RSE that you want to upload to? In case of the ATLAS, it is defined in AGIS (CRIG).

**Comment by illingwo** [comment]
There's an earlier check that the pfn is defined for non-deterministic RSEs. The test I quoted says if pfn is provided and the RSE is non-deterministic, then set `no_register = True`. That's the opposite of what the warning message says. And it means that for a non-deterministic RSE the file will be uploaded but not registered.

(And the non-deterministic flag was set correctly - first thing I checked)

**Comment by TomasJavurek** [comment]
I managed to reproduce the problem. It occurs only when:
--register-after-upload
is used.

**Comment by illingwo** [comment]
--register-after-upload is a slightly different problem - without it, on a non-deterministic RSE, the upload works, but the file isn't registered:
```
$ rucio -v upload --rse FNAL_DCACHE_PERSISTENT --lifetime 3600 --scope np04_reco_keepup --pfn gsiftp://fndca1.fnal.gov:2811/pnfs/fnal.gov/usr/dune/persistent/RSE/dunepro/protodune/np04/beam/output/detector/full-reconstructed/11/54/96/00/np04_raw_run007301_0014_dl7_reco_17438455_0_20190326T164443.root np04_raw_run007301_0014_dl7_reco_17438455_0_20190326T164443.root
2019-06-11 08:01:02,994	INFO	Preparing upload for file np04_raw_run007301_0014_dl7_reco_17438455_0_20190326T164443.root
2019-06-11 08:01:02,994	WARNING	Upload with given pfn implies that no_register is True, except non-deterministic RSEs
2019-06-11 08:01:03,073	INFO	Trying upload with gsiftp to FNAL_DCACHE_PERSISTENT
2019-06-11 08:01:09,009	INFO	Successfully uploaded file np04_raw_run007301_0014_dl7_reco_17438455_0_20190326T164443.root
Completed in 12.5664 sec.
$ rucio list-file-replicas --rse FNAL_DCACHE_PERSISTENT np04_reco_keepup:np04_raw_run007301_0014_dl7_reco_17438455_0_20190326T164443.root
+---------+--------+------------+-----------+----------------+
| SCOPE   | NAME   | FILESIZE   | ADLER32   | RSE: REPLICA   |
|---------+--------+------------+-----------+----------------|
+---------+--------+------------+-----------+----------------+
```
with --register-after-upload
```
2019-06-11 08:00:10,845	INFO	Preparing upload for file np04_raw_run007301_0014_dl7_reco_17438455_0_20190326T164443.root
2019-06-11 08:00:10,846	WARNING	Upload with given pfn implies that no_register is True, except non-deterministic RSEs
2019-06-11 08:00:11,497	ERROR	An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
Completed in 17.1711 sec.
```

**Comment by illingwo** [comment]
I've updated the pull request to fix the --register-after-upload issue as well. But I can still see a few potential issues

- On a deterministic RSE, if you provide a pfn it will automatically switch to no-register mode. This appears to be what was intended, only it was doing it for _non_-deterministic RSEs instead, but it seems dangerous to me; I think it'd be better to make these fail unless --no-register is explicitly given.
- With --register-after-upload, if the file exists it tests if it already registered and skips it if it is. But the check is if the DID exists, not if there's a replica at this RSE. So if the DID has been used before it won't be added to the RSE even though the file is there.
- This is getting off the scope of this ticket a bit, but rsemanager.exists() fails badly with an unknown error exception for non-deterministic RSEs if there is no file replica at the RSE. This is inconsistent with deterministic RSEs where it just returns false.

**Comment by TomasJavurek** [comment]
I doesn't work even with api. Furthermore, the registration doesn't take into account name of the file, and rather attempt to register according to the name of the source file.

**Comment by TomasJavurek** [comment]
> I've updated the pull request to fix the --register-after-upload issue as well. But I can still see a few potential issues
> 
>     * On a deterministic RSE, if you provide a pfn it will automatically switch to no-register mode. This appears to be what was intended, only it was doing it for _non_-deterministic RSEs instead, but it seems dangerous to me; I think it'd be better to make these fail unless --no-register is explicitly given.
> 
>     * With --register-after-upload, if the file exists it tests if it already registered and skips it if it is. But the check is if the DID exists, not if there's a replica at this RSE. So if the DID has been used before it won't be added to the RSE even though the file is there.
> 
>     * This is getting off the scope of this ticket a bit, but rsemanager.exists() fails badly with an unknown error exception for non-deterministic RSEs if there is no file replica at the RSE. This is inconsistent with deterministic RSEs where it just returns false.

1) our WM system uses pfn without registration. If an user attempts to upload something with pfn, it will be soon deleted by the agent that deletes non-registered data. 

2) yes. I think it is better to check DID. If we check replica only, it could attempt to register did, that is already present at different rses. We don't allow reuse of the same dids.

3) thx, to be fixed.

**Comment by illingwo** [comment]
> our WM system uses pfn without registration. If an user attempts to upload something with pfn, it will be soon deleted by the agent that deletes non-registered data.
Does it use --no-register (or the API equivalent)? Because I'm arguing that automatically changing between registration/no registration depending on the RSE type is potentially error prone. If it's explicit then there's no problem.

**Comment by TomasJavurek** [comment]
> > our WM system uses pfn without registration. If an user attempts to upload something with pfn, it will be soon deleted by the agent that deletes non-registered data.
> > Does it use --no-register (or the API equivalent)? Because I'm arguing that automatically changing between registration/no registration depending on the RSE type is potentially error prone. If it's explicit then there's no problem.

yes, no_register flag in the API. But right, it doesn't sound generic enough.

**Comment by TomasJavurek** [comment]
excluding 'not' from: _if pfn and not is_deterministic_
solves the problem with registration.
the register_after_upload is however still failing.

**Comment by TomasJavurek** [comment]
ah, ok I am bit behind. register_after_upload doesn't work exactly because rsemgr.exists() is failing for non-deterministic sites, that @illingwo already mentioned above. That needs to be fixed first. I'll open separate ticket for that.

**Comment by TomasJavurek** [comment]
was this the travis issue why it failed? I'll restart the pr from @illingwo as well, an that one would be preferred to approve.
