### ISSUE TITLE
Conveyor Finisher is not honouring activity

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2621]
Motivation
----------
Most likely because `activity_shares` is missing here: https://github.com/rucio/rucio/blob/master/lib/rucio/daemons/conveyor/finisher.py#L118

**Comment by cserf** [comment]
Is it still valid ?

**Comment by cserf** [comment]
I don't think it is valid. There is a loop on activity, so I don't understand what's wrong.
Martin, can you double check ?

**Comment by bari12** [comment]
I think the issue is that `activity` is not passed through to `get_next`
It loops over the activities but does nothing with it.
