### ISSUE TITLE
Links to disappeared documentation pages.

### ISSUE THREAD

**Issue by andy-slac** [rucio/rucio#2634]
I have noticed that in several places on CERN intranet and presentations/slides there is a link to Rucio HOWTO page https://rucio.cern.ch/client_howto.html which does not exist anymore. If the page has been moved or replaced it would be nice to have a redirect to a new location.

Also the output from `rucio list-file-replicas --help` shows a link to http://rucio.cern.ch/client_tutorial.html, that page is not there too.

**Comment by nataliaratnikova** [comment]
Yet another non-existing web page referred to in "rucio list-rses" help for --expressions option:
http://rucio.cern.ch/client_tutorial.html#adding-rules-for-replication
