### ISSUE TITLE
Log the parameters used in all POST/PUT requests

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#2686]
Motivation
----------
One cannot see the parameters used in the POST/PUT requests making it very difficult for debugging

**Comment by bari12** [comment]
i wonder what the most appropriate way to do this is. We can basically do a json dump of the post/put data to the logfile or even ES. It still wouldn't be in the apache access log, but it would be easy to correlate the access with the line in the logfile/ES.

**Comment by mlassnig** [comment]
dumping the request json to the logfile seems the right thing to do to me. i've had a look at the different parameters in the mod_wsgi documentation, but there's just no way you can write to the access_log. we can however dump the access itself also in the error_log, and silence the access_log, so everything would be in a single file?
