### ISSUE TITLE
Possibility to pass a timeout for a protocol

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#27]
_Migrated from JIRA [RUCIO-2247](https://its.cern.ch/jira/browse/RUCIO-2247)_

**Comment by nikmagini** [comment]
Proposed implementation:

1) For protocols/tools that natively support timeout (e.g. gfal), pass the timeout to the underlying command. Targeting this for the next client release.

2) Later, for all protocols implement a watchdog in rucio download/upload that kills the transfer after the timeout expiration. The plan is to do this only for the new downloadclient/uploadclient libraries.

**Comment by nikmagini** [comment]
Checking the code, the gfal protocol already has a hardcoded 3600 s timeout
