### ISSUE TITLE
Improve the procedure of submitting exceptions for the lifetime model DAOD/AOD

### ISSUE THREAD

**Issue by llll-2469** [rucio/rucio#2703]
Motivation
----------
Would be great to support text file upload, or command line method to submit exceptions for the lifetime model.
Currently it requires user to pick up samples one-by-one (with wildcard but still, not that convenient), which is low efficient, and very easily to introduce mistakes there.

Modification
------------

**Comment by kalderon** [comment]
For what it's worth, I would also find this very useful, so I'll add my support!

**Comment by guescio** [comment]
This would indeed be very useful and much appreciated.

**Comment by dchristidis** [comment]
Fixed in #5292 and included in Rucio 1.27.9 and later.
