### ISSUE TITLE
Storage Classes and Co-location hints

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2706]
Motivation
----------

To help tape systems with colocation, we will pass two metadata hints per file:

`storage_class`:`<classname>` as a single value,

and `group_hints`:`['<mostimportant>', .... , '<leastimportant>']` as an ordered list of string values.

**Comment by bari12** [comment]
@mlassnig What's the status on this? I doubt that FTS will forward this properly to Tape, but can't we already add it to the transfer requests?

**Comment by mlassnig** [comment]
I'm currently revisiting this, as we are trying to run a real-world demonstration with KIT.

If the destination RSE has the RSE attribute `archive_metadata` set to `True`, then the conveyor will produce the following `xattr` extensions for the destination URL (which can be understood by dCache):

`?xattr.dataset_name=my_dataset&xattr.dataset_length=1234&xattr.dataset_bytes=5678`

**Comment by mlassnig** [comment]
I'm closing this ticket and will make a proper new one, based on the ongoing discussions with tape people and site people.
