### ISSUE TITLE
Parent directory creation with gfal

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2754]
Motivation
----------
Hi @jamesp-epcc,

@bjwhite-fnal reported an issue with the parent directory creation in gfal, related to your URL signing commit https://github.com/rucio/rucio/commit/7a2d0f80426ecda5353f88ced5345e34a0805c45#diff-ec75c6aaaffa4d185e36f4b16f57f861L398

> Looking at the code for __gfal2_copy() in rse/protocols/gfal.py I see that in Rucio 1.19.8 ctx.mkdir_rec(str(dir_name), 0o775) is still called in order to create the intermediate parent directories for every transfer, regardless of protocol. This comes with a comment in the source that # This function will be removed soon. gfal2 will create parent dir automatically. By Rucio version 1.20.1 this try block to create parent directories has been modified to only be executed for https transfers in accordance with this comment. However, as far as I can tell the most recent version of gfal2 (2.16.3) does not create the intermediate directories. This causes Rucio to instead raise a SourceNotFound exception if the parent directories of the destination do not already exist. Is this the expected behavior of Rucio 1.20.1?

```
$ rucio -v upload --rse DCACHE_BJWHITE_START --scope test $PWD/testfile2
2019-07-26 08:00:54,496 INFO    Preparing upload for file testfile2
2019-07-26 08:00:54,497 DEBUG   Registering file
2019-07-26 08:00:54,497 DEBUG   Skipping dataset registration
2019-07-26 08:00:54,533 INFO    File DID already exists
2019-07-26 08:00:54,534 DEBUG   local checksum: 8dbd0963, remote checksum: 8dbd0963
2019-07-26 08:00:54,692 INFO    Trying upload with gsiftp to DCACHE_BJWHITE_START
2019-07-26 08:00:54,759 ERROR   Access to local destination denied.
Details: Source file not found.
Details: globus_ftp_client: the server responded with an error 550 File not found
Completed in 0.3111 sec.
```

> Uploading a file to a currently existing directory works as expected (with gridFTP at least).

You put the parent directory creation directly under the condition of `not self.renaming and dest[:5] == 'https'`. Is this because you tested and gfal2 automatically creates the parents? I was checking in the gfal2 changelog, but could not 100% confirm this.

**Comment by mlassnig** [comment]
I just confirmed with GFAL people that GFAL indeed does **not** create any parent directories.

**Comment by jamesp-epcc** [comment]
I think this is just a mistake. I think my intention was to ensure that the the directories are not created for RSEs with URL signing enabled (in which case the protocol is `https` and `self.renaming` is true). So the condition should be `not (self.renaming and dest[:5] == 'https')` instead. I will submit a pull request to correct this.
