### ISSUE TITLE
Swap out statsd for pystatsd in monitor?

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#2755]
Motivation
----------

Looking at the monitor.py code, it's using pystatsd which seems to be abandoned. It appears that https://statsd.readthedocs.io/en/latest/index.html is better supported and implements things like the context manager by default. In fact, this code looks almost like monitor.py

Maybe best to refactor and make monitor a very thing layer over statsd.

Modification
------------

**Comment by bari12** [comment]
Yes, there is already an ongoing discussion in #2690 about this. @hahahannes proposed to switch to statsd too.

**Comment by ericvaandering** [comment]
Great. Looks like that has progressed to a pull request even, so let's close this.
