### ISSUE TITLE
Prefer root protocol if local site has xCache

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2769]
Motivation
----------
From Stéphane in [JIRA](https://its.cern.ch/jira/browse/RUCIO-2888)

> Hello,
> Currently, when a job tries to access a file through rucio mover (copy2scratch) or direct access through xcache, instead of using xcache (and maybe http), the used protocol will depend on the prefer protocol of the remote site. Could this be corrected ?
> Thanks
> Stéphane

**Comment by mlassnig** [comment]
After chatting with Stephane we figured out what is actually needed ;-) Since XCache supports http, we should allow xcache usage not only for root URLs but also for http URLs.

**Comment by mlassnig** [comment]
(this also means forcefully mangling our typical davs:// into https://)
