### ISSUE TITLE
UserPass login not automatically deriving account

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#2770]
Motivation
----------

All three methods below should work equivalently:

```
[root@20920a55b4bc rucio]# rucio -S userpass -u asdf -pwd zxcv whoami
cannot get auth_token
2019-07-31 15:11:27,139 ERROR   Cannot authenticate.
Details: userpass authentication failed
```

```
[root@20920a55b4bc rucio]# RUCIO_ACCOUNT=mario rucio -S userpass -u asdf -pwd zxcv whoami
cannot get auth_token
2019-07-31 15:11:30,424 ERROR   Cannot authenticate.
Details: userpass authentication failed
```
```
[root@20920a55b4bc rucio]# rucio --account mario -S userpass -u asdf -pwd zxcv whoami
status     : ACTIVE
account    : mario
account_type : USER
created_at : 2019-07-31T14:38:57
updated_at : 2019-07-31T14:38:57
suspended_at : None
deleted_at : None
email      : None
```

**Comment by robbarnsley** [comment]
I cannot seem to replicate this with the current version:

    [root@rucio rucio]# rucio-admin account add rmb
    [root@rucio rucio]# rucio-admin identity add --account rmb --type USERPASS --id 'test' --email test@test.com --password test
 
    [root@rucio rucio]# export RUCIO_ACCOUNT="rmb"
    [root@rucio rucio]# rucio -S userpass -u test -pwd test whoami
    status     : ACTIVE
    account    : rmb
    account_type : USER
    created_at : 2020-08-18T09:25:02
    suspended_at : None
    updated_at : 2020-08-18T09:25:02
    deleted_at : None
    email      : None
 
    [root@rucio rucio]# RUCIO_ACCOUNT=rmb rucio -S userpass -u test -pwd test whoami
    status     : ACTIVE
    account    : rmb
    account_type : USER
    created_at : 2020-08-18T09:25:02
    suspended_at : None
    updated_at : 2020-08-18T09:25:02
    deleted_at : None
    email      : None

    [root@rucio rucio]# rucio --account rmb -S userpass -u test -pwd test whoami
    status     : ACTIVE
    account    : rmb
    account_type : USER
    created_at : 2020-08-18T09:25:02
    suspended_at : None
    updated_at : 2020-08-18T09:25:02
    deleted_at : None
    email      : None

Removing the auth token after each gives the same result.

**Comment by mlassnig** [comment]
Ok, this can be closed then. Thanks @robbarnsley !
