### ISSUE TITLE
missing dot in schema in alembic scripts

### ISSUE THREAD

**Issue by hahahannes** [rucio/rucio#2823]
Motivation
----------
Some alembic scripts on next branch are not working in the new dev environment, because of a missing dot in the schema identifier

Modification
------------
In all the alembic files 
`schema = context.get_context().version_table_schema if context.get_context().version_table_schema else ''`
should be 
`schema = context.get_context().version_table_schema + '.' if context.get_context().version_table_schema else ''`
where schema is used in a string

**Comment by mlassnig** [comment]
Hmmm, alembic runs fine for me in the container, both down and up.

**Comment by mlassnig** [comment]
Or is this a problem with master/next being out of sync (when they shouldn't be?)

**Comment by hahahannes** [comment]
I made some wrong changes on the next branch with the feature PR https://github.com/rucio/rucio/pull/2478 that removed the dots in some alembic files.
