### ISSUE TITLE
Rule page shows RSE IDs instead of names

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#2830]
![image](https://user-images.githubusercontent.com/2452306/63096904-621f3c00-bf6f-11e9-8608-ad812655c18e.png)

**Comment by DhruvSondhi** [comment]
Hello, I was thinking that I can try to work on this issue. Can this be assigned to me?

**Comment by bari12** [comment]
Hi @DhruvSondhi please go ahead with the implementation :-)

**Comment by DhruvSondhi** [comment]
Hello @bari12 ... I had a small doubt that what part of the RSE Id is considered as the name? Is the First part of the string up to the `"."` ? or Does it consists of everything except the last `".data"` field?

**Comment by DhruvSondhi** [comment]
Hello, I have found the required file where the reading & updating of data is being done on the Rule's page. Checking the data being passed, I am not able to find any mistake & the database shows the same fields as well 🤔 . Can some more information about the erroneous data being passed be provided?
