### ISSUE TITLE
Importer fails to import RSEs that were deleted

### ISSUE THREAD

**Issue by arisfkiaras** [rucio/rucio#2896]
Motivation
----------
I was experimenting with the Rucio-CRIC integration and while doing so, I was disabling and re enabling RSEs.
What I noticed is that when the importer tries to configure an RSE that already exists on the database but is marked as 'Deleted', it will throw an error: 
`Details: RSE with id 'f9c7592cdc6344eabce00e8ea4d2641a' cannot be found`

After further investigation I found out that when the importer sees an RSE on the json it will check if it already exists to avoid creating it again. It does so using the `rse_module.get_rse_id` method. This method though returns the id even if the RSE is already marked as deleted.
https://github.com/rucio/rucio/blob/9388a53bf2b0b9b82b0727d897ef0ab818ade60f/lib/rucio/core/importer.py#L37
Further down on the code that the rse_id (of the deleted RSE) is referenced, of course it throws an error.

Modification
------------
Possible  solution: Check if the RSE is marked as 'deleted' and enable it again before trying to modify it.

**Comment by bari12** [comment]
We have to make a bit of a policy decision here. Significant operations like deleting an RSE or re-creating it we always considered strictly manual operations, since it can have quite severe impacts. @cserf do you have an opinion how we should handle this with CRIC? Keep it manual?

**Comment by arisfkiaras** [comment]
Well, as it is the importer right now it 'deletes' all RSEs that are not part of the JSON.

**Comment by mlassnig** [comment]
i'm still in favour of my old proposal that we should have an RSE state, so not only exists/not_exists, but also something like enabled/suspended/decomissioning/removed_from_cric, etc... right now this can all be handled via RSE attributes, but I think it would make sense to have this as a dedicated RSEState.

**Comment by bari12** [comment]
As discussed today, we should make the "merge" strategy configurable here.
- If not present in CRIC, delete RSE
- If not present in CRIC, keep RSE and make deletion only manual
@hahahannes, @arisfkiaras can one of you have a look on this please.

**Comment by hahahannes** [comment]
Ok, I guess you mean soft delete the RSE?
Also, how do we deal with a "new" RSE with the same name in the first case? Should we reactivate and then update it
