### ISSUE TITLE
Option to specify protocol implementation for upload

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#29]
_Migrated from JIRA [RUCIO-2349](https://its.cern.ch/jira/browse/RUCIO-2349)_

**Comment by TWAtGH** [comment]
Hi, if you don't mind I will take this too, since I need it for the new api upload.

**Comment by nikmagini** [comment]
Hi,

sure, sorry for the delay. Maybe you can simply reuse my changes to rsemanager.py here:

https://github.com/rucio/rucio/commit/7883be7685d906b3edbb4dc9dfdb098980ad8968#diff-8777b68ebcb342123d7ce30a3ff039b5

Cheers
N.

**Comment by TWAtGH** [comment]
Ah great! Thanks for  the hint!

**Comment by bari12** [comment]
Done in bin/rucio, but not in uploadclient

**Comment by TWAtGH** [comment]
It is
https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L218
https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L276
https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L296

**Comment by bari12** [comment]
So this has to be prepared in the list of dicts given to the uploadclient?

**Comment by TWAtGH** [comment]
Exactly. Most options are file specific in the API.

**Comment by bari12** [comment]
I see, thanks 👍 . Closing
