### ISSUE TITLE
Allow RSEs to be re-enabled

### ISSUE THREAD

**Issue by arisfkiaras** [rucio/rucio#2911]
Motivation
----------
Right now there are methods to 'soft' delete an RSE and disable it but no methods to bring it back. 
Wouldn't it make sense to allow for an RSE to be enabled again without doing manual operations on the database? This might be useful for synchronization with CRIC https://github.com/rucio/rucio/issues/2896

Modification
------------
Add method that sets up deleted RSE as active again. 
Would a CLI command `rucio-admin rse recover` make sense?

**Comment by bari12** [comment]
To me that makes sense, but @cserf is mostly an advocate of not making these commands too accessibly. 😄 
But I think you can go ahead and implement that.
