### ISSUE TITLE
list_replicas for archive

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#2961]
Motivation
----------
From Rod (See [JIRA](https://its.cern.ch/jira/browse/RUCIO-2891))

> This file
> data15_13TeV:data15_13TeV.00280673.physics_CosmicCalo.merge.RAW._lb0080._SFO-ALL._0001.1
> has 3 tape replicas, plus in an archive on tape and disk.
> rucio list-file-replicas shows only the replica from the staged zip file on IN2P3-CC_DATADISK
> not the archive on IN2P3-CC_DATATAPE and not the 3 constituent replicas on tape. 
> The see the latter again,
> --no-resolve-archives
> The python client shows all 5 replicas.
> I don`t think it will break prod - just confusing.
> I had another example with no replicas, before adding --no-resolve-archives
> data17_13TeV.00341294.physics_Background.merge.RAW._lb0130._SFO-7._0001.1
> Cheers,
> Rod.

**Comment by rcarpa** [comment]
This is one is probably fixed
