### ISSUE TITLE
Reaper 2.0 is creating error traces for SourceNotFound

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#2969]
Motivation
----------

For example:
```Thread [17/20] : Deletion NOTFOUND of HOST.1 as IP|HOST:PORT/PATH on MWT2_DATADISK```
This is different from the previous Reaper implementation. Such traces reduce the deletion efficiency as we are currently calculating it in our monitoring. Is it intentional?

Modification
------------

Potentially do not submit traces for `SourceNotFound`.

**Comment by cserf** [comment]
Need discussion

**Comment by dchristidis** [comment]
This issue was tagged erroneously. It is not related to the thread information contained in the messages.
