### ISSUE TITLE
Use GFAL’s create_parent transfer parameter

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#2973]
Motivation
----------

The implementation here can be simplified:
https://github.com/rucio/rucio/blob/master/lib/rucio/rse/protocols/gfal.py#L398

*This should not be done until GFAL 2.16.4 reaches EPEL.*

Modification
------------

Do not make a separate call to GFAL to create the destination path. Use the `create_parent` transfer parameter instead.

**Comment by bari12** [comment]
2.18 now on EPEL; this can be done now; Possibly for summer student.

**Comment by bari12** [comment]
See #3681

**Comment by ThePhisch** [comment]
that would be https://github.com/rucio/rucio/blob/d7e04cb2cd46aca683bb5372faf50ba158c8de26/lib/rucio/rse/protocols/gfal.py#L398
