### ISSUE TITLE
Support traces in bulk download/upload

### ISSUE THREAD

**Issue by berghaus** [rucio/rucio#2980]
Motivation
----------
At the moment the [pilot](https://github.com/pandawms/pilot2) need to download and upload files one at a time. The reason is that the pilot also needs to handle the traces. I would be usful if either the Rucio client can handle the traces - given the correct options - or return something that can easily be used to record the traces of a bulk upload.

Modification
------------
Either introduce code to optionally handle traces in the code of:

 * [ ] `rucio.client.downloadclient`
 * [ ] `rucio.client.uploadclient`

or format the return data to allow the pilot to construct the trace information from it.

**Comment by TWAtGH** [comment]
Actually this should already be implemented on Rucio side. There is a parameter called something like `copy_traces_out`. Or is there something missing?

**Comment by TWAtGH** [comment]
I think this can be closed
