### ISSUE TITLE
Add staging timestamps to request history

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#3023]
Motivation
----------

Transfers with the source files on tape are done in several steps by FTS: The staging and then the transfers to the final destinations. Now, only the later it is reported in Rucio.  It might be be good to add the beginning and end of the staging as reported by FTS in order to do further analysis, e.g. staged_at, staging_at. Both values are reported as  "staging_finished"  and "staging_start" by FTS when querying the file transfer statuses.

**Comment by bari12** [comment]
@cserf: The columns are added to the table by @jwackito You can add the filling of the values to the poller.

**Comment by jwackito** [comment]
transfertool/fts3.py bulk_query method wasn't querying staging info, that's why staging_start and staging_finished columns in the requests were not populated...

**Comment by bari12** [comment]
@jwackito this still doesn't seem to work. We have to check if we are losing this info somewhere in the workflow or if we just don't get the value from FTS. @jwackito please try to debug this on one of the integration pollers.
