### ISSUE TITLE
Copy_pin_lifetime values in FTS

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#3035]
Motivation
----------
cf. Data carousel discussion for the full thread.

In summary: It appears that the desideredLifetime / Copy_pin_lifetime values in FTS are set to -1 in FTS. FTS fallbacks to a different default values depending on the FTS settings. This pin lifetime is too small to retain files on the tape buffer which leads to have staged files deleted before being tranfered. 

Modification
------------

Set the desideredLifetime / Copy_pin_lifetime to the same value.  The rule lifetime is the most appropriate to express to the sites how much time the file should be kept around and get same value.

**Comment by bari12** [comment]
Reading through the thread the rule lifetime also seems appropriate to me. We are doing something similar for the pure STAGING requests for the STAGING_AREA rules.
The `copy_pin_lifetime` we are setting already (to -1). Do we need to add a parameter called `desideredLifetime` as well?

**Comment by mlassnig** [comment]
No, the `copy_pin_lifetime` needs to be set to the rule lifetime, then everything is fine. In lieu of a rule lifetime, we can set a default of something like 48 hours. FTS will release the SRM pin after the transfer out of the tapebuffer is done.

**Comment by andrea-manzi** [comment]
sorry i still i don't understand what are you referring to here as desideredLifetime as parameter for FTS. The only parameter to set FTS side is the copy_pin_lifetime, which is set as default to 8 hours now as Rucio fills it to -1 when submitting the job ( or it does not fill it at all).

The _srmBringOnline.desideredLifetime_ is set by FTS  and it takes as value the copy_pin_lifetime value passed by the client.

What is changing from FTS to FTS cause this is a parameter on gfal2 is the _srmPrepareToGet.desideredLifetime_   but  it does not affect the pin lifetime of the file on disk after the file has been staged via srmBringOnline though as this is taken from the copy_pin_lifetime.

Anyway by changing gfal2 to avoid to run a srmPrepareToGet if the file is not online we also avoid  to have different desideredLifetime if the file is then staged by the srmPrepareToGet.

i know it's a mess but everything around SRM is a mess:-)

**Comment by andrea-manzi** [comment]
just to mention that Castor does not take into account the pin lifetime as the pinning is disabled.
But both Castor at CERN and RAL will be  decommissioned and ATM they have huge buffer space so they don't have garbage collector issues.

**Comment by vingar** [comment]
We can assume that desideredLifetime  == Copy_pin_lifetime. I have followed too much the srm spec... I've modified the title too.

**Comment by vingar** [comment]
There is a pin leak in FTS: For the Staging + transfer case, FTS creates two pins. One for `bringonline` and another for `srmpreparetoget`.  On transfer completion, only the pin generated by `srmpreparetoget` is released. The one from `bringonline` is kept. https://its.cern.ch/jira/browse/FTS-1491 

For now, the pin lifetime from Rucio to FTS cannot be set to the rule lifetime as it will keep files for too long on the buffer. 

As the same time, the current default pin lifetime is too short and doesn't protect the files: Files are staged several times, garbaged collected, etc before the final transfer. This also impact site performance in general.  https://its.cern.ch/jira/browse/FTS-1492

**Comment by bari12** [comment]
Since this was just discussed in the data carousel meeting:
If we don't set it to the rule lifetime (since this might be too long) is it sufficient to set it to 48h?

**Comment by bari12** [comment]
So specifically changing
https://github.com/rucio/rucio/blob/c2e73d4a4c5583d195a6bc78ecf41fc79f9a8d67/lib/rucio/core/transfer.py#L835
to 48h
