### ISSUE TITLE
Ability to query metadata of deleted dids

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3097]
Motivation
----------

Quite often people ask DDM support "what happened to my dataset?" for datasets that have been deleted. It would be good to be able to query the metadata of these datasets, eg time it was deleted.

Modification
------------

Add an option to the CLI like `--deleted` to query the deleted DIDs table.

**Comment by bari12** [comment]
@cserf This seems to be related to #5484 ?

**Comment by cserf** [comment]
I think it's partially related. The new feature will be able to expose metadata of deleted DIDs like `deleted_at`, but it won't show what actually issued the deletion. In DQ2 time, we had the information of the IP that issued the deletion command. Maybe we should store that information.

**Comment by bari12** [comment]
Duplicate #5484
