### ISSUE TITLE
Site Decommissioning Daemon

### ISSUE THREAD

**Issue by jwackito** [rucio/rucio#3103]
Motivation
----------
Decommissioning of sites with problems take too much human intervention. Automation is needed to cover the corner cases (around 10% of rules fail not because the site to be decommissioned but for other factors).

Modification
------------
New daemon/service that keep track of the rules and transfers exiting the site to be decommissioned.

**Comment by cheapkai** [comment]
Sir could you assign me to a similar issue or assign me any part of this issue .
