### ISSUE TITLE
Rebalancing breaks in decomissioning mode

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#312]
Motivation
----------
The query against the locks takes too much time and Oracle fails with "snapshot too old"
`
***************************
BB8 - Execution Summary
Mode:    DECOMISSION
Dry Run: False
***************************
scope:name rule_id bytes(Gb) target_rse child_rule_id
(cx_Oracle.DatabaseError) ORA-01555: snapshot too old: rollback segment number 7078 with name "_SYSSMU7078_1542158916$" too small
 [SQL: "SELECT r.scope, r.name, rawtohex(r.id) as rule_id, r.rse_expression as rse_expression, r.subscription_id as subscription_id, 0 as bytes, 0 as length FROM atlas_rucio.rules r\nWHERE\nr.id IN (SELECT rule_id FROM atlas_rucio.locks WHERE rse_id = atlas_rucio.rse2id(:rse) GROUP BY rule_id) and\nr.state = 'O' and\nr.child_rule_id is NULL"] [parameters: {'rse': 'xxxx']
`

Modification
------------
Use some dumps on Hadoop. The dumps must be grouped by rule_id, rse and state

**Comment by TomasJavurek** [comment]
The solution is not streightforeward since we don't have dump of lock table in hadoop.
