### ISSUE TITLE
Pin paramiko to 1.18.4 for python 2.6 compatibility of the clients

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#314]
Motivation
----------
Pin the dependency **paramiko** to version 1.18.4 for python 2.6 compatibility.

**Comment by hugovk** [comment]
One option is to drop support for Python 2.6, it's not received any security updates for four years and is little used.

Here's the pip installs for rucio from PyPI for the last month (via `pypinfo --percent --pip rucio pyversion`)

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 2.7            |   67.1% |            116 |
| 3.5            |   32.4% |             56 |
| 3.4            |    0.6% |              1 |
