### ISSUE TITLE
Misleading message about transfers in rule page

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#3153]
Motivation
----------

In the locks overview, when requesting the URL to the FTS monitoring, the UI will show the message ‘The request has not yet been submitted’ even if the transfer is done and the Finisher has yet to process it.

Modification
------------

In addition to `SUBMITTED`, display the FTS URL when the request is either `DONE` or `FAILED`.

**Comment by bari12** [comment]
I think we can just show the ones in `DONE` and `FAILED` already. But under normal conditions the requests will only be in this state very shortly...
