### ISSUE TITLE
`Bring_online` timeout can be too short

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#3164]
Motivation
----------

The `Bring_online` parameter is the timeout for the FTS polling to check that the file is online.
The current default value defined in Rucio is 43200s  / 12 h.  At the last data carousel exercice, many transfers  reached this timeout and the corresponding FTS requests failed  (error message in Rucio 'Stage was cancelled'). Such staging request are then rescheduled on the same site, participating to the long tail effect.

Based on the values in FTS about the max staging request pers site, e.g.,  200000 requests  https://fts3-atlas.cern.ch:8449/fts3/ftsmon/#/config/storages, the avg file size 2.5 GB and the observed throughput (e.g., from 300 MB/s to 1GB/s), the timeout value of 12 hours is too small and lead to some unnecessary overheads and scheduling operations.

Modification
------------

I would suggest either to Increase the bring_online timeout to reflect the storage / tape performance wrt the number of queued staging request or set to the rule lifetime with some potential renormalisation or set it to a bigger constant value for all staging requests.

**Comment by xzhao87** [comment]
Yes the 12h default timeout is too short, given the fact that we expect to always do bulky staging submissions to sites.  
A longer default timeout setting in FTS, plus respecting the timeout passed by client (e.g. rucio), may just do it. 
Hope it helps,
Xin

**Comment by bari12** [comment]
Since we are discussing this also via mail:
We can increase this by changing the rucio.cfg `bring_online` setting, so we do not need to change the default in the Rucio code as well.
