### ISSUE TITLE
Move to snake_case for RSE attributes for total and used space

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#3178]
Motivation
----------

After discussion, it looks like many people prefer snake_case instead of CamelCase for RSE attributes for total and used space. That's obviously a wrong choice similar to choosing emacs instead of vi (my 2 satoshis), but since the majority decides, let it be...

**Comment by mlassnig** [comment]
Of course, the right choice is hyphen-case!

Compare:

`tpc-commission-davs: True`
`tpc-commission-root: True`

vs.

`tpc_commission_davs: True`
`tpc_commission_root: True`

vs.

`TPCCommissionDAVS: True`
`TPCCommissionROOT: True`

**Comment by bari12** [comment]
Let's finish the collection of all attributes in #2630 first. Then we can organize a rename of the mismatched ones
