### ISSUE TITLE
Rucio CSI interface

### ISSUE THREAD

**Issue by rptaylor** [rucio/rucio#3204]
Motivation
----------
I recall some recent discussion (CHEP or pre-GDB?) about possibly developing a Rucio CSI plugin for Kubernetes. Are there any plans to do this? If I understand correctly it seems like the right way to stage in data for grid jobs on kubernetes, because the staging would occur in the background before the compute job starts running and occupying resources. A user would request a Rucio volume and specify a secret (proxy) to use and the desired files to download. When the job starts running the files would be downloaded and available in the volume.

**Comment by bari12** [comment]
Hi @rptaylor 
I don't think there are any concrete plans to do that. @tbeerman or @ericvaandering do you know any plans about that?

**Comment by ericvaandering** [comment]
Not that I know of.

**Comment by bari12** [comment]
Ok I asked around a bit but nobody knows anyone planning to do this. I will close the ticket until we can find somebody interested in this development.
