### ISSUE TITLE
Provide dev container that mounts code

### ISSUE THREAD

**Issue by berghaus** [rucio/rucio#322]
Motivation
----------
When developing code it is much faster to just mount the modified code in the container for testing than to rebuild the container to test every change.

Modification
------------
 - [x] Remove source code from docker image in:
    - [x] bin
    - [x] lib
    - [x] tools
 - [x] Provide docker-compose manifest that launches dev environment in `etc/docker/dev`
 - [x] Provide docker based pre-commit hook
 - [x] Document usage in `etc/docker/dev` (README.md)

Expected behavior
-----------------
The developer may use docker-compose with the manifest to launch dev container environment. The code may be tested in the container using `docker exec ...`. The pre-commit hook runs `pylint` analysis in a container based on the dev image.

**Comment by mlassnig** [comment]
Sounds like a good modification to me, but then, I don't use the docker dev env, so someone who does should confirm ;-)

**Comment by tbeerman** [comment]
Definitely a good idea.

**Comment by vingar** [comment]
+1

**Comment by berghaus** [comment]
Great, I'll get to it :smile: 

The docker build looks for a flake8 config `.flake8` which isn't in the repo. The `.pep8` has a `[flake8]` section though. I just took the liberty to move the flake8 section to its own file.

**Comment by berghaus** [comment]
Apologies, I had forgotten to format my commit messages, hence the rewrite.

**Comment by berghaus** [comment]
May I presume that we will build a container called `rucio-dev` that will be available from the `rucio` docker repository, i.e. so one could pull it like this:
```
docker pull rucio/rucio-dev
```

**Comment by vingar** [comment]
yes, we should replace the current rucio container with rucio-dev
