### ISSUE TITLE
Standalone upload tests in the travis and the docker.

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#3250]
Motivation
----------
Following an example of download, add tests of upload to the list of tests:
https://github.com/rucio/rucio/tree/master/lib/rucio/tests

Modification
------------
- add site name to the test rses, important for client location and lan/wan decissions
- almost copy paste download, it is already using upload functionality
- enhance that for several test settings: fake file, fake site, corrupted file, etc.
- ensure that it is running under both: travis/docker and dev docker env.

**Comment by bari12** [comment]
Duplicate of #2311 closing
