### ISSUE TITLE
Weight is not applied correctly in inject_rule

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3282]
Motivation
----------

We noticed in the data carousel that all datasets were going to a single site in each cloud, when they should have been distributed by the freespace weight. It looks like inject_rule does not use the weight properly.

When `__create_locks_replicas_transfers` is called, `preferred_rse_ids` is empty

https://github.com/rucio/rucio/blob/master/lib/rucio/core/rule.py#L698

This eventually goes to `rule_grouping`

https://github.com/rucio/rucio/blob/master/lib/rucio/core/rule_grouping.py#L439

where if `preferred_rse_ids` is empty, `prioritize_order_over_weight=True` which means the first RSE in the list is chosen instead of taking the weight into account.

Modification
------------

The simple modification would be setting `preferred_rse_ids=rses` in `inject_rule` but there are probably other ways.

**Comment by bari12** [comment]
Thanks David, I will have a look.

**Comment by davidgcameron** [comment]
I read the code again and I don't think this is an issue. What happens is that the weighting is skipped if any files in the dataset have replicas on any RSEs in the rule expression, which make sense in principle because it means less data movement. So I wonder if the bias in the data carousel was because some sites had RAW files lying around and so those sites were preferred even though they had less free space.
