### ISSUE TITLE
Stat *.rucio.upload with protocol.renaming false

### ISSUE THREAD

**Issue by vokac** [rucio/rucio#3289]
Motivation
----------
It is no longer possible to upload files to Dynfed, because of an attempt to stat non-existing file

Modification
------------
This line doesn't seem to me correct in section related to `protocol.renaming == False`
https://github.com/rucio/rucio/blob/66cbcf81a7205958bf6f2bc670d98bd760b60088/lib/rucio/rse/rsemanager.py#L413

**Comment by bari12** [comment]
@TomasJavurek please have a look on this. I am not sure why this line was introduced (It did work before) Maybe it was just a mistake.

**Comment by rodwalker** [comment]
Is this also the reason gridftp fails and thus the reason we can`t have a release with the wrote_wan fix?
Then it is urgent.

Cheers,
Rod.

**Comment by TomasJavurek** [comment]
The line was introduced by @berghaus on our request, because @TWAtGH discovered volatile behaviour of protocol.stat, when it sometimes returned not correct answer. Thus we implemented retries we certain schedule, but it should not exceed few minutes.
