### ISSUE TITLE
Specify client configuration file via env var and/or CLI option

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3377]
Motivation
----------
The current ways of specifying a client config file are not very flexible and don't make it easy to use two different rucio systems from the same machine.

Modification
------------
Use an environment variable like `RUCIO_CFG` to specify a config file, and add a command line option like `-c CONFFILE`.

**Comment by bari12** [comment]
I think that's a good idea. Not the highest priority though 😄

**Comment by bziemons** [comment]
@mlassnig @TomasJavurek would you be okay with me taking this?

The question would be what the environment variable looks like. There are many abbreviations for configuration: `CONF`, `CFG`, `CONFIG` (and maybe more). I personally like `RUCIO_CONFIG` best.

Now for the command line argument I would start with `--config`. `-c` would collide with the `--certificate` option in `rucio-cache-client`, so I don't know if it's a good short form to use. Please provide me with more info regarding this.

**Comment by TomasJavurek** [comment]
@bziemons sure. Thanks a lot. As far as I remember, we have more config files, not just rucio.cfg. But I think with this ticket, we want to access just this one.

**Comment by davidgcameron** [comment]
Related to this, I wonder if we should change the ordering of the config file look up:

```
if 'RUCIO_HOME' in os.environ:
    __CONFIGFILES.append('%s/etc/rucio.cfg' % os.environ['RUCIO_HOME'])

__CONFIGFILES.append('/opt/rucio/etc/rucio.cfg')

if 'VIRTUAL_ENV' in os.environ:
    __CONFIGFILES.append('%s/etc/rucio.cfg' % os.environ['VIRTUAL_ENV'])
```

Can we put the virtualenv conf file first in the list? I think it's better to prefer user-definable locations over system locations, especially since users may not be able to change the system conf.

**Comment by bari12** [comment]
I think that makes sense. 👍

**Comment by bziemons** [comment]
> Can we put the virtualenv conf file first in the list?

Since `VIRTUAL_ENV` is not necessarily user-defined, but rather defined by the use of a virtual environment, I would still look for `RUCIO_HOME` first. This ensures that the user is able to set a different configuration directory even if he is using a virtual environment.

**Comment by davidgcameron** [comment]
Ok, sounds good to me :)
