### ISSUE TITLE
Problems with get_hops

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#3381]
Motivation
----------
Debugging with Katy her attempt to multi hop, we noticed that while there is a check in non-multihopping code which ignores distances set to None, there is no check in the multi hop link finder. We're now running a version which ignores such links in its test.

I also noticed the function is using [] as a default argument, which is a python no-no.

I can make a PR that fixes both issues. Hopefully after we get MH working.

Modification
------------

**Comment by bari12** [comment]
Hi @ericvaandering 
Please go ahead with the changes. The code worked fine for us in our testing, there is other changes still to be done though since the link finder is sometimes a bit slow.
