### ISSUE TITLE
Agis collector - editing protocol in AGIS causes duplicating it in attributes

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#3382]
Motivation
----------
only one storm protocol is defined in AGIS:
http://atlas-agis.cern.ch/agis/service/detail/INFN-T1_SE_0/

two found in the attributes:
rucio-admin rse info INFN-T1_DATADISK
`  storm
    extended_attributes: None
    hostname: storm-fe.cr.cnaf.infn.it
    prefix: /storage/gpfs_atlas/atlas/atlasdatadisk/rucio/
    domains: {u'wan': {u'read': 4, u'write': 0, u'third_party_copy': 0, u'delete': 0}, u'lan': {u'read': 1, u'write': 0, u'delete': 0}}
    scheme: storm
    port: 8443
    impl: rucio.rse.protocols.storm.Default
  strom
    extended_attributes: None
    hostname: storm-fe.cr.cnaf.infn.it
    prefix: /webdav/atlas/atlasdatadisk/rucio/
    domains: {u'wan': {u'read': 4, u'write': 0, u'third_party_copy': 0, u'delete': 0}, u'lan': {u'read': 1, u'write': 0, u'delete': 0}}
    scheme: strom
    port: 8443
    impl: rucio.rse.protocols.storm.Default
`

Modification
------------

**Comment by TomasJavurek** [comment]
I'll try to delete the storm protocol manually (which removes both I suppose) and add the correct one with the correct prefix to the attributes.

**Comment by TomasJavurek** [comment]
After running:
rucio-admin delete-protocol --scheme storm INFN-T1_DATADISK
the correct protocol was removed but the wrong one remains.
At least this is shown in rucio-admin rse info
However, when I try to run the command for removing protocol again, it states that there is no storm protocol.

**Comment by TomasJavurek** [comment]
`[root@rucio-nagios-prod-02 test_area]# rucio-admin rse delete-protocol --scheme storm INFN-T1_DATADISK
RSE does not support requested protocol.
Details: RSE 'INFN-T1_DATADISK' does not support protocol 'storm'
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/usr/bin/rucio-admin", line 126, in new_funct
    return function(*args, **kwargs)
  File "/usr/bin/rucio-admin", line 668, in del_protocol_rse
    client.delete_protocols(args.rse, args.scheme, **kwargs)
  File "/usr/lib/python2.7/site-packages/rucio/client/rseclient.py", line 355, in delete_protocols
    raise exc_cls(exc_msg)
RSEProtocolNotSupported: RSE does not support requested protocol.
Details: RSE 'INFN-T1_DATADISK' does not support protocol 'storm'

[root@rucio-nagios-prod-02 test_area]# 
[root@rucio-nagios-prod-02 test_area]# 
[root@rucio-nagios-prod-02 test_area]# 
[root@rucio-nagios-prod-02 test_area]# rucio-admin rse add-protocol --hostname storm-fe.cr.cnaf.infn.it --scheme strom --prefix /storage/gpfs_atlas/atlasdatadisk/rucio/ --port 8443 --impl rucio.rse.protocols.storm.Default --domain-json '{"wan": {"read": 4, "write": 0, "third_party_copy": 0, "delete": 0}, "lan": {"read": 1, "write": 0, "delete": 0}}' INFN-T1_DATADISK
An object with the same identifier already exists.
Details: Protocol 'strom' on port 8443 already registered for  'INFN-T1_DATADISK' with hostname 'storm-fe.cr.cnaf.infn.it'.
This means that you are trying to add something that already exists.`

**Comment by TomasJavurek** [comment]
From Cedric:
this is a known feature. It should disappear when we move to CRIC + new importer

**Comment by dchristidis** [comment]
Additionally, there was a typo (`strom` instead of `storm`). Nothing to do here.
