### ISSUE TITLE
CMS: Pluggable schema definitions

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#339]
Right now, the security policy is encoded into a separate Python module; the selected security policy for a given Rucio instance is part of the `rucio.cfg`.  This allows Rucio to implement security policies that differ fairly drastically from ATLAS's default ones.

Analogously, the current schema is somewhat specific to ATLAS: it would be useful if we had an override mechanism to provide a CMS-specific schema.

For example, CMS site names are of the form `T2_US_Nebraska`; this is not currently a valid RSE as RSEs must be capitalized.

Another example is CMS LFNs and dataset names, which liberally utilize the `/` character (as in `/store/generator/Fall13pLHE/BprimeTToBZ_M1200GeV_Tune4C_13TeV-madgraph-tauola/GEN/START62_V1-v1/00000/5EE73686-1651-E411-B447-02163E00EF58.root` and `/BprimeTToBZ_M1200GeV_Tune4C_13TeV-madgraph-tauola/Fall13pLHE-START62_V1-v1/GEN`, respectively).

**Comment by bbockelm** [comment]
@vingar - is this fixed by #356 ?

**Comment by bari12** [comment]
Yes it is. Closing 😄
