### ISSUE TITLE
Documentation shows wrong Python versions for Server and Client

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#3402]
Motivation
----------
Documentation shows wrong Python versions in prerequisites for Server and Client.

https://github.com/rucio/rucio/blob/master/doc/source/installing_clients.rst#prerequisites
https://github.com/rucio/rucio/blob/master/doc/source/installing_server.rst#prerequisites

It should probably be 2.6, 2.7, 3.6, 3.7 and currently additionally 3.8 for the client? Is 2.6 still supported in the upcoming release?

**Comment by bari12** [comment]
You are right. We do not support 2.6 anymore at all.
So it should say: 2.7, 3.6, 3.7, 3.8 for both clients and server right now. (Plan is to drop 2.7 for the server with the November release)

**Comment by bziemons** [comment]
Why I said 3.8 for the client only: Numpy in version 1.14.2 does not compile with my Python 3.8 installation. I needed to install a newer Numpy version to set my venv up.

**Comment by bari12** [comment]
Ah good to know. `numpy` is not a very strict dependency though. We can (almost) remove that one since it is only used in one function which is not used much/at all.
