### ISSUE TITLE
Decorators are changing the function signatures

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#3415]
Motivation
----------

This comes up occasionally during operations or development. Using Python’s `help` will show, for example:
```
Help on function delete_rule in module rucio.core.rule:

delete_rule(*args, **kwargs)
    Delete a replication rule.
    
    :param rule_id:         The rule to delete.
    :param purge_replicas:  Purge the replicas immediately.
    :param soft:            Only perform a soft deletion.
    :param delete_parent:   Delete rules even if they have a child_rule_id set.
    :param nowait:          Nowait parameter for the FOR UPDATE statement.
    :param session:         The database session in use.
    :raises:                RuleNotFound if no Rule can be found.
    :raises:                UnsupportedOperation if the Rule is locked.
```

The documentation string is intact, but information like default parameter values is lost and one needs to look into the source code.

Modification
------------

Some ideas: https://hynek.me/articles/decorators/

**Comment by bziemons** [comment]
Running the following on Python 3.8.5:
```python3
import functools

def dec(func):
  @functools.wraps(func)
  def wrapper(*args, **kwargs):
    print("start")
    ret = func(*args, **kwargs)
    print("stop")
    return ret
  return wrapper

dec(print)("hi")
```
returns:
```
start
hi
stop
```

adding
```python3
@dec
def blub(bla: str):
  print("blubber", bla)
```
and actually, using `help(blub)` returns
```
Help on function blub in module __main__:

blub(bla: str)
```

even without the type hints this does not work on Python 2 though. But I think it is good to know that this issue is solved on newer Python versions.

**Comment by bari12** [comment]
Thanks @bziemons 
I would suggest to close this since we drop Python2.7 (For Server) with 1.24 anyway. @dchristidis is this ok for you?

**Comment by dchristidis** [comment]
That would be fine.
