### ISSUE TITLE
Infinite scalability for size of rules

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#3418]
Motivation
----------
Due to the way we load database contents to memory there is a physical restriction in the size of rules. 

Modification
------------
This methodology should be adapted to make rules infinitely scalable.

**Comment by cheapkai** [comment]
Sir could i be assigned this issue ?

**Comment by bari12** [comment]
Dear @cheapkai 
This issue was already implemented. It stayed open by accident unfortunately. If you are looking for some other issues in the Replication Rule area, might I suggest #2639
Cheers,
Martin

**Comment by cheapkai** [comment]
Thanks ballot Sir will look into it!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
