### ISSUE TITLE
Dependencies of paramiko (Crypto) need to be pinned explicitly for python 2.6 compatibility

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#345]
Motivation
----------
To ensure python 2.6 compatibility, the package paramiko was downgraded to an older version. However, it's dependencies, such as Crypto, need to be pinned to a Python 2.6 version as well to ensure compatibility.

**Comment by hugovk** [comment]
Is Python 2.6 support still required? It's EOL and hasn't received security updates in 4 years and generally isn't used much any more.

Here's the pip installs for rucio from PyPI for the last month (via `pypinfo --percent --pip rucio pyversion`)

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 2.7            |   59.3% |             83 |
| 3.5            |   40.0% |             56 |
| 3.4            |    0.7% |              1 |

And for rucio-clients:

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 3.5            |   65.1% |             54 |
| 2.7            |   28.9% |             24 |
| 2.6            |    6.0% |              5 |

And rucio-webui:

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 3.5            |   73.8% |             59 |
| 2.7            |   26.2% |             21 |
