### ISSUE TITLE
Rucio client package imports rucio.common.schema which is not part of distribution

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#3450]
Motivation
----------
From Isabel:
```
cmd: rucio upload --scope user.itrigger --rse TRIUMF-LCG2_SCRATCHDISK /tmp/itrigger/itrigger/.alrb/testing/tester.NKHUnK/rucio/bash/rucioUpload
2020-04-06 18:30:38,129
INFO Preparing upload for file myFile.d314ec0d-6684-4e3f-8501-47467586e335.log
2020-04-06 18:30:38,293
INFO Successfully added replica in Rucio catalogue at TRIUMF-LCG2_SCRATCHDISK
2020-04-06 18:30:38,842
INFO Successfully added replication rule at TRIUMF-LCG2_SCRATCHDISK
2020-04-06 18:30:39,962
ERROR No module named schema
2020-04-06 18:30:39,963
ERROR 
Rucio exited with an unexpected/unknown error.
Please rerun the last command with the "-v" option to gather more information.
If you're sure there is a problem with Rucio itself, please followup at: https://github.com/rucio/rucio/issues
rucio upload dataset (bash)                                         [FAILED]
```
For some reason the schema module seems to be imported, which is not part of the client distribution.

Modification
------------
We can add it to the distribution, but for me it is not clear why this is even needed, so we should understand this first.

**Comment by TomasJavurek** [comment]
line where we import the schema in client mode:
https://github.com/rucio/rucio/blob/next/lib/rucio/rse/protocols/protocol.py#L230

**Comment by bari12** [comment]
Ok, I followed this up and I think in this case we have to include common.schema as well to the clients package, as it is needed for the VO policy packages. I will prepare a PR.
