### ISSUE TITLE
Retrival of a lost file from an archive

### ISSUE THREAD

**Issue by TomasJavurek** [rucio/rucio#3485]
Motivation
----------
The archives should be also checked for a healthy replica of a lost/corrupted one. 

Modification
------------
1) archive replicas being visible when declaring the replica bad
2) possibility to use an archive replica for the recovery

**Comment by TomasJavurek** [comment]
The folowing query checks whether there is an additional available replica for a given suspicious file. The code is present in core/replicas.py -> get_suspicious_file() module:

`        available_replica = exists(select([1]).where(and_(replicas_alias.state == ReplicaState.AVAILABLE,
                                                          replicas_alias.scope == bad_replicas_alias.scope,
                                                          replicas_alias.name == bad_replicas_alias.name,
                                                          replicas_alias.rse_id != bad_replicas_alias.rse_id)))`
The question is if the query sees also a constituents of an archive. And if not, how it needs to be changed.

**Comment by TomasJavurek** [comment]
> The folowing query checks whether there is an additional available replica for a given suspicious file. The code is present in core/replicas.py -> get_suspicious_file() module:
> 
> ` available_replica = exists(select([1]).where(and_(replicas_alias.state == ReplicaState.AVAILABLE, replicas_alias.scope == bad_replicas_alias.scope, replicas_alias.name == bad_replicas_alias.name, replicas_alias.rse_id != bad_replicas_alias.rse_id)))`

**Comment by TomasJavurek** [comment]
The last pull request is solving the first task: a corrupted file won't be deleted by necromancer in case that there is a healthy replica in an archive. But there are few BUTs:

1) I am upgrading get_replicas_state() method in core of rucio. This method is used also by minos and test_replicas. It shouldn't cause problem there as far as I checeked, but it desereves more attention.

2) the query is now getting bit longer. I split that into two queries with inner join rather than use one query with outer join. I believe this is optimal, but I am not expert in DBs.

3) Needs to be tested better. I would like to see a file, that is both archived and not archived. In such case, we would get some result from both queries. I tried to achive that with picking up some archived constituent and copying it elsewhere with rule creation. The unarchived replica however appeared in result of the query for the archived replicas, which is strange. On the other hand, if I test a file with no archived replica, the result correctly comes from the query for the non-archived replicas.

**Comment by TomasJavurek** [comment]
Suggestion of Martin for (2), adding  a check whether a file is constituent in did table. If not, only the query to replicas table is used. In the other case, inner join to constituent table is applied.

**Comment by cheapkai** [comment]
Sir could you assign me a similar issue ?

**Comment by bari12** [comment]
Closing, no capacity
