### ISSUE TITLE
Unable to create new meta key with string type

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#3512]
Motivation
----------
If one attempts to make a DID key with a string value type:
```python
client.add_key(
    key="asdf",
    key_type="COLLECTION",
    value_type=str,
    value_regexp="\w{,50}",
)
```
then an exception is raised:
```
rucio.common.exception.UnsupportedValueType: Unsupported type for the value. List of supported types: (<type 'float'>, <type 'int'>, (<type 'basestring'>,)).
Details: The type '<type 'str'>' is not supported for values!
```

Proposal
---------
This is due to https://github.com/rucio/rucio/blob/master/lib/rucio/common/constraints.py#L25 where `six.string_types` is a tuple and should be added rather than nested. But that is not enough, as depending on whether you are in python2 or python3, different types will be valid. Really this should be an enum.

Note: tested in v1.22.2

**Comment by bari12** [comment]
Hi @nsmith- 
I just submitted a PR for this just with adding the string_types correctly. I think in the long run we should also change this to enums, but for now this should be sufficient.

**Comment by nsmith-** [comment]
Thanks!
