### ISSUE TITLE
rucio-admin subcommands display "Strange error" instead of help message

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3562]
Motivation
----------
```
$ rucio-admin scope
Strange error: 'Namespace' object has no attribute 'which'
```
As far as I can see this only happens when using python3.

Modification
------------

The help should be displayed showing subcommands and options.

**Comment by rak108** [comment]
This seems to be fixed, when I try running it I get the subcommands and options. Please confirm the same!

**Comment by bari12** [comment]
👍 I am closing this for now unless it is reported again.
