### ISSUE TITLE
Rucio client requires all OIDC properties in rucio.cfg when auth_type=oidc specified

### ISSUE THREAD

**Issue by paulmillar** [rucio/rucio#3581]
Motivation
----------

The rucio client may be run with the command-line option `-S OIDC` to specify that authentication should use OpenID-Connect.  The `auth_type` configuration property may be specified in the `rucio.cfg` configuration file's `[client]` stanza, to indicate which authentication scheme is used when the rucio client is run without the `-S` command-line option.

If the `auth_type` configuration property is specified with `oidc` (note the case) then the rucio client will default to using OIDC-based authentication.

Specifying `auth_type = oidc` triggers the rucio client to require all OIDC properties (those starting with `oidc_`) be defined .  If any OIDC configuration property is not defined in `rucio.cfg` then the rucio client will not run.

This is unfortunate for several reasons.

1. defaults exist for a reason.  By using a default, the user is allowing the rucio team to select a reasonable value without being an expert and understanding the implications of the different options. This is especially true for OIDC as the default values are not always obvious (requiring good knowledge of the OIDC protocol) and not all OIDC command-line option default values are documented.

2. default values can change over time.  The default value is the best choice, which may depend on several factors.  These factors can change over time, which means the default option may also change.  By forcing users to specify all values in their `rucio.cfg` file, such changes become harder to propagate.

3. The rucio client appears to behave differently, depending on whether values are specified.  A specific example is the `--oidc-issuer` command-line option and corresponding `oidc_issuer` configuration property.  If left unspecified then the rucio client uses a (server configured) default issuer; however, when `auth_type = oidc` is specified then `oidc_issuer` must be specified and the client must configure `oidc_issuer` with a specific issuer.

4. When `auth_type = oidc` is specified then both `oidc_user` and `oidc_password` properties must be specified.  When specified, the rucio client then attempts username+password based Authn against the OP.  Therefore, when `auth_type = oidc` the user is forced to store sensitive information in the `rucio.cfg` file.

Modification
------------

I think the best solution would be to update the parser so it uses the same default values as the command-line processing; in other words, specifying `-S OIDC` on the command line should be equivalent to specifying `auth_type = oidc` in the `rucio.cfg` file.  If values are not specified in the `rucio.cfg` file then defaults will be used irrespective of whether or not `auth_type = oidc` is specified.

**Comment by gumond** [comment]
Hello Paul, 

please I have already included this in my new patch branch from the previous issue #3572. Could we keep this under the same ticket #3572 ? I have already solution implemented in my dev branch. 

Thank you for testing and feedback ! 

Cheers, 
Jaroslav

**Comment by gumond** [comment]
Btw. to fix just the default auth_type, you should be able to define env variable, such as: 
export RUCIO_AUTH_TYPE=oidc
When I tried this, I see there is 'oidc' missing in the list on line 160 of baseclient.py, this is being fixed. I am also fixing the separation of the use cases for the rucio.cfg file along the lines you describe.

**Comment by paulmillar** [comment]
Thanks!

**Comment by bari12** [comment]
Closed & Moved to #3572
