### ISSUE TITLE
Failed to create protocol for PFN:

### ISSUE THREAD

**Issue by pzhao26** [rucio/rucio#3585]
Motivation
----------
Hi All, I am trying to download some MC files using rucio download. I have valid grid certificate and installed in my local cvmfs machine I have succesfully downloaded MC samples before until recently when I try to downlaod. It gives the error Failed to create protocol for PFN: root://lcgdpmse.dnp.fmph.uniba.sk:1094//dpm/dnp.fmph.uniba.sk/home/atlas/atlasdatadisk/rucio/mc16_13TeV/c3/a6/AOD.20823956._000002.pool.root.1
All other rucio command is functioning perfectly i.e rucio list-dids, rucio ping, rucio whoami but whenever I try to download it failed to create protocol for PFN: 
Any idea to help solved this problem? Is it related to network settings?

**Comment by bari12** [comment]
Hi,
There was a recent change on the ATLAS Local Rootbase which expects that you have installed `HEP_OSlibs` on your machine. So installing them should fix that issue.

**Comment by pzhao26** [comment]
> expects that you have installed `HEP_OSlibs` on your machine. So installing them should fix that issue.

Hi!
That worked! Thanks!

**Comment by pzhao26** [comment]
> Hi,
> There was a recent change on the ATLAS Local Rootbase which expects that you have installed `HEP_OSlibs` on your machine. So installing them should fix that issue.

Hi Bari12, 
It worked for a week, and now it does not download dataset and the error is simply
ERROR	Thread 0/3: Failed to download file mc16_13TeV:AOD.19980185._000001.pool.root.1
Again it worked on the lxplus but not my cvmfs area 
Package HEP_OSlibs-7.2.14-1.el7.cern.x86_64 already installed and latest version
Nothing to do

Is there some new change made recently?
