### ISSUE TITLE
Creation of rules on files for non-determinitic RSEs break the conveyor

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#36]
_Migrated from JIRA [RUCIO-2512](https://its.cern.ch/jira/browse/RUCIO-2512)_

**Comment by bari12** [comment]
scope:name for fake_dataset: other:other

**Comment by cserf** [comment]
I checked the code, and it looks like what is done in the conveyor is OK. 
But, there might be a problem if the file has a parent DID with the wrong number of `.`. It will be fixed. In addition this part is very ATLAS specific :
```
                    # DQ2 path always starts with /, but prefix might not end with /
                    naming_convention = rse_attrs[dest_rse_id].get('naming_convention', None)
                    dest_path = construct_surl(dsn, name, naming_convention)
```
We should have a way to have different conventions for different collaboration.
