### ISSUE TITLE
GridFTP uploads fail to create parent hash directories

### ISSUE THREAD

**Issue by mkszuba** [rucio/rucio#3681]
Motivation
----------

Not quite sure whether this belongs to Rucio or gfal2, then again it's the former that is responsible for the directory structure so I'm posting this here. We have a (dCache-based) RSE whose default access protocol is GridFTP and which uses the "two levels of hash directories" file-system structure. When I attempt to _rucio upload_ to copy a file to it which would require having both directory levels to be created from scratch, the upload fails:

```
WARNING	Upload attempt failed
DEBUG	Exception: The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: TRANSFER  ERROR: Copy failed with mode streamed, with error:
Authentication error, reached maximum number of attempts
INFO	Trying upload with gsiftp to DESY-DCACHE
ERROR	Access to local destination denied.
Details: Source file not found.
Details: globus_ftp_client: the server responded with an error 550 File
not found
```

On the server the error shows as follows:

```
event=org.dcache.ftp.response session=door:GFTP-dcache-door-doma01-AAWlrc5L6YA@dcache-door-doma01_gridftpDomain command="ENC{PUT path=/escape/wp2_rucio_testbed/desy_dcache/testing/b1/7a/a_file.rucio.upload;pasv;}" reply="ENC{550 File not found}"
```

So, rucio (or the client) is attempting to upload the file _a_file.rucio.upload_ into the directory _/escape/wp2_rucio_testbed/desy_dcache/testing/b1/7a_ but _ /escape/wp2_rucio_testbed/desy_dcache/testing/b1_ does not exist, causing the upload to fail.

Modification
------------

Make sure all parent directories are created before uploading the file.

**Comment by bari12** [comment]
So GFAL usually creates the directory if it does not exist. But this might also be a setting/permission issue on the DESY dcache. I remember Paul was mentioning something like this once.

**Comment by vokac** [comment]
Without `params.create_parent = True` (not set in rucio code) parent directories are not created automatically by gfal except for xrootd protocol, where it is not gfal but XRootD server "bug" (automatically create all parent directories) that is now kept for compatibility reasons and it was recently implemented also in dCache to provide compatible behaviour with XRootD server.

Currently rucio directly create parent directories for gfal protocol (except for HTTPS, so uploads with this protocol always fails in case of missing parent directory ... interesting behaviour):
https://github.com/rucio/rucio/blob/00798c9d6a47e495b0d6642ea255ae1021bb93dd/lib/rucio/rse/protocols/gfal.py#L412-L418

Transfers done with FTS always call gfal with "create_parent" set to True, so all parent directories are automatically create for TPC managed by FTS.

**Comment by bari12** [comment]
Thanks @vokac for the investigation. This is a bit of a pain though. We could add `params.create_parent` parameter, but I am not entirely sure that this is a good general solution either.

**Comment by mlassnig** [comment]
We should always strive to create the directories, in any case we want to put a file there! It doesn't fail when the directories already exist, right, because that would require a bit more complex logic, but still not so bad.

PS: For "https://" that's there for the cloud storage that uses the HTTPS signed URLs. For the typical davs:// endpoints it works as expected.

**Comment by mkszuba** [comment]
Sorry about the delay, I hoped I could test if setting _params.create_parent = True_ helps before responding but unfortunately DESY-DCACHE has developed some authentication issues and it is the only GridFTP RSE I can presently work with. Anyway, Paul is confident this is not a problem with their dCache permissions.

**Comment by bari12** [comment]
Closing; #2973 stays open (Duplicate)
