### ISSUE TITLE
Remove "old" dashboard link from Rucio UI

### ISSUE THREAD

**Issue by davidgcameron** [rucio/rucio#3691]
Motivation
----------
The old DDM dashboards have been decommissioned so I think you can remove the "old" link to dashb-atlas-ddm-old.cern.ch on the locks view of the UI.

Modification
------------
Remove the "old" link.

**Comment by varunbankar** [comment]
I would like to work on this issue.

**Comment by DhruvSondhi** [comment]
I would also like to work on this if it's not a problem?

**Comment by bari12** [comment]
Hi @varunbankar and @DhruvSondhi 
You can both work on this and submit a PR for it 👍 
Thanks
