### ISSUE TITLE
Add dirac_add_files method for the Rucio/Dirac integration

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#3692]
Motivation
----------
The goal of the method is to have a atomic way to create files for Dirac. Use case : I would like to create a file named `/belle//user/serfon/dir/mytest.root`. This should be part of dataset `/belle/user/serfon/dir`. The method needs to : 
- Check if `/belle/user/serfon/dir`  and all it's ascendants `/belle/user/serfon`, `/belle/user`, etc. exist. If not it creates and attachs them. 
- Create the file+replicas and a rule on the dataset.

Modification
------------
Create a new client, REST, API, core for dirac methods

**Comment by mlassnig** [comment]
Don't we have something like this for ATLAS Tier-0 already?

**Comment by cserf** [comment]
Nope. T0 just does a only `add_replicas` + `attach` and it's not atomic. What we want here is different, because we need to reconstruct the hierarchical namespace : 
Container `/belle` containing container `/belle/user` (and so on)  containing dataset `/belle/user/serfon/dir` containing file `/belle//user/serfon/dir/mytest.root` . The method should be able to create any of the non existing directories in an atomic way.
