### ISSUE TITLE
Add file to content history when the last replica is deleted by the reaper

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#37]
When the latest replica (eligible for deletion) is removed, the file is removed from the content but not archived.

_Migrated from JIRA [RUCIO-2570](https://its.cern.ch/jira/browse/RUCIO-2570)_

**Comment by bari12** [comment]
Needs to be checked

**Comment by bari12** [comment]
Needs to be done 😄

**Comment by dchristidis** [comment]
Starting today, I will be marking each time DDM Ops is affected by this issue.
:fire:
