### ISSUE TITLE
rucio get --no-subdir does not check if file already exists

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#3737]
Motivation
----------
From Rod on [JIRA](https://its.cern.ch/jira/browse/RUCIO-2896)

> Running this repeatedly always downloads the file
> rucio get --no-subdir --dir /tmp/walkerr mc15_13TeV:TXT.15373536._052641.tar.gz.1
> DID mc15_13TeV:TXT.15373536._052641.tar.gz.1
> Total files : 1
> Downloaded files : 1
> Files already found locally : 0
> Files that cannot be downloaded : 0
> i.e. Never "Files already found locally : 1"
> Cheers,
> Rod.

**Comment by bziemons** [comment]
For some reason it did state this explicitly: https://github.com/rucio/rucio/blob/36449940cf08788c70e941483630c3b5f81b6a5a/lib/rucio/client/downloadclient.py#L1390
Therefore I don't think this is a bug, but that's just a formality.
