### ISSUE TITLE
Gfal protocol does not handle xrootd double-slash requirement

### ISSUE THREAD

**Issue by mkszuba** [rucio/rucio#3738]
The old xrootd client protocol did account for the fact that in order for paths to be recognised as absolute they must be separated from the hostname/port part by two slashes rather than just one. Unfortunately the gfal protocol does not account for this, as a result when I try to upload a file to an xrootd-based RSE _rucio upload_ fails with "Permission denied", whereas the target xrootd server complains (only in debug mode though, in case you want to try reproducing this) about statting relative paths not being allowed.

I have worked around the problem by hacking _lfns2pfns()_ so that _web_service_path = '/'_ if the scheme is 'root', which allows uploads to succeed. No idea if this takes care of all the use cases, though.

**Comment by mkszuba** [comment]
Update: it was NOT enough, the file replica registered with Rucio still uses a relative path.

**Comment by bari12** [comment]
Hi,

When you create the protocol (root with implementation gfal) you can add the prefix starting with two slashes, that should take care of it. If you directly use the xrootd implementation it shouldn't be necessary, but for root with gfal it is.

**Comment by mkszuba** [comment]
I have contacted our Rucio-server admins to update the protocol. Thank you for the explanation!
