### ISSUE TITLE
Incorrect documentation on passing the dynamic parameter to /dids/(scope)/(name)

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#3761]
Motivation
----------

Following the documentation, adding `?dynamic` to the URL has no effect. Instead, one has to use something like `?dynamic=anything`. Possibly also applies to `/dids/(scope)/(name)/dids`.

Modification
------------

Either address the documentation or investigate why the parameter isn’t properly propagated.

**Comment by bziemons** [comment]
For Flask that is not the case anymore, I just debugged through https://github.com/rucio/rucio/blob/02e86830f10c1bd7e5ea2a05d306706a09127bfe/lib/rucio/web/rest/flaskapi/v1/dids.py#L368 and dynamic is True as soon as it is in the args. This might have been different with web.py. I will fix the documentation hickup on `/dids/(scope)/(name)/dids`.
