### ISSUE TITLE
long=True query string does not work for /dids/{scope}/dids/search REST API

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#3762]
Motivation
----------
According to the RESTFul API documentation in:
https://rucio.readthedocs.io/en/latest/restapi/did.html#get--dids-(scope)-dids-search

one could pass `long=True` as a query string to get further information about DIDs, otherwise only the DID name gets returned. It seems to have no effect on the output, and I get only the DID names regardless of setting that flag to True or not.

Modification
------------
Either fix the code such that the `long` parameter acts as expected; or fix the documentation in case this parameter is not supposed to be there.

**Comment by bari12** [comment]
@bziemons can you please have a look on this. It is probably not correctly passed through from the rest to api layer. Might also be a True vs 1 thing. Thanks!

**Comment by bari12** [comment]
This change broke backwards compatibility.
The reason is that old clients will still submit with `long=1`, but this is not handled correctly on the server, since the server ist just looking for `long=True` now. I missed that in the review as well :-) I will add this and produce a hotfix release.

**Comment by amaltaro** [comment]
Apologies Martin, I knew it would change the way long is evaluated on the server, but I didn't consider making it backwards compatible with external clients, my bad!

**Comment by bari12** [comment]
No worries. These backwards-compatibility issues are really hard to spot and unfortunately also quite hard to test for. I didn't spot it either during review.
