### ISSUE TITLE
CMS: Allow `rucio upload` to accept alternate LFNs

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#377]
Currently, `rucio upload` is a bit tied to the ATLAS concept that the filename on disk (`foo.root`) is going to match the filename in Rucio (`user.bbockelm:foo.root`).

This is a bit broken by CMS, where the LFN differs significantly from the name on disk.  We should allow the LFN to be specified via a CLI flag, just like the GUID.

The `rucio upload` interface should, by default, retain the current behavior.

**Comment by mlassnig** [comment]
I'm trying to wrap my head around the implications of this. This mapping of DID ( path+name on disk) <-> LFN(CMS namespace) needs to be stored somehow. If you just give a different LFN to the DID that you're storing, how will you be able to use/download it later again? (as the lookup is against the DID, and not against an LFN).

**Comment by vingar** [comment]
If the LFN on disk differs, `rucio upload` can take a PFN attribute (LFN on disk). But this works for non deterministic endpoint.   For deterministic, the function LFN -> PFN is needed.

**Comment by bari12** [comment]
I am trying to understand the issue a bit. Is it just for the upload purely (That's my understanding from the ticket/PR) Thus you have a filename on disk (`1234.567`) which gets uploaded and registered in rucio as (`user.bbockelm:foo.root`). Or would this also involve the download, thus when you do a `rucio download user.bbockelm:foo.root` you get `1234.567` again?

**Comment by bari12** [comment]
@bbockelm can you maybe write down an example (or a few) how the data identifiers and paths on storage look right now and the different conventions in building the path (I remember you linked some XML file on slack); Just to give us an easier understanding of what we want to achieve.

**Comment by bbockelm** [comment]
(sorry, was out sick on Friday...)

Let's assume for now that we call the CMS scope `cms` (currently, everything in the experiment is organized into a single namespace and socially, we're not likely to change this...).  Then, for the LFN we have now:

```
/store/generator/Fall13pLHE/BprimeTToBZ_M1200GeV_Tune4C_13TeV-madgraph-tauola/GEN/START62_V1-v1/00000/5EE73686-1651-E411-B447-02163E00EF58.root
```

we would use the following DID:

```
cms:/store/generator/Fall13pLHE/BprimeTToBZ_M1200GeV_Tune4C_13TeV-madgraph-tauola/GEN/START62_V1-v1/00000/5EE73686-1651-E411-B447-02163E00EF58.root
```

Currently, when `rucio upload` is invoked, the file name on the local disk is not necessarily the same as the filename in the LFN (`5EE73686-1651-E411-B447-02163E00EF58.root` in this case ... it's really a mistake in the case of CMS to attach too much value to the component after the last `/` in the LFN, as it's not really the file's name).

@mlassnig is right: this will need a corresponding patch for `rucio download` so the user can specify an output file name.  However, downloading a file is a nearly-unused case in CMS, which is why I wasn't worried about it at the outset here.  In almost all use cases, the files are accessed via the physics application, not the workflow layer (there's no concept of a "mover" for stagein as in ATLAS).

@bari12 - here's an example of what the PFN generation rules look like:

https://cmsweb.cern.ch/phedex/datasvc/xml/prod/tfc?node=T2_US_Nebraska

The discussion might really belong in #338, but we can get most of the use cases demonstrated by simply concatenating the LFN to the prefix.

**Comment by bbockelm** [comment]
Oh - as an example, here's likely how CMS would want to be able to upload files:

```
rucio --verbose upload --scope user.bbockelm --rse T2_US_NEBRASKA_USERDISK myGreatFile.root \
      --lfn /store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root
```

**Comment by bari12** [comment]
Ah I see more clearly what you mean now. I feel though that this mixes Rucio concepts a bit up, in your example above the did (Or in some sense the Rucio LFN) would be: `user.bbockelm: myGreatFile.root` but we additionally would have to store the CMS-LFN `/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root` plus the path on actual storage, as this cannot be derived just by the did `user.bbockelm:myGreatFile.root` itself. It is possible to expand the schema like this, but I wonder, would you ever address the file with the "Rucio LFN/did" ("user.bbockelm:myGreatFile.root")? Because if not, why not make the Rucio did in the first place: `user.bbockelm:/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root` We would have to extend the column and allow "/" in the name part of the did and tinker with the client a bit, but it seems like the more natural workflow to me? Please correct if I understand anything wrong 😄

**Comment by bbockelm** [comment]
@bari12 - nope, I'm not sure that's correct.

In this example, `myGreatFile.root` is some random set of characters produced by the workflow management system which have no particular meaning once the job ends.  CMS refers to the file as:

```
/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root
```

forever and ever after that.

Then, given that LFN, we construct the corresponding PFN -- usually via concatenation of a known prefix:

```
gsiftp://red-gridftp.unl.edu/user/cms/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root
```

Despite the `/` strongly suggesting a directory hierarchy, it is really treated as an opaque name.  For example, at RAL's Echo instance, I believe we have a pool group named `cms` and the object name is `/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root`.

So, for a Rucio DID, I think this file would be referred to as the concatenation of the scope (`cms`) and the LFN:

```
cms:/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root
```

**Comment by mlassnig** [comment]
Ok, so the mapping will then be simply  

DID:
  cms:/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root

and the replica at RAL-ECHO would generate this PFN:

  gsiftp://red-gridftp.unl.edu/user/cms/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root


That's certainly doable. I guess at a later stage you can explore the use of scopes in your workflow? But for now, like this your workflow management could continue as-is.

**Comment by bbockelm** [comment]
@mlassnig - that's almost right:  `s|RAL-ECHO|T2_US_Nebraska|` and it'll be 100% correct.

Given how the workflows are architected and the CMS computing project is organized, I think it's likely we'll use a single scope for >95% of our data.  A few places where we might do additional scopes:

* Testing data for things like load-tests and scaling campaigns.
* Temporary outputs from the workflow management that are later combined into "official" files.
* Release validation is often run as quite separate from the rest of CMS.

But these are not a bit second-order for now.

**Comment by bari12** [comment]
Great, that's what I thought too, that after the upload the original filename `myGreatFile.root` is basically meaningless to you. I would suggest (I think most changes are there already?) that we adapt rucio in a way to make the did `cms:/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root` If you want to use multiple scopes or not is really up to you, for Rucio there is no difference.

This should be much easier to manage, as we don't need to take care of the CMS-LFN separately, as it is already encoded in the did. For the determinism I think we could overload the 'default' handling with the hashes in the cms policy file with the lookup in the xml, such that the did `cms:/store/mc/SAM/GenericTTbar/AODSIM/CMSSW_9_2_6_91X_mcRun1_realistic_v2-v1/00000/AE237916-5D76-E711-A48C-FA163EEEBFED.root` gets transformed to the PFN easily via the xml lookup.

Plus some changes in the client to deal with the input filename and the did with slashes correctly.

**Comment by bbockelm** [comment]
@bari12 - for having alternate determinism policies, it seems the alternatives are:

1.  Have a RSE protocol attribute that enables this and have the appropriate LFN-to-PFN function look for the attribute and behave appropriately.  That's what I did in this case; you can imagine a full implementation would have a list of rules instead of a single boolean.
2.  Have a "cms mode" specified in the policy (a third policy?) where CMS can provide its own LFN2PFN function, which would internally lookup the associated RSE protocol and implement the mapping.  This could then be stored outside the Rucio source tree.

Did I capture that correctly?  Honestly, my preference would be to start with 1 as it is done (boolean toggle) here (instead of doing the full XML, simply do the concatenation without the hashing) and then do 2 later on in the evaluation.  What's done here will allow us to use probably 90% of sites -- I hope!

**Comment by bari12** [comment]
Yes, in the long run I would really prefer the second method. My thinking was to "overwrite" the current default (with the two hashes) via the CMS policy file could have the advantage that you do not have to set the determinism_type for each RSE. It just works correctly out of the box. So Rucio won't do it wrong if you create an RSE and forget to set the setting. You could do this at first with this simple method you already implemented and later on expand in the full XML rule mode.

But if you feel more comfortable to do it first with option 1 and later on only change to option 2 this is completely fine.

**Comment by bari12** [comment]
🎈 🍾
