### ISSUE TITLE
Return files size when listing scope DIDs

### ISSUE THREAD

**Issue by gabrielefronze** [rucio/rucio#3775]
Motivation
----------
The API response when listing the DIDs belonging solely to a scope or to a container is very dissimilar.
While in the first case the bytes size is not shown:

```
{"scope": "O3", "type": "FILE", "name": "K-K1_llhoft-1266855936-4096.gwf", "parent": null, "level": 0}
```

in the second it is:

```
{"adler32": "3011a75c", "name": "K-K1_C10-1268027392-4096.gwf", "bytes": 34248761, "scope": "O3", "type": "FILE", "md5": "3a46a528ff1d618f5791e3f0eceb42f8"}
```

Having a similar pattern (or at least the bytes size) would greatly improve the operations of the FUSE-Posix module, since it would enable bulk file size retrieval even at the scope level (and not only within a dataset or container).

Modification
------------
It should suffice to edit the API implementation around https://github.com/rucio/rucio/blob/master/lib/rucio/core/did.py#L1098 in order to introduce the retrieval of other fields, as done here https://github.com/rucio/rucio/blob/master/lib/rucio/core/did.py#L1141 .

**Comment by viveknigam3003** [comment]
I'll handle this one.
