### ISSUE TITLE
AUTHORS update

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#380]
Motivation
----------
In order to track all contributions to Rucio, a separate file "AUTHORS" is included top-level. It includes both individual personal contributors, as well as their associated institutes or organisations.

**Comment by jwackito** [comment]
I appear twice in AUTHORS
Joaquín Bogado <jbogado@linti.unlp.edu.ar>, 2014-2017 
Joaquin Bogado <jbogadog@cern.ch>, 2017-2017
Only the first is valid.
Also, I think UNLP (Universidad Nacional de La Plata - Argentina) should appear as institution.
:)

**Comment by vingar** [comment]
@jwackito it's because of the mail address associated to your commits and the difference of accent in the first name. Could you try to stick to one mail address ? ideally the one associated to you github account to get the activity history linked to it.

**Comment by jwackito** [comment]
@vingar I will do. Thanks!
