### ISSUE TITLE
Incomplete download looks "complete" when restricting RSEs

### ISSUE THREAD

**Issue by rgugel** [rucio/rucio#3824]
Motivation
----------
As a user one may naively assume that a dataset/container is completely downloaded when seeing an output like
```
Total files :                                93
Downloaded files :                            0
Files already found locally :                93
Files that cannot be downloaded :             0
```
and a return code of 0. However, this example is taken from a case where I restricted the RSEs to download from, e.g., via `rucio download --rse '*\SOME_PROBLEMATIC_SITE' someContainer` and the full container contains more than the 93 files reported. (Downloads from the problematic site in this case keep failing for a subset of the files involved)

The effect is the same if some RSE is explicitly selected (`--rse 'SOME_GOOD_RSE'`) or individual RSEs are vetoed as in the example above.

Modification
------------
The total number of files should likely be determined without the RSE restriction to avoid files only present on the excluded RSEs being forgotten about. If the current counting is intentional it would be good to at least print a warning in case only a restricted set of RSEs was considered.

**Comment by TomasJavurek** [comment]
this can be close since it is solved in #3805

**Comment by bari12** [comment]
https://github.com/rucio/rucio/blob/3eeeca8f99e8f58fd24925e014289f23edc0c534/bin/rucio#L1043
The implementation for this breaks the possibility to do `rucio download <name>` without giving the `<scope>:<name>` pair.

I am reverting the code and reopen the ticket. We will add the fixed feature in a later release again.

**Comment by bari12** [comment]
Ideally, we should count the files of the dataset and display this information as well.
The output should show:
```
Total files (did):                            This should show the logical files in DID
Total files (after filter):                   This should show the files available & after applying filter
Downloaded files:                             0
Files already found locally:                  93
Files that cannot be downloaded:              0
```
