### ISSUE TITLE
Cannot deny rule which is made with a lock

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#3843]
Motivation
----------
CMS is going to use the approve/deny rule functionality to make sure sites have tape families for datasets before allowing them onto tape. Those rules are made in a locked state (by Rucio, we think). 

Denying these rules does not work. 

Modification
------------

I think the way to solve this is to add a parameter ignore_locks to delete_rule in core/rule.py and make deny rule use it.

There is a separate issue that when using the web UI, there is no useful message output, just a red bar.

**Comment by bari12** [comment]
I think that solution is good. I would just call the parameter `ignore_rule_lock` so there is no confusion with replica locks.
Alternatively, within `deny_rule` you can also just check if there is a lock active and remove it. (Might be easier)
