### ISSUE TITLE
rucio-admin rse info does not return protocols and/or RSE usages

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#3854]
Motivation
----------

```
'<' not supported between instances of 'dict' and 'dict'
This means the parameter you passed has a wrong type.
```

Modification
------------

**Comment by patrick-austin** [comment]
I ran into this problem on the RAL instance, my solution was to change the line [`for protocol in sorted(rseinfo['protocols']):`](https://github.com/rucio/rucio/blob/master/bin/rucio-admin#L564) in `rucio-admin` to `for protocol in sorted(rseinfo['protocols'], key=lambda x: x['scheme']):`, so we explicitly sort the dictionaries alphabetically by their scheme (which I assume is what we were trying to do before?)

**Comment by bziemons** [comment]
Since the scheme is the first thing that is printed, I am assuming so
https://github.com/rucio/rucio/blob/4ba63bb3388de25993d6ee8225396e1878662a8e/bin/rucio-admin#L565

@patrick-austin do you want to open a PR or should I?

**Comment by bziemons** [comment]
@mlassnig since you did add the `sorted` (https://github.com/rucio/rucio/pull/3665), would you agree with the change mentioned by Patrick?

**Comment by patrick-austin** [comment]
@bziemons I can open a PR for it, I just wanted to check that sorting by scheme was the intended behaviour beforehand.
