### ISSUE TITLE
 WARNING   : Failed to create protocol for PFN

### ISSUE THREAD

**Issue by robertosussex** [rucio/rucio#3863]
Hi there,

We are using cvmfs on the HPC.
We are loading rucio with
export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
source $ATLAS_LOCAL_ROOT_BASE/user/atlasLocalSetup.sh
lsetup rucio

However the command:
rucio download group.phys-susy.XAMPP.HadHad.Prod_V3_16e.C1N2_Stau_900p0_400p0_XAMPP --nrandom 1 --dir .

fails on one of the nodes
(after voms-proxy-init -voms atlas)

with the error
WARNING  Failed to create protocol for PFN ... etc

However on another node with almost the same setting it works fine

What do you reckon I should check to troubleshoot the issue ?
we have

 rpm -qa --last | grep cvmfs

egi-cvmfs-2-4.0.14.obs.el7.noarch             Fri 17 Jul 2020 16:25:14 BST
cvmfs-x509-helper-1.2-1.28.obs.el7.x86_64     Fri 17 Jul 2020 16:25:14 BST
cvmfs-2.7.2-1.el7.x86_64                      Fri 17 Jul 2020 16:25:00 BST
cvmfs-config-egi-2.4-4.0.13.obs.el7.noarch    Fri 17 Jul 2020 16:24:59 BST
cvmfs-contrib-release-1.11-1.noarch           Fri 17 Jul 2020 16:24:50 BST
cvmfs-release-2-6.noarch                      Wed 12 Dec 2018 05:12:08 GMT

and the initial setup gives

export ATLAS_LOCAL_ROOT_BASE=/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
-bash-4.2$ source $ATLAS_LOCAL_ROOT_BASE/user/atlasLocalSetup.sh
lsetup               lsetup <tool1> [ <tool2> ...] (see lsetup -h):
 lsetup agis          ATLAS Grid Information System
 lsetup asetup        (or asetup) to setup an Athena release
 lsetup atlantis      Atlantis: event display
 lsetup eiclient      Event Index
 lsetup emi           EMI: grid middleware user interface
 lsetup ganga         Ganga: job definition and management client
 lsetup lcgenv        lcgenv: setup tools from cvmfs SFT repository
 lsetup panda         Panda: Production ANd Distributed Analysis
 lsetup pod           Proof-on-Demand (obsolete)
 lsetup pyami         pyAMI: ATLAS Metadata Interface python client
 lsetup root          ROOT data processing framework
 lsetup rucio         distributed data management system client
 lsetup views         Set up a full LCG release
 lsetup xcache        XRootD local proxy cache
 lsetup xrootd        XRootD data access
advancedTools        advanced tools menu
diagnostics          diagnostic tools menu
helpMe               more help
printMenu            show this menu
showVersions         show versions of installed software

-bash-4.2$ #lsetup "root 6.18.04-x86_64-centos7-gcc8-opt"
-bash-4.2$ #root
-bash-4.2$ lsetup rucio
************************************************************************
Requested:  rucio ...
 Setting up emi 4.0.2-1_200423.fix1 ...
 Setting up rucio 1.22.8 ...
Info: Setting compatibility to centos7
Info: Set RUCIO_AUTH_TYPE to x509_proxy
Do you want to set the RUCIO_ACCOUNT to rs558 (y/n)?

Any advice ?

Roberto Scipioni
MPS Research Computing Support
University of Sussex

----------

Modification
------------

**Comment by bari12** [comment]
Hi @robertosussex 
There was a somewhat recent change on the ATLAS Local Rootbase which requires that the `HEP_OSLibs` are installed on the machine, which includes dependencies like protocols etc. This is not coming anymore directly from the ALRB setup. I would assume that this might be related to your issue. Can you try to install `HEP_OSLibs` on the node and try again?
