### ISSUE TITLE
Change m-VO tests to use postgres

### ISSUE THREAD

**Issue by patrick-austin** [rucio/rucio#3865]
Motivation
----------
PostgreSQL is a more widely used DB dialect than the currently used SQLite. It should still be sufficient to only test m-VO explicitly against one of the supported DB dialects however.

Modification
------------
Alter the `.cfg`s used in the test suite to use PostgreSQL, and rename files appropriately.

**Comment by bziemons** [comment]
I think SQLAlchemy does a pretty good job of abstracting the actual DB away and since SQLite is somewhat faster to setup and less error prone on its own, because it is much simpler, I'd suggest to think about it again. What is the gain from this?

**Comment by bari12** [comment]
There is some peculiarities with the different databases, e.g. in handling constraints, compound indices, partitioning etc. which sqlalchemy does not entirely cover. It's better to test multi-VO with a DB which is actually being used by clients in production. Postgres is a good choice for that. I don't think we need to test all the other ones (like we do for the single-vo mode), but running the multi-vo tests on postgres has just a bigger potential to uncover an issue than with sqlite.

**Comment by patrick-austin** [comment]
I'm not knowledgeable on the pros/cons of the different DBs myself (initially I chose SQLite because the client suite used it so it seemed sensible to pick that one). Martin brought up the points above at a m-VO development meeting on the 23rd of June, so I made a note to make the change from SQLite to PostgreSQL. The change wasn't included in the main m-VO PR, but the work was done a while ago.
I'm happy to make this change or not make it depending on what people think is best, but personally I don't know enough to contribute to the discussion.

**Comment by patrick-austin** [comment]
Changing to PostgreSQL uncovered that the (new?) delete_metadata function wasn't passing the VO through the REST layer (SQLite doesn't support JSON metadata so the test for that function wasn't running before). No impact for single-VO as the API defaults the VO to 'def' when REST doesn't provide it.

Will include a fix in the PR for this issue.
