### ISSUE TITLE
Poor error message when the Rucio server certificate has expired.

### ISSUE THREAD

**Issue by paulmillar** [rucio/rucio#3866]
Motivation
----------

I would like to understand why the Rucio client is unable to connect to the server, as this may facilitate diagnosing the problem and speed up its resolution.  For example, some problems the user can fix by themselves while other problems require changes on the server.

Modification
------------

The Rucio server at escape-dios-dl.cern.ch currently has an expired certificate:

```
paul@sprocket:~$ host escape-dios-dl.cern.ch
escape-dios-dl.cern.ch has address 188.184.86.179
paul@sprocket:~$ openssl s_client -connect escape-dios-dl.cern.ch:443 2>/dev/null </dev/null | openssl x509 -noout -dates
notBefore=Jun  5 08:52:03 2019 GMT
notAfter=Jul  9 08:52:03 2020 GMT
paul@sprocket:~$ 
```

While this is unfortunately, what is interesting is how the rucio client reacts to this problem, and reports back to the user:

```
paul@sprocket:~$ rucio whoami
2020-07-21 19:16:11,245 ERROR   Cannot connect to the Rucio server.
paul@sprocket:~$ 
```

While this is technically correct, it provides no information about why the client cannot connect to the server.  From the limited available information, the problem could be due to some networking problem, the rucio server's certificate not being trusted, certificate has expired, or some other problem.

It would be helpful if the error message contained some more details on why the connection failed.

**Comment by bari12** [comment]
Hi @paulmillar 
I agree, some more descriptive error message would be helpful here.

**Comment by TomasJavurek** [comment]
Hi @paulmillar,
the correct error message about a wrong auth. should be in place:
https://github.com/rucio/rucio/blob/master/bin/rucio#L275
only explanation I see is, that the config is not set properly. Could I see your rucio cfg file?

**Comment by TomasJavurek** [comment]
Hi @paulmillar @bari12,
I think I found the bug preventing the proper logging to be printed. It is really not lack of verbosity, it just can not get to the right lines. Check:
[baceclient-l363](https://github.com/rucio/rucio/blob/4cec8f5ac13c3ce1d37f8f0248f9b3697a70e190/lib/rucio/client/baseclient.py#L363)
There is a for loop running until `self.AUTH_RETRIES`, but exception is raised only if `retry > self.request_retries` and this condition can be sometimes unreachable. So naturally, the `ServerConnectionException` is thrown. Also, there's an empty `raise` without an exception, I guess this could cause unpredictable issues if that happened. I'll try to fix that and @mlassnig will need to check that.

**Comment by TomasJavurek** [comment]
Linked to this is also #3912 , with current log level, the message wouldn't be displayed at all.

**Comment by bari12** [comment]
Error should probably be mentioned in request return object, just needs to be displayed client side.

**Comment by ThePhisch** [comment]
As per the conversation with @bari12, I will include a check whether the `cryptography` module can be imported. If it is possible, we return the expiration date, if not, we simply return an error message. This means that `cryptography` does not necessarily have to be installed, saving the project from including further dependencies.
