### ISSUE TITLE
Enabling tests for different policy package

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#3878]
Motivation
----------
Up-to now the tests only include tests following the ATLAS policy (i.e. ATLAS schema, permission, etc.). Some methods like the `addfile` method in `core.rucio.dirac` request different DID naming convention and won't work with ATLAS schema. It would be good if one can specify different sets of tests depending on different policies.

**Comment by bziemons** [comment]
How are the tests for different policy packages planned? Is it going to be a new test suite or do you plan to integrate it into the existing test suites? Currently there are exclusion rules and no 'inclusion' of tests. I guess adding more exclusion rules for the different polices would be sufficient? If possible, please add a *Modification* section with the information.

**Comment by cserf** [comment]
We need to discuss what we want with @bari12. From my point of view, having a list of exclusion rule for each policy would be enough.

**Comment by bari12** [comment]
👍 Let's discuss when I am back from vacation. I think in general this would be a good idea, and we could also add community/policy specific tests, which the communities would have to provide.
