### ISSUE TITLE
Multihop monitoring

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#3902]
Motivation
----------
Currently the monitoring does not really show which transfers are multihop. Moreover, we send a different message for each hop. In case when an intermediate hop fails, we'll send a failure message for each hop starting the failure location, but the next hops will all have an empty reason. 

This information would be helpful for debugging and also in general to know how much multihop is being done.

Modification
------------
Add a multihop flag to the messages. (For each leg). Also, ensure that the reason is set for all hops starting the failure hop.

**Comment by mlassnig** [comment]
Adding @vokac
