### ISSUE TITLE
Logged exceptions could contain much more useful information

### ISSUE THREAD

**Issue by knservis** [rucio/rucio#3911]
Motivation
----------

Improve logged exceptions.

Modification
------------

Where the logged messages is uninformative, using `logger.exception` could improve troubleshooting, for instance here:

https://github.com/rucio/rucio/blob/7820df402a54bcf1436173fa517f79b9bcc8986b/bin/rucio#L227

and here:

https://github.com/rucio/rucio/blob/7820df402a54bcf1436173fa517f79b9bcc8986b/bin/rucio#L2371

In the last instance the assessment 'Strange error' probably does not add any value or helps the log reader diagnose the issue. I suggest clarifying the message.

**Comment by bari12** [comment]
I agree, that would be helpful. Esepcially in the "strange error" case which was always quite unhelpful.

**Comment by bari12** [comment]
Remove try/except block for the strange (unexpected) error and let the stack trace happen.
