### ISSUE TITLE
Unconditionally reducing the log level omits important information even under '-v' 

### ISSUE THREAD

**Issue by knservis** [rucio/rucio#3912]
The following reduces the log level, even when the user has requested '-v' for verbose (which also sets the log level to DEBUG).

https://github.com/rucio/rucio/blob/7820df402a54bcf1436173fa517f79b9bcc8986b/lib/rucio/client/baseclient.py#L96

In addition the following line:
https://github.com/rucio/rucio/blob/7820df402a54bcf1436173fa517f79b9bcc8986b/lib/rucio/client/baseclient.py#L376

Would be much more informative using `LOG.exception()`

**Comment by TomasJavurek** [comment]
Exception is perhaps not the ideal one, since we use custom Formatter. I guess exception would print the warning as an error, which might be inpropriete (I believe the developer that coded this placed the warning for a reason). But the question is why the debug is temporarily switched off, and maybe rather switch that back here.

**Comment by TomasJavurek** [comment]
An obvious solution would be to set the log level globaly: 
`logging.basicConfig(level=logging.DEBUG)`
on line:
https://github.com/rucio/rucio/blob/release-1.23-LTS/bin/rucio#L2365
but that would produce uncontralled tracks with no correct formater like the following, rucio - whoami reseulted to:

`DEBUG:rucio.client.baseclient:no creds passed. Trying to get it from the config file.
DEBUG:rucio.client.baseclient:no ca_cert passed. Trying to get it from the config file.
DEBUG:rucio.client.baseclient:no account passed. Trying to get it from the config file.
DEBUG:rucio.client.baseclient:no vo passed. Trying to get it from the config file.
DEBUG:rucio.client.baseclient:got token from file
DEBUG:dogpile.lock:NeedRegenerationException
DEBUG:dogpile.lock:no value, waiting for create lock
DEBUG:dogpile.lock:value creation lock <dogpile.cache.region._LockWrapper object at 0x7f72e0c7c8d0> acquired
DEBUG:dogpile.lock:Calling creation function for not-yet-present value
DEBUG:dogpile.lock:Released creation lock
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): rucio:443
DEBUG:urllib3.connectionpool:https://rucio:443 "GET /accounts/whoami HTTP/1.1" 303 0
DEBUG:urllib3.connectionpool:https://rucio:443 "GET /accounts/root HTTP/1.1" 200 197`

**Comment by TomasJavurek** [comment]
I prefer to create a method in utils, that would set a logger to the level that bin/rucio logger has. This would be done only for the modules that we wish to have that feature. This would effectively mean, that for example dogpile logger from the previous example is skipped.

**Comment by TomasJavurek** [comment]
I tried to add to the utils:
`def setup_logger(logger):
    '''
    Method to set logger level and formatter.
    :param logger: logger to be set.
    '''
    import logging
    from copy import deepcopy
    loggers = [name for name in logging.root.manager.loggerDict]

    # setting log level
    user_log_level = logger.getEffectiveLevel()
    user_log = None
    if 'user' in loggers:
        user_log = getLogger('user')
        user_log_level = user_log.getEffectiveLevel()
        print('User log retrieved.', user_log_level)
    logger.setLevel(user_log_level)

    # getting formatter
    formatter = None
    for h in user_log.handlers:
        if h.formatter:
            formatter = deepcopy(h.formatter)
            print(formatter._fmt)
            print('Formatter utils', id(formatter))
            break

    # setting formatter
    if logger.handlers:
        for h in logger.handlers:
            h.setFormatter(formatter)
            print('Formatter set.')
    else:
        hdlr = logging.StreamHandler()
        hdlr.setFormatter(formatter)
        logger.addHandler(hdlr)
`

but then whenever calling the `setup_logger(logger)`, it never does the thing. It seems that it is called earlier than the formatter is added to the user logger. I tried to place it in baseclient, but also further in the other clientes, e.g. directly into the `whoami()` method of the accounclient. But it always printed a message before the one adding formatter to the user log. It might be, that the formatter is physically added only when the first message is printed. But that is weird.

**Comment by TomasJavurek** [comment]
I it is getting bit more complicate, since unit testing needs a fixed logger levels. I summarized the current knowledge here:
https://docs.google.com/presentation/d/1F6Und9AJ_YS9RVMIzO3NYyZO_zucPGs-rB2U8gwqzbg/edit?usp=sharing

**Comment by TomasJavurek** [comment]
just an explanation for the cache cleaning in the last commit:
![image](https://user-images.githubusercontent.com/33832672/99043421-86146780-258e-11eb-86d0-d59c79c2d593.png)
