### ISSUE TITLE
Error message 'NoSuchBucket' not matched via stringification

### ISSUE THREAD

**Issue by knservis** [rucio/rucio#3925]
The following test uses `str(e)` to find out whether the string contains 'NoSuchBucket', however (at least in boto 2.49.0) that message is contained in `e.message` and the default error stringification (inherited form BotoServerError):
https://github.com/boto/boto/blob/91ba037e54ef521c379263b0ac769c66182527d7/boto/exception.py#L154-L156
does not include that instance attribute. 

https://github.com/rucio/rucio/blob/59af37a14e343f938131863969d130f5336e4a28/lib/rucio/rse/protocols/s3boto.py#L247

**Comment by davidpob99** [comment]
According with https://github.com/boto/boto/blob/develop/boto/s3/connection.py#L557-L567 and https://github.com/boto/boto/blob/develop/tests/unit/s3/test_connection.py#L393 it seems that the 'NoSuchBucket' string is stored in `e.error_code` instead of in `e.message`
