### ISSUE TITLE
add # in cms regexp name

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#394]
Modification
------------
add # in cms regexp name

**Comment by ericvaandering** [comment]
I don't think this patch worked. I try to create a dataset with the name ```SingleMuonLRun2017A-PromptReco-v2LMINIAOD#7ca0e53a-4c6a-11e7-a64a-001e67ac06a0``` and it returns OK as if it worked, however 
```
[root@16ed54928c0b /]# rucio list-dids user.ewv:SingleMuonLRun\*
+----------------------------------------------------+--------------+
| SCOPE:NAME                                         | [DID TYPE]   |
|----------------------------------------------------+--------------|
| user.ewv:SingleMuonLRun2017A-PromptReco-v2LMINIAOD | DATASET      |
+----------------------------------------------------+--------------+
```

So the dataset name was truncated at the # character.

**Comment by bbockelm** [comment]
I suspect the patch worked but hit client escaping issues.  Can you try creating a different dataset with a CMS block name and note the timestamp when you did it?  I can then poke around the Apache logs.

**Comment by vingar** [comment]
From the log:
```
[19/Dec/2017:16:14:28 -0600] "POST /dids/user.ewv/SingleMuonLRun2017A-PromptReco-v2LMINIAOD HTTP/1.1" 201 7
```
the client generates the right url:
```https://localhost:443/dids/mock/SingleMuonLRun2017A-PromptReco-v2LMINIAOD%237ca0e53a-4c6a-11e7-a64a-001e67ac06a0```

but then server side the url is changed and names with hash mark should be 'urllib.quoted' ?

**Comment by ericvaandering** [comment]
If its on the client, I can try to find and fix it. Please assign to me. I'll let you know if I can't.

**Comment by vingar** [comment]
no sure, it's only on the clients. This might need some change in apache, wsgi and server code.

**Comment by ericvaandering** [comment]
Ah, "hash" is the HTML anchor.

**Comment by bbockelm** [comment]
@ericvaandering - if you want to tack a whack at this, you probably want to edit something like this:

https://github.com/rucio/rucio/blob/master/lib/rucio/client/didclient.py#L83

replacing

```
        path = '/'.join([self.DIDS_BASEURL, scope, name])
```

with

```
        path = '/'.join([self.DIDS_BASEURL, scope, urllib.quote_plus(name)])
```

However, I strongly suspect we should re-close this issue as this really appears to be a client problem, not the schema.

**Comment by ericvaandering** [comment]
Yes, this is not enough. Encoding the URL is not sufficient. It still comes back as dataset exists (dropping the # and everything after it seems).

**Comment by bbockelm** [comment]
Re-closing this issue as I can create these datasets on the CMS instance with the client patches in #437 applied.
