### ISSUE TITLE
add_replicas with PFN does not consider lower-priority protocols

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#3940]
Motivation
----------

If the primary protocol is not available via WAN, it immediately jumps to first priority LAN, and fails afterwards if not possible.
The secondary and later protocols are never tried.

**Comment by gabrielefronze** [comment]
Hey @mlassnig ,

If I get it right it is related to the algorithm here:
https://github.com/rucio/rucio/blob/f711667ee4a4ea8c898098f8380c311460dc2642/lib/rucio/core/replica.py#L1363-L1371

which internally uses:
https://github.com/rucio/rucio/blob/f711667ee4a4ea8c898098f8380c311460dc2642/lib/rucio/rse/rsemanager.py#L159-L169

called here:
https://github.com/rucio/rucio/blob/f711667ee4a4ea8c898098f8380c311460dc2642/lib/rucio/rse/rsemanager.py#L192

Would it be ok to directly call `_get_possible_protocols` from `add_replica` and iterate over the protocols?

**Comment by mlassnig** [comment]
The `_get_possible_protocols` is an internal function of the rsemanager. I think you can just refactor it to make it a public `get_possible_protocols`, and use that then.

**Comment by gabrielefronze** [comment]
Yup, that's what I wished I could do!

**Comment by gabrielefronze** [comment]
Update: `get_protocols_ordered` is already there and public, I'll rely on that.
