### ISSUE TITLE
DID format not validated leading to ValueError

### ISSUE THREAD

**Issue by knservis** [rucio/rucio#3945]
This line does not check whether there DIDs have a valid format (i.e. ':' separated string):

https://github.com/rucio/rucio/blob/4cec8f5ac13c3ce1d37f8f0248f9b3697a70e190/bin/rucio#L1040

This leads to an ungraceful error:
```
 Traceback (most recent call last):
  File "bin/rucio", line 162, in new_funct
    return function(*args, **kwargs)
  File "bin/rucio", line 1040, in download
    scope, name_exp = d.split(':')
ValueError: not enough values to unpack (expected 2, got 1)
```
Easy to diagnose of course but argument validation could provide a better error message. 

In addition, consider using the argument in `--scope` for when a scope is not given in a DID (it is stated in the help text that this is only used for filter, but it would be more intuitive in my opinion to just use that when the DID does not have a scope).

**Comment by mlassnig** [comment]
Thanks for the report! Fortunately this is an easy fix!

**Comment by mlassnig** [comment]
I see this was already fixed by reverting the buggy commit. https://github.com/rucio/rucio/pull/3936 

It made it into client release 1.23.3 though.
