### ISSUE TITLE
Provide a better error description for list_dataset_replicas_bulk client API

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#3981]
Motivation
----------
As mentioned in this GH issue comment:
https://github.com/rucio/rucio/issues/2459#issuecomment-686940735

if a call to the `list_dataset_replicas_bulk` API is not properly constructed and it fails on the server side, the server should respond with an error that best describe what the problem was, instead of responding with:
```
rucio.common.exception.RucioException: An unknown exception occurred.
Details: no error information passed (http status code: 500 ('internal_server_error', 'server_error', '/o\\', '\xe2\x9c\x97'))
``` 

In addition to that, perhaps the server http-error-logs could be a bit more verbose when these errors happen, instead of simply have a single line such as:
```
[core:error] ... Premature end of script headers: replica.py
```

NOTE: I'm not sure whether this same generic error can be returned for other APIs, but I have definitely seen it while calling a few REST APIs that require parameters to be encoded (maybe the `/rules` one).

Modification
------------
Ideally, the end user should be able to know what the problem was with his/her query/parameters. Which means, the server should report a more specific error message.

**Comment by bari12** [comment]
In principle I agree and we try to do that, but I think in this case this was really the issue with the schema, which is not all that easy to catch.

**Comment by bziemons** [comment]
> In principle I agree and we try to do that, but I think in this case this was really the issue with the schema, which is not all that easy to catch.

@bari12 I can remember seeing a nice and descriptive error on the server-side, which was not propagated to the client-side. I will see if I can fix this, since I am already looking at a lot of the APIs right now
