### ISSUE TITLE
Extend get_dataset_locks API to support requests in bulk

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#3982]
Motivation
----------
This is a similar feature request as the one made in: https://github.com/rucio/rucio/issues/2459

It would be extremely helpful to be able to provide a list of DIDs (dataset type) to the `get_dataset_locks` API, such that we could retrieve all the locks for a container with a single API call.

This is a very common use case for CMS, where provided a container name, we need to find out all the RSEs holding part of that container.

Modification
------------
Support a list of DIDs to be passed to the `get_dataset_locks`, such that the number of API calls can be drastically decreased for larger containers.

**Comment by bari12** [comment]
That should be easy to do, similar to the #2459. @ericvaandering any chance anyone from the CMS team can take this issue?

**Comment by nsmith-** [comment]
Should this API also be able to filter the locks by account?

**Comment by ivmfnal** [comment]
How do you expect the resulting list to be structured ? Just plain list of all locks found, or by did ?

**Comment by bari12** [comment]
Just a question, if it is always all datasetlocks for a given container, wouldn't it be better to have a feature where you can query by container? (Instead of resolving to all the datasets and then querying them in bulk?) - This can be in addition to a bulk query.

For the server it would probably be better to stream these through, so you don't have to build any dictionaries in memory. The did organization could then be done client side.

**Comment by amaltaro** [comment]
> How do you expect the resulting list to be structured ? Just plain list of all locks found, or by did ?

Igor, having them organized by DID would be the best.

>Just a question, if it is always all datasetlocks for a given container, wouldn't it be better to have a feature where you can query by container? (Instead of resolving to all the datasets and then querying them in bulk?) - This can be in addition to a bulk query.

Honestly, it would be great to have a dataset_locks lookup for a given container. However, having the ability to provide a list of datasets is also needed. Shall we create another GH issue for the container based API?

**Comment by bari12** [comment]
Yes, a second (related) issue would be good. 
This would also be more in line how, for example, `list_replicas` works, there you can also use a file/dataset/container did interchangeable and it will resolve to all replicas.

**Comment by ivmfnal** [comment]
If we do both:

1. list locks for a list of datasets
2. list locks for datasets found in the container

Can in fact (2) be implemented using (1) at the web client level, hidden from the user as following ?

1. get list of datasets for the container
2. get list of locks for the list of datasets

**Comment by amaltaro** [comment]
Okay, I have created a new issue for the container dataset_lock discovery: https://github.com/rucio/rucio/issues/4807

And having a second thought on this discussion, it could be that listing dataset_locks for a given container would be sufficient for the CMS WM system. Thus, leaving the external application to do any necessary filtering on the wanted datasets. From my side, if I had to prioritize these two issues, I would say that the container-based lookup should go first :)
