### ISSUE TITLE
Add archive timestamps to database

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#3983]
Motivation
----------
As described in slide 5 of
https://docs.google.com/presentation/d/1xygW4F272XvdTYKDP2Snux2NicEi-neG_5bJQFhBLKw/edit#slide=id.g93e536a259_0_94

update Rucio to store the relevant timestamps for archiving as well.

Modification
------------

Suggestion from @bari12 : 2. These timestamps are set here: https://github.com/rucio/rucio/blob/be2ac1cb86f3fe426b2e8aa5dd87491bce771d3c/lib/rucio/core/request.py#L464
Eg. staging_started_at etc. So we would need to check to get the value from fts and then pass it (and adapt) this method.

**Comment by bari12** [comment]
Any update on this ticket?

**Comment by rcarpa** [comment]
@ericvaandering , are you working on this ticket? Is it still desired? 
I could take over the work on the ticket if you describe a bit what exactly is desired. Is it just about adding the archive_started_at and archive_ended_at timestamps and filling them into rucio ?

**Comment by ericvaandering** [comment]
I am not working on it. Honestly I don't remember why we were interested in this, but if you would like to add it, you can. I think it requires a schema change and another query to FTS for tape writes. Probably the idea is to track tape write delays to get a better handle on what archive_timeout should be set to for each site.

**Comment by rcarpa** [comment]
If it's not needed anymore, I'd rather just close the ticket. Otherwise we just two fields to the database for nothing.
