### ISSUE TITLE
Collection replicas are not being updated for temporarily unavailable replicas

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4015]
Motivation
----------

This affects PanDA and potentially users who rely solely on the result of `list-dataset-replicas` to deduce whether a dataset is fully replicated at a particular RSE.

Modification
------------

Propagate the state change, both when the replica is declared as temporarily unavailable and when it’s made available again. If it makes any difference, there’s a another workflow: a temporarily unavailable replica being declared as lost and, consequently, either recovered or removed from the parent DID.

**Comment by dchristidis** [comment]
There was a report of another workflow where the collection replicas are not kept up-to-date: When a file is declared as lost and there’s another copy to recover from, the dataset appears fully replicated while the recovery in on-going. In most cases this should be fairly quick, but not always (e.g. recovering from tape).

Should this be handled in this ticket or would you prefer a separate one?

**Comment by rodwalker** [comment]
This one is important. Declaring the 500k lost files at AGLT2 does not help panda brokerage at all when the dataset replicas are left complete.

Cheers,
Rod

**Comment by rodwalker** [comment]
This one is important. Declaring the 500k lost files at AGLT2 does not help panda brokerage at all when the dataset replicas are left complete.

Cheers,
Rod

**Comment by bari12** [comment]
Closing, duplicate of #3526
