### ISSUE TITLE
Database JSON compatibility check

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4019]
Motivation
----------
At multiple points in the code we check if the database supports JSON compatibility. This check however has already been generalised in 
https://github.com/rucio/rucio/blob/75de3f9fe85f33667de3da282e3607185dd37ec0/lib/rucio/core/did_meta_plugins/json_meta.py#L200

Modification
------------
I would suggest to move the check method to `common.utils` and call this method at all the different parts in the code where JSON compatibility has to be checked.

**Comment by bziemons** [comment]
Fixed in #4255: https://github.com/rucio/rucio/pull/4255/files#diff-32882e2964a57c2774f2daf224f26c75a7c2a846dc998bac2f3ef8841a05578dR286-R304
