### ISSUE TITLE
Update error messages to refer to GitHub

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#402]
Motivation
----------

On error, it's possible to get something like this:

```
2017-12-18 21:48:29,429 ERROR   Rucio exited with an unexpected/unknown error.
Please rerun the last command with the '-v' option and submit a ticket with all the
available information to reproduce this error at https://its.cern.ch/jira/browse/RUCIO
```

(linebreaks added by me for readability)

Should this be just changed to GitHub?

Modification
------------

Modify `rucio` CLI as needed to selectively remove references to CERN JIRA (there may be some cases that are ATLAS-specific where this is warranted).  Probably worthwhile to `grep` through the entire code base to see if there's any other place where this can be done.

**Comment by mlassnig** [comment]
I already had a PR for this submitted, but reverted it as it ties in with the discussion about the whole policy/permissions thing.

The idea was to have something like this in rucio.cfg:

[common]
vo_support = <email_address>
rucio_support = https://github.com/rucio/rucio/issues


and depending on the error show the appropriate followup.

**Comment by vingar** [comment]
pull request: #247 
issue duplicated with: #243  
Proposal:

```
[policy]
organization_support = <>
rucio_support =<>
```
in the pull request, the error messages are generated client side, which forces to have the right parameters with the clients (in addition to the hostnames, etc). Server side would have been more flexible.

**Comment by bari12** [comment]
It is more flexible,  but some errors might be generated client side and then you would have to contact the server to know the addresses. Overall not a big issue I think, as the config has to be distributed anyway. I am closing this, let's follow up in #243
