### ISSUE TITLE
Distance based sorting of replicas

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4020]
Motivation
----------
Currently `list_replicas` offers two ways of sorting replicas which happens on the API level: geoip and random, with random being the default. The idea of this development would be to offer a distance based sorting (Based on the distance table) similar to how it is done for third party transfers. At first that sorting method should just be optional, but eventually it should be the default sorting method to bring this in line with how the source sorting is done for third party transfers.

**Comment by mlassnig** [comment]
```
Hi @mlassnig,

I just checked and Rucio is still not giving back properly ordered replicas. They should be ordered by geo distance.
Code was done probably 1y ago but it was never debugged as I have no access rights and Martin was looking for a student to do the job.
Since this is important not only for VP but everything that access data remotely (eg. servicex), this is really high priority.
I bet it would take you a few hours to solve it.

To reproduce problem run the code attached to this email at lxplus. 
```
[testSORTING.txt](https://github.com/rucio/rucio/files/8611358/testSORTING.txt)
```
The code will look up replicas for a dataset that exists at FZK and MWT2. 
First time you run it, it will give priority to FZK replica.

Then you set these:
export RUCIO_LATITUDE=41.7821
export RUCIO_LONGITUDE=-87.6046

This should make rucio think client is at Chicago.

Run the code again and it will again give priority to FZK which is wrong.

Please let me know what do you find.

Thanks,
@ivukotic 
```

**Comment by bari12** [comment]
This is the wrong issue for this. This issue is strictly about `distance` (Thus distance table) based sorting, not geoip distance. We should create a new issue for this, but a test-case reproducing the issue as a unit-test (Not on a production instance) would be really appreciated.

**Comment by bari12** [comment]
Closed for now, not needed
