### ISSUE TITLE
Client : Remove CryptographyDeprecationWarning

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#4024]
Motivation
----------
```
>>> from rucio.client import Client
/usr/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
```

**Comment by tbeerman** [comment]
Why don't you just use python3?

**Comment by bziemons** [comment]
Just to bring this here: There is a `PYTHONWARNINGS`[\[1\]] environment variable which is in control of warning output. It was said that it does not work on Python 2.7, but I just tested this with our docker dev environment which runs Python 2 and it worked fine:
`docker exec -it dev_rucio_1 /bin/sh -c 'PYTHONWARNINGS=ignore tools/run_tests_docker.sh -ir'`

[\[1\]]: https://docs.python.org/2.7/using/cmdline.html?highlight=pythonwarnings#envvar-PYTHONWARNINGS
