### ISSUE TITLE
Automatic recovery of suspicious files that have more than one replica

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#403]
Motivation
----------
If often happens that suspicious files have more than one replica. In that case an automatic recovery can be done without the need of a human confirmation.

Modification
------------
Automatic recovery of suspicious files that have more than one replica

**Comment by bari12** [comment]
Don't we have this behaviour already for files marked as BAD? So wouldn't it be enough to mark a suspicious file as bad?

**Comment by mlassnig** [comment]
@gumond has volunteered for this task

**Comment by bari12** [comment]
This was implemented as a probe in #1871, but it should probably be it's own daemon.

**Comment by gumond** [comment]
I have not had a look at this task yet. I considered it closed. When I come back tomorrow, I will see with you & Cedric how rucio daemons are implemented and what could I do about creating this one.

**Comment by gumond** [comment]
bin/rucio-replica-recoverer:
- Contains, in an epilog variable, my current procedure for manual testing.  
- Once I learn more about rucio, should I write a test for this daemon ? 

lib/rucio/core/replica.py: 
- Although there are some differences, the two functions 'get_suspicious_files' and the new 'get_available_suspicious_replicas' seem to be aiming for similar outputs. Could we merge the two into one ?
