### ISSUE TITLE
Evaluate dataset replication state in the get_dataset_locks API

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#4034]
Motivation
----------
As quickly discussed over slack. One could have a use case where given a rule on a container, we want to check which datasets are locked, where, and whether all the files have already been transferred.
If one queries the `get_dataset_locks` API, it would return the state of the rule itself, instead of returning the current state of that given dataset. That means, dataset_locks will only consider the lock as state=OK, once the container-level rule is completely satisfied; which is of course sub-optimal for large containers.

Modification
------------
It would be beneficial if `get_dataset_locks` would return the actual state of that dataset replication, i.e. if all the files for a given dataset have already replicated to their final destination (under a given rule), then the expected state should be OK, even if the container rule hasn't yet being completely satisfied.

**Comment by bari12** [comment]
As discussed on Slack, I will look into this (no eta though).
To only return the state of the container-rule was somewhat of an optimization done to save on complexity. I would have to check how complex it is to reflect the actual dataset state.
