### ISSUE TITLE
Scope check in upload client crashes in certain conditions

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4039]
Motivation
----------
https://github.com/rucio/rucio/blob/fe6eb2e9cd7e1bc9464b955aa0a7d974c961fe82/lib/rucio/client/uploadclient.py#L350
Here the uploadclient checks if the account owns the scope it is uploading to and if not displays a warning message.
However, due to this check is done, if the account does not own any scopes, the `ScopeNotFound` exception is raised which crashes the uploadclient at that point.

Modification
------------
Catch that exception, display the warning but continue with the upload otherwise.

**Comment by TomasJavurek** [comment]
The suggestion from Martin is implemented, but I think it didn't solve the problem entirely. If we don't raise exception here, we get the prblem at db level later:

`Details: [u'(psycopg2.errors.ForeignKeyViolation) insert or update on table "dids" violates foreign key constraint "DIDS_SCOPE_FK"\nDETAIL:  Key (scope)=(test) is not present in table "scopes".\n']`
