### ISSUE TITLE
Port web ui to Flask

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4041]
Motivation
----------
Recently I have finished porting tests to the the Flask REST endpoints and fixed a lot of issues on the endpoints to make the tests run. The web ui currently still runs on the webpy framwork and needs porting before we can completely remove webpy.

Modification
------------
Port templates and all ui related code from webpy to Flask.

**Comment by bziemons** [comment]
@tbeerman @gabrielefronze any input on this or do any of you want to take it?

**Comment by tbeerman** [comment]
I can take it.

**Comment by gabrielefronze** [comment]
Feel free to ask my support in case some more manpower is needed!
