### ISSUE TITLE
OIDC authentication endpoint on Flask

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4042]
Motivation
----------
Currently the OIDC authentication endpoint on Flask returns simple one-liner texts. Since the webpy version returned HTML via an HTML template, this needs to be evaluated for necessity and ported accordingly. This is probably related to #4041 since it uses templates as well. This is a leftover task from #3975 since the OIDC endpoints weren't created for Flask before.

Modification
------------
Create HTML templates for the Flask OIDC authentication endpoints and render them instead of returning simple text.

**Comment by bari12** [comment]
👍 yes we will still need these html renders.

**Comment by bziemons** [comment]
@gabrielefronze there is also this, which is on a smaller scale than #4041 but essentially quite similar.
