### ISSUE TITLE
Unicode support along all Core/API/REST API

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4045]
Motivation
----------
When working on porting the REST framework tests to Flask #4033 I encountered problems when handing Python 2 `unicode` type text. While we want to remove Python 2 compatibility in 1.24, these layers of compatibility can be removed. Left to research is how these functions work with Python 3 unicode native `str` type strings. I have already fixed an issue in #3995 but I think there is more to find and fix.

Modification
------------
Research API functions and called functions for unicode support and remove Python 2 compatibility code (for the server only).

**Comment by sayang14** [comment]
Hi @mlassnig!, I am Sayandeep and I am deeply interested in open source projects and also applied to ROOT TMVA project in gsoc this year.
Currently I am really attracted to Rucio especially after reading the documentation. This issue looks interesting. Can I have a try at this issue?

**Comment by bari12** [comment]
Hi @sayang14 yes please go ahead, thanks 😄

**Comment by joeldierkes** [comment]
Related to #5435

**Comment by bziemons** [comment]
Since we got rid of `six` as a dependency and Python 2 compatibility, all unicode type references are gone. I still identified the following code lines that could be simplified:

https://github.com/rucio/rucio/blob/2a41a64899f41b356660fff80a7530765b5d59e0/lib/rucio/__init__.py#L20

https://github.com/rucio/rucio/blob/2a41a64899f41b356660fff80a7530765b5d59e0/lib/rucio/core/permission/cms.py#L25-L30

https://github.com/rucio/rucio/blob/1ac5d8a00d5894d27025528590d0a80bae4d1f69/lib/rucio/web/ui/flask/common/utils.py#L33-L35

CC @bari12
