### ISSUE TITLE
Test suite for importing python modules

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4046]
Motivation
----------
There were several issues with importing modules that automatically load configuration values or importing modules that imported server dependencies on the clients.

Modification
------------
Create a test suite that outputs warnings for all files being imported that load configuration values so this general issue can be followed up on.
Also add a test to this suite that imports all client modules without any server or test pip dependencies, so that errors are thrown when unavailable dependencies are loaded.

Replaces `lib/rucio/tests/test_module_import.py`

**Comment by maany** [comment]
Hey @bziemons, when you have some time, could you loop me into this?

**Comment by LukasMoll** [comment]
Hi, I want to work on this.

Quesion: for the files that import configuration values, are those the files mentioned inside before_script.sh (for example alembic_sqlite.ini)?

@bziemons

**Comment by bziemons** [comment]
@LukasMoll Specifically, I meant the use of this module: https://github.com/rucio/rucio/blob/c44effdbc4598db7b35e6b4df38e2c055acaa14b/lib/rucio/common/config.py

Using `config_get` without default value in the global scope (on import) will unfortunately crash Rucio (if the configuration file is absent or incomplete) without a good description of the error and should be avoided. Therefore, I thought a warning in a test suite would be a good start to catch these problems. Even with a default value set, to a new user/developer it is sometimes unclear what Rucio does and tests might not reach certain code.

**Comment by LukasMoll** [comment]
@bziemons Thank you.

Here's an overview of what I'm thinking

I check in the cfg directories wether there is a file if not: warning, if: check wether all the fields are there, if not warning(references: [config1 template](https://github.com/rucio/rucio/blob/c44effdbc4598db7b35e6b4df38e2c055acaa14b/etc/rse-accounts.cfg.template), [config2 template](https://github.com/rucio/rucio/blob/c44effdbc4598db7b35e6b4df38e2c055acaa14b/etc/rucio.cfg.template)).

For the second part: scrape all imports from clients folder and try to import them, if not: error.

Does this sound good?

**Comment by bziemons** [comment]
> I check in the cfg directories wether there is a file if not: warning, if: check wether all the fields are there, if not warning(references: [config1 template](https://github.com/rucio/rucio/blob/c44effdbc4598db7b35e6b4df38e2c055acaa14b/etc/rse-accounts.cfg.template), [config2 template](https://github.com/rucio/rucio/blob/c44effdbc4598db7b35e6b4df38e2c055acaa14b/etc/rucio.cfg.template)).

I am afraid you have to run the code to actually know which config variables are used and which aren't. Also it would be valuable to know the exact file and line where the config variable is "misused" (as described in my first answer).

> For the second part: scrape all imports from clients folder and try to import them, if not: error.

Basically sounds correct, but to make it easier I would probably use the rucio_client package and then just import every python file in the same context as the client tests would run. That would reuse the client test setup and then just does basic `importlib` usage on all modules. Parsing python files should really be left to the Python runtime. It is way too complicated to scrape all imports in all different ways they could occur.

**Comment by LukasMoll** [comment]
> I am afraid you have to run the code to actually know which config variables are used and which aren't. Also it would be valuable to know the exact file and line where the config variable is "misused" (as described in my first answer).

Sorry I don't understand. My idea was to check if for example [here](https://github.com/rucio/rucio/blob/c44effdbc4598db7b35e6b4df38e2c055acaa14b/etc/rse-accounts.cfg.template#L2-L6) that it contains one "username": "..." and so forth for the rest. So basically I'm comparing against the template and if it's not similar (not there, double, not right format etc.) then we'll give an error message with the info. This goes for all possible files mentioned in your first response config.py.

>Basically sounds correct, but to make it easier I would probably use the rucio_client package and then just import every python file in the same context as the client tests would run. That would reuse the client test setup and then just does basic importlib usage on all modules. Parsing python files should really be left to the Python runtime. It is way too complicated to scrape all imports in all different ways they could occur.

Forgot to mention: I was planning on using modulefinder, a library that gives a list of all the imports in a given directory to scrape. I can use rucio_client if you want.

**Comment by bziemons** [comment]
> Sorry I don't understand. My idea was to check if for example [here](https://github.com/rucio/rucio/blob/c44effdbc4598db7b35e6b4df38e2c055acaa14b/etc/rse-accounts.cfg.template#L2-L6) that it contains one "username": "..." and so forth for the rest. So basically I'm comparing against the template and if it's not similar (not there, double, not right format etc.) then we'll give an error message with the info. This goes for all possible files mentioned in your first response config.py.

Sorry, maybe I misunderstood you before. What I mean are code occurrences like these that need reporting: https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/daemons/c3po/utils/popularity.py#L23
This has nothing to do with the configuration templates directly.

> Forgot to mention: I was planning on using modulefinder, a library that gives a list of all the imports in a given directory to scrape. I can use rucio_client if you want.

Sounds alright, as long as the result is basically the same.
