### ISSUE TITLE
Improve the usability of manually running the CI tests

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4047]
Motivation
----------
Make `tools/run_autotests.sh` more usable and useful without CI by honoring exit signals and clean up started conatiners.

Modification
------------
Make `tools/test/run_tests.py` and probably `build_images.py` honor signals like `SIGTERM` and `SIGINT` and properly cleanup, also on docker (requested by @mlassnig ;) ). This includes moving container creation from `tools/test/before_script.sh` to python for ownership.

**Comment by bziemons** [comment]
@maany I would start working on this soon, any objections or recent information?

**Comment by maany** [comment]
Hey @bziemons, that's awesome! Good to have you aboard again. No objections and no significant changes to the autotest workflows. So your proposed solution is still the way to go :)
