### ISSUE TITLE
`rucio erase` with wildcards

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#406]
Motivation
----------
```
# rucio erase user.ewv:Astore\*
2017-12-18 15:48:14,645    INFO    CAUTION! erase operation is irreversible after 24 hours. To cancel this operation you can run the following command:
rucio erase --undo user.ewv:Astore*
```
Expected behavior
-----------------

Fail with error message

**Comment by TWAtGH** [comment]
Will it be enough to just check in bin/rucio erase if there is a wildcard given and then print an error?
I'm wondering why set_metadata isn't rising an exception for the `(key='lifetime' and '*' in did_name)` case.

**Comment by bari12** [comment]
Yes, the error should be raised on server side though.
