### ISSUE TITLE
Unhelpful error message for certificates with incorrect permissions

### ISSUE THREAD

**Issue by pchanial** [rucio/rucio#4071]
Motivation
----------
Using auth_type=x509, authentication fails when the personal certificate and private key have not the permission 400. Mines had 600. And I got the following error message.

```
$ rucio whoami
Internal error: Request for authentication token returned no result!
2020-10-13 08:58:00,389    ERROR    Cannot authenticate.
Details: x509 authentication failed for account=pchanial with identity={'client_cert': '/opt/rucio/etc/client.crt', 'client_key': '/opt/rucio/etc/client.key'}

```

Modification
------------
Certificate permissions should be checked and the user should be told what to do to fix it if they are not 400, to prevent wasting time on checking the validity of his/her certificates.

**Comment by pchanial** [comment]
Thanks. But it looks like the fix is still too liberal since it only checks the group and other permissions. In the issue I've reported, the fix wouldn't have helped since the certificate permission was 600 instead of 400. Also, in the error message, I guess 'maximum' was intended instead of 'minimum'.

**Comment by mlassnig** [comment]
Interesting, my openssl did not complain for 600. I will add the check for this as well.

Maximum/Minimum: hah, classic.

Thanks!
