### ISSUE TITLE
Allow Rucio upload to copy files from remote location with gfal

### ISSUE THREAD

**Issue by dciangot** [rucio/rucio#4072]
Motivation
----------
Right now the upload python API is checking for files to be uploaded only on local fs (*). It would be useful to allow the copy of the source files from a remote location with gfal.

(*) https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L488-L501)

Modification
------------
It should be possible to use gfal.stat instead to do the checks and to allow the remote copy.

**Comment by TomasJavurek** [comment]
just short summary of what I tried so far:

`gfal-copy srm://se.bfg.uni-freiburg.de:8443/srm/managerv2?SFN=/pnfs/bfg.uni-freiburg.de/data/atlasdatadisk/rucio/user/ddmadmin/c8/ae/sonar.test.UNI-FREIBURG_DATADISK.file1.rnd gsiftp://eosatlassftp.cern.ch:2811/eos/atlas/atlasdatadisk/rucio/user/ddmadmin/e0/e4/sonar.test.UNI-FREIBURG_DATADISK.file1.rnd`

worked well. However for the gfal implementations in Rucio and its bindings to the gfal plugin:

`2020-11-03 13:08:36,092	9885	INFO	Event triggered: BOTH GFAL2:CORE:COPY LIST:ITEM srm://se.bfg.uni-freiburg.de:8443/srm/managerv2?SFN=/pnfs/bfg.uni-freiburg.de/data/atlasdatadisk/rucio/user/ddmadmin/c8/ae/sonar.test.UNI-FREIBURG_DATADISK.file1.rnd => gsiftp://eosatlassftp.cern.ch:2811/eos/atlas/atlasdatadisk/rucio/user/ddmadmin/e0/e4/sonar.test.UNI-FREIBURG_DATADISK.file11.rnd
2020-11-03 13:08:36,093	9885	INFO	Event triggered: BOTH GFAL2:CORE:COPY LIST:EXIT 
2020-11-03 13:08:36,105	9885	WARNING	Failed to ping srm://se.bfg.uni-freiburg.de:8443/srm/managerv2?SFN=/pnfs/bfg.uni-freiburg.de/data/atlasdatadisk/rucio/user/ddmadmin/c8/ae/sonar.test.UNI-FREIBURG_DATADISK.file1.rnd`

the failure was an outcome of the following script:

`from rucio.rse import rsemanager as rsemgr

src_pfn = 'srm://se.bfg.uni-freiburg.de:8443/srm/managerv2?SFN=/pnfs/bfg.uni-freiburg.de/data/atlasdatadisk/rucio/user/ddmadmin/c8/ae/sonar.test.UNI-FREIBURG_DATADISK.file1.rnd'
dst_pfn = 'gsiftp://eosatlassftp.cern.ch:2811/eos/atlas/atlasdatadisk/rucio/user/ddmadmin/e0/e4/sonar.test.UNI-FREIBURG_DATADISK.file11.rnd'
dst_rse = 'CERN-PROD_DATADISK'

rse_settings = rsemgr.get_rse_info(dst_rse)
u_prot = rsemgr.create_protocol(rse_settings, 'write')
u_prot.connect()
u_prot.put(src_pfn, dst_pfn, None)`

where the prtocol points to the gfal.

**Comment by bari12** [comment]
@dciangot I think nobody is working on this. Can this be closed? Should we leave it open just in case?

**Comment by dciangot** [comment]
I think it's fine to be closed
