### ISSUE TITLE
Rucio upload with rse_expression

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4129]
Motivation
----------
For certain workflows it would be useful to do an upload to an rse_expression, where the rucio clients then select the RSE to upload to. E.g. `country=de` and a (random) RSE in germany is selected. This should be addable somewhere here:
https://github.com/rucio/rucio/blob/9f7a71b03dcf90c3b4c28123de51cb8a60f41000/lib/rucio/client/uploadclient.py#L134

I checked a little bit for any corner-cases here, but I think as long as the RSE is selected at the beginning and further on the selected RSE is used, this workflow should be fine.

**Comment by TomasJavurek** [comment]
A separate option for this in the item list? e.g. dst_rse_expression? Or leaving the rse option to be optionally an expression?
This might depend on the way how items in the upload workflow are created (outside of the uploadclient). In case of cli: https://github.com/rucio/rucio/blob/master/bin/rucio#L946, both options should be fine.
