### ISSUE TITLE
remove unnecessary log messages from reaper2

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#4143]
Motivation
----------
The reaper2 currently spams the logs with some unnecessary debug outputs messages, e.g.,
```
Using cached value for RSE usage on RSE ...
```
or
```
count: 1
```

Modification
------------
completely remove these logs.

**Comment by cserf** [comment]
The `count: 1` comes from `rucio/rse/protocols/gfal.py` and not from the reaper code
