### ISSUE TITLE
Rule repair does not respect ignore_availability setting

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#4152]
Motivation
----------
If a rule was made with `ignore_availability=True` and a replica lock becomes stuck, any subsequent repair operation should consider `ignore_availability`. Currently it seems that RSE availability is always required before a repair can be submitted, per https://github.com/rucio/rucio/blob/51dd4f09c6541a10186b1e1360e38b6205ea5f28/lib/rucio/core/rule_grouping.py#L770

There may be some question if this is done on purpose for any reason.

Modification
------------
Probably just a change to https://github.com/rucio/rucio/blob/51dd4f09c6541a10186b1e1360e38b6205ea5f28/lib/rucio/core/rule_grouping.py#L770

**Comment by nsmith-** [comment]
Any update? I can make a PR with that change though idk about what kind of testing is desired

**Comment by bari12** [comment]
Hi @nsmith- 
I didn't get to it, if you have time to submit a PR that would be great. I agree that the proposed change should be sufficient, but it has to be done at the three different locations in the repair code (for NONE/ALL/DATASET grouped rules).
For the tests you can probably largely duplicate https://github.com/rucio/rucio/blob/c15716f9494cbbfb1da70e5a77f2d907a61e01a0/lib/rucio/tests/test_judge_repairer.py#L98
But you will need to create a new (test RSE and make it a write-disabled one)
