### ISSUE TITLE
Follow-up for moving EXTRA_MODULES importing to util function

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4168]
https://github.com/rucio/rucio/blob/5cc5020284ea490386fb1f97f53f4f0674abdfec/lib/rucio/client/baseclient.py#L87-L98

> can this be moved to a util function? I have seen similar code.
> 
> (can also be solved in a follow-up)

_Originally posted by @bziemons in https://github.com/rucio/rucio/pull/4133#discussion_r532436299_

> follow-up sounds good. this was just one of the random improvements i did while waiting for the github actions to finish.

_Originally posted by @mlassnig in https://github.com/rucio/rucio/pull/4133#discussion_r532475668_

**Comment by dchristidis** [comment]
I am aware that Python 3.9 is not supported, but I wished to advise you that this appears to be causing some problem.

```
$ rucio whoami
Traceback (most recent call last):
  File "/var/home/dchristidis/.local/bin/rucio", line 65, in <module>
    from rucio.client import Client
  File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/__init__.py", line 20, in <module>
    from .client import Client  # noqa: F401
  File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/client.py", line 30, in <module>
    from rucio.client.accountclient import AccountClient
  File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/accountclient.py", line 39, in <module>
    from rucio.client.baseclient import BaseClient
  File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/baseclient.py", line 90, in <module>
    imp.find_module(extra_module)
NameError: name 'imp' is not defined
```

**Comment by nikoladze** [comment]
> I am aware that Python 3.9 is not supported, but I wished to advise you that this appears to be causing some problem.
> 
> ```
> $ rucio whoami
> Traceback (most recent call last):
>   File "/var/home/dchristidis/.local/bin/rucio", line 65, in <module>
>     from rucio.client import Client
>   File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/__init__.py", line 20, in <module>
>     from .client import Client  # noqa: F401
>   File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/client.py", line 30, in <module>
>     from rucio.client.accountclient import AccountClient
>   File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/accountclient.py", line 39, in <module>
>     from rucio.client.baseclient import BaseClient
>   File "/var/home/dchristidis/.local/lib/python3.9/site-packages/rucio/client/baseclient.py", line 90, in <module>
>     imp.find_module(extra_module)
> NameError: name 'imp' is not defined
> ```

I get a similar error in python 3.8 when i try to import the rucio client in a jupyter notebook:

```
from rucio.client import Client
```

gives

```
NameError                                 Traceback (most recent call last)
<ipython-input-1-7c6990a03cf9> in <module>
----> 1 from rucio.client import Client

~/.conda/envs/rucio-test/lib/python3.8/site-packages/rucio/client/__init__.py in <module>
     18 # - Benedikt Ziemons <benedikt.ziemons@cern.ch>, 2020
     19 
---> 20 from .client import Client  # noqa: F401

~/.conda/envs/rucio-test/lib/python3.8/site-packages/rucio/client/client.py in <module>
     28 """
     29 
---> 30 from rucio.client.accountclient import AccountClient
     31 from rucio.client.accountlimitclient import AccountLimitClient
     32 from rucio.client.didclient import DIDClient

~/.conda/envs/rucio-test/lib/python3.8/site-packages/rucio/client/accountclient.py in <module>
     37 from requests.status_codes import codes
     38 
---> 39 from rucio.client.baseclient import BaseClient
     40 from rucio.client.baseclient import choice
     41 from rucio.common.utils import build_url

~/.conda/envs/rucio-test/lib/python3.8/site-packages/rucio/client/baseclient.py in <module>
     64                                     NoAuthInformation, MissingClientParameter,
     65                                     MissingModuleException, ServerConnectionException)
---> 66 from rucio.common.utils import build_url, get_tmp_dir, my_key_generator, parse_response, ssh_sign, setup_logger
     67 from rucio import version
     68 

~/.conda/envs/rucio-test/lib/python3.8/site-packages/rucio/common/utils.py in <module>
    105     if 'imp' in sys.modules:
    106         try:
--> 107             imp.find_module(extra_module)
    108             EXTRA_MODULES[extra_module] = True
    109         except ImportError:

NameError: name 'imp' is not defined
```

The error does not come up in a regular (I)python shell.

I tested this in a conda environment:

```sh
$ conda create -n rucio-test python=3.8
$ conda activate rucio-test
$ conda install jupyter
$ pip install rucio
$ jupyter notebook
```

**Comment by mlassnig** [comment]
Check again after #4373

**Comment by dchristidis** [comment]
After upgrading to 1.25.0, I can say that It Works On My Machine™.

**Comment by bziemons** [comment]
:exploding_head:

**Comment by nikoladze** [comment]
I can confirm the issue with rucio client in jupyter notebooks is fixed using the latest rucio version (1.25.0) from pip. Thanks!

**Comment by bari12** [comment]
Would still be good to move this to a util function 😏 
But good to know that it is working 🥳

**Comment by bziemons** [comment]
Related: #4373 (which doesn't fix this issue, sadly)
