### ISSUE TITLE
Non optimal rule reevaluation when attach_dids_to_dids is used with ignore_duplicate option

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#4178]
Motivation
----------
`attach_dids_to_dids` has  an `ignore_duplicate` option to not trigger an exception if an attempt to reattach the same DID is done. But if this option is used, it will always insert a row into the `updated_dids` table.

**Comment by bari12** [comment]
This will only go to 1.27 due to the usage of the new config methods. (Otherwise a separate PR addressing this in 1.26 would have to be made)
