### ISSUE TITLE
RSEManager doesn't allow to create a protocol with operation third_party_copy

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#420]
Motivation
----------

Traceback (most recent call last):
  File "recreate_protocol.py", line 37, in <module>
    c.add_protocol(rse=rse, params=protocol)
  File "/usr/lib/python2.7/site-packages/rucio/client/rseclient.py", line 229, in add_protocol
    raise exc_cls(exc_msg)
rucio.common.exception.RSEOperationNotSupported: RSE does not support requested operation.
Details: Operation 'third_party_copy' not defined in schema.

Modification
------------
Add third_party_copy to the list of supported operations

**Comment by bari12** [comment]
third_party_copy has been added to the schema in December 2017. This should be fine now.
