### ISSUE TITLE
Capability-based authorization for Rucio

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#421]
Motivation
----------
As GSI is starting the long road of phasing out, there's increased interest in widening work around capability-based authorization for transfers.  Capabilities are authorization mechanisms that describe what the bearer is _allowed to do_, rather than _who it is_.

The most common implementation of capabilities is a HTTP bearer token.  A token is added to the `Authorization` header of a HTTP request and the contents of this token prove that the requester is authorized.  Done via `curl`, it might look something like this:

```
curl -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2RlbW8uc2NpdG9rZW5zLm9yZyIsImV4cCI6MTUxNDk5ODg1MywiaWF0IjoxNTE0OTk4MjUzLCJuYmYiOjE1MTQ5OTgyNTN9.JWXvRpy1BRGHYckDdvP9FjdGrSHZgMjqi1OzlGJfxFtAWHRQ7nOm2gLJyV9LO16vPDOJnfy0fDzOLGOvKbGXFJ4KVoX6rvl8pbKkSPe9IumE4hzN8gwo1x0IZXW-oFDqF8mFw8xSPoBs0Dvj3QArjsM0dl2Uwk0AmCx-d2U1ysMUJgrcvtCeS2rnndEs_uVY7cAHxNSyYRQoWjWFavZ3CzWHeX2hH8ZRdpQsxie1D4s4Vyk6IEjgjxNGNwtdBCdvnhVW2_mx2nLfcsuuD82Jma0wafg_nzfKbxPoP9sDujy_90b2kDpdLthPbYYmby8orEitZRXVnp0jBsiqvalV9g" https://demo.scitokens.org/protected
```

For the WLCG, I'm aware of three different models around capabilities being investigated:

1.  *VO-issued bearer tokens*: The VO creates a token, authorizing the bearer to perform a certain operation at a site storage service.  The storage service verifies the token was signed by the VO and honors the token within the VO's storage area (allowing CMS to issue authorizations for CMS data, but not ATLAS data).  How the VO determines the authorizations and how the VO user retrieves the token is still a bit implementation-defined.  The token itself is formatted as a JWT; the SciTokens implementation of this scheme additionally uses the `scp` (scope) claim to specify the authorizations.  The WLCG Authorization Task Force is working on an agreed-upon profile.

    * Here, Rucio would issue a fine-grained token signed with Rucio's public key and return the token to the client.  The storage services would be configured to trust Rucio as an issuer for a certain area (using a standardized REST API to download the set of public keys that the issuer has blessed).

2.  *Storage-issued bearer tokens*: A client authenticates with a storage, requesting token to access a particular resource.  The storage creates the token and returns it to the client.  The client can then hand the token to any third party; the third party can only perform the specific operation listed in the token.  The example implementation here is dCache-issued macaroons: one would authenticate with dCache via GSI, request a macaroon via a dCache-specific (but relatively generic) REST API, and hand the returned token to a third party.

   * Here, Rucio would retrieve the macaroons from dCache and return it to the client.

3.  *Signed URLs*: AWS allows object owners to pre-sign a URL to have a specific authorization.  Anyone with possession of the URL would automatically get authorized by the storage service.  Note that this is somewhat problematic as URLs are typically treated as public within the WLCG -- for example, FTS3 monitoring allows any user to view anyone else's transfer URLs.  In the other two schemes, the resource being accessed and the capability authorizing the access are managed separately.

   * Rucio would create the pre-signed URL with its credentials and return this to the client.

In all three cases, the user interacts with the storage utilizing non-GSI and interaction with Rucio can be done via any of the Rucio-supported methods.

Modification
------------
This is a significant piece of work and ties into lots of external activity (WLCG Authorization Task Force and development cycles of various storage projects).  It's not a "one pull request and done" -- in fact, it's likely a bit of a moving target (token formats may change over the next 6 months).

However, I think there's some commonalities between the approaches that allow us to lay the groundwork:

1.  Token approaches are done per-RSE protocol.  That is, each RSE will have a particular "style" of capabilities they support that can be done as an attribute.  This suggests we should reserve an attribute name (`token-type`?); unfortunately, as we want to support non-WLCG storage, it is unlikely we'll ever converge to a single token type.
2.  Server-side handlers for `rucio upload` and `rucio download` should get access to the token type and be able to invoke plugins for each type that issue the corresponding capabilities.
3.  Client code for `rucio upload` and `rucio download` should be able to handle both a returned URL and a bearer token in the server response, using the bearer token as appropriate.
4.  For *VO-issued bearer tokens*, it would make the most sense to have Rucio's current token issuing endpoint issue the tokens.  For a python prototype, see https://github.com/bbockelm/x509-scitokens-issuer.  I have a parallel set of patches for FTS3 that allow third-party-copies using tokens issued with that API.

**Comment by bbockelm** [comment]
@vingar mentioned that there is already signed URL support in Rucio and will be updating the ticket with some example code.

Additionally, here is some sample code for getting a macaroon from a dCache endpoint: https://github.com/bbockelm/x509-scitokens-issuer/blob/master/tools/macaroon-init

**Comment by mlassnig** [comment]
Creating bearer tokens is already the basic authn/authz scheme in Rucio, where we delegate the verification of the requestor to separate entities (Kerberos Servers, VO CAs, SSH pubkeys, ...). Creating Rucio-issued bearer tokens (e.g., based on the SciTokens proposal) which can then be given to rucio clients and transfertools should be doable by adding a new token generator which takes account, identity, and optionally RSEs as input. (In case a challenge-response handshake is needed, there's a workflow in place as we need to do this for SSH-based auth already and which can be adapted.) This could even supersede the X-Rucio-Auth-Token.

To auth with storage, generating signed URLs follows naturally from this, as instead asking a third party to sign the URL Rucio could do it internally by passing the optional RSE to the token generator.

Few things to take care about:
- thrash rate on the token table
- length of the bearer tokens
- attributes of the bearer tokens which are not part of the token itself

**Comment by bbockelm** [comment]
Length can be a legitimate problem.  Apache's limit tends to be around 4KB.  A narrowly scoped token (including a full PFN) would be around 1KB.  So, if you issued a token to download a specific file, it would not be a problem.  The problem would crop up if you wanted to do something like a token for a long list of files -- in such a case, you'd probably have to do a more coarse-grained scope (e.g., at the directory level).

Since the tokens are signed with a public key, they don't need to be recorded in a manner analogous to the existing table.  It is a good idea to have a log activity of tokens recently (no need to record the tokens themselves) issued for auditing purposes, but that's more a log file than a DB table.

For attributes - for the pure file transfer use case, that's fairly well specified already.  If we wanted to include internal Rucio authorizations, you'd probably just embed the authorization name in the `scp` (scope) claim.

**Comment by bari12** [comment]
Scheduled for 1.19.1

**Comment by bari12** [comment]
Closing this issue. Token support is there but this was followed up in other issues.
