### ISSUE TITLE
tools/reset_database.py should remove postgres types

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4212]
Motivation
----------
Since the sqlalchemy update (#4133) I am getting errors that types already exist on postgres after resetting the database (with or without --drop-everything) in my docker-compose environment.

Modification
------------
Since the `tools/reset_database.py` script is meant to "destroy" the database and leave nothing behind, one option would be to remove all types found in the database.

**Comment by mlassnig** [comment]
Correct, this is because the types always end up in the `public` schema of PostgreSQL.

Quickest way to do this, in two steps:

`drop schema if exists public cascade;`
`create schema public;`

**Comment by bziemons** [comment]
That seems to help a bit, but some types seem to be in the dev schema and aren't removed either:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) type "RULES_HIST_RECENT_DIDTYPE_CHK" already exists

[SQL: CREATE TYPE dev."RULES_HIST_RECENT_DIDTYPE_CHK" AS ENUM ('F', 'D', 'C', 'A', 'X', 'Y', 'Z')]
```
