### ISSUE TITLE
Logging review

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4220]
Motivation
----------
Over the years the log messages in Rucio evolved into an inconsistent state. This leads to difficulties in reading the logs and in some cases also to a large number of log messages being produced. The aim of this review is to
- Enforce consistency between the different log levels. DEBUG / INFO / WARNING / ERROR / CRITICAL
  - Especially between INFO and DEBUG: INFO should be used for information useful to the user or for stable operation of a daemon/server, otherwise messages should go to DEBUG. However, this should still be generally still useful information and not just any log statements leftover from development - these should be removed.
  - In general daemons/server should only need to be operated in INFO mode.
- Log format
  - make the log format configurable. The log output should be different depending if the logging is used inside the servers or daemons.
  - Daemon messages should be in the format `daemon_name[heartbeat['assign_thread']/heartbeat['nr_threads']]: ...`
- Reduce number of messages 

Note: At the moment logging.basicConfig is called in a lot of different modules in the daemons and in the core. If a daemon sets the logging and then imports a module it could potentially overwrite the config. This should be removed from all modules and instead put in a central place that is only called once when the application starts.

Modification
------------
List of components to be checked. The individual component leaders are in charge of checking their components.
- [ ] Authentication & Authorization
- [X] Clients
- [ ] Consistency checks
- [x] Core & Internals
- [ ] Data Pre-Placement
- [ ] Database
- [ ] Dataset deletion
- [ ] Deletion
- [ ] DIRAC
- [x] Docker & Kubernetes
- [x] Documentation
- [ ] Functional tests
- [ ] Life time model
- [ ] Messaging
- [x] Monitoring & Logging
- [ ] Multi VO
- [ ] Policies
- [ ] Probes & Alarms
- [ ] Protocols
- [ ] Rebalancing
- [ ] Recovery
- [x] Release management
- [x] Replicas
- [x] REST & API
- [x] Rules
- [x] Subscriptions
- [x] Testing
- [x] Traces
- [x] Transfers
- [ ] WebUI

**Comment by dchristidis** [comment]
I understand how the daemon logging is to be implemented inside the threads, but what about before (e.g. in `start()`)?
