### ISSUE TITLE
Replace FTSState

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#4241]
Motivation
----------

FTSState is not a database column, but still in `db/constants.py`, that's why it has to be used with `.name` all over the code.

Modification
------------

Migrate from `db/constants.py` to `common/constants.py` and replace the appropriate code parts with better checks.

**Comment by rak108** [comment]
Can I take this up?

**Comment by rak108** [comment]
I had a doubt: since FTSState is not a database column, even FTSCompleteState should be moved to common/constants.py right?

**Comment by mlassnig** [comment]
Hmmmm o_O yes!
