### ISSUE TITLE
Report deletion events when the destination does not exist

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4258]
Motivation
----------

Currently, when the Reaper fails to delete a file because the destination does not exist, no event is reported. This can be potentially useful information.

Modification
------------

Report a `deletion-notfound` event.

**Comment by dynamic-entropy** [comment]
~~resolved #4272~~
https://github.com/rucio/rucio/blob/69e41371ab367407347a5a9f1a8aa95a6b5a1f8b/lib/rucio/daemons/reaper/reaper2.py#L577

**Comment by dchristidis** [comment]
> resolved #4272 .

Sorry, that PR is not related. The relevant part of the code is here instead:

https://github.com/rucio/rucio/blob/69e41371ab367407347a5a9f1a8aa95a6b5a1f8b/lib/rucio/daemons/reaper/reaper2.py#L192-L195

**Comment by dynamic-entropy** [comment]
Oops, sorry! But still isn't the desired message logged. Or is it that, I did not just point to the wrong code but also mixed up events with logs.  Kindly, direct me to an example/definition of an event in Rucio.

**Comment by dchristidis** [comment]
An event is reported with `add_message()`. The real question is whether additional changes are needed in order to process it, either in Rucio or in our monitoring infrastructure (which lives outside of this repository). To that, I don’t have an answer.

**Comment by mlassnig** [comment]
Making a distinction between "deletion success" and "deletion not found" is potentially helpful. Down the line, this gives us some statistics on files that were lost on storage. If there are data centres with particularly high numbers of deletion not found that can inform us about more systematic problems.
