### ISSUE TITLE
Consider changing the add_bad_pfns API to use an enum for the state parameter

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4269]
Motivation
----------

Following issue #4265, having the argument of `state` be a string in the API and core layers is not ideal.

Modification
------------

Consider using the appropriate enum instead in the next major Rucio release.

**Comment by bari12** [comment]
This is done and can be closed? @dchristidis

**Comment by dchristidis** [comment]
No, I do not believe this to be done. You can see that from the REST all the way down to the core layer, the `state` is a `str`.

https://github.com/rucio/rucio/blob/b5874bf02c0b1b8401593ef45991b9363cdd7fa4/lib/rucio/web/rest/flaskapi/v1/replicas.py#L1692-L1695
https://github.com/rucio/rucio/blob/b5874bf02c0b1b8401593ef45991b9363cdd7fa4/lib/rucio/api/replica.py#L446-L447
https://github.com/rucio/rucio/blob/b5874bf02c0b1b8401593ef45991b9363cdd7fa4/lib/rucio/core/permission/atlas.py#L1210
https://github.com/rucio/rucio/blob/b5874bf02c0b1b8401593ef45991b9363cdd7fa4/lib/rucio/core/replica.py#L3909-L3912

I believe it will become more clear when we introduce type hints (in this case, it will have to be `Union[str, BadPFNStatus]`). I’m fine with closing it for now and returning to it when type hints are in place. Note that is an issue that manifests in many more core functions that just `add_bad_pfns()`.
