### ISSUE TITLE
API: Add command list-suspicious-replicas

### ISSUE THREAD

**Issue by ChristophAmes** [rucio/rucio#4273]
Motivation
----------
Implementing the ability to get a list of suspicious replicas with the API, which is already possible with the REST-API.

Modification
------------

Added a method to replicaclient.py and added the command to bin/rucio.

**Comment by bari12** [comment]
Hi Christoph,
Sorry for the late reply. Judging from the commits you added, I guess you are preparing a PR for this :-)
Thanks
