### ISSUE TITLE
Add the possibility to enable FTS overwrite for the TAPE endpoints

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#4303]
Motivation
----------
Transfers : Add the possibility to enable FTS overwrite for the TAPE endpoints

**Comment by rcarpa** [comment]
@cserf , can you please be more specific about what is needed for this ticket ? Do we just want a config option which would enable overwrite on all TAPE endpoints? or do we want something more granular and specific ?

**Comment by rcarpa** [comment]
Any updates on my question ?

**Comment by cserf** [comment]
I need to check if  #4447 is enough

**Comment by bari12** [comment]
Ping Cedric, please clarify, otherwise we will close it.
