### ISSUE TITLE
RSE sorting in reaper2 failing if there is no obsolete rse usage source

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#4307]
Motivation
----------
If the reaper processes a list of RSEs of which some are above the deletion threshold and some need only obsolete replica deletion, then the sorting of the RSE dictionary fails if there is no `obsolete` rse usage source.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/daemons/reaper/reaper2.py", line 483, in reaper
    sorted_dict_rses = OrderedDict(sorted(dict_rses.items(), key=itemgetter(1), reverse=True))
TypeError: '<' not supported between instances of 'int' and 'NoneType'
```

The problem is that `needed_free_space` is supposed to be an Integer but in case there are only obsolete replicas to delete but there is no `obsolete` rse usage source then it will be set to `None`.  This will then break the dict sorting and the reaper thread won't start.

Modification
------------
Prefill the obsolete variable in `__check_rse_usage` with 0 here:

https://github.com/rucio/rucio/blob/e078fa2145311186407f78c6f8bb70fd5e1b4946/lib/rucio/daemons/reaper/reaper2.py#L296

**Comment by bari12** [comment]
Backport 1.24.3.post1
