### ISSUE TITLE
Remove direct DB dependence from the WebUI

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#4319]
Motivation
----------
The WebUI has a direct dependence on the core/api, e.g. https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/main.py#L41 . This make it not possible to deploy an instance on a machine with not connected to the DB.

Modification
------------
Remove all direct DB dependence from the WebUI

**Comment by DhruvSondhi** [comment]
Hello, After checking through the given file, I found that the aforementioned authentication is being performed here https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/main.py#L175-L204 ... Please do correct me if I am wrong

**Comment by bziemons** [comment]
seems correct for web.py. The Flask blueprint would need the same changes: https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/flask/bp.py
The plan is to get rid of web.py soon™

**Comment by maany** [comment]
This issue will be resolved in the new WebUI, given its architectural differences. We won't fix this for the current WebUI, hence closing this issue
