### ISSUE TITLE
core/rule.py reencodes meta over and over again

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#4337]
Motivation
----------

core/replica.py reencodes meta to JSON over and over again inside a loop on DIDs. Eventually this makes a string so big it causes an exception in oracle. It's not clear if this also corrupts the intended metadata

Modification
------------

Use a dedicated variable for the results of the JSON encoding

**Comment by bari12** [comment]
Backport 1.20.13
Backport 1.23.13
