### ISSUE TITLE
Core list_replicas() does not make use of ignore_availability

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4353]
Motivation
----------

If an RSE is excluded for reading, the the download client should not attempt to download from that RSE.

The REST layer already does this, but once `ignore_availability` propagates to the core, it is not actually used.
https://github.com/rucio/rucio/blob/960855d6e86f4e38ebe584b1d26e65751d52a210/lib/rucio/web/rest/webpy/v1/replica.py#L336
https://github.com/rucio/rucio/blob/960855d6e86f4e38ebe584b1d26e65751d52a210/lib/rucio/core/replica.py#L1164

Modification
------------

**Comment by dynamic-entropy** [comment]
Duplicate of #1213
