### ISSUE TITLE
Relative transfer timeout for downloads

### ISSUE THREAD

**Issue by oducu** [rucio/rucio#4374]
Dear all,

Please, can we have the --transfer-timeout option by default in rucio, if the file size is larger than i.e 4 G. This would be super useful, as (in the case of large files) rucio fails as shown below:

rucio get mc16_13TeV:DAOD_EGAM1.23267689._000140.pool.root.1
2021-03-02 15:34:57,432 INFO    Processing 1 item(s) for input
2021-03-02 15:34:57,432 INFO    Getting sources of DIDs
2021-03-02 15:34:58,100 INFO    Using main thread to download 1 file(s)
2021-03-02 15:34:58,100 INFO    Preparing download of mc16_13TeV:DAOD_EGAM1.23267689._000140.pool.root.1
2021-03-02 15:34:58,236 INFO    Trying to download with gsiftp from TOKYO-LCG2_DATADISK: mc16_13TeV:DAOD_EGAM1.23267689._000140.pool.root.1
2021-03-02 15:41:24,421 WARNING Download attempt failed. Try 1/2
2021-03-02 15:47:40,551 WARNING Download attempt failed. Try 2/2
2021-03-02 15:47:40,601 INFO    Trying to download with root from TOKYO-LCG2_DATADISK: mc16_13TeV:DAOD_EGAM1.23267689._000140.pool.root.1
2021-03-02 15:55:21,619 WARNING Download attempt failed. Try 1/2
2021-03-02 16:02:29,055 WARNING Download attempt failed. Try 2/2
2021-03-02 16:02:29,109 INFO    Trying to download with davs from TOKYO-LCG2_DATADISK: mc16_13TeV:DAOD_EGAM1.23267689._000140.pool.root.1
2021-03-02 16:08:47,471 WARNING Download attempt failed. Try 1/2
2021-03-02 16:15:15,489 WARNING Download attempt failed. Try 2/2
2021-03-02 16:15:15,544 ERROR   Failed to download file mc16_13TeV:DAOD_EGAM1.23267689._000140.pool.root.1
2021-03-02 16:15:15,545 ERROR   None of the requested files have been downloaded.

This was discussed in the DAST group:
https://groups.cern.ch/group/hn-atlas-dist-analysis-help/Lists/Archive/Flat.aspx?RootFolder=%2Fgroup%2Fhn%2Datlas%2Ddist%2Danalysis%2Dhelp%2FLists%2FArchive%2FCan%20not%20download%20one%20dataset%20using%20rucio&FolderCTID=0x01200200FB8F64B0E343CB4680DEAC546A9DF813

Thank you very much!
Otilia (DAST shifter)

**Comment by rcarpa** [comment]
I don't have a good idea on how to tackle this issue. If we want to add new client/CLI/config options, I think that the best solution is to resolve #4153 and then implement a mechanism similar to the one in curl [low_speed_time](https://curl.se/libcurl/c/CURLOPT_LOW_SPEED_TIME.html)  + [low_speed_limit](https://curl.se/libcurl/c/CURLOPT_LOW_SPEED_LIMIT.html) on top of it. This would allow to set the default timeout to 0 (do not timeout) in all rucio clients while still relying on these two options to detect stale downloads.
However, this doesn't seem trivial to implement.

I don't like the idea of automatically overriding the timeout set in a config file or on the command line for big files. If a timeout is requested, it must be respected as-is, without modifications.

A compromise solution, which I like and avoids adding any new client/CLI options: if timeout is not requested explicitly, compute a default timeout which depends on the file size and some internal "min_speed_limit" constant. This way, we don't add any "not-very-well-designed" cli/config options which we would have to keep supporting in the future. 
For example: 
```
if timeout is None:
    timeout = max(360, file_size/ 1Mbps) 
```
360 is the default timeout [used now in the CLI](https://github.com/rucio/rucio/blob/afad482b259bf8a5d045480f92a8d6cb26b4d9d2/bin/rucio#L2121). We can distinguish between "timeout=0" and timeout=None. In the first case, we wouldn't compute depending on file size.

Any opinions ? The last solution changes the behavior for clients instantiating the DownloadClient directly. For example, pilot will have a timeout enforced in places where it doesn't explicitly set this option.

**Comment by bari12** [comment]
I agree.
The first one is not trivial to implement, so I would also first work with what's there.

In principle I like your proposal, but I wonder if we need to be able to let the user/external application influence this more. We could offer two parameters
`--transfer-timeout` which does what it already does.
`--transfer-speed-timeout` (in Mbps) which does basically the maximum timeout calculation like you suggested.

Per default we only set the second one to 1Mbps. 
If both are present, `--transfer-timeout` has precedence.

I do think though that the default should also be used in the DownloadClient.

**Comment by rcarpa** [comment]
So we'll have a `--transfer-timeout` defaulting to "no timeout" and `--transfer-speed-timeout` defaulting to some constant (1mbps for example). If the first one is set, it overrides the second. If not, the internal timeout is computed from the second? 
Looks OK for me: it is my proposal, but with the possibility to set the desired speed.
Do we want to maintain the current behavior and enforce a 360second minimum on the value computed from `--transfer-speed-timeout`? Seems high, I'd vote to lower it a bit.

**Comment by bari12** [comment]
Exactly. It's not perfect, but if we document the precedence well I think it should be fine.
360 seems a bit high to me, but we need to have some kind of minimum. Maybe 60s? There is some overheads with establishing the connection etc. we need to keep in mind for very small files.

**Comment by rcarpa** [comment]
I'd even go lower. Something like 10s, but you know much better than me how big the static overhead can be.

**Comment by rodwalker** [comment]
Hi,
Trying this for a big file I see

downloadclient.py	options: {'mc16_13TeV:AOD.13122612._000001.pool.root.1': {'ignore_checksum': False, 'transfer_speed_timeout': None, 'transfer_timeout': None, 'destinations': set([('.', False)])}}

which presumably means no default speed and no timeout applied.

Adding --transfer-speed-timeout 1000000
options: {'mc16_13TeV:DAOD_FTAG4.24348858._000944.pool.root.1': {'ignore_checksum': False, 'transfer_speed_timeout': 1000000, 'transfer_timeout': None, 'destinations': set([('.', False)])}}

so still no timeout, calculated or otherwise.

Also the unit for speed is unnecessarily small I think
Default: 1000000(i.e. 1Mbps)

Not every user can count to 6, when adding zeros. The default here is  125 kB/s, where a typical WAN rate is 1MB/s. I would prefer the unit kB/s with a default of 500.

Cheers,
Rod.

**Comment by rcarpa** [comment]
Hi Rod, 

Thank you for the feedback. 

It is normal that there is no timeout seen on the download_did call. At that stage, we cannot compute the actual timeout. We have to wait until we dereferenced wildcard dids and datasets dids. Moreover, we must retrieve the replicas for the file dids to finally know the file size and be able to compute timeout. 

However, if you see missing timeout in FTS calls, please report and we'll dig into it. 

Concerning the default value, it is a very easy fix as long as everybody agrees with it.

Cheers, 
Radu

**Comment by mlassnig** [comment]
Kbps is ok for me.

**Comment by rodwalker** [comment]
I think users are more likely to think in Bytes, i.e kB/s.

So the timeout is calculated and used but there is no debug message for it?
Then please can it be printed around 
INFO	Trying to download with gsiftp from TOKYO-LCG2_DATADISK: mc16_13TeV:DAOD_FTAG4.24348858._000944.pool.root.1

when printing the options, shouldn`t this show the defaults? Eg. I guess this is a default
'ignore_checksum': False

Cheers,
Rod.

**Comment by mlassnig** [comment]
Not entirely sure why I wrote kilobits, I meant kilobytes of course.

**Comment by dchristidis** [comment]
As reported by @rodwalker, this doesn’t appear to work as expected.

```
$ rucio --version
rucio 1.25.2
$ rucio --verbose download mc16_13TeV:DAOD_FTAG4.24348858._000944.pool.root.1
2021-04-14 09:42:27,098	INFO	Processing 1 item(s) for input
2021-04-14 09:42:27,099	DEBUG	downloadclient.py	num_unmerged_items=1; num_dids=1; num_merged_items=1
2021-04-14 09:42:27,099	INFO	Getting sources of DIDs
2021-04-14 09:42:27,219	DEBUG	downloadclient.py	schemes: None
2021-04-14 09:42:27,219	DEBUG	downloadclient.py	rse_expression: None
2021-04-14 09:42:27,219	DEBUG	downloadclient.py	num DIDs for list_replicas call: 1
2021-04-14 09:42:27,330	DEBUG	downloadclient.py	num resolved files: 1
2021-04-14 09:42:27,341	DEBUG	downloadclient.py	"unzip -v" returned with exitcode 0
2021-04-14 09:42:27,349	DEBUG	downloadclient.py	"tar --version" returned with exitcode 0
2021-04-14 09:42:27,350	DEBUG	downloadclient.py	Queueing file: mc16_13TeV:DAOD_FTAG4.24348858._000944.pool.root.1
2021-04-14 09:42:27,350	DEBUG	downloadclient.py	real parents: set()
2021-04-14 09:42:27,350	DEBUG	downloadclient.py	options: {'mc16_13TeV:DAOD_FTAG4.24348858._000944.pool.root.1': {'destinations': {('.', False)}, 'ignore_checksum': False, 'transfer_timeout': None, 'transfer_speed_timeout': None}}
2021-04-14 09:42:27,388	DEBUG	downloadclient.py	Prepared sources: num_sources=6/6; num_non_cea_sources=6; num_cea_ids=0
2021-04-14 09:42:27,388	INFO	Using main thread to download 1 file(s)
2021-04-14 09:42:27,388	DEBUG	downloadclient.py	Start processing queued downloads
2021-04-14 09:42:27,389	INFO	Preparing download of mc16_13TeV:DAOD_FTAG4.24348858._000944.pool.root.1
2021-04-14 09:42:27,507	INFO	Trying to download with gsiftp from TOKYO-LCG2_DATADISK: mc16_13TeV:DAOD_FTAG4.24348858._000944.pool.root.1 
2021-04-14 09:42:27,915	DEBUG	logging.py	gfal.Default: connecting to storage
2021-04-14 09:42:27,969	DEBUG	logging.py	gfal.Default: downloading file from gsiftp://lcg-se01.icepp.jp:2811/dpm/icepp.jp/home/atlas/atlasdatadisk/rucio/mc16_13TeV/1f/a4/DAOD_FTAG4.24348858._000944.pool.root.1 to /opt/rucio/auditor/cache/mc16_13TeV/DAOD_FTAG4.24348858._000944.pool.root.1.part
2021-04-14 09:48:33,155	DEBUG	downloadclient.py	The requested service is not available at the moment.
Details: An unknown exception occurred.
Details: Transfer canceled because the timeout expired
2021-04-14 09:48:33,157	WARNING	Download attempt failed. Try 1/2
^C
```

**Comment by rcarpa** [comment]
In the initial commit, I tried to not change the behavior for users who instantiate a downloadclient from python. They would continue to have a static default timeout of 360. This behavior was intended to be different from the default behavior in the CLI client, where a "relative" timeout would be used.

The attempt failed because I shouldn't have set the default value to None here : https://github.com/rucio/rucio/blob/8e48627850060a902f3b1ea5c02fa81e3e31757e/bin/rucio#L2158
Due to this line https://github.com/rucio/rucio/blob/8e48627850060a902f3b1ea5c02fa81e3e31757e/lib/rucio/client/downloadclient.py#L449

The quick fix is to just put 500 as default value here : https://github.com/rucio/rucio/blob/8e48627850060a902f3b1ea5c02fa81e3e31757e/bin/rucio#L2158, but I'm not sure anymore that it's a good idea to keep this complex behavior. Maybe it's a good idea to break the existing behavior for pilot and other users instantiating the client via the python class and make everybody obey to a "relative timeout" by default.

**Comment by bari12** [comment]
I agree, I would also unify the default timeout to the relative one, both for CLI as well as python DownloadClient. If the pilot asks for a specific timeout (Relative or absolute) it will be respected anyway. @mlassnig any opinion?

**Comment by mlassnig** [comment]
Either are fine, as long as Paul knows which one affects the pilot. I'm happy with relative being the default (or even only option).

**Comment by rcarpa** [comment]
@PalNilsson . Could you please provide your opinion on the following matter: 

We recently introduced a new option to the download client : transfer_speed_timeout. The intent is, for download_dids, to automatically compute the timeout using the file size and a configurable minimum allowed speed(set via the transfer_speed_timeout option). 
By default, for the CLI client, the intent was to have a timeout which scales with the file size to avoid the usual timeout on large transfers from different continents.
To avoid impacting the pilot in any way, I tried to keep the old behavior when instantiating the DownloadClient via the python class. This lead to some code which is complex to understand and error-prone (already discovered a small bug). 

Now we want to remove this exception. This would mean a slight change of behavior for pilot : transfers started without setting the trasnfer_timeout option will have a timeout computer dynamically. No behavior change is expected if this option is set.

**Comment by PalNilsson** [comment]
Hi,
Just let me know if there is anything I need to change in the pilot (and how).
Cheers, Paul

From: rcarpa ***@***.***>
Reply to: rucio/rucio ***@***.***>
Date: Friday, 16 April 2021 at 10:51
To: rucio/rucio ***@***.***>
Cc: Paul Nilsson ***@***.***>, Mention ***@***.***>
Subject: Re: [rucio/rucio] Relative transfer timeout for downloads (#4374)


@PalNilsson<https://github.com/PalNilsson> . Could you please provide your opinion on the following matter:

We recently introduced a new option to the download client : transfer_speed_timeout. The intent is, for download_dids, to automatically compute the timeout using the file size and a configurable minimum allowed speed(set via the transfer_speed_timeout option).
By default, for the CLI client, the intent was to have a timeout which scales with the file size to avoid the usual timeout on large transfers from different continents.
To avoid impacting the pilot in any way, I tried to keep the old behavior when instantiating the DownloadClient via the python class. This lead to some code which is complex to understand and error-prone (already discovered a small bug).

Now we want to remove this exception. This would mean a slight change of behavior for pilot : transfers started without setting the trasnfer_timeout option will have a timeout computer dynamically. No behavior change is expected if this option is set.

**Comment by rcarpa** [comment]
Nothing to change, but there will be a change of behavior for default settings: the default timeout for transfers will become much longer (hours) for very big files. And shorter for small files. If pilot already sets a custom timeout value, nothing will change.
