### ISSUE TITLE
The Dark Reaper should run continuously instead of exiting early when there’s nothing to do

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4377]
Motivation
----------

The Dark Reaper has its own implementation of `list_rses()` which only returns RSEs that have at least one quarantined replica. This is not optimal for two reasons:

 1.  If there are no quarantined replicas, then the Reaper exists early. Daemons running on Kubernetes are expected to run continuously.
 2. If quarantined replicas are added for an RSE that didn’t have any when the daemon started, then they won’t be processed until the next restart.

Modification
------------

Replace the custom `list_rses()` implementation with the one from the core.

**Comment by ericvaandering** [comment]
@dchristidis We still see issues with this in 1.25.2. The DR runs continuously, it just refuses to pick up new work from the database. 

More specifically, we add a file to quarantined_replicas for Purdue and start DR. It deletes the file. We add another file to QR and DR says it has nothing to do. Then we restart DR and it picks up the work.

Thoughts?

**Comment by dchristidis** [comment]
Rucio 1.25.1 introduced a partial fix (#4379): the Dark Reaper could now start even if the quarantined replicas table were empty. However, due to an oversight, it still wouldn’t process newly-added replicas.
Rucio 1.25.3 contains an additional fix (#4524) which should correctly address the issue.
