### ISSUE TITLE
Config test fails when value looks like an e-notated number

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4382]
Motivation
----------
Adding the following test to test_config.py::TestConfigCore fails:
```python
    def test_set_and_get_e_number_as_string(self):
        """ CONFIG (CORE): Special case where a uuid being a number in e-notation """
        section = str(generate_uuid())
        option = str(generate_uuid())
        expected_value = '8e709763901742258842354556715071'
        config_core.set(section=section, option=option, value=expected_value)
        value = config_core.get(section, option, use_cache=False)
        assert value == expected_value
```
The test above is a special case of a uuid generated in the test `test_get_and_set_section_option`

Modification
------------
As Martin pointed out, the problem seems to be in `__convert_type` [(1)], where any string is forcefully converted to an int/float. That should not happen.

[(1)]: https://github.com/rucio/rucio/blob/2d6bf5dbfddd0b8b9f372e502ede14b9b6b762ac/lib/rucio/core/config.py#L312

**Comment by bari12** [comment]
Would be good to fix this in course of the Config Table vs. rucio.cfg changes.
