### ISSUE TITLE
Archive information on dataset level

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4385]
Motivation
----------
In recent discussion with developers from ATLAS prodsys the use case was raised that it would be helpful to know if a dataset holds any files which are archives. Eg. via a simple `get_metadata(...)` query.

Right now, Rucio does not propagate this information to the dataset level. There are two fields associated with **file** dids:

- `constituent` which evaluates to `True` if a file is available in an archive (But can have conventional physical replicas as well)
- `is_archive` which evaluates to `True` if a file is an archive, and holds constituent file.

Modification
------------

I think we have two options:

1. Re-use the existing `is_archive` field and propagate this information from the content dids to the archive. Thus, if at least one content file in a dataset has the `is_archive` flag, the dataset will get it too. Needs to be removed again in case of detach operations.
2. Essentially the same as option (1) but with a new field. `contains_archives` - this would need a schema change.

Then this information could simply be queried with the dataset did.

**Comment by rcarpa** [comment]
Should the information be recursively available on the container level ?
