### ISSUE TITLE
prune daemon for remnant directories

### ISSUE THREAD

**Issue by thdesy** [rucio/rucio#4389]
Dear Developers,

Motivation
----------

I am spring cleaning our RSE from empty directories, that have been accumulated over the last year. So far `5554078` empty dirs have been pruned with the trimming still ongoing - primarily end leaf directories and (probably not totally a surprise) SCRATCHDISK with the most directories so far.

Modification
------------

A prune daemon, that occassionally cleans up empty sub-dirs, that are not in current use - to free inodes and vacuuming the SE DBs

Cheers,
  Thomas

**Comment by bari12** [comment]
I am not sure if this is something which we should generally promote. Although small, there is some risk in deleting directories, because there is always a small race condition between checking if it is empty, deleting, and a third party writing to the directory.

Is this cleanup really something significant in terms of performance, etc?

**Comment by thdesy** [comment]
na - performance-wise walking through the namespace is not really significant (it just takes time...).

the prune took nearly two days and removed ~8642315 empty directories (with probably O(1/ff) now newly empty eaf dirs around that could be pruned now as well, I guess). Maybe we could speed it up and operate directly on the DB (had been walking through the NFS mount)

it is not something really mission critical

**Comment by bziemons** [comment]
> Although small, there is some risk in deleting directories, because there is always a small race condition between checking if it is empty, deleting, and a third party writing to the directory.

Depends on how you delete the directory. The filesystem has a specific rmdir operation (in Python: <https://docs.python.org/3/library/os.html?highlight=rmdir#os.rmdir>) that will not delete directories with contents. What could happen is that something checks if a directory exists to write a file in it, then opens the file to write, but the directory was deleted between those operations.

**Comment by bari12** [comment]
These would be remote deletions via the available storage protocols, so nothing called directly on the filesystem. It really depends how this is implemented in the different storage doors. But again, unless there is some big advantage in performance, I don't think it is worth to go into this, although I understand from a site-admin point of view wanting to cleanup these directories.

**Comment by bari12** [comment]
I am closing this now, I think this is something we shouldn't really promote centrally. 
@thdesy of course, if there are scripts to clean this up locally on storage in a safe way (trying to minimise the risk of race conditions) then I think this is something we could at least mention/link in the documentation, but this gets very much into site-specific territory.
