### ISSUE TITLE
Support filters in the get_dataset_locks client API

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#4392]
Motivation
----------
Given that a dataset can be locked under multiple accounts, or multiple rses, and so on; it would be extremely useful to have the ability to provide further filters to the `get_dataset_locks` API, which right now only support `scope` and `name` parameters.

Modification
------------
Support key/value pair filters in the `get_dataset_locks` API, such that only relevant data is returned to the client.
The list of filters to be supported still requires further discussion, but one of those that would be quite helpful is `account`.

**Comment by nsmith-** [comment]
This is something I mentioned also in #3982 as one we'll want in the bulk query as well.

**Comment by ivmfnal** [comment]
What would be examples of additional filters ?

**Comment by amaltaro** [comment]
@ivmfnal Igor, without looking into the API documentation, I would say from the top of my head: account name, rse name (or rse expression?), perhaps DID status (S/A/etc).
Perhaps @nsmith- would have some idea here as well.

**Comment by ivmfnal** [comment]
Would it be helpful to include the filterable data into the output of the request like "all locks for a container or a dataset" (see [4807](https://github.com/rucio/rucio/issues/4807)) instead and let the client filter interesting info ?

**Comment by nsmith-** [comment]
There is `get_dataset_locks_by_rse` API which queries direclty the `locks - rse` relation, but I agree it would be nice to be able to use RSE expression here, since this is querying the `rules - locks` relation instead. In general any filter valid for rules would be a candidate for a filter for this API.

**Comment by ivmfnal** [comment]
I doubt is it practical for the API to try to cover all possible complexities of the filters which a users might find useful. I think better approach is to provide comprehensive information and let the application implement the filtering logic.
So my question is: what pieces of information, in addition to those already provided by `get_dataset_locks` should be included ?

**Comment by amaltaro** [comment]
That's a fair point (and I confirm that `account`, `rse` and `state` are already provided in the results)!

However, filtering data at the database layer gives a performance boost to the overall system. Said that, I'd rather have only a small set of filters supported than no support at all.

AFAICS, dataset locks are made against a given RSE name, so I'd say supporting RSE expression is not very important here (it would probably complicate this development as well).

**Comment by ivmfnal** [comment]
I am not sure I agree with the statement that filtering at the database level always gives a performance boost to the overall system. If the underlying query can benefit from a database index, then probably yes. However, if there is no index to support the query, then filtering done by the database shifts the load to the database, which is a shared resource, and can lead to slow down of the overall system.

**Comment by ivmfnal** [comment]
Another question I have.
There is this issue https://github.com/rucio/rucio/issues/4807 and the PR for it is in the review stage.
Would it make sense to add same filtering capabilities to the API proposed there too ?

**Comment by ivmfnal** [comment]
Implemented in the latest release
