### ISSUE TITLE
ValueError: hour must be in 0..23

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#4400]
Motivation
----------
Will close this issue myself. Opened it for testing purposes. 
Actually saw the same integration test failure for different commits. 
Trying to understand the problem. 

______ TestRequestCoreRelease.test_release_waiting_requests_grouped_fifo _______
lib/rucio/tests/test_throttler.py:1809: in test_release_waiting_requests_grouped_fifo
    'requested_at': datetime.now().replace(hour=current_hour - 2),
E   ValueError: hour must be in 0..23

Modification
------------
Testing builds with the addition of a single comment.

**Comment by dynamic-entropy** [comment]
@mlassnig @bari12 Explanation required: Will these not fail when the time of the request is in 0..2? Is there a specific reason why this window is not allowed?

current_hour = datetime.now().hour
'requested_at': datetime.now().replace(hour=current_hour - 2)

**Comment by bziemons** [comment]
No, that is a plain bug. I overlooked it in https://github.com/rucio/rucio/pull/4233 and there is a fix ready in https://github.com/rucio/rucio/pull/4166/files#diff-b0a030753693e96abe3544908f7f45b29fa66ea1f0debfb28d7a135f4739d783R1825

**Comment by dynamic-entropy** [comment]
Thanks for clearing things up.  I will leave this open for the linked PR to close it automatically,
