### ISSUE TITLE
K8-Tutorial Documentation: Add Change Directory Instruction To Documentation 

### ISSUE THREAD

**Issue by DhruvSondhi** [rucio/rucio#4406]
Motivation
----------
The `README` file for the _K8 tutorial_ gives the commands under the **Installation of Rucio + FTS + Storage** section for executing the command but doesn't state that it must be run under the cloned directory.

Modification
------------
Adding a small step of changing into the correct directory before executing the commands will make it very clear & hence remove the ambiguity for any errors.

**Comment by DhruvSondhi** [comment]
@mlassnig Can this issue be assigned to me?

**Comment by mlassnig** [comment]
Pinging @tbeerman for information

**Comment by tbeerman** [comment]
Sure, @DhruvSondhi, you can take this one.
