### ISSUE TITLE
Docker & Kubernetes: Error occurred while setting up the docker dev environment

### ISSUE THREAD

**Issue by sahandilshan** [rucio/rucio#4413]
Motivation
----------
An error occurred while starting the docker containers with the following commands
`docker-compose --file etc/docker/dev/docker-compose.yml up -d`
`docker-compose --file etc/docker/dev/docker-compose-storage.yml up -d`
`docker-compose --file etc/docker/dev/docker-compose-storage-monit.yml up -d`

Error Log
```
ERROR: The Compose file './etc/docker/dev/docker-compose.yml' is invalid because:
Unsupported config option for services: 'ruciodb'
```
Docker Version: 19.03.8
Docker Compose Version: 1.25.0

**Comment by bziemons** [comment]
Hi! Please update docker-compose.
