### ISSUE TITLE
Remove reference to JIRA from Web UI

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4426]
Motivation
----------

![image](https://user-images.githubusercontent.com/2452306/111264366-aa10b400-8627-11eb-8d01-d8e6f5b52da7.png)

The Rucio Jira project has been archived.

Modification
------------

I would suggest removing this completely. Alternatively, we can point users to the GitHub issues instead.

**Comment by DhruvSondhi** [comment]
Hello @dchristidis, If it is possible can I work on this? 
Another question that I had is that do we need to remove all the `Jira` references or should we just change this specific one?

**Comment by bari12** [comment]
Hi @DhruvSondhi 
Yes, please just submit a PR. No need to assign the ticket in this case. Thanks!
