### ISSUE TITLE
Unregistered test markers

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#4432]
Motivation
----------
Unregistered custom marks result in numerous unhelpful warnings leading to unnecessary bloat of test results.

Modification
------------
Register markers, noparallel and dirty to get rid of the warnings.

**Comment by bziemons** [comment]
They are registered here: https://github.com/rucio/rucio/blob/fcf1f052c9af234b075b0f58be4c75b607588589/lib/rucio/tests/ruciopytest/plugin.py#L28-L33

how are you running the tests?

**Comment by dynamic-entropy** [comment]
<img width="909" alt="Screenshot 2021-03-16 at 2 51 42 PM" src="https://user-images.githubusercontent.com/69708588/111299244-b885bc80-8675-11eb-84e0-c67df07392ef.png">

I still get these warnings. Inside docker containers I run `tools/run_tests_docker.sh`

**Comment by dynamic-entropy** [comment]
<img width="917" alt="Screenshot 2021-03-16 at 4 38 24 PM" src="https://user-images.githubusercontent.com/69708588/111299688-3ea20300-8676-11eb-9d31-6e8df9535ed8.png">

**Comment by bziemons** [comment]
Ah, I see the problem. The plugin is not loaded when pytest-xdist is not loaded. I will check if this works without xdist.

**Comment by bziemons** [comment]
meanwhile you could `docker exec -it dev_rucio_1 pip install 'pytest-xdist~=2.2.0'`

**Comment by dynamic-entropy** [comment]
Adding a pytest.ini solves the problem too.

**Comment by bziemons** [comment]
I'd rather load the plugin. That gives us more headroom for future additions and pytest hooks.

**Comment by dynamic-entropy** [comment]
So, shall I close this issue?

**Comment by bziemons** [comment]
No, it's fine. Thanks for noticing this.
