### ISSUE TITLE
Documentation: Advance Usage & Client Pages Not Working as intended

### ISSUE THREAD

**Issue by DhruvSondhi** [rucio/rucio#4435]
Motivation
----------

After going through the documentation, I found that the following pages & section of the documentation are not being correctly built by Sphinx:
1. Advance Usage, found [here](https://rucio.readthedocs.io/en/latest/advanced_usage.html)
2. Installing Rucio Clients via Docker, found [here](https://rucio.readthedocs.io/en/latest/installing_clients.html#installing-with-docker)

Modification
------------
The suggestion from my side is that we can remove both the sections/pages from the documentation or We can modify the pages so as to remove this discrepancy 😄 
For the same, I would like to help fix it 😃

**Comment by bari12** [comment]
We are in the process of dropping the sphinx doc in favor of rucio/documentation (Markdown/docusaurus based).
But in the meanwhile it would still be nice to have this build correctly :-)

**Comment by DhruvSondhi** [comment]
Sure, I will do the needful :)
