### ISSUE TITLE
Base client should retry when receiving a 502 error

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4444]
Motivation
----------

ATLAS has observed a couple of times when requests to Rucio would fail with a 502 Bad Gateway error. This does not seem to be a wide-spread problem, but during those times it was happening consistently. Initial discussions pointed to HAProxy. 

Depending on which use of the Rucio client is failing, this can have detrimental effects on DPA. We could ask the users of the client to implement some protection around this, but there’s no doubt that it’s better for Rucio to handle it internally. The base client already has a mechanism for retrying requests that fail with a connection error.

Modification
------------

We should consider extending the retrying mechanism to also cover this type of error.

**Comment by bziemons** [comment]
I would do the same for 503 and 504, but that's debatable.
