### ISSUE TITLE
mypy static code analysis

### ISSUE THREAD

**Issue by bziemons** [rucio/rucio#4455]
Motivation
----------
Since there were many foreseeable problems with Python code and wrong type usages, I suggested adding mypy as a static code analysis tool.

For a quick introduction, see [mypy.pdf](https://github.com/rucio/rucio/files/6165303/mypy.pdf)

Modification
------------
Add mypy check script in tools/ and add CI step to automatically check type usages for PRs and commits.

**Comment by bziemons** [comment]
@maany @joeldierkes I made a simple first script to run mypy on the client sources here: https://github.com/bziemons/rucio/blob/5408a5e32c657a3c46355949ec0502a7c22824d7/tools/check_mypy.sh (in case you haven't seen it yet)
Please message me on slack if you have any general questions. I assume you will take this task over, but I'll be happy to help out where I can.

**Comment by maany** [comment]
Hey @bziemons , awesome. I will try to plug this in the autotest/integration-test workflows. I just need to check that mypy raises just warnings about the violations, and not hard errors, to begin with ;)

**Comment by bari12** [comment]
I am closing this in regards to what is needed for 1.29 
However, this doesn't mean the mypi story in general is done, particularly we need:
- A guide of how we expect developers to use types in Rucio
- Activate the actual type-checking
- A sprint to actually improve the current code-base
But especially the second and third I see beyond 1.29. Please create tickets for these @maany and @joeldierkes
