### ISSUE TITLE
Query hints for update queries

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4460]
Motivation
----------
For UPDATE queries on oracle the querie hints are missing.

Modification
------------
This might be related to the fact that there are two different ways in sqlalchemy to generate hints:
- [with_hint](https://docs.sqlalchemy.org/en/14/orm/query.html#sqlalchemy.orm.Query.with_hint) which is generally used by us, but according to the documentation should only work for SELECT queries.
- [prefix_with](https://docs.sqlalchemy.org/en/14/core/selectable.html#sqlalchemy.sql.expression.HasPrefixes.prefix_with) whcih can be used for all queries.

Change UPDATES to `prefix_with`.

**Comment by bziemons** [comment]
I think the culprit lies here: https://docs.sqlalchemy.org/en/14/core/dml.html?highlight=with_hint#sqlalchemy.sql.expression.UpdateBase.with_hint

While `with_hint` is a well-defined method for any non-select queries, it seems to be a no-op except for MSSQL.
