### ISSUE TITLE
Correct and Avoid redefining of built-in function

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#4466]
Motivation
----------
There are multiple redefinitions of built-in functions, such as:
1. type in client
2. filter in core

This is both confusing and a bad practice which renders the built-in functions useless.

Modification
------------
Come up with better alternatives. Maybe, request_type instead of type, filter_ (trailing underscore) when an alternative does not suit the requirements and avoid using built-in names or something else.

**Comment by bari12** [comment]
For the core we can easily change it, for the clients we need to align this with a feature release, as we shouldn't just break it within a release line.
