### ISSUE TITLE
Request with one tape and one multihop tape source will crash submitter

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#4516]
Motivation
----------
Suppose in the `get_transfer_requests_and_source_replicas` main loop, a request is added with a multihop tape source. Then in another iteration, a direct tape source is identified. We end up in https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/core/transfer.py#L968
Since the first source was multihop, we clear `transfers[req_id]['sources']` at https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/core/transfer.py#L1005-L1009
Then shortly after, if the second source is tape, we will end up in https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/core/transfer.py#L1042-L1050
where there is an unchecked access to `transfers[req_id]['sources'][0]` that crashes.

Modification
------------
In this situation, I believe we still want to prefer the direct tape source over the multihop tape source and want to take the path at L1047. So I would suggest modifying L1045 to
```python
if len(transfers[req_id]["sources"]) and (
    transfers[req_id]["sources"][0][3] > ranking
    or (
        transfers[req_id]["sources"][0][3] == ranking
        and transfers[req_id]["sources"][0][4] <= link_ranking
    )
):
    continue
```

**Comment by bari12** [comment]
I agree.
Direct source (Tape or Disk) should always be preferred over multihop.
@rcarpa can you please have a look on this.

**Comment by rcarpa** [comment]
The issue reported by @nsmith-  is real and should be fixed. But I don't understand why we need the special case in `get_transfer_requests_and_source_replicas` at https://github.com/rucio/rucio/blob/740b825cac747280ca159089bca4635264c07fc1/lib/rucio/core/transfer.py#L1005-L1009 

`get_hops` already prioritizes single hops by applying the HOP_PENALTY. Shouldn't we prioritize a multihop transfer with better cost over a single hop with worst cost? 

I believe we should just respect the costs/configurations. If somebody wants to always prioritize single hops, he can always set a very high hop penalty in configuration.

**Comment by bari12** [comment]
Yes you are right, letting `get_hops` decide is good I think, which then allows people to get their preferred behaviour via setting the `HOP_PENALTY`. 

But `get_hops` is executed on a specific source-destination pair. So we would have to store that ranking priority in the loop. But we are discussing two issues here.

a) The issue Nick is describing, which we need to fix.
b) How to improve the source selection, and for that I agree, just letting the `HOP_PENALTY` do it's work is probably enough without having special direct > multihop conditions.

**Comment by rcarpa** [comment]
In this case we agree about it. I just misunderstood your previous message : "Direct source (Tape or Disk) should always be preferred over multihop."
