### ISSUE TITLE
FTS Server based on a pair of RSEs

### ISSUE THREAD

**Issue by juztas** [rucio/rucio#4555]
Motivation
----------
Previously in CMS, we were able to set the FTS3 server based on RSE pairs (regex), while in Rucio - we are able to set only the main FTS3 Server. We had several cases, where we needed to change FTS3 Server based on RSE pair, e.g.:
T[12]_US* to RSE-X use cmsfts3@fnal.
T1_IT_CNAF_Tape to RSE-X - use fts3@cern. 

This is needed sometimes due to FTS related issues or for testing new protocols like davs for specific RSE pairs, etc and sometimes a fix of FTS Server takes weeks. This feature would be very useful to have.

**Comment by bari12** [comment]
Hi @juztas 

Can you explain the use-cases a bit more why this is needed? If it is just for testing some other solutions are maybe possible. To me micro-managing FTS transfers/servers at that level is really not something we should be aiming at. These workflows get overly complicated in my opinion and hard to understand.

To add the feature is of course not impossible and we might consider some kind of plugin approach for this, which then might also be based on regular expressions, but to me this feels like something we should avoid. So understanding the use-case better would be good.

**Comment by juztas** [comment]
Sure, by default we use FTS3@FNAL, but due to its an old version - it is failing transfers from Tape storage to Disk (it is failing for quite some time now (weeks)). I could change the FTS3 order and always use FTS3@CERN - but by doing so - we have seen in the past overloading FTS3@CERN and delaying transfers even longer - so it is also not the best solution. 
So in such case until FTS3@FNAL is fixed - I want to have the ability to change transfers from Tape to use FTS3@CERN, while everything else can continue to use FTS3@FNAL. There might be similar cases in the future (we have seen such in the past, so not excluding such failures)

**Comment by bari12** [comment]
I see, I mean I would highly recommend to make sure your FTS infrastructure is able to run any CMS workload. So having this version incompatibility is not great. That gives you also safety in case one of the FTSes has problems and you need to shift the workload.

For the FTS-server selection plugin, in principle this is something which could be hooked in the code where the FTS server is selected. It would then be part of the community (e.g. CMS) policy. An alternative would be to associate it in the `distances` table (RSE to RSE pairs) but I would prefer to keep this table clean from transfertool specific information.
The development needs to come from CMS though, however I can help with the plugin part. @ericvaandering what do you think?

**Comment by bari12** [comment]
I am closing this now. @ericvaandering please re-open if this is something CMS wants to look into.
