### ISSUE TITLE
Add DID data type to transfer and deletion events

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4557]
Motivation
----------

This will improve our monitoring capabilities, allowing for better understanding of data flows.

Modification
------------

Enrich the transfer and deletion events with the DID data type. It’s fine if it’s unset or some communities do not use it at all. We should carefully evaluate the performance cost.

**Comment by cserf** [comment]
:thinking:
I'm not sure I understand this issue. Deletion and transfers always apply to files. Can you elaborate what is needed ?

**Comment by dchristidis** [comment]
This came up as a request from the sites; they would like to be able to identify what kind of files are being deleted. On the DDM Dashboard, it appears to be useful to be able to group by data type. For example, `mc15_pPb8TeV:EVNT.18626196._000899.pool.root.1` should appear as `EVNT`, `mc16_13TeV:HITS.26797763._039273.pool.root.1` should appear as `HITS` (in short, the `datatype` from the file’s metadata).

**Comment by bari12** [comment]
I think it would be much easier if this is added to the monitoring/dashboard pipeline. Adding the `datatype` hardcoded to the events is not very elegant for Rucio, since that field has no meaning outside ATLAS/CMS. So we would have to do something configurable. I wonder if it is just easier to address this in the monitoring pipeline.

**Comment by rcarpa** [comment]
What was the decision about this one ?

**Comment by bari12** [comment]
I don't remember discussing this anymore. @dchristidis @cserf any info? 
Adding it to the deletion message is not that problematic, I guess.

**Comment by maany** [comment]
I support the idea to add this to the monitoring pipeline, @dchristidis do you prefer to get this info on some dashboards or from rucio directly?

**Comment by bari12** [comment]
Cedric and I just discussed this: It should be the datatype ([link](https://github.com/rucio/rucio/blob/433991b8c2bf32ab10a018d070cda268ab91b0a1/lib/rucio/db/sqla/models.py#L418)) field from the `dids` table. Simply from the `name` it is not consistent. 
Probably should also be added for the submitter.

Let's evaluate where we can most efficiently get the did information pulled in. Join in an existing query?
