### ISSUE TITLE
Allow for additional fields from transfer response on the poller daemon for messages

### ISSUE THREAD

**Issue by maatthias** [rucio/rucio#4576]
Motivation
----------
Currently `request.set_request_state` and `request.add_monitor_message` only allow for static list of fields from the transfer response to add to message.

Modification
------------
Allow passing of other fields from transfer response message.

**Comment by rcarpa** [comment]
Most of the work was done in https://github.com/rucio/rucio/pull/5269. I consider this issue can be closed
