### ISSUE TITLE
PolicyPackageNotFound: Module rucio.common.permission.generic_multi_vo not found

### ISSUE THREAD

**Issue by sfayer** [rucio/rucio#4579]
Hi,

While setting up an instance with multi_vo mode enabled using the default permissions package, I got the following error on the client (just from running rucio whoami):
```
2021-04-26 10:40:51,035 ERROR   Cannot authenticate.
Details: PolicyPackageNotFound: Module rucio.common.permission.generic_multi_vo not found 
```

I think this may just be a simple typo in the fallback package name here:
https://github.com/rucio/rucio/blob/b7102af49b39ed79e3fafa43d82e91620d721be6/lib/rucio/core/permission/__init__.py#L88

Is this meant to be "rucio.core.permission." instead and could it please be fixed?

Regards,
Simon

**Comment by bari12** [comment]
Yes that should be fixed. Thanks for reporting.
