### ISSUE TITLE
Stuck rule without a stuck timestamp

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#4592]
Motivation
----------
After a remake of the CMS Rucio integration server, we happened to hit a new issue where a rule got in the state STUCK, but its `stuck_at` property still contained the value `None`, see:
```
{u'locks_ok_cnt': 0, u'source_replica_expression': None, u'weight': None, u'purge_replicas': False, u'rse_expression': u'T1_US_FNAL_Disk', u'updated_at': u'Thu, 29 Apr 2021 15:19:30 UTC', u'meta': None, u'child_rule_id': None, u'id': u'3a4f4e10708c425cb6858855667a43a4', u'ignore_account_limit': False, u'locks_stuck_cnt': 8, u'locks_replicating_cnt': 0, u'notification': u'NO', u'copies': 1, u'comments': u'BLAH', u'split_container': False, u'priority': 3, u'state': u'STUCK', u'scope': u'cms', u'subscription_id': None, u'ignore_availability': False, u'stuck_at': None, u'error': u'RequestErrMsg.MISMATCH_SCHEME:RequestState.MISMATCH_SCHEME', u'eol_at': None, u'expires_at': u'Fri, 30 Apr 2021 13:15:42 UTC', u'did_type': u'CONTAINER', u'account': u'BLAH', u'locked': False, u'name': u'ANY DIDI NAME', u'created_at': u'Thu, 29 Apr 2021 13:15:42 UTC', u'activity': u'Production Input', u'grouping': u'ALL'}
```

Modification
------------
I believe it would make sense to ensure that `stuck_at` contains a valid timestamp for rules in `state='STUCK'`, as well as any other possible STUCK property that should be updated at the same time (i.e., an atomic operation).

**Comment by bari12** [comment]
Hi @amaltaro 
The `stuck_at` value is filled asynchronously when the `judge-repairer` touches it first. In principle nothing speaks against to set it immediately, it just has to be done in all the workflows.
