### ISSUE TITLE
rucio-clients: add extract support to download

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#46]
Add a flag --extract, which will automatically extract compressed files.

To be precise: This should download a full zip file and extract a specific file needed from that archive.

_Migrated from JIRA [RUCIO-2633](https://its.cern.ch/jira/browse/RUCIO-2633)_

**Comment by vingar** [comment]
So more suggestion from Rod on the archive/workflow support:
'It might be instructive to put together a rucio client archive command. One might archive a dataset
- check for files or download
- zip to N GB archives
- register archives and contents
- upload archive
- mark individual replicas secondary'

**Comment by rodwalker** [comment]
xrdcp has the option to just pull a file from a zip archive. It was a bit broken(for dpm at least) but fixed and in the next release I guess. It works for eos though
xrdcp -f --zip log.13685606._000001.job.log.tgz.1 root://eosatlas.cern.ch:1094//eos/atlas/atlasscratchdisk/rucio/user/walkerr/82/e4/user.walkerr.test2.zip /tmp/pants

Cheers,
Rod.

**Comment by TomasJavurek** [comment]
I summarized issues we have with extracting the files here:
https://docs.google.com/document/d/10Lu4jkbGh8bJ9AmRZQnDFwB8KamcO5ZmEG2vEfw8cCs/edit#
