### ISSUE TITLE
Cleanup FTS3 transfer tool code

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#461]
Motivation
----------
I spotted three things wrong with the FTS3 transfer tool:

   * The FTS3 transfer tool code disables TLS verification everywhere.  See https://github.com/rucio/rucio/blob/master/lib/rucio/transfertool/fts3.py#L69 as an example.
   * The FTS3 transfer tool creates a new session (TCP connection + SSL) for every operation and utilizes no session caching.
   * It doesn't seem to actually create any delegation, which is necessary for using the JSON interface directly.

Modification
------------
We absolutely should not disable TLS verification.  That should be improved ASAP.

The transfer tool should additionally cache / reuse / keep-alive SSL sessions in order to efficiently interact with FTS.  Finally, the delegation should be done to avoid a cronjob that must be run by the sysadmin.

**Comment by bari12** [comment]
The `verify=False` I vaguely remember was a fix due to a temporary issue, but I might be wrong. Maybe @mlassnig remembers.

**Comment by mlassnig** [comment]
verify=False: Indeed, this looks like a remnant.

For the session handling, yes, you're right.

For the delegation, this is done via a periodic cron outside the conveyor. We didn't want to couple this as a failure of one could affect the other:

- tools/delegate_proxy_fts.py

(btw, once FTS3 releases their CLI which can set the delegation lifetime longer than 4 hours this script can be made much more simple. With this script we get a safety buffer of 96 hours.)

**Comment by bbockelm** [comment]
@mlassnig - we really need to come back to this one (but, unfortunately, I don't think I'll personally have time to tackle it).  `verify=False` is bad news.

**Comment by mlassnig** [comment]
We need to add a separate ca_cert chain per FTS host (eg. BNL hostcert vs UKeS vs CERN). Shouldn't be too difficult. I'll have a look next week.

**Comment by bbockelm** [comment]
I'm not entirely sure that's necessary - current version of the `requests` module (really, it's probably `urllib3` that does this...) allows you to point at a directory (such as `/etc/grid-security/certificates`).

Additionally, even older versions allowed multiple CAs per file (simply concatenate them all together).  In other projects that use clients that don't understand directory-based CA layouts, we've just written scripts to do the concatenation at startup.

**Comment by mlassnig** [comment]
That makes it even easier then. Thanks for the heads-up.

**Comment by dciangot** [comment]
Hi,

can you take a look at (*) and see if that can be of any use in this regards?
I mean that as a starting point to get your feedback on how to proceed for the integration of fts delegation, if that can be useful.

(*)
https://github.com/dciangot/rucio/commit/00c012d6ae51c7125295ec3a25528270213021e9

**Comment by dciangot** [comment]
I have pushed this part (*) of the changes needed for transfers in CMS, but that is more general for FTS proxy delegation. I splitted it because I think that can be safely introduced and utilized for other purposes not CMS related. 
So I was thinking that for the other changes, more CMS specific, I could open an issue to better follow up without delaying further the proxy delegation stuff.  How does it sound @bbockelm @mlassnig @vgaronne @bari12 ?

(*) https://github.com/dciangot/rucio/commit/f3095add17e980f544019fc571bc5a81f18778c4

**Comment by bari12** [comment]
Hi Diego, I only had a quick look (will look more in detail later), but it looks good to me like that. I would propose you open a separate issue (even for the proxy delegation) and submit the PR already to rucio so we can comment there. No need to just keep it in your private repo.

**Comment by dciangot** [comment]
Agreed, I'm doing that. Thanks
