### ISSUE TITLE
Replica registration protocol issue

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4617]
Motivation
----------
The following replica registration issue was reported to DDM Support. Registration fails with

```
Error description:  ddm, 200: Could not add files to DDM: Details: One of the PFNs provided does not match the Rucio expected PFN : got {'gsiftp': ['gsiftp://cephc05.gla.scotgrid.ac.uk:2811/atlas:datadisk/rucio/hc_test/31/70/c5ebc528-d8e1-47ed-8d9e-35a2a674c794_13327.1.job.log.tgz', 'gsiftp://cephc05.gla.scotgrid.ac.uk:2811/atlas:datadisk/rucio/hc_test/71/57/output.1.c5ebc528-d8e1-47ed-8d9e-35a2a674c794_13327.pool.root']}, expected ['gsiftp://cephc04.gla.scotgrid.ac.uk:2811/atlas:datadisk/rucio/hc_test/31/70/c5ebc528-d8e1-47
```

There was some work done in #3940 to also allow lower-priority protocols, but the issue here seems to be that multiple protocols are registered with different endpoints, and Rucio "picks" one of them, but doesn't allow the other.

**Comment by snafus** [comment]
Hi,
  This appears now to be introducing operational issues at the site affected by this issue [https://ggus.eu/index.php?mode=ticket_info&ticket_id=152006]. 
  Is there a timeline on a fix; or any proposed workaround that we could try (to ensure the site can route its transfers correctly again)?
  Thanks in advance.
  James

**Comment by mlassnig** [comment]
Hi, I haven't had time yet to look into this. This is potentially tricky, so no guarantees yet when this is done. As a workaround, could you try removing the write_lan/1 for the gsiftp endpoint to see if that helps?
