### ISSUE TITLE
Registering lfn2pfn algorithm in policy package causes import loop

### ISSUE THREAD

**Issue by jamesp-epcc** [rucio/rucio#4624]
My original intention was that policy packages would register any lfn2pfn algorithms when first loaded, by calling `rucio.rse.protocols.protocol.RSEDeterministicTranslation.register`. But this can cause a circular import (because it imports from `rucio.core.rse`, but `rucio.core.rse` indirectly causes `rucio.common.schema` to be imported, which in turn loads the policy package) and loading the policy package fails.
To fix this I propose having the policy package define an optional function that returns a dictionary of lfn2pfn algorithms that it wants to register, and have Rucio call this function if it exists, and add the result to the main registry. We should probably do the same for SURL functions as well. This should remove the need for policy packages to import Rucio modules when they first load, removing the potential for circular imports.

**Comment by maxnoe** [comment]
Python actually has a mechanism for plugins supported in the standard library: entry points. This would allow the policy packages to just define the free functions, mark them in their project configuration as entry points for rucio and rucio could then load them.


For the example of lfn2pfn, the policy package would have a function:

# rucio_policy_foo.py
```python
def lfn2pfn(scope, name, rse, rse_attrs, protocol_attrs):
    return name
```

And would configure the entry point:
# pyproject.toml of rucio_policy_foo
```toml
[project.entry-points.rucio_fn2pfn]
foo = "rucio_policy_foo:lfn2pfn"
```

In the rucio core package, you would then get the lfn2pfn algorithm via the importlib.metadata std lib module:

```python
from importlib.metadata import entry_points

def get_lfn2pfn_algorithm(name):
    (lfn2pfn, ) = entry_points(group='rucio_lfn2pfn', name=name)
    return lfn2pfn  
```
