### ISSUE TITLE
Conveyor submitter not fully consuming their partitions

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4625]
Motivation
----------
Recently we observe that some conveyor submitter threads do not fully consume their partitions and some requests stay behind. This has the noticeable effect that only a fraction of transfers for a replication rule (submitted at the same time) are processed, while the others stay in `QUEUED` state and are only picked up (sometimes hours) later. 

However, due to the partitions backlog being even below the submitters bulk size, these partitions should be submitted immediately, or latest a few minutes later.

Modification
------------
Under investigation.

**Comment by rcarpa** [comment]
Can we consider this one as being fixed?

**Comment by bari12** [comment]
Yes 👍 
We can re-open should it come up again.
