### ISSUE TITLE
Add the ability to quicken the transition of STUCK rules to REPLICATING

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4634]
Motivation
----------

Following a `rucio update-rule --stuck --cancel-requests __RULE__`, there might be a considerable delay (up to 8 hours; see [here](https://github.com/rucio/rucio/blob/98c87d1f943d92a8e3a121e772178e79aa9622c7/lib/rucio/core/rule_grouping.py#L777)) until the requests are recreated. Currently, one needs to manipulate the `updated_at` timestamps of the `STUCK` locks and the replication rule itself.

Modification
------------

Consider adding a new option in the client and the necessary implementation in the various layers to quicken the transition from `STUCK` to `REPLICATING`. This operation should be reserved to accounts with elevated privileges.

**Comment by bari12** [comment]
I think we could add a `rucio update-rule --boost-rule <ruleid>` option.
That option needs to do the following steps:
- For each STUCK lock it needs to set the `updated_at` time to 24h prior.
- Set the `updated_at` of the rule to 24h earlier.
This will force, in the next run of the repairer, that the requests are immediately resubmitted.

We need to consider that this might be executed together with `--stuck and --cancel-requests` thus:
`rucio update-rule --stuck --cancel-requests --boost-rule <rule_id>` so this needs to be considered in the `update_rule` part of the core.
