### ISSUE TITLE
Collaborate with Intake?

### ISSUE THREAD

**Issue by jsignell** [rucio/rucio#4635]
@martindurant and @douglasdavis it just came up at the dask conference that there might be an opportunity for intake and rucio to collaborate. 

I am just putting this here as a placeholder for that conversation.

**Comment by martindurant** [comment]
Thanks for the ping @jsignell 

I had not heard of this project before. After 10s, it seems to me that `rucio` could well be a source of Catalogs for Intake, so that people could access data via the Intake API. Is that an interesting abstraction, would Intake's features be of interest?

**Comment by bari12** [comment]
Hi everyone,
Thanks for the interest. I have to say I don't know much about Intake, will have to do some reading. I believe @nsmith- brought this up at the DASK conference and already has some experience? Maybe we could have a quick chat about this these days.

**Comment by nsmith-** [comment]
It sounds like @jpivarski is due credit for the connection, but indeed I do play around with both projects, much more rucio than intake however.

**Comment by martindurant** [comment]
Happy to get together virtually to spur conversation and bounce ideas around. That could be in the Summit (come to the data-access workshop!) or after.
