### ISSUE TITLE
Force GSI authentication for root fix did not work

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#467]
Motivation
----------
The fix done in #83 to force GSI authentication did not work for gfal. The related merge request is #223

**Comment by mlassnig** [comment]
This is the statement that should be working (but doesn't):

self.__ctx.set_opt_string("XROOTD PLUGIN", "XRD.WANTPROT", "gsi")

Might be necessary to follow this up with the gfal people.

**Comment by nikmagini** [comment]
Hi Mario,

yes, it seems to be an issue with the gfal library. If I put xrd.wantprot explicitly in the root URL, I can force gfal to use GSI auth on xrootd(1) However, if I set XRD.WANTPROT as an env option, gfal falls back to krb5 auth (2) I'll follow up with gfal devs.

Cheers
Nicolo'

(1)
`
import gfal2
ctx=gfal2.creat_context()
ctx.filecopy("root://eosatlas.cern.ch//eos/atlas/atlasdatadisk/rucio/mc15_valid/ff/f4/EVNT.12362219._000320.pool.root.1?&xrd.wantprot=gsi", "file:///tmp/niccotest66")
180112 18:11:10 7805 cryptossl_X509CreateProxy: Your identity: /C=IT/O=INFN/OU=Personal Certificate/L=Genova/CN=Nicolo Magini
Enter PEM pass phrase:
`

(2)
`
import gfal2
ctx=gfal2.creat_context()
ctx.set_opt_string("XROOTD PLUGIN", "XRD.WANTPROT", "gsi")
0
ctx.get_opt_string("XROOTD PLUGIN", "XRD.WANTPROT")
'gsi'
ctx.filecopy("root://eosatlas.cern.ch//eos/atlas/atlasdatadisk/rucio/mc15_valid/ff/f4/EVNT.12362219._000320.pool.root.1", "file:///tmp/niccotest66")
0
`

**Comment by mlassnig** [comment]
Great, thanks!

**Comment by nikmagini** [comment]
Hi all,

summary of the investigation:

1) Indeed there's a bug in the current gfal2 version 2.14.2 with the 'XRD.WANTPROT' option which is not passed in the root TURL. The gfal2 team provided a fix which should be released in the next gfal2 version 2.15.0

2) However, even with this fix, adding xrd.wantprot to the root TURL doesn't seem to work on EOS - transfers fail with "Network is unreachable". Actually it's not gfal2 specific; I get this error even with the xrd client.

I'll continue to follow up with gfal and eos devs

Cheers
N.

`[nmagini@lxplus102 ~]$ xrdcopy "root://eosatlas.cern.ch//eos/atlas/atlasdatadisk/rucio/mc15_valid/ff/f4/EVNT.12362219._000320.pool.root.1?xrd.wantprot=gsi" /tmp/niccotest68`
`[0B/0B][100%][==================================================][0B/s]`
`Run: [ERROR] Server responded with an error: [3014] Unable to open file  /eos/atlas/atlasdatadisk/rucio/mc15_valid/ff/f4/EVNT.12362219._000320.pool.root.1; Network is unreachable`

**Comment by nikmagini** [comment]
Note about the change: this is needed to make sure that 'xrd.wantprot' works on EOS. However it's not sufficient to disable the fallback to krb5 - for this we also need to wait for the release of gfal 2.15.0 as mentioned in the previous comment

**Comment by nikmagini** [comment]
More details about the reason for the change, from gfal devs:

- On EOS we need to pass both gsi (for auth to the headnode) and unix (for auth between headnode and FSTs)
- On other xrootd storages gsi is sufficient; adding unix shouldn't do harm since as second option it won't be selected

**Comment by mlassnig** [comment]
Thanks for the thorough investigation!
