### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by fstagni** [rucio/rucio#4670]
Hi,
Is there a specific reason why python 3.9 is explicitly disabled in pypi? After including `rucio-clients` (from https://pypi.org/project/rucio-clients/) as a DIRAC dependency, the python 3 tests are failing, as we install using python 3.9. We are applying some workaround just to make the tests to pass.

Motivation
----------

Python 3.9 is explicitly disabled (https://pypi.org/project/rucio/, https://pypi.org/project/rucio-clients/)

Modification
------------

Enable python 3.9 on pypi for `rucio-clients` package

**Comment by bziemons** [comment]
While the Python 3.9 tests for clients ran through without any issues, we just added the tests and made adjustments in the server code of Rucio to be Python 3.9 compatible: https://github.com/rucio/rucio/pull/4602
This won't be an issue with the 1.26 release, which should come at the end of this month.

**Comment by bari12** [comment]
As @bziemons said, this will be solved with 1.26 at the end of the month. I'll assign the ticket to the milestone. You'll get a notification once it is out and this is closed.
