### ISSUE TITLE
Rucio-clients (+rucio?) on conda-forge

### ISSUE THREAD

**Issue by fstagni** [rucio/rucio#4671]
Motivation
----------

We'd like to install `rucio-clients` from conda-forge.
DIRAC relies on conda for its own running environment. Given that a DIRAC --> Rucio Catalog bridge has been recently integrated in DIRAC, we'd like that at least the `rucio-clients` package is maintained on conda-forge.

Modification
------------

Would it be possible to add at least `rucio-clients` on conda-forge? https://github.com/conda-forge
For questions and trouble-shooting you can ask @chrisburr

**Comment by chrisburr** [comment]
Assuming you're unfamiliar with conda, packages can be added to conda-forge by making a PR to https://github.com/conda-forge/staged-recipes. In this case most of the work can be handled by grayskull which generates recipes using the PyPI metadata. It's available from either as a [CLI](https://github.com/conda-incubator/grayskull) or [on this website](https://www.marcelotrevisani.com/grayskull).

Once it's been accepted a new GitHub repository will be created (a "feedstock") which can be used for releasing new versions (the "recipe maintainers" have merge rights). Updates can often by handled by the bots though changes to the dependencies made manually (for now at least).

**Comment by bari12** [comment]
I am not too familiar with conda-forge, so I will have to have a look first. I don't think it will be a problem though.

**Comment by joeldierkes** [comment]
A PR (conda-forge/staged-recipes#16601) to the [conda-forge/staged-recipes](https://github.com/conda-forge/staged-recipes) was submitted and awits approval.

**Comment by bari12** [comment]
Thanks for merging @chrisburr 
I am closing this ticket now. @fstagni please give it a try and let us know. (Sorry that it took a while)
