### ISSUE TITLE
Invalid JSON returned when querying database for transfers

### ISSUE THREAD

**Issue by thysk** [rucio/rucio#4701]
Motivation
----------
I am looking to utilise either the JSON from the job_params, or the transfer_file which are passed to the FTS in order to sort jobs by VO so correct certificates can be selected based on the VO.
The scope, and account parameters passed are not JSON as they are not encapsulated within any quotes.

If there is a reason for this that I have missed please do let me know. I am still looking into where this issue arrises. I will update should I find anything.

for single VO environment:
FILES
[{'sources': ['root://xrd2:1095//rucio/test/a9/23/file3'], 'destinations': ['root://xrd3:1096//rucio/test/a9/23/file3'], 'metadata': {'request_id': '1a97b34681294f968712c45a949b6d20', 'scope': test, 'name': 'file3', 'activity': 'User Subscriptions', 'request_type': <RequestType.TRANSFER: 'T'>, 'src_type': 'DISK', 'dst_type': 'DISK', 'src_rse': 'XRD2', 'dst_rse': 'XRD3', 'src_rse_id': '2751d14e03c3488fb5cab2cfb689cbca', 'dest_rse_id': 'f72d72a2b0b34781b63f8c8a9207d7ae', 'filesize': 10485760, 'md5': 'bcc13e60f542e1e2002ffb2c9a13363c', 'adler32': 'a273a398', 'verify_checksum': 'both', 'source_globus_endpoint_id': None, 'dest_globus_endpoint_id': None}, 'filesize': 10485760, 'checksum': 'ADLER32:a273a398', 'verify_checksum': 'both', 'selection_strategy': 'orderly', 'request_type': <RequestType.TRANSFER: 'T'>, 'activity': 'User Subscriptions'}]
JOB_PARAMS
{'account': root, 'use_oidc': False, 'verify_checksum': 'both', 'copy_pin_lifetime': -1, 'bring_online': None, 'job_metadata': {'issuer': 'rucio', 'multi_sources': False}, 'overwrite': True, 'priority': 3, 'max_time_in_queue': 168}

for multi_VO environment:
JOB_PARAMS
{'account': root@tst, 'use_oidc': False, 'verify_checksum': 'both', 'copy_pin_lifetime': -1, 'bring_online': None, 'job_metadata': {'issuer': 'rucio', 'multi_sources': False}, 'overwrite': True, 'priority': 3, 'max_time_in_queue': 168}
TRANSFER_FILE
{'sources': ['root://xrd2:1095//rucio/test/2b/c2/file4'], 'destinations': ['root://xrd3:1096//rucio/test/2b/c2/file4'], 'metadata': {'request_id': 'a6ec78e3ff334f1fb93d39cc82e20e9d', 'scope': test@tst, 'name': 'file4', 'activity': 'User Subscriptions', 'request_type': <RequestType.TRANSFER: 'T'>, 'src_type': 'DISK', 'dst_type': 'DISK', 'src_rse': 'XRD2', 'dst_rse': 'XRD3', 'src_rse_id': '9327cda2af8a4add9816e0193d0b296c', 'dest_rse_id': 'e25b5f2f17c3406ebd50fbacbf2fa981', 'filesize': 10485760, 'md5': '31cd1f53a64534fc6439316a2775d0c6', 'adler32': 'fc1bf052', 'verify_checksum': 'both', 'source_globus_endpoint_id': None, 'dest_globus_endpoint_id': None}, 'filesize': 10485760, 'checksum': 'ADLER32:fc1bf052', 'verify_checksum': 'both', 'selection_strategy': 'orderly', 'request_type': <RequestType.TRANSFER: 'T'>, 'activity': 'User Subscriptions'}

**Comment by bziemons** [comment]
This looks like a plain python dictionary dumped

**Comment by bari12** [comment]
At what point in the code/interface are you reading this?

**Comment by thysk** [comment]
this is the information within files, and job_params passed to fts3.py submit()
I have placed in a few prints to see what the information, so in this case the information above was from
print(transfer_files)
and 
print(job_params)
respectively.

**Comment by thysk** [comment]
but the same information and lack of quotation marks around the account and scope information can be seen on my m-VO rucio server in use as well when a debug message comes up in the logs
