### ISSUE TITLE
Allow client to choose data access library

### ISSUE THREAD

**Issue by jamesp-epcc** [rucio/rucio#4730]
This is part of the work to make the Rucio client more lightweight.

At present, the protocol (and hence the library) to be used for accessing an RSE is determined by the RSE settings on the server. This can mean that additional dependencies are required on the client side. For example, the settings may specify that GFAL must be used to access a given RSE, when in fact the RSE provides an HTTP interface that could be accessed via a more lightweight library.

To avoid this problem, the library selection could be moved to the client side. The client code could include a list of protocols and a list of libraries that can be used to access each one. The client can then detect which libraries it has installed and select a suitable one rather than being constrained by the settings on the server.

**Comment by bari12** [comment]
So this should be covered by @rak108 #4780
