### ISSUE TITLE
Delete distance API

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#4742]
Although there is a core method
https://github.com/rucio/rucio/blob/a0823b3ec19ff1f98639361a14b628ca6c908651/lib/rucio/core/distance.py#L115
we have no client or REST API access to this method.

**Comment by bari12** [comment]
@davidpob99 please have a look on this one and ask me if anything is unclear. It's mainly mirroring the interface and exposing it to the REST and rucio-admin.
