### ISSUE TITLE
breaking tests following change of nomenclature

### ISSUE THREAD

**Issue by robbarnsley** [rucio/rucio#4772]
Motivation
----------

https://github.com/rucio/rucio/blob/a5e5e7d54b1d48ced74ec59673f9a9e27e9316b0/lib/rucio/client/rseclient.py#L679 needs changing in line with changes made in #4735  

Modification
------------

"type" -> "type_"

**Comment by robbarnsley** [comment]
also "bytes" -> "bytes_": https://github.com/rucio/rucio/blob/a5e5e7d54b1d48ced74ec59673f9a9e27e9316b0/lib/rucio/tests/test_judge_repairer.py#L326

**Comment by rcarpa** [comment]
Should be fixed by 

https://github.com/rucio/rucio/pull/4775

**Comment by robbarnsley** [comment]
confirmed
