### ISSUE TITLE
helm-charts release management

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4794]
Motivation
----------
Currently we do not maintain helm-charts for LTS releases, which puts LTS users in an akward situation, as newer helm-charts might not be compatible with the old release.

- [ ] Need to find a release management scheme which is compatible to the LTS releases
- [ ] Need to have the auto-build feature (via github actions) be able to support this (possible multiple branches)

**Comment by ericvaandering** [comment]
I think the first part of this is easy in that we'd re-do the helm-chart version numbers to fit in with Rucio release numbers to the major and minor level. So helm chart 1.26.x will work with any Rucio 1.26.y release (I think Rucio defacto does not change the interface on the patch release boundaries).

Getting the second part working to where it's possible to submit a new helm chart for an LTS release and have it auto-built looks more involved. 

As a stop-gap it's completely possible to install helm charts from git repos, not from packaged tar balls. Or to add things manually. I would expect releasing a chart for an LTS release would be an infrequent occurrence. 

As a start we can adopt the naming scheme and try to solve the other issues afterwards.

**Comment by rcarpa** [comment]
I have a feeling that this ticket is solved. Isn't it ?

**Comment by ericvaandering** [comment]
Yes
