### ISSUE TITLE
Rename Daemons to commonly understandable names

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4795]
Motivation
----------
This should be done in several steps

- [ ] Should try with one daemon first

Within `lib/rucio/daemons` the internal daemon names can stay.

Modification
------------

Table of daemon names

Old name | new name
------------ | -------------
Abacus-Account | usage-calculator-account ✅ 
Abacus-Collection-Replica | usage-calculator-replica ✅ 
Abacus-RSE | usage-calculator-rse ✅ 
Atropos  | ~~rule-cleaner, rule-deleter~~ lifetime-rule-cleaner
Auditor | ~~storage-inconsistency-finder, inconsistency-finder, storage-conflict-finder, clashing-storage-finder~~ storage-auditor
Automatix | ~~rse-validator~~ rse-functional-tester
BB8 | data-rebalancer ✅ 
C3PO | ~~data-placement~~ dynamic-data-placer
Cache-Client | cache-client
Cache-Consumer | cache-consumer
Conveyor-Finisher | transfer-finisher ✅ 
Conveyor-Fts-Throttler | fts-throttler ✅ 
Conveyor-Poller | transfer-poller ✅ 
Conveyer-Preparer | transfer-preparer ✅ 
Conveyer-Receiver | transfer-receiver ✅ 
Conveyer-Stager | stager, ~~transfer-stager~~ 
Conveyor-Submitter | transfer-submitter ✅ 
Conveyor-Throttler | transfer-throttler ✅ 
Follower | ~~did-report-creator, did-report-architect, did-event-collector, did-event-notifier~~, event-follower
Hermes | message-submitter ✅ 
Hermes2 | message-submitter2 ✅ 
Judge-Cleaner | rule-cleaner ✅ 
Judge-Evalator | rule-evaluator ✅ 
Judge-Injector | rule-injector ✅ 
Judge-Repairer | rule-repairer ✅ 
Kronos | tracer ✅ 
Minos | ~~tempreplicas~~ tempreplicas-processor
Minos-Temporary-Expiration | ~~tempreplicas-expiration~~, tempreplicas-cleaner
Necromancer | ~~badreplicas~~, badreplica-recoverer
OAuthManager | oauth-manager ✅ 
Reaper | ~~file-deleter~~, replica-remover
Reaper-Dark (aka. Dark-Reaper) | ~~bad-file-deleter~~, dark-replica-remover
Reaper-Light (aka. Light-Reaper) | ~~cache-file-deleter~~, cache-replica-remover
Replica-Recoverer | ~~bad-replica-filterer, bad-replica-terminator~~, suspicious-replica-processor
Transmogrifier | ~~replication-rule-resolver, replication-rule-creator~~, subscription-processor
Undertaker | ~~expired-did-manager, expired-did-deleter, expired-did-handler~~, expired-did-processor

**Comment by ericvaandering** [comment]
oath-manager (add a dash)

I don't think tracer is particularly clear. What about trace-injector?

**Comment by bari12** [comment]
👍 Maybe `trace-processor` would be better. It's a little bit of both.

**Comment by ericvaandering** [comment]
Even better

**Comment by mlassnig** [comment]
some proposals:


cache-consumer -> cache-update-receiver

fts-throttler -> transfer-fts-throttler

follower -> did-event-submitter

stager -> transfer-tape-stager

hermes -> message-submitter-legacy

hermes2 -> message-submitter

kronos -> trace-evaluator

minos -> temporary-replicas-evaluator

minos-temporary-expiration -> temporary-replicas-cleaner

necromancer -> replica-recoverer-bad

replica-recoverer -> replica-recoverer-suspicious

transmogrifier -> subscription-evaluator

undertaker -> did-expiration-evaluator

reaper -> replica-remover

dark reaper -> replica-remover-dark

light reaper -> replica-remover-cache

**Comment by voetberg** [comment]
I agree with @mlassnig 's suggestions w.r.t. Hermes and Hermes2, 
> hermes -> message-submitter-legacy
> hermes2 -> message-submitter

Naming something with numbers is always opaque, we should avoid it if possible and doing a refactor like seems like the perfect time to make those changes
