### ISSUE TITLE
Prepare replacement of current policy import with policy packages

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4798]
Motivation
----------
- [x] Need to explain communities how to build these packages
- [x] #5138 

Current upstream policies
----------
(Checked ones can be removed)

- [x] ATLAS
- [x] Belle II to be checked
- [x] CMS
- [x] DOMA TPC to be checked
- [x] ESCAPE to be checked
- [x] Icecube to be checked
- [x] LSST / RUBIN

**Comment by jamesp-epcc** [comment]
Belle II are no longer using the code in the main tree in production (they are using a policy package instead). However it is still used for the Belle II VO tests so it cannot be removed without breaking those. I guess the right solution is for the VO tests to use the policy package as well. Once we have the DUNE tests merged (which use DUNE's policy package), maybe we can use the same pattern to load the Belle II policy package for the Belle II tests.

**Comment by rdimaio** [comment]
> I guess the right solution is for the VO tests to use the policy package as well.

I think it would instead be better to move the responsibility of VO-specific tests to the VOs themselves, e.g. Belle II running their own tests and so on.

IMO, if a VO test fails, it's either due to:
1. an issue with Rucio itself - in this case we would likely see it in the Rucio tests first; I personally have never seen a VO test fail in a situation where the autotests and integ tests did not fail (except for flaky tests). However, in case this happens (no failure in Rucio's CI/CD but VO tests failing) and the VO determines this is an issue with Rucio itself, they can open an issue to us.
3. an issue with the VO's policy package - in which case it is not within the Rucio's team scope to fix the issue.

I don't think it's scalable to maintain VO-specific tests in Rucio's main CI pipeline, for the same reason that it is not scalable for Rucio to maintain VO-specific policies in the core repository.

For reference: https://github.com/rucio/rucio/discussions/6576

**Comment by bari12** [comment]
I agree that we should get all VO-specific code out of the upstream repo. 

For the VO-specific CI tests I am not so sure though. I think there is a benefit of having these tests, I agree though that this might be a scalability problem at some point. But the different VOs run things different from the generic policy, such as having `/` in names (Belle II, CMS), or using an external metadata store (DUNE) etc.
I think the alternative would be to capture the "essence" of these differences and bake them into the core CI and not allow VO-tests at all, but this always has the risk that we do not identify these differences correctly and do not keep it up to date.

**Comment by rdimaio** [comment]
> I agree that we should get all VO-specific code out of the upstream repo.
> 
> For the VO-specific CI tests I am not so sure though. I think there is a benefit of having these tests, I agree though that this might be a scalability problem at some point. But the different VOs run things different from the generic policy, such as having `/` in names (Belle II, CMS), or using an external metadata store (DUNE) etc. I think the alternative would be to capture the "essence" of these differences and bake them into the core CI and not allow VO-tests at all, but this always has the risk that we do not identify these differences correctly and do not keep it up to date.

I'm in favour of the last point (capturing the "essence") of these differences - IMO things like supporting `/` in names depend on core functionality, so they should be tested as part of the core CI.

> the risk that we do not identify these differences correctly and do not keep it up to date.

I think this would be up to the VO to identify possible issues that arise and opening bug reports / feature requests

**Comment by garciagenrique** [comment]
ESCAPE policies were moved here: https://gitlab.cern.ch/escape-wp2/escape-rucio-policy-package

**Comment by rdimaio** [comment]
ATLAS policies have been moved, but the policy package is not being used yet

**Comment by rdimaio** [comment]
ATLAS policy package published to PyPI: https://pypi.org/project/atlas-rucio-policy-package/

**Comment by garciagenrique** [comment]
ESCAPE policy package published to PyPI too: https://pypi.org/project/escape-rucio-policy-package/

**Comment by bari12** [comment]
@jamesp-epcc @rdimaio just an update on this
* @cserf agreed that the belle 2 package can be removed (We will need some kind of hack for that since they do not have an official policy package yet. So i would suggest to put a temporary one somewhere)
* escape can be removed (see @garciagenrique message)
* domatpc can be removed
* icecube can be removed
Thanks! :-)

**Comment by rdimaio** [comment]
I am confused about the state of Belle II

I see [this comment](https://github.com/rucio/rucio/issues/4798#issuecomment-2182841424) mentions:
> Belle II are no longer using the code in the main tree in production (they are using a policy package instead). However it is still used for the Belle II VO tests so it cannot be removed without breaking those.

While [this comment](https://github.com/rucio/rucio/issues/4798#issuecomment-2443990926) says:
> @cserf agreed that the belle 2 package can be removed (We will need some kind of hack for that since they do not have an official policy package yet. So i would suggest to put a temporary one somewhere)

1. Do they have a policy package already or not?
2. If not - can the hardcoded Belle II logic in the main Rucio codebase be safely removed without breaking their installation, and is it just used for VO tests?

**Comment by bari12** [comment]
Belle II is on a much older Rucio version at the moment. So it can be removed without breaking anything immediately. Once they move to Rucio 36, this would have to be checked of course, but by then they should have a policy package.
But since we need to produce a "temporary" Belle II policy package anyway, they can just use this one as an example. So I think this is fine.

**Comment by jamesp-epcc** [comment]
There are still a few VO-specific algorithms in `rucio.rse.translation` and `rucio.common.utils` used for various translations. Should we be aiming to get these out of the core code as well? Do we know which ones are still being used?

pfn2lfn:
* ATLAS

lfn2pfn:
* BelleII
* Ligo
* Xenon

non-deterministic pfn:
* DQ2
* T0
* BelleII

scope extraction:
* ATLAS
* Dirac
* BelleII

**Comment by rdimaio** [comment]
> pfn2lfn:
> 
>     * ATLAS
> 
> 

Being removed here: https://github.com/rucio/rucio/pull/7169

> lfn2pfn:
> 
>     * BelleII
> 

Being removed here: https://github.com/rucio/rucio/pull/7166

>     * Ligo
> 
>     * Xenon
> 
> 

Not sure about these two. Are they still being used?

> non-deterministic pfn:
> 
>     * DQ2
> 
>     * T0
> 

Being removed here: https://github.com/rucio/rucio/pull/7169

>     * BelleII
> 
> 

Being removed here: https://github.com/rucio/rucio/pull/7166

> scope extraction:
> 
>     * ATLAS
> 

Being removed here: https://github.com/rucio/rucio/pull/7169

>     * Dirac
> 

Not sure where we should put this - maybe as a separate Dirac plugin?

>     * BelleII

Being removed here: https://github.com/rucio/rucio/pull/7166

**Comment by rdimaio** [comment]
Opened https://github.com/rucio/rucio/issues/7187 to discuss the remaining algorithms that don't fit in the upstream policies list from the top post
