### ISSUE TITLE
Messages payload are limited to 4000 characters and throw exception

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#48]
When inserting messages to hermes which are too long this throws a DB exception

`DatabaseException: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (cx_Oracle.DatabaseError) ORA-01461: can bind a LONG value only for insert into a LONG column [SQL: 'INSERT INTO atlas_rucio.messages (id, event_type, payload, updated_at, created_at) VALUES (:id, :event_type, :payload, :updated_at, :created_at)'] [parameters: {'id': , 'created_at': datetime.datetime(2017, 5, 18, 14, 26, 32, 316246), 'event_type': 'email', 'updated_at': datetime.datetime(2017, 5, 18, 14, 26, 32, 316240), 'payload': '{"body": "A new rule has been requested for approval in Rucio.\\n\\nRule description:\\n\\n ID: 89593c3ea1e449cea3b2dbbd81033b06\\ ... (3749 characters truncated) ... TED MESSAG\\n", "to": ["damian.alvarez.piqueras@cern.ch"], "subject": "[RUCIO] Request to approve replication rule 89593c3ea1e449cea3b2dbbd81033b06"}'}]`

We have to look into if we can update the DB to allow longer messages, but in anyway, hermes should protect against this.

_Migrated from JIRA [RUCIO-2662](https://its.cern.ch/jira/browse/RUCIO-2662)_

**Comment by bari12** [comment]
Conclusion of todays meeting was to talk to Gancho about the impact of switching to BLOB.

**Comment by mlassnig** [comment]
Gancho just confirmed. We will get varchar(32k) with the next oracle release. sqlite and mysql are 32k already, psql is unlimited size.

Will add new column payload_clob for oracle, which we can drop again as soon as oracle gets 32k varchar support.

**Comment by vingar** [comment]
it looks like a good use case for the json column type.

**Comment by mlassnig** [comment]
i also thought about that, but we don't select on the message, it's just a payload holder. so the json would just be overhead.

**Comment by vingar** [comment]
storing a json payload into a json column doesn't look too exotic even if we don't select on it. Something to add on the gsoc proposal as a first contribution ?

**Comment by bari12** [comment]
This could have implications both on INSERT as well as on SELECT. For CLOB at least oracle has to make context switches into pl/sql to execute this. For JSON I imagine this could be the same, especially since oracle might try to create some structure of the stored json?
But I don't get the point of doing this, since we are never trying to search inside the payload, it's always the selection of the full row. It's an optimisation for something which we don't use, and I doubt that it makes the current workflow faster 😄

**Comment by vingar** [comment]
The json type is quite new and it can be the opportunity to get more experience with it on a simple use case: support on different db, sqlachelmy, measure the overhead, save some json dumps/load operations etc. I would just put it as part of the gsoc project and part of the project

**Comment by cserf** [comment]
Up

**Comment by bari12** [comment]
Discussed in the [dev meeting on 2018-10-11](https://indico.cern.ch/event/760955/):
- Add new column CLOB
- Column should only be used if the normal column is NULL
