### ISSUE TITLE
Support API to return dataset locks for a given container name

### ISSUE THREAD

**Issue by amaltaro** [rucio/rucio#4807]
Motivation
----------
As an alternative to the feature requested in: https://github.com/rucio/rucio/issues/3982
we could have a new API, which would accept a container data type as input, and it would return a list with all the datasets and their corresponding locks.

This would provide a great performance improvement for client/server communication - as well as external applications - when containers contain thousands of datasets to be listed, reducing all of this to a single HTTP call.

Modification
------------
Implement an API that takes a container data type/name as input parameter, and returns as output a list with all the container datasets and their corresponding lock information. Similar to what is done for `get_dataset_locks`, provided a given dataset.

There are multiple ways to implement it, and I leave that up to the Rucio team, some ideas are:
* create a new API like get_container_locks
* or just allow the get_dataset_locks to have a container data type in the `name` parameter.

**Comment by ivmfnal** [comment]
Waiting for the code review.. The PR will include changes for both #3982 and #4807

**Comment by ivmfnal** [comment]
The PR is still under review...
