### ISSUE TITLE
FTS limits config update from CRIC

### ISSUE THREAD

**Issue by rodwalker** [rucio/rucio#4820]
Hi,
It was discussed by mail and in ddm dev - here is the ticket so we don`t forget.
For a few sites we are setting configuration in FTS to limit active transfers or throughput. It would be nice if we could make these settings in CRIC, and then update the primary FTS server periodically.
This update uses a simple json file and a curl command to the FTS server - it should be trivial to automate.

I think the parameters associated to a storage have a clear place to go in CRIC. Those for specific links between storages do not, but these are also less important/used.
An example of the json used to update the config is below
{
"gsiftp://bohr3226.tier2.hep.manchester.ac.uk": {
        "se_info": {
            "se_metadata": "My metadata",
            "ipv6": 1,
            "udt": 1,
            "debug_level": 0,
            "inbound_max_active": 100,
            "oubound_max_active": 100,
            "inbound_max_throughput": 500,
            "outbound_max_throughput": 500
        }
}
}

It might be jumping ahead but I would start in CRIC by adding these parameters to the endpoint and then CRIC spits out this json. Even without a rucio probe, this would allow us to track the desired config and ease the manual update.

Cheers,
Rod.

**Comment by bari12** [comment]
Yes, I think this can be already put into CRIC.

It's not really a Rucio development per-se though, but I get the point that we already have other probes in place, so why not add another one taking care of this. But in principle, there is no real reason this must go cric -> rucio -> fts, since we don't store this in rucio.

**Comment by bari12** [comment]
Going through old tickets. @rodwalker is this still something of interest?
