### ISSUE TITLE
Replica sorting does not work

### ISSUE THREAD

**Issue by ivukotic** [rucio/rucio#4832]
Motivation
----------

We need file replicas to be returned according to distance from client. All the code is there but something is wrong and independently where the client is, rucio returns replicas in the same order. We (ServiceX, VP, xcache) need this ASAP.

To replicate
----------------
from lxplus using lsetup 'rucio testing'.
This gives you client 1.26.3

 rucio list-file-replicas data17_13TeV:DAOD_PHYS.23589107._001299.pool.root.1
+--------------+----------------------------------------+------------+-----------+------------------------
| data17_13TeV | DAOD_PHYS.23589107._001299.pool.root.1 | 1.220 GB   | 1f07615c  | FZK-LCG2_DATADISK: root://atlasxrootd-kit.gridka.de:1094//pnfs/gridka.de/atlas/disk-only/atlasdatadisk/rucio/data17_13TeV/fd/1a/DAOD_PHYS.23589107._001299.pool.root.1 |
| data17_13TeV | DAOD_PHYS.23589107._001299.pool.root.1 | 1.220 GB   | 1f07615c  | MWT2_DATADISK: root://fax.mwt2.org:1094//pnfs/uchicago.edu/atlasdatadisk/rucio/data17_13TeV/fd/1a/DAOD_PHYS.23589107._001299.pool.root.1

gives LRZ first.

if I set the client to be at MWT2:

~ > export RUCIO_LATITUDE=41.7821
~ > export RUCIO_LONGITUDE=-87.6046

it still returns the same order.  

from python it does the same thing
{'latitude': None, 'ip': '2001:1458:d00:2f::100:2db', 'fqdn': 'lxplus734.cern.ch', 'longitude': None, 'site': 'CERN-PROD'}

Setting my lat and long to UChicago I see that it used it:

~ > export RUCIO_LATITUDE=41.7821
~ > export RUCIO_LONGITUDE=-87.6046

>>> from rucio.common.utils import detect_client_location
>>> detect_client_location()
{'latitude': 41.7821, 'ip': '2001:1458:d00:2f::100:2db', 'fqdn': 'lxplus734.cern.ch', 'longitude': -87.6046, 'site': 'CERN-PROD'}

Asking again for file replicas still gives me FZK as a first file replica...

When doing it from python the same happens:

from rucio.common.utils import detect_client_location from rucio.client.didclient import DIDClient from rucio.client.replicaclient import ReplicaClient

did_client = DIDClient()
replica_client = ReplicaClient()
detect_client_location()

scope='data17_13TeV'
ds='data17_13TeV.00339070.physics_Main.deriv.DAOD_PHYS.r10258_p3399_p4356_tid23589107_00'
fl=[]
count=0

res = did_client.list_files(scope, ds)
for f in res:
    fl.append({'scope':scope, 'name':f['name']})
    count+=1
    if count==10:
        break

reps=replica_client.list_replicas(dids=fl, schemes=['root']) for rep in reps:
    print(rep)

{u'adler32': u'4e9a36ae', u'name': u'DAOD_PHYS.23589107._000010.pool.root.1', u'rses': {u'FZK-LCG2_DATADISK': [u'root://atlasxrootd-kit.gridka.de:1094//pnfs/gridka.de/atlas/disk-only/atlasdatadisk/rucio/data17_13TeV/0d/5d/DAOD_PHYS.23589107._000010.pool.root.1'], u'MWT2_DATADISK': [u'root://fax.mwt2.org:1094//pnfs/uchicago.edu/atlasdatadisk/rucio/data17_13TeV/0d/5d/DAOD_PHYS.23589107._000010.pool.root.1']}, u'bytes': 1508349284, u'states': {u'FZK-LCG2_DATADISK': u'AVAILABLE', u'MWT2_DATADISK': u'AVAILABLE'}, u'pfns': {u'root://atlasxrootd-kit.gridka.de:1094//pnfs/gridka.de/atlas/disk-only/atlasdatadisk/rucio/data17_13TeV/0d/5d/DAOD_PHYS.23589107._000010.pool.root.1': {u'domain': u'wan', u'rse': u'FZK-LCG2_DATADISK', u'priority': 1, u'volatile': False, u'client_extract': False, u'type': u'DISK', u'rse_id': u'a9dd4f46935d46ffa0962a9150235a67'}, u'root://fax.mwt2.org:1094//pnfs/uchicago.edu/atlasdatadisk/rucio/data17_13TeV/0d/5d/DAOD_PHYS.23589107._000010.pool.root.1': {u'domain': u'wan', u'rse': u'MWT2_DATADISK', u'priority': 2, u'volatile': False, u'client_extract': False, u'type': u'DISK', u'rse_id': u'f4da89c7cef54133a45c22712dda45d5'}}, u'scope': u'data17_13TeV', u'md5': None}

so either is something wrong in calculation ,of  geoip distance or corrdinates  are not found correctly, or sorting is not done at all.  Or something completely different. I can't debug it  as I don't have access to these  k8s  pods to check what values they cache.  

I have checked that both MWT2 and LRZ-LMU ahave  reasonably good coordinates in maxmind database.

**Comment by bari12** [comment]
Just to add here, what we just discussed via mail

The issue is that the server only does the sorting if the client asks the replicas in METALINK format. Rucio download does that, rucio list-file-replicas does not.

See

https://github.com/rucio/rucio/blob/b6092bcd78f8cfac079e5b3cc25a92b4163960ed/lib/rucio/web/rest/flaskapi/v1/replicas.py#L362

and below line 397 where the sorting happens.

So if you do a list-file-replicas it never gets to the sorting step. It doesn't matter for download though. So for testing, request the metalink with --metalink to get an actual sorted result.

The issue why this was not backported to the JSON type returns is probably some sorting issue for dictionaries and the need of having the return format being stable. This can perhaps only be fixed in a v2 api (Would need to check though)

**Comment by ivukotic** [comment]
Unfortunately, this is not the only issue.
it does not work with metalink either.
`~ > rucio list-file-replicas data17_13TeV:DAOD_PHYS.23589107._001299.pool.root.1 --metalink --protocol root
<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
 <file name="DAOD_PHYS.23589107._001299.pool.root.1">
  <identity>data17_13TeV:DAOD_PHYS.23589107._001299.pool.root.1</identity>
  <hash type="adler32">1f07615c</hash>
  <size>1219706502</size>
  <glfn name="/atlas/rucio/data17_13TeV:DAOD_PHYS.23589107._001299.pool.root.1"></glfn>
  <url location="FZK-LCG2_DATADISK" domain="wan" priority="1" client_extract="false">root://atlasxrootd-kit.gridka.de:1094//pnfs/gridka.de/atlas/disk-only/atlasdatadisk/rucio/data17_13TeV/fd/1a/DAOD_PHYS.23589107._001299.pool.root.1</url>
  <url location="MWT2_DATADISK" domain="wan" priority="2" client_extract="false">root://fax.mwt2.org:1094//pnfs/uchicago.edu/atlasdatadisk/rucio/data17_13TeV/fd/1a/DAOD_PHYS.23589107._001299.pool.root.1</url>
 </file>
</metalink>
~ > export RUCIO_LATITUDE=41.7821
~ > export RUCIO_LONGITUDE=-87.6046
~ > rucio list-file-replicas data17_13TeV:DAOD_PHYS.23589107._001299.pool.root.1 --metalink --protocol root
<?xml version="1.0" encoding="UTF-8"?>
<metalink xmlns="urn:ietf:params:xml:ns:metalink">
 <file name="DAOD_PHYS.23589107._001299.pool.root.1">
  <identity>data17_13TeV:DAOD_PHYS.23589107._001299.pool.root.1</identity>
  <hash type="adler32">1f07615c</hash>
  <size>1219706502</size>
  <glfn name="/atlas/rucio/data17_13TeV:DAOD_PHYS.23589107._001299.pool.root.1"></glfn>
  <url location="FZK-LCG2_DATADISK" domain="wan" priority="1" client_extract="false">root://atlasxrootd-kit.gridka.de:1094//pnfs/gridka.de/atlas/disk-only/atlasdatadisk/rucio/data17_13TeV/fd/1a/DAOD_PHYS.23589107._001299.pool.root.1</url>
  <url location="MWT2_DATADISK" domain="wan" priority="2" client_extract="false">root://fax.mwt2.org:1094//pnfs/uchicago.edu/atlasdatadisk/rucio/data17_13TeV/fd/1a/DAOD_PHYS.23589107._001299.pool.root.1</url>
 </file>
</metalink>`

also we need this to be default independently how do we ask for the replicas, the first one should be the closest. 
two examples: 
a. pilot asks rucio for a file that is remote. It should get the closest replica.
b. a user asks for the file using gLFN (there are people still doing it). should get closest replica.

**Comment by bari12** [comment]
Then there is some other issue; This is a bit painful to debug, we should rule out that this is not based on a geoip issue on the source. Easiest way would be to also give LAT/LONG information on the RSE, and if available, not even do the geoip lookup for the source. (Would be more accurate anyway)

For the other cases I don't fully agree that it should always be ordered. For most queries the client does not care if it is ordered or not, it basically only makes sense for a subsequent download. What is not good though is that the client does not really know when the result is ordered and when not (That `--metalink` supposedly orders it, is not really clear) - there is also the `sort=None` option, I think we have to disentangle that. (But these are two different issues and can be done independently)

**Comment by bari12** [comment]
As discussed with @ivukotic today, this still doesn't work. Thanks for having a look @rcarpa 
@ivukotic if you have some additional info please provide.

**Comment by ivukotic** [comment]
from UK people:

> We tried setting RUCIO_LONGITUDE and RUCIO_LATITUDE in the worker node environment last week following this discussion, and for a few days it seemed that all was well, but now I see for the last 24h or so all the HC tests for UKI-LT2-RHUL_VP of type "Template: 1013 (functional) - AFT AthDerivation 21.2.33.0" have failed due to trying to stage the input data from Australia again.

pilot, 1099: Failed to stage-in file: data18_13TeV:data18_13TeV.00349263.physics_Main.merge.AOD.f937_m1972._lb0151._0001.1 from AUSTRALIA-ATLAS_DATADISK, Error on XrdCl:CopyProcess:Run(): [ERROR] Server responded with an error: [3011] Unable to open /root:/agh3.atlas.unimelb.edu.au:1094/dpm/atlas.unimelb.edu.au/ho

http://hammercloud.cern.ch/hc/app/atlas/siteoverview/?site=UKI-LT2-RHUL&startTime=2023-05-01&endTime=2023-05-31&templateType=isGolden

e.g.
https://bigpanda.cern.ch/jobs/?pandaid=5859381506,5859382316,5859383775&mode=nodrop
https://bigpanda.cern.ch/jobs/?pandaid=5858868325&mode=nodrop

Help please! Why is this happening and what can we do?

A little more information to help with debugging.
Taking this example:
https://aipanda024.cern.ch/condor_logs_2/23-05-29_05/grid.28106673.0.out

I see (presumably from a printenv)
RUCIO_LATITUDE=-0.566382
RUCIO_LONGITUDE=51.424579
but later
2023-05-29 05:34:59,972 | INFO     | calling rucio.list_replicas() with query={'schemes': ['root'], 'dids': [{'scope': 'data18_13TeV', 'name': 'data18_13TeV.00349263.physics_Main.merge.AOD.f937_m1972._lb0159._0001.1'}], 'sort': 'geoip', 'client_location': {'ip': '10.141.0.54', 'ip6': '::', 'fqdn': 'node054.cm.cluster', 'site': 'UKI-LT2-RHUL'}, 'rse_expression': 'istape=False\\type=SPECIAL', 'signature_lifetime': 86400}
According to the documention
https://rucio.cern.ch/documentation/client_api/replicaclient#list_replicas
the client location could include the lattitude and longitude, but it is not passed through this call apparently - is that the problem?

**Comment by dsgeorge** [comment]
I have noticed that the PFNs currently come back sorted alphabetically by PFN. This is why agh3.atlas.unimelb.edu.au is first and xrootd01.esc.qmul.ac.uk is last in the new example above. Hopefully this is a clue.

https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/flaskapi/v1/replicas.py#L209 seems to ensure that the location for sorting is *only* the client ip address, as the other keys in the location dict are set to None, with latitude and longitude omitted completely. There needs to be a way to override the use of the client_ip when it is known to be useless for geoip lookups, for example a private network address.

**Comment by rcarpa** [comment]
@dsgeorge , the code which you link is for the GET request, while the rucio client uses POST when list_replicas() is used and will go to this code: https://github.com/rucio/rucio/blob/827373aa555918ffa3035010c4424ee6295fee29/lib/rucio/web/rest/flaskapi/v1/replicas.py#L639

@ivukotic, it seems to me that you are using directly the python client. The logic converting 
```
RUCIO_LATITUDE=-0.566382
RUCIO_LONGITUDE=51.424579
```
env variables into arguments to list_replicas is never executed. Whoever is calling rucio.list_replicas() should set `'client_location': {'longitude': ..., 'latitude': ...}` in the parameters when calling it . 

It probably comes from this https://github.com/PanDAWMS/pilot/blob/a0cb4710b1bf7cb2eb6b606d32018666f3860d84/movers/mover.py#L268

**Comment by dsgeorge** [comment]
Thanks @rcarpa. So we need to get the client code to try calling with the latitude and longitude as part of the location.

**Comment by ivukotic** [comment]
> I have noticed that the PFNs currently come back sorted alphabetically by PFN. This is why agh3.atlas.unimelb.edu.au is first and xrootd01.esc.qmul.ac.uk is last in the new example above. Hopefully this is a clue.
> 
> https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/flaskapi/v1/replicas.py#L209 seems to ensure that the location for sorting is _only_ the client ip address, as the other keys in the location dict are set to None, with latitude and longitude omitted completely. There needs to be a way to override the use of the client_ip when it is known to be useless for geoip lookups, for example a private network address.

I don't fully understand the code here... For example why are we sorting after ever file: https://github.com/rucio/rucio/blob/master/lib/rucio/web/rest/flaskapi/v1/replicas.py#L233 ?
 
If location is given it has to be used. And if given it has to have priority over other location methods (GeoIP lookup, site, ...).

**Comment by rcarpa** [comment]
@ivukotic , you continue to look at the incorrect part of rucio. The code which you point is not executed for list_replicas. We know it is confusing and there is a ticket to fix this inconsistency which we have for historical reasons (https://github.com/rucio/rucio/issues/5516).
As I stated in my previous message, the problem in this particular case is pilot not sending the location data; it's not rucio ignoring it. From your previous message : 
`'client_location': {'ip': '10.141.0.54', 'ip6': '::', 'fqdn': 'node054.cm.cluster', 'site': 'UKI-LT2-RHUL'},` 
You can see that neither latitude nor longitude is given by pilot to rucio.

**Comment by ivukotic** [comment]
> @dsgeorge , the code which you link is for the GET request, while the rucio client uses POST when list_replicas() is used and will go to this code:
> 
> https://github.com/rucio/rucio/blob/827373aa555918ffa3035010c4424ee6295fee29/lib/rucio/web/rest/flaskapi/v1/replicas.py#L639
> 
> @ivukotic, it seems to me that you are using directly the python client. The logic converting
> 
> ```
> RUCIO_LATITUDE=-0.566382
> RUCIO_LONGITUDE=51.424579
> ```
> 
> env variables into arguments to list_replicas is never executed. Whoever is calling rucio.list_replicas() should set `'client_location': {'longitude': ..., 'latitude': ...}` in the parameters when calling it .
> 
> It probably comes from this https://github.com/PanDAWMS/pilot/blob/a0cb4710b1bf7cb2eb6b606d32018666f3860d84/movers/mover.py#L268


While I can do location by myself in pilot mover, I kind of expected this to be done by rucio client code. Pilot is not the only thing that will need replicas sorted by location?

**Comment by rcarpa** [comment]
It is done in rucio on client side when called from the CLI:
https://github.com/rucio/rucio/blob/85bb8a9e93f9515b5868e96349a59984eb63a110/bin/rucio#L383

https://github.com/rucio/rucio/blob/85bb8a9e93f9515b5868e96349a59984eb63a110/lib/rucio/common/utils.py#L912

**Comment by ivukotic** [comment]
ah ok... I have just asked Paul to make corresponding changes to the pilot3. 
I will now create another test code to check everything works fine.

**Comment by ivukotic** [comment]
I checked and found that the returned order is now correct.
Will close this issues.
Thanks,
Ilija
