### ISSUE TITLE
to speed up polling of FTS transfer status at file level, not to wait for the FTS job to end

### ISSUE THREAD

**Issue by xzhao87** [rucio/rucio#4841]
Motivation
----------
Right now Rucio polls from FTS on transfer status of individual files, only when the FTS job reaches a final state. 
Since one FTS job can have O(100) files in it, this way the status update of individual files to upstream clients is 
slowed down. One such use case is in Data Carousel, ProdSys2 relies on Rucio to tell how many files are in "active"
state, the delay causes the number of real staging requests at the site level is sometimes much less than the number
shown at ProdSys2, making it hard to throttle the site staging profile. 

Modification
------------

The desired behavior is for Rucio to poll status of individual files regardless of the FTS job state, so to speed 
up the status updates of ready files for upstream processing.

**Comment by rcarpa** [comment]
Looked into this one today a bit. Feels like working in a mine field. A file in a `failed` state doesn't necessarily mean that the transfer must be transitioned to a failed state (warm hello from multi-source transfers); and there is the `unused` state, which has a different meaning for multi-source; and multi-hop transfers; I think I'll manage to find a reasonable way to make the state transition, but for now it only gave me a headache.

**Comment by rcarpa** [comment]
We want to also handle files one by one for failures. So re-open the issue.
