### ISSUE TITLE
Still problems with / special character?

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#485]
Motivation
----------
It seems like things are wrong, but in the opposite direction. :-)
```
[root@5a7c89cdab88 /]# rucio add-dataset user.ewv:MyDataset1 
Added user.ewv:MyDataset1
[root@5a7c89cdab88 /]# rucio list-dids user.ewv:\*
+----------------------+--------------+
| SCOPE:NAME           | [DID TYPE]   |
|----------------------+--------------|
| user.ewv:/MyDataset1 | DATASET      |
+----------------------+--------------+
```
I'm using the latest master for the client and whatever is installed at U Chicago.

Modification
------------

Expected behavior
-----------------
/ should not be prepended to the dataset name in this case.

**Comment by ericvaandering** [comment]
However, this does not add a second leading slash when supplied with one /. Considering that all CMS datasets are /primary/secondary/Tier this won't impact CMS.

**Comment by vingar** [comment]
yes, I knew this but this was the best option I quickly managed to come with to satisfy the CMS naming convention. The proper behavior here would have been to reject the name as all CMS names start with a slash.

**Comment by ericvaandering** [comment]
Which my python API did for something that did not start with / but the CLI did not for some reason.

Anyhow, this is low/no priority for CMS, but may be useful to keep around.

**Comment by ericvaandering** [comment]
We have not seen problems with slashes in a long time
