### ISSUE TITLE
Not able to execute .sh file: /bin/bash^M: bad interpreter

### ISSUE THREAD

**Issue by SimoneGasperini** [rucio/rucio#4869]
I followed the [instructions](https://github.com/rucio/rucio/tree/master/etc/docker/dev) to set up the Docker containerised version of the Rucio development environment on Windows 10, Version 21H1 (OS Build 19043.1237): all the containers have been successfully created and run by using `docker-compose` (environment including monitoring).
When I try to run the tests in the Rucio environment by `tools/run_tests_docker.sh -ir` I get the following error message:

`bash: tools/run_tests_docker.sh: /bin/bash^M: bad interpreter: No such file or directory`

I think the problem is that my .sh file has DOS/Windows style line endings (CR LF), but on the containerised Unix-like system only the LF control character is used as line break. The additional CR control character is shown encoded as ^M. I can also see it when I run `cat -A tools/run_tests_docker.sh`.
Actually, the same issue exists for all .sh files as well as all text files in general.

My workaround was to use the [dos2unix](https://waterlan.home.xs4all.nl/dos2unix.html) text file format converter over all the text files in the Rucio repository. This seems to work but it's not a good solution at all beacuse it requires to edit a large part of the source .py files in the repo as well. Can you fix this or suggest something smarter?

**Comment by mlassnig** [comment]
When you git clone the Rucio repository make sure that git knows how to deal with line endings. Windows git automatically converts to Windows file endings. Just delete the cloned repo, configure git like this:

`git config --global core.autocrlf input`

then `git clone` again, and the files will be with proper Linux line endings.

**Comment by SimoneGasperini** [comment]
Thank you very much @mlassnig... It worked! Sorry for the elementary question: didn't know git was able to deal with it.

**Comment by SimoneGasperini** [comment]
Thank you very much @mlassnig... It worked! Sorry for the elementary question: didn't know git was able to handle it.

**Comment by mlassnig** [comment]
No worries! :-)
