### ISSUE TITLE
Requests to unavailable RSEs

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#4896]
In https://github.com/rucio/rucio/blob/631e5d5daa81ab86f310fd046350e8212b91e1eb/lib/rucio/core/transfer.py#L1675 requests are filtered to ensure the destination is available for writing. On the other hand, rules can be made with (and since #4152, repaired with) `ignore_availability` flag. I would propose to remove this filter.

**Comment by bari12** [comment]
I think this needs a bit of discussion. What worries me with that change is that sites have no option then to stop submission to their site. There is just no other switch, other than to remove the protocols to give rucio no chance to submit.

The `ignore_availability` flag for me is more at the time you execute the `add_rule`. At this point we check availability, and give an error if not possible, unless you have `ignore_availability` set. But this doesn't mean (to me) that also the submission should be done with ignored availability.

**Comment by rcarpa** [comment]
What is the meaning of an unavailable rse if we can submit transfers to/from it ? O_O

**Comment by nsmith-** [comment]
So indeed this a bit of a contrived situation, but we have a "loadtest" that routinely makes transfers to test site availability, and the results of that are used to update the actual RSE availability. So if a site is unavailable the loadtests cannot run and (possibly) succeed to bring the site back into available state. Obviously this is a niche use, and for other reasons we already run a separate conveyor for these functional tests.  What if we add a `--ignore-availability` to the conveyor daemon command to fill this role?

**Comment by bari12** [comment]
I think a `--ignore-availability` at the conveyor-submitter level is doable. @rcarpa ?

**Comment by rcarpa** [comment]
I think it would be easy to do. To be checked in the code...
