### ISSUE TITLE
rucio set-metadata returns status code 0 for non-existing DID

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#493]
Motivation
----------
rucio set-metadata returns status code 0 for non-existing DID, e.g. :
rucio set-metadata --did mc16_5TeV:non_existing_dataset --key transient --value 0
echo $?
0

Modification
------------
Should return non 0 or an error message

**Comment by cserf** [comment]
Actually this is a core issue. For some metadata, it checks that the metadata was updated :+1: 
```python
        if not rowcount:
            raise exception.UnsupportedOperation('%(key)s for %(scope)s:%(name)s cannot be updated' % locals())
```

But for others no.

**Comment by vingar** [comment]
I'm afraid that if a proper exception is raised now, It'll break certain third party programs... 

The core method can return rowcount to the clients and the client can use this value to give the right status code. Or check the presence of the dataset..

**Comment by mlassnig** [comment]
The core change will be intercepted by the web/rest layer, and eventually the client? It could be properly handled there and make the client not except out into userspace.
