### ISSUE TITLE
SRM to HTTPS optional compatibility

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#4944]
Motivation
----------
https://github.com/rucio/rucio/blob/882b662a24c75d515080606be635959566b17f14/lib/rucio/common/constants.py#L42
Defines a scheme_map between protocol compatibility in Rucio. We need an additional compatibility between `srm` and `https` (and vice-versa) which is only optionally (based on a config parameter) activated.

Modification
------------
Check if an option
```
[transfers]
srm_https_compatibility = True
```
is set and add it to the scheme_map.

**Comment by joeldierkes** [comment]
```diff
-srm_http_compatibility = True
+srm_https_compatibility = True
```
?
