### ISSUE TITLE
REST interfaces for request_history

### ISSUE THREAD

**Issue by robbarnsley** [rucio/rucio#4949]
Have extended https://github.com/rucio/rucio/issues/1786 to allow queries against the request_history table. Needed this to get throughput from fts for completed transfers. 

Can I get this merged?

**Comment by bari12** [comment]
Not entirely sure I get this, you want to add a REST interface for request_history?

The problem with all history tables is, that they are not indexed, so querying them is potentially quite expensive. You need this for monitoring purposes?

**Comment by robbarnsley** [comment]
I needed to match a requested transfer through rucio to an fts job id in order to get the throughput recorded by fts for the transfer. Similar to https://github.com/rucio/rucio/issues/1786, but I noticed that the (completed) requests I was looking for were in the _history table.

What I have works, but it's quite possible, if not probable, that there's another (better) way of doing this.

**Comment by robbarnsley** [comment]
Hi @bari12,

Have you had any further thoughts about this? Is there a better way to achieve the above?

**Comment by bari12** [comment]
Not really, I think adding a REST interface is fine, but if you want to reasonably query this, you will have to add some indices to the table. - We are getting very much into VO specific here though, not everyone will want to pay for the extra volume that index takes. Also it depends a bit on the retention of the request_history in general.

**Comment by robbarnsley** [comment]
Understood. I'm currently only using this functionality to evaluate throughputs for transfers initiated by our (low activity) prototype instance so there aren't many rows.
