### ISSUE TITLE
bring_online incorrectly set in multihops with tape source

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#4954]
Motivation
----------
The job parameters in fts are constructed from last hop (which is the initial transfer that triggered the multihop). This behavior was changed in https://github.com/rucio/rucio/pull/4837 . Until then, the job parameters where built from first hop because it was the first one inserted into the "transfers" dictionary and so the first one analyzed.

This results in multihop jobs being submitted for transfers from tape without bring_online set

**Comment by bari12** [comment]
Backport 1.26.7.post1
