### ISSUE TITLE
Make dirac server plugin multi-VO capable

### ISSUE THREAD

**Issue by martynia** [rucio/rucio#4961]
Motivation
----------
The current version of Dirac-Rucio interface on the server side does not work in a multi-VO Rucio environment

Modification
------------
We need to enhance all 3 levels of the code (`flaskapi/v1/dirac.py`, `core/dirac.py`, `api/dirac.py`) to handle VO specific requests.

To achieve this we need to get the VO name from `requests` headers and pass in down the invocation line. Multi-VO rucio makes a VO-aware decision on the API level, not in the core. This is unfortunately not true in the current Rucio-interface.

Let's look at this step-by-step. The first VO-dependent call can be found in api/dirac.py here:

https://github.com/rucio/rucio/blob/a9ea3b359d221e157830cb1961d4a2488ada32f8/lib/rucio/api/dirac.py#L52

The change is simple, adding the `vo` parameter to the call solves the problem, but not for very long ...

Another problematic call is here:

https://github.com/rucio/rucio/blob/92474868cec7d64b83b46b451ecdc4a294ef2711/lib/rucio/core/dirac.py#L68

Scopes are VO-dependent, so one could import an API counterpart of this function, rather than the core one and get the scopes for a VO we want. This is not very elegant, since the core should not call any API functions, it should rather be another way around. One could copy the filtering code from the  API, this would be code repetition. Not ideal either.

After having done any of these modifications we get a bit further:

`[Wed Oct 27 16:36:05.410228 2021] [wsgi:error] [pid 30268] [remote 146.179.232.106:34688]   File "/opt/rucio/rucio/lib/rucio/core/did.py", line 134, in add_did

[Wed Oct 27 16:36:05.410269 2021] [wsgi:error] [pid 30268] [remote 146.179.232.106:34688] rucio.common.exception.ScopeNotFound: Scope does not exist.
[Wed Oct 27 16:36:05.410276 2021] [wsgi:error] [pid 30268] [remote 146.179.232.106:34688] Details: Scope not found!
[Wed Oct 27 16:36:05.410291 2021] [wsgi:error] [pid 30268] [remote 146.179.232.106:34688]`

This is expected (_scope not found_), because once in the core we try to get dids and replicas ignoring the VO, i.e. using the core versions of the methods, rather that their API counterparts.

It looks like the only feasible (and simple) solution would be to replace `api/dirac.py` and replace is with a modified version of `core/dirac.py` so it uses VO-aware API calls. It is a question to the authors of the code if this would still maintain a single transaction handling as required.

**Comment by bari12** [comment]
Hi @martynia I was wondering who is working on this? Is it you or somebody from the multivo team?

**Comment by martynia** [comment]
I'm working on it ;-). Both on the Dirac client side (almost ready) and the rucio server side.

I have added a VO parameter in all required places to get internal scopes and internal accounts right.

The issue I'm currently seeing with the core version of `dirac.py` is that the top level container is not recognised. To follow Belle II aproach, the DIDs have to contain slashes. After a discussion with @cserf  I created a top level container in the "common" scope gridpp (the DIDs below would be in their user.x.y scopes). I created a container with a command:

`rucio add-container gridpp:/gridpp`

but the container is created with a name w/o a leading slash (we see this in the DB). Also `rucio list-metadata` lists its name w/o a slash. The slash is silently ignored.  We allow slashes in the schema and the issue described here 

https://github.com/rucio/rucio/commit/1311a7511a470fc93e808c45129061e94c704379

has been also addressed. The problem persists. What could be a cause of this ?

Any help will be greatly appreciated.
Janusz

**Comment by bari12** [comment]
@martynia I think the changes you are outlining are correct. Just be careful that in many cases the VO information can be encoded into the InternalScope and InternalAccount, Tim should also be able to help there.

For the `/` this should mostly be done via the schema, but as discussed, you ruled that already out. Another thing could be the `AllowEncodedSlashes on` directive in httpd. @cserf do you have any idea?

**Comment by martynia** [comment]
We have the `AllowEncodedSlashes on` flag in place in our server at Imperial. Tim has tested the slash issue on the server at RAL, so I believe they have that flag set to on as well.

**Comment by martynia** [comment]
Hi,
Following a discussion during last Rucio meeting I checked the value of scope name regex and it is: `SCOPE_NAME_REGEXP = '/([^/]*)(?=/)(.*)’`

So before changing that to accept just one slash I did (the gridpp scope has been created beforehand):
```
rucio add-container gridpp:/gridpp/test
2021-12-10 14:41:30,692	ERROR	Provided object does not match schema.
Details: Problem validating did : 'gridpp/gridpp' does not match '^[a-zA-Z_\\-.0-9]{1,25}$'

Failed validating 'pattern' in schema['properties']['scope']:
    {'description': 'Scope name',
     'pattern': '^[a-zA-Z_\\-.0-9]{1,25}$',
     'type': 'string'}

On instance['scope']:
    'gridpp/gridpp'
 
```

What is going on here ? Why is it trying to match `gridpp/gridpp` to that pattern ? The scope is clearly `gridpp:`, and the command above follows what is given by `rucio add-container -h`.

Furthermore, when using the API:

```
>>> from rucio.client import Client
>>> rucio_client = Client()
>>> rucio_client.ping()
{'version': '1.26.5'}
>>> res = rucio_client.add_container('gridpp', '/gridpp/test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hep/martynia/Rucio/rucio_ral/lib/python3.6/site-packages/rucio/client/didclient.py", line 211, in add_container
    return self.add_did(scope=scope, name=name, type='CONTAINER', statuses=statuses, meta=meta, rules=rules, lifetime=lifetime)
  File "/home/hep/martynia/Rucio/rucio_ral/lib/python3.6/site-packages/rucio/client/didclient.py", line 160, in add_did
    raise exc_cls(exc_msg)
rucio.common.exception.InvalidObject: Provided object does not match schema.
Details: Problem validating did : 'gridpp/gridpp' does not match '^[a-zA-Z_\\-.0-9]{1,25}$'

Failed validating 'pattern' in schema['properties']['scope']:
    {'description': 'Scope name',
     'pattern': '^[a-zA-Z_\\-.0-9]{1,25}$',
     'type': 'string'}

On instance['scope']:
    'gridpp/gridpp'
```

I must have misunderstood something obvious here. The arguments of `add_container` are scope  name and did name, aren't they ?

I might be barking at a wrong tree, and the problem with the slashes might be actually something else.

Any help will be greatly appreciated.

   thanks , JM

**Comment by martynia** [comment]
Hi again, Cedric pointed out that a function:
[https://github.com/rucio/rucio/blob/bf4c1e18e15ea5f84d49dfa7e662b504449fbe9c/lib/rucio/web/rest/flaskapi/v1/common.py#L153
](https://github.com/rucio/rucio/blob/bf4c1e18e15ea5f84d49dfa7e662b504449fbe9c/lib/rucio/web/rest/flaskapi/v1/common.py#L153)

incorrectly unpacks scope and name. To bypass this one can use `add_dids` but this clearly bypasses a schema and a VO dependence: Here is the proof:

```
>>> dids = [{'scope': 'gridpp', 'name': '/gridpp/test', 'type': 'CONTAINER’}]
>>> rucio_client.add_dids(dids)
True
>>> for item in rucio_client.list_dids('gridpp',{}):
...  print(item)
... 
gridpp
/gridpp/test

```
The first one is the ill-created no-slashed gridpp in the past with the UI (should be /gridpp). The second one is one with 2 slashes to overcome a possible schema restriction, which requires 2 / at the moment.

To see if the schema is actually checked:

```
>>> dids0=[{'scope': 'gridpp', 'name': '/gridpp', 'type': 'CONTAINER'}]
>>> rucio_client.add_dids(dids0)
True
>>> for item in rucio_client.list_dids('gridpp',{}):
...  print(item)
... 
gridpp
/gridpp
/gridpp/test
```

The function mentioned at the top would need to be modified, I believe to use scope algorithms used elsewhere.

cheers, JM

**Comment by bari12** [comment]
There are multiple mentions in the schema file
- `SCOPE_NAME_REGEXP` is functionally used to understand REST endpoint routes, but this looks correct.
- `SCOPE` will be used when you create a did
- `NAME` will be used when you create a did
So all these need to be compatible to your values in the schema. Please check these.

**Comment by martynia** [comment]
Hi,
The `scope_name` in the function turns out to have a colon replaced with a slash. So, for a basic Dirac scope extraction algorithm it might look like this:

`gridpp/gridpp/test`

So we have to split on the first slash and include it in the second group, so the top container name starts with a slash:

```python
>>> SCOPE_NAME_REGEXP = '/([^/]*)(/.*)'
>>> scope_name='gridpp/gridpp/test'
>>> scope_name = re.match(SCOPE_NAME_REGEXP, '/' + scope_name)
>>> print(scope_name.group(1, 2))
('gridpp', '/gridpp/test')
```

Using the UI:

```(rucio_ral) -bash-4.2$ rucio add-container gridpp:/gridpp/test
Added gridpp:/gridpp/test
(rucio_ral) -bash-4.2$ rucio list-dids gridpp:*
+----------------------+--------------+
| SCOPE:NAME           | [DID TYPE]   |
|----------------------+--------------|
| gridpp:/gridpp/test  | CONTAINER    |
+----------------------+--------------+
```

To summarise, the problem was entirely caused by an incorrect regex used. I'm closing the issue.

**Comment by thysk** [comment]
Is this issue still wanting to be open?
As far as I can tell it has been merged and re-opened after it was merged
@martynia?
