### ISSUE TITLE
Remove heartbeats when a service stops

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4988]
Motivation
----------

Kubernetes makes the spinning up or tearing down of servers and/or daemons much more frequent than running the same services on regular nodes. Leftover heartbeats can potentially cause partition starvation.

Modification
------------

Have each service clean up its heartbeats as part of the graceful stop.

**Comment by rcarpa** [comment]
This is already the case: heartbeats are cleaned up. Maybe something to change on kube side to wait longer at pod termination before issuing a kill, or maybe the daemons don't handle the gracefull stop correctly

**Comment by joeldierkes** [comment]
So what would be the next action here? As mentioned by @rcarpa the heartbeat is already cleaned up after a graceful stop.

**Comment by rcarpa** [comment]
- see if kubernetes config is too aggressive and performs a SIGKILL too fast. increase the wait time and see if it helps
- if containers never exit correctly even with increased wait time on kube side, modify the code to correctly exit when a SIGTERM is received

**Comment by rcarpa** [comment]
but first verify if this behavior is even disponible. According to a very quick search, we may have to upgrade kubernetes first : https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/
