### ISSUE TITLE
Deletion timeout does not work on GridFTP

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4994]
Motivation
----------

The newly-introduced deletion timeout does not appear to work on GridFTP.

https://github.com/rucio/rucio/blob/6a853eb36b25cbbd2b49159def9d6db93dd16422/lib/rucio/rse/protocols/gfal.py#L241

Modification
------------

Replace `GSIFTP PLUGIN` with `GRIDFTP PLUGIN`.

**Comment by bari12** [comment]
Backport 1.26.10
