### ISSUE TITLE
Allow overriding all possible options in move_rule

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#4995]
Motivation
----------

With #4855, it is now possible to override the activity and source replica expression when moving a rule. Client-side this looks great, but in the core the implementation could be improved (note that it’s still not possible to remove the source replica expression, which was one of the original intentions).

I would argue that there’s no need to have a fixed set of parameters. There could be a valid reason to override any of them (at the core for the needs of operations; there’s no need to expose it through the CLI yet).

Modification
------------

Could something like the following work?

```python
@transactional_session
def move_rule(rule_id: str, rse_expression: str, override: Dict[str, Any] = {}, session: Session = None):
    rule = session.query(models.ReplicationRule).filter_by(id=rule_id).one()

    …

    options = {dids=[{'scope': rule.scope, 'name': rule.name}],
               account=rule.account,
               …
    }

    for key in override:
        if key in ['dids']:
            raise Exception(f'Not allowed to override option {key!r}')
        elif key not in options:
            raise Exception(f'Non-valid override option {key!r}')
        else:
            options[key] = override[key]

    new_rule_id = add_rule(**options)

    …
```

**Comment by bari12** [comment]
Yes, that should be fine (similar to `update_rule`)
