### ISSUE TITLE
Summary page for used quotas for users

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#50]
_Migrated from JIRA [RUCIO-2677](https://its.cern.ch/jira/browse/RUCIO-2677)_

**Comment by bari12** [comment]
I think this just needs to be activated in the menu.

**Comment by bari12** [comment]
@hahahannes can you please have a look on this.

**Comment by hahahannes** [comment]
It is indeed already [there](https://github.com/rucio/rucio/blob/8665bcca2b187e154db3c2dc393f6d1cf0db4805/lib/rucio/web/ui/static/base.js#L148), but it seems to be visible only for admins.

**Comment by bari12** [comment]
This page is a bit different. It shows the the usage of all the users on an RSE. I think the initial idea of this page was a page where a user sees how much quota he is using on all RSEs.

**Comment by hahahannes** [comment]
Okay, then I will create a new page, because I couldn't find one.

**Comment by hahahannes** [comment]
I could find a page under the link /account_rse_usage which has no links directing to it, yet. Also it shows a search field. Should it be removed so that automatically the user account gets choosen or is this page relevant for admins?
