### ISSUE TITLE
.add_replication_rule allows for 0 copies as input

### ISSUE THREAD

**Issue by ygrange** [rucio/rucio#5035]
Motivation
----------
Today I was somewhat confused about replication rules because of something that happened in the backend for the ESCAPE rucio instance. Now this may have been due to something unrelated, but while discussing this with @bari12, he concluded that what I tried should probably not be possible. In My code I had lines like:
```
rul_cli = RuleClient()
rul_cli.add_replication_rule(dids=[{'scope':scope,'name':data_filename}], copies=0, rse_expression=rse, lifetime=lifetime)
```
Asking for there to be 0 copies of an existing data set seems not sensible. I think this should raise an exception somewhere. Also the command line client is totally ok with me asking it for 0 replicas of a file:

```
[grange@145 DAC21]$ rucio add-rule LOFAR_ASTRON_GRANGE:L31415_SB000.uv.tar 0 'CNAF-STORM'
c4114a72373f4e5cb7c550eb2a121044
```

**Comment by joeldierkes** [comment]
@bari12 Just for my understanding, are there any places where 0 copies should be allowed (like daemons, etc...)? If no, I would include it in the `core`, if yes, I would include it in the `api`...

**Comment by bari12** [comment]
No, this should conceptually not be allowed anywhere :-)
