### ISSUE TITLE
`common/test_rucio_server` file path bug

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5037]
Motivation
----------
https://github.com/rucio/rucio/blob/0e475d3edf88a466bb402dc2e7047b8496108c52/lib/rucio/common/test_rucio_server.py#L151
The dids added to the array for cleanup after the tests run are not constructed correctly. The entire path of the tmp files is added to construct the dids, while only the filename should be used.

Modification
------------
Don't use the full path of the testfiles.

**Comment by maany** [comment]
Yo @joeldierkes, nice find! Just a suggestion as I think this could be a good opportunity to switch this test to utilize the `FileFactory` and 'DID Factory' fixtures that @rcarpa introduced some time ago.

https://github.com/rucio/rucio/blob/b820877f58c975740d9ea1fd448c3dcf2eb013cf/lib/rucio/tests/temp_factories.py#L322

Usage example:
https://github.com/rucio/rucio/blob/b820877f58c975740d9ea1fd448c3dcf2eb013cf/lib/rucio/tests/test_upload.py#L68-L69

https://github.com/rucio/rucio/blob/b820877f58c975740d9ea1fd448c3dcf2eb013cf/lib/rucio/tests/test_tpc.py#L79

The FileFactory should take care of generating and cleaning up the temp files locally and the DID factory would clean up the server. ;)

**Comment by joeldierkes** [comment]
Yeah I will refactor more things than described in the `Modification` section, thanks for the info. :P

**Comment by rcarpa** [comment]
You cannot use there fixtures in this test. They are python3-only and these tests calling "bin/rucio" are executed in python2 env too.

**Comment by joeldierkes** [comment]
lol nvm then

**Comment by bari12** [comment]
Backport 1.26.12
