### ISSUE TITLE
Common: Combine `logging.py` and `utils.setup_logger`

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5051]
Motivation
----------
There are two logging factory functions right now:
https://github.com/rucio/rucio/blob/5d428e018fc1c81870ca42c34c382b08aef2335f/lib/rucio/common/utils.py#L1472
https://github.com/rucio/rucio/blob/47e0eb1c45ed46de611b59344e481152f2fe58ff/lib/rucio/common/logging.py#L29
Both differ in functionality, however there shouldn't be any need for two of them.

Modification
------------
- [ ] Unify the instantiation of the loggers in `logging.py`
- [ ] Use the following chain of rules to configure the logger (if `--verbose` is set, use `DEBUG` as log level):
    1. Use the environment variable `RUCIO_LOGGING_LEVEL` and `RUCIO_LOGGING_FORMAT`
    1. If (i.) is not provided, use the configuration `[common] loglevel = ...` and `[common] logformat = ...`
    1. If (i.) and (ii.) is not provided, use some default settings
- [ ] Use colors in the client logger, don't use it on the server
- [ ] Add line numbers to the debug output (this can help the developers to debug)
- [ ] Store the output of the clients logs in a Log file

**Comment by maany** [comment]
@joeldierkes any updates on this? Thanks :)
