### ISSUE TITLE
declaring replica as suspicious in finisher removes sources from DB

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5059]
Motivation
----------

As a result of this line executed under certain conditions in finisher for suspicious replicas: 
https://github.com/rucio/rucio/blob/289ce559ddfc9039d0fbab5af98544abb4256046/lib/rucio/core/replica.py#L347
and
https://github.com/rucio/rucio/blob/289ce559ddfc9039d0fbab5af98544abb4256046/lib/rucio/core/replica.py#L378

the sources are removed from the database. As a result, a suspicious best source for a request will never have it's ranking decreased. 
That source will be retried at each submission, even if other sources exist.

**Comment by bari12** [comment]
Ok, that would be true for the current retry cycle but in the next one the replica would presumably be processed by the necromancer. I wonder though if we really need to remove it as a source here?
@cserf ?

**Comment by rcarpa** [comment]
Those replicas are suspicious, not yet marked as bad. Will the necromancer act on them? 
I don't see any reason to remove the sources. Sources are only there to keep track of the state between retries. If there are no sources in the database table, submitter just assumes default values for all attributes. Removing the sources doesn't tell submitter to ignore the request (that's the reason @cserf  provided for removing sources)

**Comment by bari12** [comment]
We should probably leave it when declared suspicious, but even if it is already confirmed bad and declared, we should probably leave it. The file might already be in flight and then you have the adverse effect and it is repeatedly retried.
But we need to check the workflows both transfers & necromancer here.

**Comment by dchristidis** [comment]
I now think that there *is* a need to remove the source when the file is being declared as `BAD`.

https://github.com/rucio/rucio/blob/5ed6e6b78196afbb5650e217a3b28687e492aa2a/lib/rucio/core/replica.py#L2038

**Comment by rcarpa** [comment]
The sources will be removed when the transfer is successful (from another source) or after 3 retries. Removing sources here wouldn't help much, because submitter will add sources again at next iteration. I still think we shouldn't remove sources here.

**Comment by dchristidis** [comment]
While the source exists, the Reaper can’t delete the replica. We can’t rely on the sources being removed at some point in the future (which can take a very long time). I am fairly certain that this will be a problem.

Picture the following scenario (it happened yesterday): we’re decommissioning a site, all locks are deleted, but the replicas can’t because they are used in some multi-source transfers. I declared the replicas as lost, and this allowed us to proceed. If not, I would have had to cancel the requests or wait a significant amount of time (the jobs had been in submitted state for more than a day already).

In addition, the replica state will be `BAD`, so I believe the Submitter should not add them again.

**Comment by rcarpa** [comment]
Maybe cancel the transfers automatically then? at first glance, seems like a better solution

**Comment by rcarpa** [comment]
Wait, we are speaking about code in the finisher anyway. The transfer cannot be in a submitted state here. So... I don't buy the argument :)

**Comment by rcarpa** [comment]
The code in the reaper should probably be adapted to only prevent deletion if the source is in a "is_using"==True state.

**Comment by dchristidis** [comment]
Of course, you’re the expert. But, if a regression appears out of this, I do get the right to point to this and say ‘I told you so.’ :stuck_out_tongue:

**Comment by bari12** [comment]
Having the reaper delete the replica (plus source) if `is_using` is not `True` should work. For the ones which are already in-flight (`is_using` = `True`) they should only be in that state for a limited amount of time.
