### ISSUE TITLE
Remove/Replace obsolete links from CLI commands in help messages

### ISSUE THREAD

**Issue by rizart** [rucio/rucio#5062]
Motivation
----------
The following commands:
- rucio `list-file-replicas` [`--expression` `--rses`]
- rucio `list-rses` [`--expression` `--rses`]
- rucio `list-suspicious-replicas` [`--expression`]

display advise to follow http://rucio.cern.ch/client_tutorial.html#adding-rules-for-replication in order to get help about these options. That link does not point to any content at the moment.

Modification
------------
Remove obsolete link from help message and replace with useful information.

**Comment by Carlosbogo** [comment]
Hi, I would like to work on this, but it's the first time I contribute to this project. Could you give me some pointers on where can I find the 'useful information' that should replace the obsolete links?

**Comment by rizart** [comment]
Hello and welcome,

I just realised that `--expression` should have been deprecated by 1.27, but it's still in that release.
For the `--rses` ones I think this http://rucio.cern.ch/documentation/rse_expressions/ link should do.
Maybe just change them both for now and then the `--expression` option will be removed at some point anyway.
@bari12 what do you think?

**Comment by bari12** [comment]
Yes, that sounds good.
@Carlosbogo sure, please go ahead, thanks a lot.

**Comment by Carlosbogo** [comment]
Sorry for the delay, I have been searching through the repository to see where are the `--expression` or `--rses` you mention, but I've been unable to do so. Should I search for something else instead of those exact names?

**Comment by joeldierkes** [comment]
The main entry point for the `rucio` CLI is the `bin/rucio` script. Every command line argument gets parsed there.

These are the discussed arguments:
https://github.com/rucio/rucio/blob/226a9f8efb0dfe09b52607cd2333e184ab88d105/bin/rucio#L1963-L1966
https://github.com/rucio/rucio/blob/226a9f8efb0dfe09b52607cd2333e184ab88d105/bin/rucio#L2475-L2478
https://github.com/rucio/rucio/blob/226a9f8efb0dfe09b52607cd2333e184ab88d105/bin/rucio#L2483-L2484

The GitHub search is confusing sometimes, it is more convenient to just search the locally cloned repository
```bash
jdierkes@lxjoel ~/rucio-dev/master (master) $ grep -r -- "--expression" . | wc -l
9
jdierkes@lxjoel ~/rucio-dev/master (master) $ grep -r -- "--rses" . | wc -l
26
```
and then find the correct lines.

In this scenario, it is also a good idea to search for the subparsers (e.g. `list-file-replicas`).
