### ISSUE TITLE
"rucio upload" CLI fails if user has not WRITE privileges on the file to upload

### ISSUE THREAD

**Issue by leo-ccin2p3** [rucio/rucio#5073]
Motivation
----------

Rucio 1.26.10

Error occurs at checksum computation
```
2021-12-02 15:51:22,902	DEBUG	rucio	Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rucio/common/utils.py", line 245, in adler32
    with open(file, 'r+b') as f:
PermissionError: [Errno 13] Permission denied: '/sps/lsst/datasets/desc/DC2/Run2.2i/sim/y5-wfd/00992106/lsst_a_992106_R12_S00_z.fits'
Exception: FATAL - could not get Adler32 checksum of file /sps/lsst/datasets/desc/DC2/Run2.2i/sim/y5-wfd/00992106/lsst_a_992106_R12_S00_z.fits - [Errno 13] Permission denied: '/sps/lsst/datasets/desc/DC2/Run2.2i/sim/y5-wfd/00992106/lsst_a_992106_R12_S00_z.fits'
```

Modification
------------

Seems Rucio attempts to open the file in 'r+b' mode instead of 'rb' (since 1.26.8)
https://github.com/rucio/rucio/pull/4880/files/87c392af5873b32d23726191e0fc2dbc2e2db39c

**Comment by bari12** [comment]
@mlassnig isn't this the same observation Paul had as well?

**Comment by mlassnig** [comment]
yes, the file needs to be available in read-write mode to benefit from mmap.

**Comment by mlassnig** [comment]
While I don't understand why the file cannot be opened in read-write mode, we have to decide if we want to complicate the algorithm (check if available in read-write, if yes, use mmap, otherwise not), or just take mmap out?

**Comment by bari12** [comment]
I don't remember the performance benefits with mmap, if it is significant, we might check for `r+b` and fallback otherwise. If not significant, I think we should just do it the old way and forget about mmap.

**Comment by mlassnig** [comment]
`mmap` helps a lot in multi-user contexts, because it bypasses kernel-level IO. would be sad to see it go :-/ let me have a try beginning next week, maybe it's an easy change.

**Comment by leggerf** [comment]
hi guys, we stumbled in the same issue upgrading to rucio 1.26.10 for Virgo. Would be good to have an official fix for this

**Comment by bari12** [comment]
@mlassnig I think it would be good to just go back to the old way of doing the checksum validation. I believe this will make us problems on the ALRB as well as soon as we deploy 1.27, at least until you can implement the dual solution with fallback.

**Comment by bari12** [comment]
Backport 1.26.11
