### ISSUE TITLE
WebUI for 1.23.17 broken

### ISSUE THREAD

**Issue by thysk** [rucio/rucio#5096]
Motivation
----------
After updating to version 1.23.17, the webUI was no longer responding to http requests stating an internal error
after looking at the logs I find that it was trying to load /opt/rucio/.venv/lib/python2.7/site-packages/rucio/web/ui/main.py but an error occured on line 42: from rucio.common.utils import generate_http_error

Looking into common utils, there was no generate_http_error to import causing the error

Modification
------------

Removing this line has restored the WebUI to functionality

**Comment by bari12** [comment]
I am not sure if I follow 100% 

https://github.com/rucio/rucio/blob/d95b988b9bff02842721dae7fbf0361d377a2f1a/lib/rucio/web/ui/main.py#L43

Seems to be ok?

**Comment by thysk** [comment]
Didn't mean to send this I found my error. But this somehow got submitted
