### ISSUE TITLE
Default multihop tombstone is effectively None

### ISSUE THREAD

**Issue by nsmith-** [rucio/rucio#5110]
Motivation
----------
In
https://github.com/rucio/rucio/blob/d59c237f533f40116026dc9f347f4fc1297f1ff0/lib/rucio/core/transfer.py#L103
a `DEFAULT_MULTIHOP_TOMBSTONE_DELAY` is set, and then in 
https://github.com/rucio/rucio/blob/d59c237f533f40116026dc9f347f4fc1297f1ff0/lib/rucio/core/transfer.py#L1440
the default value is passed if no runtime configuration is set. The problem is, all cache values are converted to string in
https://github.com/rucio/rucio/blob/d59c237f533f40116026dc9f347f4fc1297f1ff0/lib/rucio/core/config.py#L191
which means that the actual default value ends up being the string `'2:00:00'`, and later on in `tombstone_from_delay` we get a ValueError which is converted to `None`
https://github.com/rucio/rucio/blob/d59c237f533f40116026dc9f347f4fc1297f1ff0/lib/rucio/core/replica.py#L1424-L1428
hence no tombstone unless `transfers.multihop_tombstone_delay` is explicitly set (or if the RSE has a `multihop_tombstone_delay` attribute)

Modification
------------
Set
```python
DEFAULT_MULTIHOP_TOMBSTONE_DELAY = int(datetime.timedelta(hours=2).total_seconds())
```

**Comment by rcarpa** [comment]
thank you for the investigation. I think the real problem is that we write the default to cache. Also, setting to none on conversion error isn't the best idea. @bari12 , WDYT?

**Comment by bari12** [comment]
Writing the default to cache is good in principle, this way we still minimise having to do database interaction in case the default is used. In principle dogpile supports writing the actual value (with type) to the cache and also retrieve it like that. I am not exactly sure why we cast it to string here. But I am a little bit concerned of changing this now and what side-effects this could result in.
For now I think @nsmith- suggestion is good. In a second step we should perhaps evaluate writing the right types to the cache.

**Comment by nsmith-** [comment]
A workaround is to set `rucio-admin config set --section transfers --option multihop_tombstone_delay --value 7200`
