### ISSUE TITLE
Clarify, implement and document a way how to include policy packages in containers/kubernetes

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5138]
Motivation
----------
It is quite clear how to include policy packages in a normally accessible environment, however, for containers used in a kubernetes deployment it is less clear. Goal of this issue is to clarify how such policy packages could be included in a container, implement/document it in the rucio documentation.

**Comment by jamesp-epcc** [comment]
I have submitted a first draft of some guidance here: https://github.com/rucio/documentation/pull/68 . If anyone has ideas for how it could be improved, please let me know.

**Comment by maxnoe** [comment]
Disclaimer: I haven't worked much yet with rucio, so I might be lacking some understanding of design choices / tradeoffs etc.

I wanted to give some feedback on creating a policy package following the given documentation.

My main feedback is that it seems very hard to maintain a policy package that only does simple changes like allowing `/` in lfns with respect to updates in the default schema / authorization policies.

The proposed way is to initially *copy* ~2000 lines of very repetitive python code. 

It seems very hard to maintain changes that were made intentionally vs. changes that are just outdated versions of the generic scheme. It's also easy to miss new functions defined in newer rucio versions.

A good way to be able to only modify parts that need to be changed would be great.

**Comment by bari12** [comment]
You are right and this is also a worry we have, so I think this is definitely the way to go. @jamesp-epcc we should probably create a ticket about this.

**Comment by rdimaio** [comment]
Opened this follow-up issue to keep track of this https://github.com/rucio/rucio/issues/6842
