### ISSUE TITLE
Add MongoDB metadata plugin

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5143]

**Comment by robbarnsley** [comment]
This feature is to add an metadata interface to allow keypairs to be kept in an external instance of mongodb.

As it utilises the `list-dids-extended` method, which is in the process of refactoring using the new filtering engine, full functionality with OR clauses and inequalities is dependent on #5144. It should, however, work with the previous method of filtering by metadata as the filtering engine is backwards compatible (hopefully).

**Comment by robbarnsley** [comment]
@bari12 would I be okay to add a mongodb instance to the development environment (for unit testing)? If so, what compose file(s)? 

Would also require the mongo client and pymongo package installed inside whatever container is going to connect to it, e.g. dev

**Comment by bari12** [comment]
Yes, that would be ok. You need to add it to the test docker files. Best get in contact with @maany about this.
