### ISSUE TITLE
Addition arguments for command "rucio list-suspicious-replicas" not working properly

### ISSUE THREAD

**Issue by ChristophAmes** [rucio/rucio#5148]
The additional arguments "--younger_than" and "--nattempts"  aren't producing the correct lists of suspicious replicas.

**Comment by joeldierkes** [comment]
Hello @ChristophAmes,

thank you for creating this issue. I had a look into `rucio list-suspicious-replicas` and did not find any bugs. Could you please provide some additional information:

- Current running version of Rucio
- The query you executed
- The result you got executing the query
- The result you expected

Please edit confidential information if necessary.

**Comment by ChristophAmes** [comment]
I used Rucio version 1.25.5 on lxplus. I am also the one who wrote the list-suspicious-replicas command.

For example, I tried the following yesterday (this is the entire output):
```
$ rucio list-suspicious-replicas --expression UKI-LT2-QMUL_DATADISK --nattempts 20
RSE Expression:        Scope:      Created at:            Nattempts:  File Name:
---------------------  ----------  -------------------  ------------  ---------------------------------
UKI-LT2-QMUL_DATADISK  mc16_13TeV  2021-01-23 12:36:05            47  AOD.23734602._002904.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV  2021-01-23 15:04:46            43  AOD.23734602._002450.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV  2021-08-06 13:12:22            48  HITS.26349900._006561.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV  2021-01-23 08:17:10            48  AOD.23734602._000158.pool.root.1
```

Now compare that to this (I've shortened the output):
```
$ rucio list-suspicious-replicas --expression UKI-LT2-QMUL_DATADISK --nattempts 10 --younger_than 2021-12-14T00:00:00 
RSE Expression:        Scope:        Created at:            Nattempts:  File Name:
---------------------  ------------  -------------------  ------------  ---------------------------------------
UKI-LT2-QMUL_DATADISK  mc16_13TeV    2021-01-22 04:47:23            16  AOD.23745346._010719.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV    2021-01-22 04:31:50            13  AOD.23745346._010722.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV    2021-01-22 04:11:21            15  AOD.23745346._010732.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV    2021-01-22 04:26:09            21  AOD.23745346._010736.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV    2021-01-23 06:04:59            14  AOD.23745346._010072.pool.root.1
UKI-LT2-QMUL_DATADISK  mc16_13TeV    2021-01-22 07:02:26            55  AOD.23745346._010098.pool.root.1
```

First of all, the file with Nattempts=55 didn't appear for `--nattempts 20` and secondly, the files that are appearing the in second output are older than `--younger_than 2021-12-14T00:00:00`.

**Comment by joeldierkes** [comment]
Okay, sorry for the confusion. I assigned you. Happy coding.

**Comment by bari12** [comment]
Hi @ChristophAmes is this still the case, can the ticket be closed?

**Comment by ChristophAmes** [comment]
Sorry for the late answer. The ticket can be closed.
