### ISSUE TITLE
Please fix documentation content

### ISSUE THREAD

**Issue by vkuznet** [rucio/rucio#5149]
Motivation
----------
I look-up rucio auto generated documentation and it is not readable. It is not properly parsed and contains pieces which are not converted into HTML. For instance, if I look at REST API [page](https://rucio.cern.ch/documentation/rucio_rest_api/#replicas.ListReplicas) I see the following:
```
## ListReplicas Objects
class ListReplicas(ErrorHandlingMethodView)
#### post
 | @check_accept_header_wrapper_flask(['application/x-json-stream', 'application/metalink4+xml'])
 | post()
List all replicas for data identifiers.

.. :quickref: Replicas; List replicas for multiple DIDs.

:reqheader HTTP_ACCEPT: application/metalink4+xml :query schemes: A list of schemes to filter the replicas. :query sort: Requested sorting of the result, e.g., 'geoip', 'closeness', 'dynamic', 'ranking', 'random'. :\<json list dids: list of DIDs....
```
As you can see it is not rendered HTML on a page and it is hardly readable.

On a client API page it looks better but still some pieces are not rendered, e.g.
```
#### list\_dids\_extended
```

Modification
------------
I suggest either to fix your parser which generates HTML pages for your documentation or fix syntax of markdown you use with your parser which should fix the issue.

**Comment by bari12** [comment]
Hi @vkuznet 
This is tracked in #4992 and part of a bigger issue with the auto-generated REST and API doc. Closing this.
