### ISSUE TITLE
Per-RSE checksum specification misbehaving for MD5-only

### ISSUE THREAD

**Issue by astroclark** [rucio/rucio#5155]
Motivation
----------
I'm trying to use an admittedly ancient gridftp server which reports the MD5 value instead of Adler32.  I thought the solution/workaround was to use:
```
rucio-admin rse set-attribute --rse LIGO-CIT --key supported_checksums --value md5
```
However, I notice that this actually completely disables all FTS checksums.

Modification
------------
If i check the supported checksums with `get_rse_supported_checksums_from_attributes`, the result is:
```
['m']
```
And `checksum_validation_strategy` returns:
```
('destination', ['m'])
```
but I believe the correct result should instead be:
```
('both', ['md5'])
```
As far as I can tell, it looks like the problem is in [`rse.py#L641`](https://github.com/rucio/rucio/blob/master/lib/rucio/core/rse.py#L641):
```
checksum_attribute[0].split(',')
```
I'm not sure what useful purpose that `[0]` serves?

**Comment by gabrielefronze** [comment]
Ciao @astroclark ,
I think the `[0]` is something which might have worked once but now might be un-necessary and in fact might broke the whole behaviour.
Can you try editing the code removing the `[0]`? If that's the case I can manage to fix it with a PR.
Cheers!

**Comment by astroclark** [comment]
Hm, removing the `[0]` ultimately gives:
```
  File "/usr/local/lib/python3.6/site-packages/rucio/core/rse.py", line 641, in parse_checksum_support_attribute
    supported_checksum_list = checksum_attribute.split(',')
AttributeError: 'list' object has no attribute 'split'
```
So I guess `checksum_attribute` is already a list of length 1 *unless* it's getting those values from the RSE attributes, in which case it's a string.  In fact, if i set:
```
$ rucio-admin rse set-attribute --rse LIGO-CIT --key supported_checksums --value md5,alder32
```
The supported checksums are still returned as:
```
supported by RSE settings: ['md5', 'alder32']
supported by RSE attrs: ['m']
```
using `get_rse_supported_checksums` and `get_rse_supported_checksums_from_attributes`, respectively.

I'm a little short of time now but might be able to take a more careful look tomorrow.
