### ISSUE TITLE
Unused `key` parameter in post account attribute API

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5167]
Motivation
----------
The `key` parameter in the path to post an account attribute is not used.
https://github.com/rucio/rucio/blob/d19db9eeb09440ae97477840fff57112f9b25620/lib/rucio/web/rest/flaskapi/v1/accounts.py#L72-L90

Modification
------------
Set the path parameter as default and override it with the json parameter if necessary.

**Comment by sayang14** [comment]
Hi @joeldierkes  and @bari12 , can I work on this issue as a part of Google summer of code 2023 evaluation for Rucio project ?
Also the code which is being mentioned is not from master branch where their is a small difference default = key) is present (https://github.com/rucio/rucio/blob/ea4d2c7e2702b85a86a8668b2d852971f42fceb4/lib/rucio/web/rest/flaskapi/v1/accounts.py#L134). So, is this issue solved or there is still something that I can work with ? Thanks!
