### ISSUE TITLE
Remove all instances of mutable objects (e.g. empty lists or dictionaries) as default parameter values

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5169]
Motivation
----------

Read [Python Mutable Defaults Are The Source of All Evil](https://florimond.dev/en/posts/2018/08/python-mutable-defaults-are-the-source-of-all-evil/). The likelihood of this anti-pattern is low, but given the magnitude, it might be worth removing all such instances.

Modification
------------

Identify all instances with `pylint --disable=all --enable=W0102 lib/rucio/`. Use `None` as default value, but *add type hints* and initialise the parameter in the body. For example:

https://github.com/rucio/rucio/blob/d19db9eeb09440ae97477840fff57112f9b25620/lib/rucio/core/rule.py#L735

Should become:

```python
@stream_session
def list_rules(filters: Optional[Dict] = None, session: Session = None) -> Iterable[Dict]:
    …
    filters = filters or {}
    …
```

**Comment by chinmaym07** [comment]
Hey Can I work on this ?

**Comment by bari12** [comment]
Hi @chinmaym07 yes, please go ahead. I would suggest to go module by module, starting with the ones in https://github.com/rucio/rucio/tree/master/lib/rucio/core
