### ISSUE TITLE
Remove hardcoded references to rucio-ui-dev.cern.ch

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5171]
Motivation
----------

It is expected that this node will cease to exist very soon.

Modification
------------

```
$ git grep rucio-ui-dev.cern.ch
lib/rucio/web/ui/static/base.js:    if (window.location.host == "rucio-ui-dev.cern.ch") {
lib/rucio/web/ui/static/http_api_usage.js:  var src = "https://rucio-ui-dev.cern.ch/kibana/#/dashboard/Rucio-RESTAPI-Account-Usage?embed&_g=("+
```

**Comment by nimishbongale** [comment]
Can I take this up @maany @dchristidis @bari12?

If so, do we want it to be extracted into a config file and then be replaced eventually or removed entirely?

**Comment by bari12** [comment]
Sorry for the late reply, yes please go ahead 👍

**Comment by nimishbongale** [comment]
> yes please go ahead 👍

Thank you! Just to confirm, I can extract this URL string out into maybe a config.json file and refer it from there? Would that be the desired way of implementation?

**Comment by maany** [comment]
Maybe an environment variable is better in this case ( to avoid creating a file with a single configuration variable). To completely resolve this issue, we'd also have to update the [Helm Chart for the UI](https://github.com/rucio/helm-charts/blob/master/charts/rucio-ui/templates/deployment.yaml#L124) to allow people to provide this value to the UI containers and provide the documentation to the users so they are aware of this ;) .

**Comment by nimishbongale** [comment]
> Maybe an environment variable is better in this case ( to avoid creating a file with a single configuration variable). To completely resolve this issue, we'd also have to update the [Helm Chart for the UI](https://github.com/rucio/helm-charts/blob/master/charts/rucio-ui/templates/deployment.yaml#L124) to allow people to provide this value to the UI containers and provide the documentation to the users so they are aware of this ;) .

Thanks for this, will get to work right away! 👍

**Comment by nimishbongale** [comment]
> Maybe an environment variable is better in this case (to avoid creating a file with a single configuration variable)

Passing environment variables into static .js files seem a little more complicated than I had expected. The environment variable would be accessible only to my flask server, which I would have to pass into my HTML templates, via render_template, and then pass it as a query parameter into the static .js files, and access it accordingly. Is there a better way? Let me know 😄

**Comment by maany** [comment]
One way to get around this, would be to modify the [docker `entrypoint` for the UI containers](https://github.com/rucio/containers/blob/0a373c0ea3ccabcce241719d48c9c7b590ed861a/ui/docker-entrypoint.sh#L33-L34)

The script should check if the environment variable for hostname is defined i.e. `RUCIO_HOST`. If found, it should modify the concerned `js` files using the `sed` utility.

@bari12 what do you think? also, do you agree that we can use a new environment variable called `RUCIO_HOST` or should we call it something else?

**Comment by nimishbongale** [comment]
> docker `entrypoint` for the UI containers

Definitely a better way to solve this problem. Thanks for this! 👍

**Comment by bari12** [comment]
Sorry getting a bit late into this. I think you can just remove these entirely. No need to have this configurable etc.
