### ISSUE TITLE
Remove forecast extension and numpy as a dependency

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5172]
Motivation
----------
The forecast extension is not used anymore, thus it should be removed from the codebase along with the numpy dependency.

Modification
------------
- Remove `lib/rucio/extensions/forecast.py` and references to it in the code.
- Remove numpy as a dependency

**Comment by joeldierkes** [comment]
https://github.com/rucio/rucio/blob/80f8c5a96e06abb80e3e6c854b89298f16be6270/lib/rucio/core/rule.py#L1197-L1202
How should we handle that? This seems to be the only reference to `forecast.py`.

**Comment by joeldierkes** [comment]
From my pov we could just deprecate the `estimate_ttc` in general, this however would be a breaking change...

**Comment by bari12** [comment]
Yes, just remove/deprecate it completely.
