### ISSUE TITLE
Delete redundant README files

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5193]
Motivation
----------
Rucio has, due to historic reasons, 4 README files:
- README.rst
- README.client.rst
- README.rucio.rst
- README.webui.rst

These README files are identical, which makes three of them redundant.

Modification
------------
Delete the three redundant README files and keep the README.rst.

**Comment by joeldierkes** [comment]
@bari12 Thought on that?

**Comment by bari12** [comment]
This comes from the fact that they are packaged to the pypi package in the build script
https://github.com/rucio/rucio/blob/master/tools/build_sdist_and_upload.sh
But since they are actually the same, it's probably better to just remove them and adapt the build script to use the same file.
