### ISSUE TITLE
Keyword `type` gets overwritten

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5208]
Motivation
----------
The keyword `type` in identities.py gets overwritten, this is a bad practice.
https://github.com/rucio/rucio/blob/1b68bbf6d44013b193db3f668b1e4b608e488bce/lib/rucio/web/rest/flaskapi/v1/identities.py#L134

Modification
------------
Use another variable name.

**Comment by bari12** [comment]
Should be replaced by `type_`
