### ISSUE TITLE
user environment variables to override client_cert and client_key of rucio.cfg

### ISSUE THREAD

**Issue by cale64** [rucio/rucio#5216]
Motivation
----------
Having the **environment variable** CLIENT_CERT and CLIENT_KEY evaluated by rucio clients (overriding defaults in a system-wide config file's _client_cert_ and _client_key_) would allow implementing of system-wide defaults (e.g. in /etc/profile) pointing to each user's individual certificate stored in his/her home directory. 

Rucio version is: 1.27.3

Modification
------------
Have those two variables checked (probably in baseclient.py), and set _client_cert_ and _client_key_ accordingly.

**Comment by bari12** [comment]
For joel: 
Change to be done is in the baseclient. This should be pretty much the same as with the `X509_USER_PROXY`, where we also check ENV first, then rucio.cfg.
