### ISSUE TITLE
allow_user_oidc_tokens config item not retrieved as boolean

### ISSUE THREAD

**Issue by robbarnsley** [rucio/rucio#5219]
`allow_user_oidc_tokens` config item needs to be changed from `config_get` to `config_get_bool`:

https://github.com/rucio/rucio/blob/d18fb0183a1456957994a94fb981d1386e11b386/lib/rucio/transfertool/fts3.py#L94

otherwise following (string) equivalence always evaluates to False:

https://github.com/rucio/rucio/blob/d18fb0183a1456957994a94fb981d1386e11b386/lib/rucio/transfertool/fts3.py#L380

**Comment by bari12** [comment]
👍 Will you submit a PR for this?

**Comment by robbarnsley** [comment]
Yep, will do.
