### ISSUE TITLE
oidc_redirect URL is incorrect for routes with a path

### ISSUE THREAD

**Issue by robbarnsley** [rucio/rucio#5220]
The URL sent to the user for authentication with the IdP:

https://github.com/rucio/rucio/blob/d18fb0183a1456957994a94fb981d1386e11b386/lib/rucio/core/oidc.py#L310-L311

assumes that the server sits at the root, i.e. `oidc_redirect` is found at `https://<netloc>/auth/oidc_redirect`. This is not correct if there is any path after the network location. 

In our case, the server, and consequently `oidc_redirect`, is routed via an nginx proxy to `https://<netloc>/rucio/auth/oidc_redirect`, so the above doesn't work.

I have hacked this in our own deployment to:

```python
auth_url = build_url('https://{}{}'.format(auth_server.netloc, auth_server.path.split('/auth/')[0]),
    path='auth/oidc_redirect', params=access_msg)
```

which works (for us), but I haven't thought about possible edge cases or whether there is a more sensible way of constructing this URL.

**Comment by bari12** [comment]
Isn't the full URL available somewhere? I mean do we have to build it like this. Seems to be very error-prone.

**Comment by robbarnsley** [comment]
The way it currently builds this URL is using the `redirect_url` from the token https://github.com/rucio/rucio/blob/d18fb0183a1456957994a94fb981d1386e11b386/lib/rucio/core/oidc.py#L309
which will always require some level of parsing/manipulation.

Unfortunately I don't have the knowledge to say if the (external) path to the auth server exists elsewhere. As you say, that would probably be the best option.

Probably a slightly safer option would be to simply strip `/oidc_token` off the redirect_url and rebuild it from there.
