### ISSUE TITLE
Remove global variables in `common.config`

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5223]
Motivation
----------
There are several mentions of the `__CONFIG` global variable in common.config. It would be good to get rid of it since it doesn't seem to be clearly needed for the functionality. Some review of the method parameters (clean_cache, etc.) might be needed.

**Comment by joeldierkes** [comment]
https://github.com/rucio/rucio/blob/cd26638b337e82a393d3eab0cfb9c330e9bb077e/lib/rucio/common/config.py#L369-L377
The `__CONFIG` global variable is used in a Singleton. From my POV it is needed, since otherwise we would load the config every time we call `get_config`.

Could you elaborate on that?
