### ISSUE TITLE
Update/Re-design `core.meta` module

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5224]
Motivation
----------
Currently the `core.meta.py` module makes it look like it deals with metadata directly, while this is not true, it is about metadata conventions and enforcing these. To make this more clear and avoid confusion, parts of the module (module name, method names, descriptions) should be updated. I would suggest to name everything as `meta_conventions`. 

Modification
------------
- Change the nodule name, method names, descriptions
- Check that the new metadata handling with the different plugins is actually compatible to this

**Comment by voetberg** [comment]
Would `metadata_interface` make more sense? While it isn't the metadata itself, it does control interactions with metadata

**Comment by bari12** [comment]
This would be a bit confusing with the actual metadata interface (in core/did_meta_plugins). I think I would call it somewhat like `metadata_conventions`?

**Comment by voetberg** [comment]
For the rest api - it advisable to make a legacy endpoint that responds to `/meta/` and a new one for `/meta_conventions/`, or just leave it as `meta`?

**Comment by bari12** [comment]
I think a new one + legacy, and we deprecate the legacy one over time.
