### ISSUE TITLE
Create download and upload capability in python clients

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#523]
Motivation
----------
At the moment downloading and uploading data is only possible via the command line interface. For the rucio movers it is necessary that this functionality exists via python callable methods. Thus the functionality should be added to the python clients; Afterwards the bin/rucio method can also use these methods for downloading.

**Comment by TWAtGH** [comment]
@bari12  I think this issue can be closed. We have #669 #670 and #717 for the next steps.
