### ISSUE TITLE
Flask fails after itsdangerous module’s update

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5258]
Motivation
----------
As described in https://github.com/pallets/flask/issues/4455, the `itsdangerous` package version 2.1.0 breaks Flask 1.1.2.

Modification
------------
Bump the Flask version to 1.1.4 as proposed by the flask issue. This is just a minor version bump and will fix the dependency version mismatch.

**Comment by bari12** [comment]
Backport 1.26.12
Backport 1.23.19

**Comment by bari12** [comment]
Thanks!
@joeldierkes Please also submit this on the `release-1.23-LTS` branch, although it needs to be a little bit different there.
