### ISSUE TITLE
Minos/Bad replicas database inefficiency

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5266]
Motivation
----------
There is a few queries in Minos (and Bad replica declaration in general) which are executed did by did, instead of bulks. This creates big CPU load spikes on the database which need to be avoided.

Modification
------------
- Investigate queries which can be executed in bulk.
- Add bulk executions for these.

One example is https://github.com/rucio/rucio/blob/a50a60f20f5fc78079d77f5f55cd20f465339b9b/lib/rucio/core/replica.py#L344
The `__exists_replicas` check is done one file after the other.

**Comment by cserf** [comment]
I would prefer that this PR https://github.com/rucio/rucio/pull/5068 is merged before starting working on this issue
