### ISSUE TITLE
webdav module: TLS version

### ISSUE THREAD

**Issue by cfenell** [rucio/rucio#5302]
Motivation
----------
In module lib/rucio/rse/protocols/webdav.py, class TLSv1HttpAdapter,
ssl version is explicitly set like this
    ssl_version=ssl.PROTOCOL_TLSv1

This seems to mean TLS version 1.0 which is deprecated and considered insecure. 

Modification
------------
Version 1.2 or higher if available should be preferred, such as
    ssl_version=ssl.PROTOCOL_TLSv1_2

**Comment by mlassnig** [comment]
Hi, yes, you seem correct, however when looking at the documentation it says:
```
Deprecated since version 3.6: OpenSSL has deprecated all version specific protocols.
```
Is the correct way now simply not to set a ssl_version at all?

**Comment by cfenell** [comment]
Hi, yes it is probably better not to set it explicitly!
I will test.

**Comment by bari12** [comment]
Functionally fixed, code comments/method name however still say TLSv1 - needs to be fixed
