### ISSUE TITLE
posix protocol modifications

### ISSUE THREAD

**Issue by afortiorama** [rucio/rucio#5319]
Motivation
----------

in ATLAS StoRM sites can can read directly from the file system (probably write too) but the path resolution is done via storm server. 

Some sites setting up cephFS would like to read directly from the FS but there is no possibility at the moment.  

Modification
------------

Modify posix protocol to allow direct access to the fs. At the moment it copies the files but the best thing would be to have a symlink like storm sites but without needing to get the information from a storage server.

this would simplify the setup at sites removing the need of extra hardware to handle the read and possibly write to the file system.

**Comment by mlassnig** [comment]
This one needs a symlink subclass on the posix protocol, and overwrite the get() with a symlink variant, and a overwrite the exists() to check that not the symlink but the file followed by a symlink actually exists.

**Comment by KarthikSundar2002** [comment]
I would like to work on this, but I feel like I may need some pointers on where to get started.

**Comment by snafus** [comment]
Hi, 
  I've started work on this topic here: 
 https://github.com/snafus/rucio/tree/patch-5319-PosixWithSymlinkProtocolImpl 
 The current version appears to demonstrate the required functionality, and I hope to make a PR shortly. 
 Any comments are happily received at this point.
 https://github.com/snafus/rucio/tree/patch-5319-PosixWithSymlinkProtocolImpl 
 
 I did not overwrite the exists() method, as this gets the path from PFN of the 'remote' file; but let me know if I missed something. 
 Thanks,
 James

**Comment by snafus** [comment]
Hi, I've updated the pull request with a couple of fixes for logging output formatting. 

In terms of testing; I've tried the following:
```
rucio-admin rse add POS1
rucio-admin rse add-protocol --hostname "" --scheme file --prefix /tmp/pos1  --impl rucio.rse.protocols.posix.Symlink --domain-json '{"wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}, "lan": {"read": 1, "write": 1, "delete": 1}}' POS1
mkdir /tmp/pos1
rucio-admin rse info POS1

dd if=/dev/urandom of=fpos1 bs=10M count=1
dd if=/dev/urandom of=fpos2 bs=10M count=1

rucio upload --rse POS1 --scope test fpos1
rucio upload --rse POS1 --scope test fpos2
rucio add-dataset test:posdataset1
rucio attach test:posdataset1 test:fpos1 test:fpos2

rucio list-file-replicas test:posdataset1

rucio download test:posdataset1
ls -ltrh posdataset1
```

With outputs of 
```
rucio list-file-replicas --protocol file test:posdataset1
+---------+--------+------------+-----------+-----------------------------------------+
| SCOPE   | NAME   | FILESIZE   | ADLER32   | RSE: REPLICA                            |
|---------+--------+------------+-----------+-----------------------------------------|
| test    | fpos1  | 10.486 MB  | fbf84b82  | POS1: file:///tmp/pos1/test/16/f4/fpos1 |
| test    | fpos2  | 10.486 MB  | 211742a4  | POS1: file:///tmp/pos1/test/cb/41/fpos2 |
+---------+--------+------------+-----------+-----------------------------------------+

rucio download test:posdataset1
ls -ltrh posdataset1/
total 0
lrwxrwxrwx 1 root root 26 May 18 05:09 fpos1 -> /tmp/pos1/test/16/f4/fpos1
lrwxrwxrwx 1 root root 26 May 18 05:09 fpos2 -> /tmp/pos1/test/cb/41/fpos2
```

James

**Comment by mlassnig** [comment]
Hi James, sorry, completely missed this. Let me have a closer look.

**Comment by snafus** [comment]
Hi @mlassnig ; I've added some slightly improved exception handling, and a basic unit test (although I think the get methods are not yet available?).
I hope this is a suitable version to be considered. Thanks, James
