### ISSUE TITLE
Possibility to make a pip install directly from git url

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#532]
Motivation
----------
To be able to install directly from master.

**Comment by vingar** [comment]
the openstack package pbr is nice for this and can be used (or at least as a source of inspiration)

cf. http://git.openstack.org/cgit/openstack-dev/pbr/tree/pbr/version.py

**Comment by vingar** [comment]
Implemented the following:
```
$ pip install git+git://github.com/vgaronne/rucio.git
$ rucio --version 
rucio 1.13.2-52-ge63dfb28-dev1519211244
```

**Comment by bari12** [comment]
The ge63dfb28-dev1519211244 is just based on the commit id?

**Comment by vingar** [comment]
not completely. Have a look on the corresponding pull request.

**Comment by bari12** [comment]
Ah I see. Did you solve the issue with the installation of dependencies?

**Comment by vingar** [comment]
I didn't have a look on it. On next it is solved
