### ISSUE TITLE
DB/ATLAS : Improve query for filling rucio_accounting_tab

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5327]
Motivation
----------
Some scopes are too big resulting in snapshot too old. DBAs suggested the following improvement : 
https://its.cern.ch/jira/secure/attachment/307216/RUCIO_ACCOUNTING_change_20220307.txt

**Comment by bari12** [comment]
Can this be closed?

**Comment by bari12** [comment]
Please update etc/sql/oracle/procedurs.sql file with the current procedure.

**Comment by bari12** [comment]
@cserf ?
