### ISSUE TITLE
receiver incorrectly handles multi-source transfers

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5335]
Motivation
----------

In case of multi-source transfers, receiver analyzes the message even if the job didn't yet finish:
https://github.com/rucio/rucio/blob/8acc9c9b873eef1d7e3b081821665ee03b95f4a0/lib/rucio/daemons/conveyor/receiver.py#L93

If the the message concerns one failed source, this results in a transition of the transfer to a failed state :  
https://github.com/rucio/rucio/blob/8acc9c9b873eef1d7e3b081821665ee03b95f4a0/lib/rucio/transfertool/fts3.py#L523

One may be miss-leaded, me included until now, that the `t_final_transfer_state` field is related to the job_state, but it  doesn't seem to be the case on FTS side. It depends on the file_state and the job state may not yet be final: 
https://gitlab.cern.ch/fts/fts3/-/blob/a34b78420e7f06aebca4f468e39312189e9e1454/src/url-copy/LegacyReporter.cpp#L214

This means that the receiver may transition the file to a failed state even if the job is not yet completed.

**Comment by bari12** [comment]
Backport 1.26.13
