### ISSUE TITLE
Consistent headers for all source files

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#534]
Motivation
----------
Docstrings and Copyright.

https://github.com/PyCQA/pylint/issues/1164
https://stackoverflow.com/questions/7877522/how-do-i-disable-missing-docstring-warnings-at-a-file-level-in-pylint

**Comment by vingar** [comment]
The docstring headers are not handled properly by sphinx for the API documentation. The clients source files will be updated to:
```
# Copyright (c) 20XX-2018 CERN for the benefit of the ATLAS collaboration.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
#
# Authors:
# - ...
```

**Comment by mlassnig** [comment]
Back to block comments ;-)

Correct dates according to git are 2012-2018. I'd also modify the first to lines to be a bit more explicit (no need for (c) for example)


```
 # Copyright 2012-2018 European Organization for Nuclear Research (CERN)
 # For the benefit of the ATLAS Collaboration
 # 

```...

(also makes it nicer to modify the second line later on, if necessary)

**Comment by vingar** [comment]
yes, back to block comments and we can hope that pylint will offer a way to mute the missing docstring at the top of the file

I was thinking having the starting date based on the file creation date.

According to http://hepsoftwarefoundation.org/notes/HSF-TN-2016-01.pdf
The format must be:

(c) Copyright [year] CERN [for the benefit of the [Name of appropriate
group] Collaboration]

**Comment by mlassnig** [comment]
Right, then that's how it is ;-)

**Comment by vingar** [comment]
this one is not true everywhere ...

**Comment by bari12** [comment]
Ah I thought with your recent patches you iterated all files.

**Comment by vingar** [comment]
only the ones I've modified to get the doc generation working
