### ISSUE TITLE
Replace deprecated `oauth2client` dependency

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5343]
Motivation
----------
Dependency is deprecated since 2018. Needs to be replaced. Common recommendation seems to be http://oauthlib.readthedocs.io/

Modification
------------
Investigate `oauth2client` alternatives and change the dependency.

**Comment by rizart** [comment]
This dependency is only used in the context of the service account credentials that we need to sign urls for Google Cloud Storage. I believe this [1] library is a better fit, I already figured out and tested the changes that are needed and everything seems to work fine. I haven't yet explored [2] in depth, but from a quick look it doesn't seem to have out of the box support for managing these credentials.

[1] https://google-auth.readthedocs.io/en/latest/index.html
[2] http://oauthlib.readthedocs.io/

**Comment by bari12** [comment]
👍 Thanks Rizart. That makes sense. I thought at first that this is used for the oauth tokens, did not see that it is only used for the signed urls. Since [1] also supports AWS that should be fine.
@cserf ?

**Comment by rizart** [comment]
> 👍 Thanks Rizart. That makes sense. I thought at first that this is used for the oauth tokens, did not see that it is only used for the signed urls. Since [1] also supports AWS that should be fine. @cserf ?

A short update on this, you were right @bari12 , this is a direct dependency for `oic`, which means that we probably need to deprecate that library as well if we want the code completely `oauth2client` free.
