### ISSUE TITLE
Remove `retrying` dependency

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5344]
Motivation
----------
The `retrying` dependency has not been updated since 2014.

Modification
------------
Remove and either switch to Rucio-internal code, such as `rucio.common.utils.retry()` or include a different, up-to-date dependency.

**Comment by rcarpa** [comment]
Is there any reason to remove the dependency other than "not updated"  ? it seems straight-forward; without many dependencies:
https://github.com/rholder/retrying/blob/master/retrying.py
I think that some things in our `rucio.common.utils` are as old and unmaintained :)

**Comment by bari12** [comment]
Although nothing is failing now, in general I would like to avoid having non-maintained dependencies. It's just a problem in the making.
For this one it's known that it won't install under Py 3.10 anymore, and technically not flagged as compatible with 3.6+ either (Although it seems to be working) 😄
