### ISSUE TITLE
Remove legacy S3 protocols and libraries

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5346]
Motivation
----------
In the Rucio dependencies we use both `boto` (Clients) and `boto3` (Server/Daemons)
`boto` has de-facto been deprecated in favour of `boto3`. With the drop of python2 for Rucio 1.29, we can finally fully remove `boto` in favour of `boto3`.

Modification
------------
Remove `boto` and replace with `boto3`.

**Comment by jamesp-epcc** [comment]
One option would be to remove the protocol that uses boto altogether. The new method using the signed urls uses boto3 on the server and doesn't require any S3-specific libraries on the client. Though we should check if anyone is still using the s3boto protocol before doing that. (There is also `s3.py` which uses the S3 library instead of boto but otherwise it looks as if it basically does the same thing).

**Comment by bari12** [comment]
If nobody uses it, I would also be in favour of removing and simplify things.

**Comment by jamesp-epcc** [comment]
I've started putting together a PR to remove this legacy code. I wasn't sure what to do about `light_reaper.py`. It doesn't use the S3 libraries, but it does manually construct a `s3://` URL. Is this still the right thing for it to do?

**Comment by mlassnig** [comment]
Any kind of s3:// URL seems wrong to me.

**Comment by rizart** [comment]
Not sure if this helps, but FTS expects `https://` when you provide an already signed URL, as is the case now for Rucio. This supports additionally Mario's point.

**Comment by jamesp-epcc** [comment]
I agree, we should probably not be using `s3://` URLs now. In the case of the light reaper, it appears it used to call `rsemgr.lfns2pfns` to generate the URL, but at some point was changed to construct only S3 URLs instead:

https://github.com/rucio/rucio/blob/5e92ee1e6d323d7e2f9eeb6e97ecb4f6fc4c3abe/lib/rucio/daemons/reaper/light_reaper.py#L108-L111

This seems strange to me. I have no experience with the light reaper so I'm not sure what the correct fix is.

**Comment by rizart** [comment]
Please also pay attention to [this](https://docs.google.com/document/d/1ofV5iIgpCKCnANNuqIavN_6FvvMTE6QPtQKK_n1P3SE/edit#heading=h.bvzk0w47bfs7) behavior when it comes to the connection of signed URLS and GFAL/FTS.

**Comment by jamesp-epcc** [comment]
> Please also pay attention to [this](https://docs.google.com/document/d/1ofV5iIgpCKCnANNuqIavN_6FvvMTE6QPtQKK_n1P3SE/edit#heading=h.bvzk0w47bfs7) behavior when it comes to the connection of signed URLS and GFAL/FTS.

Thanks for bringing that to my attention. I don't think the changes I am making just now will affect the FTS behaviour. The code in `transfer.py` that ensures the correct URL scheme is used for FTS when accessing objectstores doesn't rely on any of the S3 libraries.
