### ISSUE TITLE
Remove/change `bz2file` dependency

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5348]
Motivation
----------
`bz2file` has not been updated since 2014. Switch to a different dependency if needed, or remove entirely from the codebase.

**Comment by faluchet** [comment]
Would plain bz2 (currently mainteined) be OK? 

Motivation for using bz2file looks to be here.
https://github.com/rucio/rucio/blob/680b88876e5df65f87c7a3888020de28acb33c5e/lib/rucio/common/dumper/__init__.py#L38-L42

I assume that by dropping python2 the problem won't be there anymore. Remains python 3.0 to 3.2, but I would not care that much if its just for the multistream TBH.
And I assume that the transition to bz2 would be quite transparent.
