### ISSUE TITLE
rucio update-rule --locked is case sensitive

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#5356]
Motivation
----------

It should accept not only `False`, but also `false`

**Comment by mlassnig** [comment]
(well, any case actually... `fALse` etc..) :-)

**Comment by KarthikSundar2002** [comment]
![image](https://user-images.githubusercontent.com/66824631/158009696-810c3fb2-1b14-4938-b262-51cdcaaca4bf.png)
I think this should solve this issue
Shall I proceed to make a PR?

**Comment by joeldierkes** [comment]
How about the `.lower()` function. It is more used and known than the `.title()` one.
```python
if args.locked.lower() == "true"
```

**Comment by KarthikSundar2002** [comment]
As of now, the existing values are in titlecase so I just used that, but it isn't a big deal so it's fine even if we have to change it
