### ISSUE TITLE
WebUI: Add support Flask Sessions (GSoC Qualification Task - Rucio WebUI Revamp)

### ISSUE THREAD

**Issue by maany** [rucio/rucio#5363]
**NOTE** This issue is only for candidates interested in the [Rucio WebUI Revamp project](https://hepsoftwarefoundation.org/gsoc/2022/proposal_Rucio-WebUI.html).

Motivation
----------
Currently, the sessions in WebUI are managed by using session cookies that are maintained with custom server-side logic. The goal of this task is to deprecate the custom cookie management by introducing sessions/session-cookies managed directly by Flask.

 
Task Items
-----------
1. Setup the WebUI on your local machine or development instance in your favorite IDE of choice.
2. Go through [bp.py](https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/flask/bp.py) and understand how it interacts with core rucio authentication packages.
3.  Come up with the minimum set of modifications required to replace the use of custom cookies with flask sessions.

Modification Hints
-------------------
A large part of the modifications will be made primarily in [bp.py](https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/flask/bp.py)

Submission Details
-------------------
- The submissions can be made directly to the mentors via email with the subject `Rucio WebUI Revamp - GSoC Qualification Task - Rucio-Rucio - <your_name>`.  
- Please feel to work on this issue in your own fork. Create a branch in your fork to maintain the changes. 
- Once you are happy with the changes, create a pull request to `<your_git_username>/rucio` master branch. 
- Make sure that the Github Action workflows pass in your fork. You might have to enable GitHub Actions here: https://github.com/<your_github_username>/rucio/settings/actions
- You can then share either the link to your branch or a `git patch`  showing your changes.
- If you are unable to implement the entire functionality or have suggestions on how you would further improve your submission, please do describe them in the same submission email.

Where to ask questions?
------------------------
- You can ask any questions directly in the issue discussion.
- You can ask questions in our [Slack Channel](https://join.slack.com/t/rucio/shared_invite/zt-yvk2uk8l-1fIgdE9sUKaJbYEUc8yBVQ).
- You can also write to the mentors via email or over Slack direct messages.

Mentor Info
------------
- [Mayank Sharma](mailto:mayank.sharma@cern.ch)
- [Cedric Serfon](mailto:cedric.serfon@cern.ch)
- [Martin Barisits](mailto:martin.barisits@cern.ch)

**Comment by sambhavsaxena** [comment]
Hello @maany ,
Is there a doc available to guide through setting up WebUI on a local machine?

**Comment by maany** [comment]
Hey @sambhavsaxena,
You can set up the dev containers as described in the [documentation](https://rucio.cern.ch/documentation/setting_up_demo)
**NOTE**: You can modify the docker-compose file to expose another port ( e.g 5000) for the `rucio-dev` container.

To UI is a [flask app](https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/flask/main.py) which you can start inside the `dev_rucio_1` container with [flask CLI or with python directly](https://www.twilio.com/blog/how-run-flask-application)
**NOTE**: Make sure you start the application on the port you exposed in the docker-compose file ;) 

Let me know if you still have troubles with this and good luck :)

**Comment by maany** [comment]
Closing as not relevant
