### ISSUE TITLE
Remove Jira references

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5368]
Motivation
----------
Jira was the old bug tracker of rucio. It is not used anymore. We should delete all references to it. (Except informational ones)
```bash
jdierkes@lxjoel ~/rucio (master*) $ rg -i jira
lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py
265:                        logger(logging.INFO, "%s is problematic (more than %s suspicious replicas). Send a Jira ticket for the RSE (to be implemented).", rse_key, limit_suspicious_files_on_rse)

lib/rucio/daemons/hermes/hermes.py
350:            # silence this error: https://its.cern.ch/jira/browse/RUCIO-1699
```

Modification
------------
Delete all references to Jira and optionally add references to GitHub Issues.

**Comment by dchristidis** [comment]
Note that the first one is correct for ATLAS: it refers to JIRA projects for DDM operations, not the Rucio project. Opening a GitHub issue would be inappropriate.

**Comment by joeldierkes** [comment]
Okay, good to know. The second one is informational and still accessible. Nothing to be done then.
