### ISSUE TITLE
Change ClientState to type string

### ISSUE THREAD

**Issue by maany** [rucio/rucio#5393]
Motivation
----------
There have been a lot of cases where the ClientState parameter in the incoming traces violates the values specified in the clienstState enum. So far, we have been watching the logs, identifying the new clientState values, and then updating the enum. This solution has to be repeated every time there is a new value for clientState introduced.

Modification
------------
Change clientState to type str
As a follow-up, we should agree on the client state values with the panda team.

**Comment by bari12** [comment]
Backport 1.27.12
