### ISSUE TITLE
Jinja2 3.1.0 is incompatible with Flask 1.1.2

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5398]
Motivation
----------
The new Jinja2 version 3.1.0 is incompatible with the Flask 1.1.2 version. This is a problem in the release-1.27 and previous versions, since they use Flask 1.1.2.

Modification
------------
Pin the Jinja2 version to some version prior to 3.1.0.

**Comment by bari12** [comment]
Backport 1.27.12

**Comment by bari12** [comment]
Backport 1.23.19
