### ISSUE TITLE
Flag transfer errors coming from tape sources

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5410]
Motivation
----------
For the ATLAS data carousel it would be very beneficial to understand if a transfer error comes from a tape source, or a disk source.

Modification
------------
Right now we store transfer errors coming from FTS in the `error` field of the rule. The proposal here is to just prepend this with a `[TAPE SOURCE]` (or equivalent) string so it is clear that the error comes due to a tape source. (Source should be mentioned in the respective request already)

**Comment by mishaborodin** [comment]
Thanks a lot for this feature, It's very useful. Could some kind of filter be added to a rucio rule web page when it's ready.

**Comment by bari12** [comment]
You mean on this page: https://rucio-ui.cern.ch/r2d2 ?

Probably yes, but let's deal with this in a second issue then.

**Comment by mishaborodin** [comment]
No, I meant pages like that https://rucio-ui.cern.ch/rule?rule_id=f3bc86a501d348a98712150dbc470529 
so it could be obvious in a glance from this page that it has some tape related problem.
