### ISSUE TITLE
Pin the `werkzeug` package version prior to 2.1.0 in Flask 1.1.2 versions

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5419]
Motivation
----------
Since `werkzeug` version 2.1.0 the `Flask` version 1.1.2 breaks. We have to pin the `werkzeug` version as well.

Modification
------------
Pin the `werkzeug` version in every release that uses Flask 1.1.2.

**Comment by bari12** [comment]
Backport 1.26.12
