### ISSUE TITLE
Calculation of container `length` and `events`

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5422]
Motivation
----------
For datasets the `length` and `events` field is updated via the `re_evaluate_did` workflow whenever a file is attached/detached from the dataset. However, this information is not communicated up the tree to parent containers (and possibly their parents).

This is not easily do-able in the same workflow, as it opens the risk of row contention.

It raises the question if, for containers, this information should ever be filled in the database, or always kept `NULL`?

Modification
------------
For containers, this information should be calculated dynamically, not necessarily down to the file level, but to the dataset level, since the dataset information is trustworthy. It also needs to be done for closed containers, since the information can potentially still change if the containing datasets are not closed yet.

**Comment by rcarpa** [comment]
The problem seems even more complex. A lot of code relies on DataIdentifierAssociation length/bytes and those are never updated. For Datasets it's not a problem. For Containers it is.
