### ISSUE TITLE
Globus transfers not being handled properly by MONIT

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5432]
Motivation
----------

The protocol is not properly extracted, see:
https://monit-grafana.cern.ch/dashboard/snapshot/en9K4Tc2vSpD54ToTLr5pydfei1GSAil

Modification
------------

Not sure whether something to address on our side or MONIT’s.

**Comment by bari12** [comment]
This looks to me more on the monit side in the transformation job. I think we need to check this with them.

**Comment by mlassnig** [comment]
Submitted: RQF2010563

**Comment by dchristidis** [comment]
https://github.com/rucio/rucio/blob/abe3c77ed31b89661a7a13209d58ff3b62e2a266/lib/rucio/core/request.py#L1575
Maybe?
