### ISSUE TITLE
Rules on containers in state OK but not all the files from the containers have locks

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5447]
Motivation
----------
There is a bug for the rules on containers, example below :
```
rucio list-files mc16_13TeV:mc16_13TeV.700337.Sh_2211_Znunu_pTV2_CVetoBVeto.deriv.DAOD_PHYS.e8351_s3126_r9364_p4355 | grep "Total files"
Total files : 603
```
But :
```
rucio list-rules mc16_13TeV:mc16_13TeV.700337.Sh_2211_Znunu_pTV2_CVetoBVeto.deriv.DAOD_PHYS.e8351_s3126_r9364_p4355
ID                                ACCOUNT    SCOPE:NAME                                                                                          STATE[OK/REPL/STUCK]    RSE_EXPRESSION           COPIES    EXPIRES (UTC)    CREATED (UTC)
--------------------------------  ---------  --------------------------------------------------------------------------------------------------  ----------------------  -----------------------  --------  ---------------  -------------------
0e089533f57a4237adebd02954e81cfe  whopkins   mc16_13TeV:mc16_13TeV.700337.Sh_2211_Znunu_pTV2_CVetoBVeto.deriv.DAOD_PHYS.e8351_s3126_r9364_p4355  OK[269/0/0]             BNL-OSG2_LOCALGROUPDISK  1                          2021-11-26 19:12:53
793ba313ff5a4ccba33ff69c46092138  ddmadmin   mc16_13TeV:mc16_13TeV.700337.Sh_2211_Znunu_pTV2_CVetoBVeto.deriv.DAOD_PHYS.e8351_s3126_r9364_p4355  REPLICATING[38/565/0]   GOOGLE_EU                1                          2022-04-05 13:54:53
```

The rule at BNL is in state OK but has only 269 locks out of 603

**Comment by bari12** [comment]
Just to add a quick investigation here
I am pretty sure that fundamentally never worked, since there is no `UpdatedDID` created for * -> Container attaches:
https://github.com/rucio/rucio/blob/c57e7219e4db46f302b5e35b9741ff252466aaec/lib/rucio/core/did.py#L585

**Comment by ThePhisch** [comment]
As per my conversation with @cserf , the bug can presumably be triggered in the following manner:
1. A container is created and a first dataset is added to this container.
2. A first rule A is created on the container.
3. Then another (or more) dataset is added to the container.
4. Then a rule B is created on the container.

At the end, the rule A is in state OK but doesn't have all the files from the container, whereas rule B has the same number of files than the container
