### ISSUE TITLE
Cannot update `continent` attribute of RSE

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5464]
Motivation
----------
The `continent` attribute of an RSE can not be changed. This is inconsistent, since all other place related attributes (`city`, `region_code`, ...) can be changed.

https://github.com/rucio/rucio/blob/3d6a672da0401c57b5ea4dfe2037ca83a7bfbadd/lib/rucio/core/rse.py#L1280

Modification
------------
Allow the update of the `continent` attribute.

**Comment by bari12** [comment]
Side-comment: Maybe re-design RSE attributes vs. rse settings (RSE Settings should only be a very limited list of keys)
