### ISSUE TITLE
Rucio documentation: duplicate CLI examples.

### ISSUE THREAD

**Issue by LukasMoll** [rucio/rucio#5485]
As you can see in the picture the Rucio CLI example is visible twice in the sidebar.
![image](https://user-images.githubusercontent.com/86722560/163711011-937213c7-3177-4f26-b9e6-322784c5f41b.png).
Can be replicated in any browser.

**Comment by joeldierkes** [comment]
Hello @LukasMoll, thank you for issuing the bug.
The documentation you're looking at is deprecated. You can find the new one here: https://rucio.cern.ch/documentation/
The site you're looking for was renamed to [`Using the Client`](https://rucio.cern.ch/documentation/using_the_client).

The old documentation still contains some data, which is not migrated to the new one yet. As soon as we migrated all the data, the old one will be deleted. #5446
