### ISSUE TITLE
Misleading documentation for replicaclient.update_replicas_states()

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5487]
Motivation
----------

https://github.com/rucio/rucio/blob/47e93cfbe5887071c70de4ba815c1bbdddfac2ce/lib/rucio/client/replicaclient.py#L278-L284

This appears to be a mix between `ReplicaState` and `BadFilesStatus`.

Note that the schemas are also inconsistent. For example:

https://github.com/rucio/rucio/blob/47e93cfbe5887071c70de4ba815c1bbdddfac2ce/lib/rucio/common/schema/atlas.py#L98-L100

Modification
------------

**Comment by bari12** [comment]
@joeldierkes can you please have a look on this and back-track this a little bit. I am not sure if this is on purpose or a bug.

**Comment by joeldierkes** [comment]
https://github.com/rucio/rucio/commit/4df2b3e35603a198a2bfa16d59ef80de59b01a7a This commit adds the missing documentation for the `update_replicas_states` in the `replicaclient`. It seems that the description just got wrongly added, the `BadFilesStatus` is never used or mentioned anywhere. I think this is a simple mistake.

https://github.com/rucio/rucio/issues/2240 Is the tracking issue for the missing documentation.
