### ISSUE TITLE
Deprecation message in Paramiko

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5500]
Motivation
----------
Paramiko outputs a deprecation message due to an outdated security algorithm. We do not depend on that algorithm.
https://github.com/paramiko/paramiko/pull/2039

Modification
------------
The paramiko team is aware of the problem. They opened a PR to fix it.

**Comment by joeldierkes** [comment]
Proposed solution: Set the `cryptography` version fixed to the last working one. The only relevant change in the new version 37.0.0 is the deprecation message, which fails some of our test cases. As soon as `paramiko` does not use the deprecated feature anymore we can dump up the version.

**Comment by bari12** [comment]
Backport 1.26.13
