### ISSUE TITLE
Improve doc for the CLI

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#551]
Motivation
----------
Missing doc for the CLI

Modification
------------
Improve doc for the CLI

**Comment by nataliaratnikova** [comment]
HI, there seems to be a typo  in the example for adding protocols: underscores are used instead of dashes in --web_service_path :  
https://github.com/rucio/rucio/blame/3d9fe6112c64b155734cf9e7c8cb7d9bfedf5b69/bin/rucio-admin#L1442

**Comment by bbockelm** [comment]
Hi Natalia,

Can you send a PR in for that change?

Thanks!

Brian

**Comment by vingar** [comment]
not a big change... Just sent two PRs about it #814 #815

I'm sure @nataliaratnikova will find other inconsistencies and submit new PRs :)

**Comment by nataliaratnikova** [comment]
Hi Brian,
Vincent already corrected this one, I believe.
I noticed that Rucio client is not very consistent about using _ and - 
in the options and names.  It's not always clear to me what the intended 
conventions are, and this particular code is under rapid development. 
May be it is worth going over the whole client code, once it is stable 
and the conventions are clarified.
Thanks,
    Natalia.

**Comment by vingar** [comment]
Hi,
yes, I did that one as the example value was not appropriate as well.  I would be happy if you report more such inconsistency.

Vincent

**Comment by mlassnig** [comment]
The convention is that "-" (minus) should be used in CLI arguments instead of "_" (underscore). Anything else is a typo/mistake.

**Comment by nataliaratnikova** [comment]
Submitted https://github.com/rucio/rucio/pull/818 with two more fixes, 
hopefully all are caught now.
