### ISSUE TITLE
third_party_copy update is not applied on third_party_copy_read/write columns

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5515]
Motivation
----------

starting 1.28, we use third_party_copy_read/write columns instead of third_party_copy. For reverse compatibility, create_protocol, accepts third_party_copy as input, but converts it into third_party_copy_read/write. 

Update_protocol doesn't have the same behavior. Meaning that communities may encounter unexpected behavior when updating third_party_copy, which isn't used anymore by conveyor.

**Comment by bari12** [comment]
Will not be fixed; We rather want to have people move to `third_party_copy_read/write` and remove the deprecated `third_party_copy` column entirely.

**Comment by rcarpa** [comment]
Removed in https://github.com/rucio/rucio/issues/5634
