### ISSUE TITLE
Propagate dataset metadata to transfer

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#5521]
Motivation
----------

```
Dear rucio devs,

I am making RAW data to DAOD_PHYS plot (https://its.cern.ch/jira/browse/ADCMONITOR-507). There, I need to plot duration of RAW/AOD data transfer to Tier-1s. This is doable using data in rucio is sending to the monit infrastructure, namely data.dataset variable. But it seems that T0 export data do not have that field defined.

example:

https://rucio-ui.cern.ch/did?scope=data17_13TeV&name=AOD.28873750._000372.pool.root.1

is part of data17_13TeV:data17_13TeV.00340030.calibration_BphysPEB.merge.AOD.r13576_p5087_tid28873750_00

but in the monit data, there is no data.dataset variable filled:

https://es-monit-st.cern.ch/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-02T00:00:00.000Z',to:'2022-05-02T23:59:59.999Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,key:data.activity,negate:!f,params:(query:'T0%20Export'),type:phrase,value:'T0%20Export'),query:(match:(data.activity:(query:'T0%20Export',type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,key:data.name,negate:!f,params:(query:AOD.28873750._000372.pool.root.1),type:phrase,value:AOD.28873750._000372.pool.root.1),query:(match:(data.name:(query:AOD.28873750._000372.pool.root.1,type:phrase))))),index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,interval:auto,query:(language:kuery,query:''),sort:!(metadata.timestamp,desc))

Would it be possible to send dataset info for all files?


thanks

Michal 
```

**Comment by svatosFZU** [comment]
Thanks, Mario. Just to be clear, the dataset information is sometimes sent, e.g.

https://es-monit-st.cern.ch/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:'2022-05-04T00:00:00.000Z',to:'2022-05-04T23:59:59.999Z'))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,key:data.dataset,negate:!f,params:(query:'data16_13TeV:data16_13TeV.00300863.physics_Main.merge.AOD.r9264_p3083_tid11192585_00'),type:phrase,value:'data16_13TeV:data16_13TeV.00300863.physics_Main.merge.AOD.r9264_p3083_tid11192585_00'),query:(match:(data.dataset:(query:'data16_13TeV:data16_13TeV.00300863.physics_Main.merge.AOD.r9264_p3083_tid11192585_00',type:phrase))))),index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,interval:auto,query:(language:kuery,query:''),sort:!(metadata.timestamp,desc))

but not always (I cannot really say when).


Michal

**Comment by cserf** [comment]
See also https://github.com/rucio/rucio/issues/4557

**Comment by svatosFZU** [comment]
Hi,
as the data-taking is about to start, I would like to know when this could be implemented.

**Comment by rcarpa** [comment]
Can somebody please explain where does the data from that kibana link come from ? It doesn't seem to be entirely generated by rucio. Many fields don't seem to come from rucio. Is there some system in the middle which takes data from rucio and transforms it/adds additional fields ?

**Comment by Foorth** [comment]
Hi @rcarpa ,

yes the Monit team enriches this data using a spark job (if I remember correctly). At the moment, it is not clear to us why this field is present for all jobs in the ElasticSearch index except T0. 

Cheers,
Aleksandr

**Comment by rcarpa** [comment]
I'm confused because I cannot find any place where this would be set by rucio for the cases when it is actually set :/

**Comment by Foorth** [comment]
Not sure if I can help you here, but this comes from Rucio Tracers. We have a similar index, but the data in it is not written in an enriched form:
https://es-atlas.cern.ch/kibana/goto/e683ea0d8000ba0fa284be6acf0d8cfb?security_tenant=global

**Comment by rcarpa** [comment]
yes, it helps. Thanks! I was very confused by `dataset` containing both `scope` and `name` separated by a colon. Rucio never sends it in such a format. The non-enriched index proves that. So the `dataset` field in the previous dashboard was actually enriched by spark.

**Comment by svatosFZU** [comment]
Hi @rcarpa ,
is this info sufficient? So, should this be addressed in rucio or in monit?

**Comment by rcarpa** [comment]
Hi @svatosFZU , there is a pull request in rucio waiting for review: https://github.com/rucio/rucio/pull/5646 
It should be sufficient to fix the issue if it's accepted to be merged.

**Comment by svatosFZU** [comment]
Hi,
it is great that the problem was solved. But can I ask when the version with this solution will be put into production?

**Comment by rcarpa** [comment]
It will come with the 1.29 release to production. If everything goes smoothly : in a week or two. Can be longer if issues are detected with this major release

**Comment by rcarpa** [comment]
Hi @svatosFZU , it is running in production now.

**Comment by svatosFZU** [comment]
Hi @rcarpa ,
unfortunately, I still cannot see the T0 Export data with dataset defined. 

https://es-monit-st.cern.ch/kibana/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-01T00:00:00.000Z',to:'2022-07-12T23:59:59.999Z'))&_a=(columns:!(data.pandaid),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,key:data.activity,negate:!f,params:(query:'T0%20Export'),type:phrase,value:'T0%20Export'),query:(match:(data.activity:(query:'T0%20Export',type:phrase)))),('$state':(store:appState),exists:(field:data.dataset),meta:(alias:!n,disabled:!f,index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,key:data.dataset,negate:!f,type:exists,value:exists))),index:d2660fe0-d0ba-11ea-a34a-f59641c8979f,interval:auto,query:(language:kuery,query:''),sort:!(metadata.timestamp,desc))

Could you tell me where the rucio sends it (name of index, producer, or whatever you could find)? I will then discuss with the monit team how these data can be accessed.

**Comment by svatosFZU** [comment]
Just for closure:
It turned out that the dataset field just was not taken into account when received ([RQF2083975](https://cern.service-now.com/service-portal?id=ticket&table=u_request_fulfillment&n=RQF2083975)).
