### ISSUE TITLE
implement sending logs directly to ES

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5573]
Motivation
----------
In servers, we write logs to a file. Then have filebeat read that file, merge lines together, and send it to ES. This is counter-productive. First of all, we can send formatted ES messages directly from our logger. Second, filebeat does a bad job of merging stacktraces into one message, making it completely impossible for an operator to find meaningful information in ES

**Comment by maany** [comment]
I could take this over @rcarpa if you prefer to spend effort on other things ;)

**Comment by rcarpa** [comment]
Feel free to pick it up if you want :)

**Comment by rcarpa** [comment]
Just to inform that I'm working on it
