### ISSUE TITLE
dark-reaper not exposing the prometheus metrics port

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5574]
Motivation
----------
The prometheus target is always down when enabling metrics via the helm chart. 

Modification
------------
Either fix the helm chart to not try to scrape dark reaper (difficult fix); or instantiate the prometheus metric endpoint (without any metrics) in dark-reaper (very simple fix)

**Comment by ericvaandering** [comment]
We selectively scrape things in CMS with pod annotations.

**Comment by rcarpa** [comment]
Hi, thanks for the info. I didn't check the helm chart when writing this ticket and thought that pod annotations are common for all daemons. Still, even with them being per-component, I would like to avoid having to set them manually on each component just to avoid scrapping one component. So the ticket is still relevant IMHO
