### ISSUE TITLE
Performance regression with 1.28.4

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#5593]
Motivation
----------
On the ATLAS deployment we saw a performance regression on writers with the 1.28.4 release.

![Screenshot 2022-05-23 at 14 58 43](https://user-images.githubusercontent.com/983013/169824675-84692eed-64f7-4f15-bf3e-52633e6488da.png)

As far as I can tell this is mostly related to

```
POST /dids/attachments
POST /rules/
```

commands. But this needs to be investigated.

I suspect either https://github.com/rucio/rucio/commit/1f191d1c5a085bb90975ebc5617af90a593d973a or https://github.com/rucio/rucio/commit/a0555abd6816b8b76fae8c11372a5d8c4781881a to be the issue here.

Modification
------------
TBD

**Comment by bari12** [comment]
Confirmed, it is 1f191d1c5a085bb90975ebc5617af90a593d973a at fault. 
Commit is reverted for now until further investigation

**Comment by rcarpa** [comment]
Nobody checked what queries where at fault ?
