### ISSUE TITLE
Support overriding the account of replication rules produced by subscriptions

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5599]
Motivation
----------

https://github.com/rucio/rucio/blob/b8e5795c5065a5d493cf9e4088169ddd48c26b3a/lib/rucio/daemons/transmogrifier/transmogrifier.py#L293

Modification
------------

If `account` is specified in a `replication_rule` definition, then said rule should be created with that account.

**Comment by cserf** [comment]
Note : We have to check that a normal user creating a subscription is not able to create rules with an account with higher privileges (e.g. `root`)

**Comment by dchristidis** [comment]
I would suggest only allowing this feature for subscriptions owned by accounts of type `admin=True`.

**Comment by cserf** [comment]
Actually, this is the permission for `add_subscription` for `generic` and `atlas` policies:
```python
def perm_add_subscription(issuer, kwargs, session=None):
    """
    Checks if an account can add a subscription.

    :param issuer: Account identifier which issues the command.
    :param kwargs: List of arguments for the action.
    :param session: The DB session to use
    :returns: True if account is allowed, otherwise False
    """
    if _is_root(issuer) or has_account_attribute(account=issuer, key='admin', session=session):
        return True
    return False
```

So normal users cannot create subscriptions.
