### ISSUE TITLE
create_did_sample broken for DIDs with "/"

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5608]
Motivation
----------
`create_did_sample` is broken for DIDs with "/" (problem at the REST layer), so cannot be used for policies with `SCOPE_NAME_REGEXP = '/([^/]*)(?=/)(.*)'` (Belle II, CMS, Icecube, etc.)

**Comment by ThePhisch** [comment]
https://github.com/rucio/rucio/blob/937c75344c68a143c278e42fa853918eb452b56a/lib/rucio/web/ui/static/rucio.js#L1387-L1405

the webui uses `create_did_sample` too, this needs to be reworked (and tested!!)
