### ISSUE TITLE
Fix the trailing-whitespaces and file-ends

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5618]
Motivation
----------
The `end-of-file fixer` and `trailing-whilespace` pre-commit hooks change some files, due to their incorrect formatting.

It is a good practice to fix these problems, since they add clutter and inconsistencies to the code-base.

Modification
------------
Resolve the trailing whitespace and end-of-file problems.

**Comment by mlassnig** [comment]
Wait, why?

**Comment by joeldierkes** [comment]
https://github.com/rucio/rucio/pull/5428
See the comments, especially:
https://github.com/rucio/rucio/pull/5428#discussion_r872176409
https://github.com/rucio/rucio/pull/5428#discussion_r872187154

**Comment by joeldierkes** [comment]
When run on the entire repository:
```bash
$ pre-commit install
pre-commit installed at .git/hooks/pre-commit
$ pre-commit run --all-files end-of-file-fixer
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing etc/docker/dev/README.rst
Fixing etc/sql/oracle/jobs.sql
Fixing tools/monitoring/visualization/transfer_destinations.json
Fixing .pep8
...
Fixing .github/actions/build-images-and-run-tests/action.yml
```

`end-of-file-fixer`: 47 files get changed
`trailing-whitespace`: 34 files get changed

A possibility would be to fix the files and keep the pre-commit hooks, I'd actually prefer this.

**Comment by mlassnig** [comment]
Yes, the fixers are doing the right thing. The way we deal with the webui version file is wrong though.

**Comment by joeldierkes** [comment]
:+1: 

Lets fix it then!
