### ISSUE TITLE
Declare a list of bad replicas bug

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5642]
Motivation
----------
The `add_bad_dids` function in `core` creates a temporary list of dids from the input, which should be used to determine the replicas. This list (falsely labeled as `replicas_list`) https://github.com/rucio/rucio/blob/21c93bd7d02dbc70bc3127ad77fb1a1981b83058/lib/rucio/core/replica.py#L352 however is never filled. Instead, the `list_replicas` function tries to be filled https://github.com/rucio/rucio/blob/21c93bd7d02dbc70bc3127ad77fb1a1981b83058/lib/rucio/core/replica.py#L357

This should throw an error.

The bug got introduced in https://github.com/rucio/rucio/commit/f432881425d62aa35979a0b726c2c2ea512abcd2, the `add_bad_dids` function is not tested.

Modification
------------
Resolve the bug, add tests.

**Comment by joeldierkes** [comment]
The commit with the bug got merged four months ago, a follow-up may be needed to determine some inconsistent data.

**Comment by bari12** [comment]
@cserf I think this is only used by Belle 2? Did this ever show up?

**Comment by cserf** [comment]
:scream: 
Still running 1.26.4, so we're safe. Thanks @joeldierkes for catching this stupid bug

**Comment by bari12** [comment]
This just came up on Slack, CMS is actually affected by this, so we should fix this for the next release.
