### ISSUE TITLE
Split the availability value into its respective values

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5664]
Motivation
----------
The `availability` column (in RSEs and DIDs) is an integer value where the three lest significant bits represent the different values for read, write and delete. This has some drawbacks:

- The SQL queries get overcomplicated due to arithmetic
- The code gets unreadable because of the bit shifting

While it saves space compared to three bits saved separately (and therefore storing each value in its own byte), the save is negligible.

Modification
------------
Split the `availability` column into three different ones: `availability_read`, `availability_write`, `availability_delete`.

- [ ] RSE
- [ ] DID

**Comment by dchristidis** [comment]
I believe this issue may be mark as resolved with #5858. The RSE availability is done. The DID availability is completely different and must *not* be changed.
