### ISSUE TITLE
bin/rucio upload/download still have a lot of return FAILURE statements

### ISSUE THREAD

**Issue by TWAtGH** [rucio/rucio#567]
Motivation
----------
Pilot2 test cases are parsing the output of rucio download in case of errors. The tests are failing because there are still cases in rucio download where return FAILURE is used instead of raising the appropriate exception.

Modification
------------
Change return FAILURE statements to raising the correct exceptions.

Expected behavior
-----------------

**Comment by bari12** [comment]
As discussed today, this should probably be coordinated with @TomasJavurek as he is already working on the download function.
