### ISSUE TITLE
Rework caching

### ISSUE THREAD

**Issue by akselaase** [rucio/rucio#5675]
Motivation
----------
The codebase is currently littered with `REGION.get` and checks for `NO_VALUE` to determine cache misses, as well as multiple places with insufficient cache invalidation (for instance, `add_rse_attribute` currently doesn't invalidate the keys for `get_rse_attribute`, instead causing wrong values returned from the cache).

Modification
------------
Add a new `cache` decorator that can be applied to functions eligible for caching (like `get_rse_attribute`). The decorator handles cache lookups and calls the inner function on misses. Another new `invalidates_cache` decorator can be applied to functions like `add_rse_attribute` to invalidate the relevant cache keys.

Example usage:

```python3
@cache(prefix=rucio.cache.keys.rse_attribute, exclude=['session'])
def get_rse_attribute(self, rse_id: str, key: str, session=None):
    ...

@invalidates_cache(prefix=rucio.cache.keys.rse_attribute, exclude=['value'])
def add_rse_attribute(self, rse_id: str, key: str, value=None):
    ...
```

The decorates would as demonstrated accept the argument `exclude` to exclude certain parameters from being used in the cache key, or optionally an `include` argument to specifically pick certain parameters for the key.

### Different cache backends
The `cache` decorator, as a common point of entry, enables the ability to use different caching backends (no caching, Python functools-lru, memcached, ...) without having to change anything elsewhere. To implement this, an abstract caching interface will be defined, which a specific subclass to wrap the current memcache-region implementation. Other subclasses can later be implemented if needed, and they can be activated depending on config values or the executable (for instance, client-code could enable a dummy-implementation that does no caching, potentially removing the current `WARNING:root:Cannot import pymemcache. Caching will be disabled` spam).

#### Disabling cache (tests, client-code)
Refactoring the caching logic to a separate module also allows easily changing caching behavior (useful in tests and client code) without having to recursively pass relevant arguments through multiple functions, for instance: 

```python3
with disable_cache():
    _ = get_rse_is_checksum_supported('md5', 'test_rse_id')
```

instead of

```python3
_ = get_rse_is_checksum_supported('md5', 'test_rse_id', use_cache=False)

def get_rse_is_checksum_supported(..., use_cache: bool):
    ...
    get_rse_supported_checksums(..., use_cache=use_cache)
    ...

def get_rse_supported_checksums(..., use_cache: bool):
    ...
    get_rse_attribute(..., use_cache=use_cache)
    ...
```

This would be implemented through some thread-local state determining which caching backend is active.

### Cache keys
Cache keys would be defined in the `rucio.cache.keys` module, which provides a direct overview of all keys in use, and provides IDE and tooling support to prevent misspelling keys. Though, it only defines the prefix, and the `cache` decorator has to determine the full key by combining the prefix and the values of the specified arguments. The same arguments therefore have to appear in all functions using the same cache key (`add`, `get`, `delete`, ...).

Alternatively, the cache-key could be provided inline with the function definition:

```python3
@cache(key="rse_attribute_{rse_id}_{key}")
def get_rse_attribute(rse_id: str, key: str):
    ...

@invalidates_cache(key="rse_attribute_{rse_id}_{key}")
def add_rse_attribute(rse_id: str, key: str, value):
    ...
```

This looses the benefit of tooling/IDE code suggestion for attribute keys defined in the common `rucio.cache.keys` module, which leads to increased risk of spelling mistakes. On the other hand, it does provide more freedom in what the cache key looks like.

**Comment by rcarpa** [comment]
Almost everything you speak about is natively supported by dogpile.cache. This includes using it as a decorator. And multiple cache backends, including one which doesn't do caching (disables the cache). 

Considering the `WARNING:root:Cannot import pymemcache. Caching will be disabled` spam: it is a desired behavior. The issue is not the message being printed, but the fact that client code for some reason tries to access memcached. The correct fix is to ensure that clients don't even try to access the cache : https://github.com/rucio/rucio/issues/5656

Some improvements can definitely be done to the caching layer, but we must take care to not just add an additional wrapper on top of dogpile.cache (which is already a wrapper) if it's not needed.

**Comment by akselaase** [comment]
I see! Then the two actual issues are the client code importing the cache code-path and the lack of cache invalidation I guess. Closing.

**Comment by rcarpa** [comment]
I actually think it's a good idea to migrate/rework current code and use decorators for cache management. We may re-open the issue for that goal (using the function provided by dogpile.cache, I believe)

**Comment by bari12** [comment]
Getting in to that quite late. I quickly already discussed this with several people.
I think key here is to check the different caching usecases/workflows we have in the code. The reason why we don't use the dogpile decorator in many places is that it doesn't exactly do what's needed, so we would have to cover these things by the new workflow.
