### ISSUE TITLE
generate_email_for_rule_ok_notification silent fails if exception is raised

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5681]
Motivation
----------
`generate_email_for_rule_ok_notification` silently fails if `mailtemplatedir` option is not define in the `common` session, or if the directory it points to doesn't contain the file `rule_ok_notification.tmpl` :
https://github.com/rucio/rucio/blob/master/lib/rucio/core/rule.py#L1999

**Comment by bari12** [comment]
Let's add an error, however, the workflow should still go through.
