### ISSUE TITLE
transmogrifier test flacky 

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5698]
Motivation
----------
I had frequently this kind of random failure recently : https://github.com/rcarpa/rucio/runs/7183421993?check_suite_focus=true

I'm not 100% sure, but I think I only saw this happen for postgresql database. Which means it should have issues with being run in parallel with some other test. We only run parallel tests on postgresql

**Comment by cserf** [comment]
Should be fixed by this : https://github.com/rucio/rucio/pull/5644/files#diff-cc4bb39d1f378197921144c4ce4e9a96831f88652e3b30da5699f38f27182e2e (hopefully).
