### ISSUE TITLE
Pluggable LFN2PFN algorithms

### ISSUE THREAD

**Issue by bbockelm** [rucio/rucio#570]
Previously, we introduced a mechanism to specify the algorithm used for LFN2PFN at the RSE.  The options now are `default` and `identity`.  The `default` algorithm creates subdirectories based on hashes of the LFN, while `identity` is the identity function: LFN is used directly.

As new communities come in, each has their own twist on the LFN2PFN mapping.  Currently, there's no good way to add community-specific code for the mapping.  I propose we:

* In the Rucio server configuration, provide a module that is loaded on startup which can register additional plugins (mapping the algorithm name to a Python callable).
* Continue to allow the algorithm to be set per-RSE as an attribute.
* In the Rucio server configuration, specify the default algorithm to use if not specified as an attribute.

So, Rucio could continue to offer one or two stock algorithms -- but as experiments mature, this can become part of their policies.

**Comment by bari12** [comment]
Fully agree with all Brian wrote 😄(This also hooks in a little bit with the way we import external policies. eventually we should have a better mechanism to import the policies, without the need of them being part of the rucio package - but lets have a separate issue for this)

Just one side note, as I looked at the code recently. For the site2site transfers a different method (`construct_surl`) is used to build the PFN for a site2site transferred replica. This has to be changed and the method should also inherit the algorithm from the lfn2pfn function of the respective policy.

**Comment by bbockelm** [comment]
Ok, I have a work-in-progress branch for this -- will be testing this out for LIGO (where this is most urgent).

**Comment by bbockelm** [comment]
Alright, I think this one is good to go!
