### ISSUE TITLE
temp tables cannot be used with read-only user

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5716]
Motivation
----------

Details: (cx_Oracle.DatabaseError) ORA-01031: insufficient privileges
[SQL: DELETE FROM atlas_rucio."TEMPORARY_SCOPE_NAME_0"]

 from harmless looking command rucio -v get user.tpelzer.mc15_13TeV.PhPy8EG_ZH4b_qqbb_VpT.testProd_4b.7_EXT1.YODA.3_EXT0

**Comment by rcarpa** [comment]
The mystery is why a `get` reached a temporary table creation code, which is only used in delete_replicas and attach_dids right now

**Comment by rcarpa** [comment]
Ah, it's also used in get_did(dynamic) . Forgot about that one

**Comment by bari12** [comment]
Probably nothing to be done here, this is a permission issue to be solved on DB side?
