### ISSUE TITLE
Misleading warning in srm scheme 

### ISSUE THREAD

**Issue by nataliaratnikova** [rucio/rucio#575]
Motivation
----------
The srm scheme currently requires space_token as  extended_attribute, however when space_token is not set, rucio complains about  extended_attributes and web_service_path not specfied.

Modification
------------
Happens in these lines: 
https://github.com/rucio/rucio/blob/5fa4bb25b6f5b75913773b65217a5fcde6e94f1c/lib/rucio/core/rse.py#L691-L692

Expected behavior
-----------------
Ideally , space_token would be an optional attribute,  and if not used, no spacetoken should be passed to FTS transfer job submission command.    See also  #574

**Comment by bbockelm** [comment]
Note - this is fixed in `next` but not in `master`.  So, I think this becomes a backport exercise.
