### ISSUE TITLE
submitter may be using different paths from the same source on re-submission

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5778]
Motivation
----------

CMS mentioned that they had retries from the same source, but with a different path (multi-hop at second try). :

`A -> B`  at first try
`A -> C -> B` at second try 

This should not happen, unless the cost of the two paths is identical. 

Modification
------------

Check with CMS to understand what is really happening and, if the issue is confirmed, fix it

**Comment by rcarpa** [comment]
@ericvaandering , could you please confirm that's what happens, and that the cost of `A->B` != cost of `A -> C -> B`

**Comment by ericvaandering** [comment]
I think on election we do not see this.
