### ISSUE TITLE
Fix Potential for time zone confusion

### ISSUE THREAD

**Issue by akselaase** [rucio/rucio#5781]
Motivation
----------
The REST API and Clients components serializes `datetime.datetime` objects to strings for transmission between client and server. Proper treatment of time zones is important to prevent confusion around for instance rule expiry dates.

In Rucio, the client and server often uses the format `%Y-%m-%dT%H:%M:%S` to serialize dates, which does not encode time zone information. In that case the client and server have to agree on which time zone is assumed, and UTC is the most common convention. The problem is that the Rucio clients and server rarely, if not never, specify time zones to the string conversion functions and mostly use naive datetime objects, which will cause the client and servers local time to be assumed. If the client and server are located in different time zones, this could cause confusion.

I'm not entirely sure whether this is a problem in practice or not. The [Rucio Documentation](https://rucio.cern.ch/documentation/developing_with_rucio/#date-format) specifies that all dates are always in UTC, which might mitigate this issue. I am also not sure whether this mitigates the issue completely, or if it just never occurred in practice yet.

Another motivating factor is user friendliness with regards to local time zones. Updating the `rucio` command line tools to support local time zone entry could improve the user experience a bit, unless it leads to too much confusion with the existing UTC convention.

Modification
------------
Review all usages of `str(dt)`, `dt.strftime` and `dt.strptime` where `dt` is a `datetime.datetime` object, and ensure that timezones are properly formatted and parsed. Dedicated utility functions for serializing and deserializing datetime objects could help reduce code duplication.

More specifically, we should stay away from naive datetime objects, and always use TZ-aware objects. Under the assumption that naive date objects are in UTC (current behaviour), we can convert as follows
```python3
naive_date = datetime.utcnow()  # or from user-input or other sources
aware_date = naive_date.replace(tzinfo=timezone.utc)
```
We could also treat naive datetime objects as local time like this
```python3
naive_date = datetime.now()  # or from user-input or other sources
aware_date = naive_date.astimezone()
```

Then serialization and deserialization of datetime should be done using a format with the `%z` specifier, for instance
```python3
from datetime import datetime, timezone
api_format_string = '%Y-%m-%dT%H:%M:%S.%f%z'
dt = datetime.now(timezone.utc)  # or from user-input or other sources
# Serialize
res_str = dt.strftime(api_format_string)
# Deserialize
res_dt = datetime.strptime(res_str, api_format_string)
assert dt == res_dt
```

This could increase user friendliness by allowing users to enter dates in their local time zone by converting naive dates to aware dates with `.astimezone()`:
```python3
user_friendly_format_string = '%Y-%m-%dT%H:%M:%S.%f'
user_input_string = '2022-08-05T15:40:43.849406'
user_input = datetime.strptime(user_input_string, user_friendly_format_string).astimezone()
```

Displaying dates in the users' local timezone is also easy:
```python3
server_date_string = '2022-08-05T15:42:18.864398+0600'
server_date = datetime.strptime(server_date_string, api_format_string)
client_date = server_date.astimezone()
client_date_string = client_date.strftime(user_friendly_format_string) # == '2022-08-05T11:42:18.864398'
```

**Comment by akselaase** [comment]
After a bit of research I think the existing naive-UTC-approach works perfectly well without risk of TZ confusion, as long as it is consistent. The problem is that a lot of usages of `datetime.now()` should be replaced with `datetime.utcnow()`. Currently `datetime.now()`, which returns a server local time, is used multiple places where a UTC-time is assumed. Some instances:
- `core/replica.py::get_suspicious_files` 
- `core/request.py::release_waiting_requests_per_deadline`
- `daemons/automatix/automatix.py::generate_didname`
- `daemons/badreplicas/minos.py::__update_temporary_unavailable`
- `daemons/bb8/common.py::list_rebalance_rule_candidates`

So:
1) Keep using naive dates on server, under the assumption that they are all UTC. 
2) Fix instances where the UTC-assumption is broken.
3) If desired, support user-local dates for the Rucio executables

**Comment by bari12** [comment]
I think the approach to always assume UTC should be fine. We can think about adding TZ support additionally, but I am not sure if it is worth the effort. 
`datetime.now()` should indeed be replaced by `utcnow()` everywhere 👍
