### ISSUE TITLE
Reaper not processing all Epoch tombstone replicas when no space is needed

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5816]
Motivation
----------
Reaper not processing all Epoch tombstone replicas when no space is needed

**Comment by rcarpa** [comment]
I always thought this is "by design". I think we even have tests ensuring this is the case.

**Comment by rcarpa** [comment]
https://github.com/rucio/rucio/blob/9ae4c7cdaff12db9f69259314164cb41311e54ae/lib/rucio/tests/test_reaper.py#L93

**Comment by bari12** [comment]
The Epoch ones are "special". To flag a replica as "needs to be deleted right now" we just give them an epoch tombstone (Since we don't have a special flag for it otherwise)
