### ISSUE TITLE
Enforce tokens by default in Flask

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#5822]
Motivation
----------

Currently we explicitly require

`bp.before_request(request_auth_env)`

for each call that requires authentication.

We should flip this around and make that the default, and instead introduce something like

`bp.before_request(no_request_auth_env_necessary)`

on the few where it makes sense.

This provides hardening against accidental issues like #5820 [5820](https://github.com/rucio/rucio/issues/5820)

**Comment by sayang14** [comment]
Hi @mlassnig , can I take the issue? loos like there should be some modification required in https://github.com/rucio/rucio/blob/master/lib/rucio/web/ui/flask/bp.py

**Comment by bari12** [comment]
Hi @sayang14
Sorry for the late reply; Yes, feel free to submit a PR for this issue.
