### ISSUE TITLE
R2D2 wrongly creates a container if the list of dids is containing only files

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#583]
Motivation
----------

If a user specifies only files in the list of DIDs field R2D2 will still create a container and will try to put the files in the container.

Modification
------------

Check the type of DIDs and create a container of dataset accordingly.

**Comment by sahandilshan** [comment]
Hi @bari12, is it okay if I take this up?

**Comment by bari12** [comment]
Please just go ahead and submit a PR, we do not assign the tickets to a specific gsoc student, so multiple students are allowed to submit a solution for the issue.
