### ISSUE TITLE
get rid of unittest.TestCase in tests

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5840]
Motivation
----------
It puts many restrictions on usage of fixtures : https://docs.pytest.org/en/7.1.x/how-to/unittest.html#pytest-features-in-unittest-testcase-subclasses

**Comment by cserf** [comment]
It might overlap with : https://github.com/rucio/rucio/issues/5839
Have you already started working on it ? If yes, I will wait before working on the other ticket

**Comment by rcarpa** [comment]
https://github.com/rucio/rucio/pull/5841 

There are still more tests to be migrated, but I'll stop working on this issue for a while to work on another issue. What exact test files you are intending to touch ? or everything ?

**Comment by cserf** [comment]
I will just work on the following ones:
```
      - rucio_tests/test_rse_protocol_ssh.py
      - rucio_tests/test_redirect.py
      - rucio_tests/test_credential.py
      - rucio_tests/test_bad_replica.py
      - rucio_tests/test_bb8.py
      - rucio_tests/test_rse_lfn2path.py
      - rucio_tests/test_s3.py
      - rucio_tests/test_rule.py
      - rucio_tests/test_multi_vo.py
      - rucio_tests/test_naming_convention.py
      - rucio_tests/test_dataset_replicas.py
      - rucio_tests/test_did_meta_plugins.py
      - rucio_tests/test_bin_rucio.py
      - rucio_tests/test_boolean.py
      - rucio_tests/test_auditor_hdfs.py
```

**Comment by rcarpa** [comment]
Seems like test_rule has a potential to be a big merge conflict (see the PR I linked in previous message). I didn't touch any of the other files

edit: autidor_hdf too

**Comment by rcarpa** [comment]
@cserf, where are you in your work on files which you listed ? I took care of most other ones, and I'm now blocked waiting for your change
