### ISSUE TITLE
Support RFC format for X509 identities

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#5842]
Motivation
----------

For `x509` and `x509_proxy` authentication, the current implementation relies on the `LegacyDNStringFormat` configuration [^1] of `mod_ssl`. With this option enabled, the value of `SSL_CLIENT_S_DN` may look like:
```
/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=jdoe/CN=000000/CN=John Doe
```
Instead, the default format is compliant to RFC 2253/4514 and looks like:
```
CN=John Doe,CN=000000,CN=jdoe,OU=Users,OU=Organic Units,DC=cern,DC=ch
```
VOMS proxy certificates will have additional attributes. The current implementation strips them so that there’s no need to store multiple identities.

Modification
------------

Refactor the mentioned stripping code so that it can handle both formats. Add comprehensive tests to ensure that it can also handle problematic cases, like the existence of commas or slashes in the attribute values.

It’s important to note that no work is to be done on an automatic transition. Instead, it will have to be done manually with the following steps:
 1. Add RFC-2253-compliant identities for all the existing ones.
 2. Remove the use of the `LegacyDNStringFormat` configuration option.
 3. Remove the original identities.

[^1]: See comment below.

**Comment by dchristidis** [comment]
The current implementation also tries to convert a new RFC-compliant DN representation to the legacy one. This should work, except if a comma is present in any of the values.

https://github.com/rucio/rucio/blob/13a65e8d68f9a487d3181926ac1613e7b8aece5b/lib/rucio/web/rest/flaskapi/v1/auth.py#L614-L615

We need to decide whether we can remove this or if we must make it configurable.

The current situation is as follows:
|                                 | `LegacyDNStringFormat` enabled | `LegacyDNStringFormat` disabled              |
| -------------------------------:|:------------------------------ |:-------------------------------------------- |
| **Identities in legacy format** |  supported                     | relies on conversion, won’t work with commas |
|    **Identities in RFC format** |  *not supported*               | *not supported*                              |

The proposed changes, without adding an additional configuration option, will result in:
|                                 | `LegacyDNStringFormat` enabled | `LegacyDNStringFormat` disabled |
| -------------------------------:|:------------------------------ |:------------------------------- |
| **Identities in legacy format** |  supported                     | *not supported*                 |
|    **Identities in RFC format** |  *not supported*               | supported                       |

**Comment by ivmfnal** [comment]
Is not this true that legacy DN always starts with '/' and in RFC format it never starts with '/' ?

**Comment by dchristidis** [comment]
Yes, this is true. We will continue relying on this fact in order to remove the additional attributes from VOMS proxy certificates.

**Comment by ivmfnal** [comment]
I was trying to propose a slightly different solution.

Instead of trying to convert one text representation format to another, parse the text representation of DNs from the client and from the DB into a dictionary keyed by the field name holding sorted lists of values for repeating fields with the same name. The parser can be written to parse both formats, recognizing the format based on first character of the text DN - whether it is '/' or not.

For example, both DNs above can be parsed to the same dictionary:
```
{
  "DC": ["cern","ch"],
  "OU":["Organic Units", "Users"],
  "CN":["000000","John Doe","jdoe"]
}
```

And then compare the dictionaries.  

here is what I meant in Python:
```python
import re

class DN(object):

    def __init__(self, inp):
        self.Text = inp
        self.Fields = self.parse(inp)

    def __str__(self):
        return f"DN({self.Text})"

    __repr__ = __str__


    RFCRE=re.compile(",?([A-Z]+)=")
    LegacyRE=re.compile("/([A-Z]+)=")

    @staticmethod
    def parse(text):
        fields = {}
        if text.startswith('/'):
            parts = DN.LegacyRE.split(text)[1:]
        else:
            parts = DN.RFCRE.split(text)[1:]
        pairs = [parts[i:i+2] for i in range(0, len(parts), 2)]
        for name, value in pairs:
            name = name.upper()
            if name == "CN":
                # if this is numric CN, e.g. CN=12345, ignore it
                try:    _=int(value)
                except: pass
                else:   continue        # if it's an integer, skip it
            fields.setdefault(name, []).append(value)
        return {name: sorted(lst) for name, lst in fields.items()}

    def __eq__(self, other):
        return self.Fields == other.Fields

    def __ge__(self, other):
        for name, lst in self.Fields.items():
            lst1 = other.Fields.get(name, [])
            if any(v not in lst for v in lst1):
                return False
        else:
            return True

    def __le__(self, other):
        return other >= self

    def legacy(self):
        out = []
        for name, values in self.Fields.items():
            for value in values:
                out.append(f"/{name}={value}")
        return ''.join(out)

    def rfc(self):
        out = []
        for name, values in self.Fields.items():
            for value in values:
                out.append(f"{name}={value}")
        return ','.join(out)
```

**Comment by dchristidis** [comment]
I am intrigued by your proposal. Right now, I have one major concern: for accounts with a lot of identities, this would mean having to load, parse and compare all of them. Maybe we can first do the simple database lookup, then go over this procedure. Still, to be investigated.

Let me consider it some more and get back to you.

**Comment by ivmfnal** [comment]
Does Oracle support JSON as native data type ?
If it was Postgres, I would store JSON representation of the parsed DN in the database as jsonb data.

**Comment by dchristidis** [comment]
No, moving to JSON would necessitate a schema change and add more complexity. This should not be taken lightly.

@bari12 brought up another major issue: for the Web UI, Rucio initially knows only the DN and tries to guess the default account. If it’s not already in the database in the correct format, then we would have to fetch, process, and compare *all* identities.

Finally, the RFCs are significantly more complex than this implementation would suggest. I’m sure we could improve compliance, but it’s something that we should not pursue at this time.

For the above reasons, we decided that it’s best to stick to the original plan for the 1.30 release, then potentially explore this alternative option in a future release.
