### ISSUE TITLE
incorrect rse_expression length in rule_history* migrations

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5846]
Motivation
----------

The rse_expression length in "rule history" and "recent rule history" tables doesn't correspond to what is expected in models:

Ex: 
https://github.com/rucio/rucio/blob/46dc0d03dccdd8d676e2c3af64146cea968d3fa8/lib/rucio/db/sqla/models.py#L1143
vs 
https://github.com/rucio/rucio/blob/2a41a64899f41b356660fff80a7530765b5d59e0/lib/rucio/db/sqla/migrate_repo/versions/384b96aa0f60_created_rule_history_tables.py#L56

This results in the table being created with wrong string length when applying migrations. Also, the length allowed in rules is different from the one allowed in rule_history.

Modification
------------
Add another migration which correctly extends the column to have the correct length everywhere.

**Comment by bari12** [comment]
I think in the oracle schema we actually defined this correctly.
https://github.com/rucio/rucio/blob/5454697ab981db8c700afe9ab1a737e0947dbfac/etc/sql/oracle/schema.sql#L738
Nevertheless this needs to be corrected for everyone else.

@dchristidis can you take care of this?
