### ISSUE TITLE
test files not transferred using preparer

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5873]
Motivation
----------

Test files, like `tests:step14.98537.16336.recon.ESD.63546.99070` are put directly into 'Queued' state even when `use_preparer` is enabed. These files should come from Automatix and Transmogrifier.

Ensure transfers are correctly put into the "preparing" state

**Comment by bari12** [comment]
Is this still the case?

**Comment by rcarpa** [comment]
I wonder if it always was some miss-configuration on ATLAS side. Transmogrifier uses "add_rule" internally, which "should" respect "use_preparer" configuration.

**Comment by cserf** [comment]
I also think it is a mis-configuration. As you mention the `transmogrifier` uses `add_rule` so it should be done properly. My assumption is that at that time we had a `transmogrifier` running were the configuration was not set (`use_preparer` is not defined in the config table but in `rucio.cfg`). But it's hard to confirm after 8 months

**Comment by rcarpa** [comment]
I'm closing the issue then. There doesn't seem to be anything to fix here
