### ISSUE TITLE
sign_url used either as a RSE setting or RSE attribute

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5895]
Motivation
----------
Sometimes sign_url is extracted from rse settings (e.g. https://github.com/rucio/rucio/blob/e5d701a555ebdec64d10361523390365a32402a6/lib/rucio/daemons/reaper/reaper.py#L168), sometimes it comes from RSE attribute : (e.g. https://github.com/rucio/rucio/blob/38ec2ecafe436fafbc148176a9ab3244b3815be6/lib/rucio/core/transfer.py#L209)
We need to use it in a coherent way (either as RSE setting or RSE attribute)

**Comment by bari12** [comment]
It's not really RSE settings. It's just a different way to load the attribute. But if you follow the path how the `rse_info` is loaded, you end up here
https://github.com/rucio/rucio/blob/1326078774bb1bd77361788e3dc9fc513f5fc42d/lib/rucio/core/rse.py#L1111
Which just loads the attribute.

I agree that this can be made more obvious, but both of them read it from the attributes.
