### ISSUE TITLE
Support STAGEIN requests in preparer daemon

### ISSUE THREAD

**Issue by maatthias** [rucio/rucio#5904]
Motivation
----------
In the ATLAS PanDA workflow for QoS the preparer and stager daemons are used for stagein requests.  Currently the preparer daemon only handles `TRANSFER` requests.

Modification
------------
Add support for `STAGEIN` requests.

**Comment by mlassnig** [comment]
Can I propose to use the more generic terms used by the tape community, i.e., `ARCHIVE` (to tape) and `RECALL` (from tape)?

**Comment by maatthias** [comment]
Do you mean in the issue description above?  Sure I can change that to be generic for archive/recall.  However I purposefully refer above to the RequestType enum here https://github.com/rucio/rucio/blob/1326078774bb1bd77361788e3dc9fc513f5fc42d/lib/rucio/db/sqla/constants.py#L141

**Comment by bari12** [comment]
Yes, this is nothing new, it's already how it is named in Rucio (since many years). I would just keep it like it, there is not much to gain in renaming.
