### ISSUE TITLE
Automatix / transmogrifier race condition

### ISSUE THREAD

**Issue by astroclark** [rucio/rucio#5945]
Motivation
----------
Transmogrifier is often / sometimes failing to set rules for subscriptions to automatix data. 

It looks like a race condition:  the new version of automatix uses the upload client to create datasets and *then* sets the metadata for the new DIDs.

If transmogrifier runs and processes the new DIDs *before* automatix has finished uploading, it does not find any matching subscriptions as there is not yet metadata associated with the DIDs.  Those DIDs are then no longer new to transmogrifier and will be ignored in future cycles.

This will presumably affect anything created with the UploadClient whose metadata is attached afterwards.

Modification
------------
I think this can be mitigated by simply making sure the transmogrifier sleep cycle is >> the automatix / upload client work cycle.

Ultimately, I guess the upload client needs to know about metadata so that metadata can be attached at DID creation time.

**Comment by astroclark** [comment]
I just realised there is an additional consequence of the distinct upload/set_metadata operations:  if an upload fails (say due to some transient problem on an end point), we still get dataset and file DIDs but they have no metadata.  Consequently, we sometimes get infinitely long-lived DIDs and rules for automatix datasets/files even when `dataset_lifetime` is defined.

**Comment by cserf** [comment]
I think that the best solution is to modify the upload client to accept metadata. That shouldn't be too complicated as the`add_dataset` method used in `upload_client` https://github.com/rucio/rucio/blob/master/lib/rucio/client/uploadclient.py#L372 can already accept metadata.
