### ISSUE TITLE
Ability to run Web UI without access to the database

### ISSUE THREAD

**Issue by ericvaandering** [rucio/rucio#595]
Motivation
----------
Currently the web UI needs access to the DB connection to not crash. This may be simply a problem of side effects of importing modules

Expected behavior
-----------------
Stand alone web UI with a minimal rucio config and httpd config should be possible.

**Comment by ericvaandering** [comment]
Is this needed still?

**Comment by tbeerman** [comment]
Without the DB there are no tokens and without tokens the webui will be quite useless. It will still show the header and it is possible to go to the different pages but the content won't be loaded. So not really useful. I'll close this issue.
