### ISSUE TITLE
lfn to pfn for file: protocol returns localhost in the path

### ISSUE THREAD

**Issue by dougbenjamin** [rucio/rucio#5963]
Motivation
----------

At BNL for the sPHENIX, we use Lustre storage where the Lustre client is mounted on all compute nodes.

for example - 

[sphnx02]> ls -ltr /sphenix/lustre01/sphnxpro/rucio/user/tmaeno/04/f6/user.tmaeno.5ac80131-087b-4e1b-9849-982607576e0e.log.121832.000001.log.tgz
-rw-r--r-- 1 sphnxpro sphenix 162844 Jun 20 07:53 /sphenix/lustre01/sphnxpro/rucio/user/tmaeno/04/f6/user.tmaeno.5ac80131-087b-4e1b-9849-982607576e0e.log.121832.000001.log.tgz

and yet - 

[sphnx02]> rucio list-file-replicas user.tmaeno:user.tmaeno.5ac80131-087b-4e1b-9849-982607576e0e.log.121832.000001.log.tgz
+-------------+----------------------------------------------------------------------------+------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
| SCOPE       | NAME                                                                       | FILESIZE   | ADLER32   | RSE: REPLICA                                                                                                                                            |
|-------------+----------------------------------------------------------------------------+------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------|
| user.tmaeno | user.tmaeno.5ac80131-087b-4e1b-9849-982607576e0e.log.121832.000001.log.tgz | 162.844 kB | 32cb5d67  | BNL_PROD: file://localhost/sphenix/lustre01/sphnxpro/rucio/user/tmaeno/04/f6/user.tmaeno.5ac80131-087b-4e1b-9849-982607576e0e.log.121832.000001.log.tgz |
+-------------+----------------------------------------------------------------------------+------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------+

Notice /localhost part of pfn.   Rucio download works but so should other posix access methods using the Lustre client. 

Here is how the RSE is set up -

```[sphnx02]> rucio-admin rse info BNL_PROD
Settings:
=========
  availability_delete: True
  availability_read: True
  availability_write: True
  credentials: None
  delete_protocol: 1
  deterministic: False
  domain: ['lan', 'wan']
  id: f7594e2cb9304cdc8ee4130e2c3f1cc7
  lfn2pfn_algorithm: hash
  qos_class: None
  read_protocol: 1
  rse: BNL_PROD
  rse_type: DISK
  sign_url: None
  staging_area: False
  third_party_copy_protocol: 1
  verify_checksum: True
  volatile: False
  write_protocol: 1
Attributes:
===========
  BNL_PROD: True
Protocols:
==========
  file
    domains: '{"lan": {"read": 1, "write": 1, "delete": 1}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 0}}'
    extended_attributes: None
    hostname: localhost
    impl: rucio.rse.protocols.posix.Default
    port: 0
    prefix: /sphenix/lustre01/sphnxpro/rucio
    scheme: file
  root
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 0, "write": 0, "delete": 0, "third_party_copy": 0}}'
    extended_attributes: None
    hostname: xrdsphenix.rcf.bnl.gov
    impl: rucio.rse.protocols.gfal.Default
    port: 1094
    prefix: //sphenix/lustre01/sphnxpro/rucio
    scheme: root
Usage:
======
  rucio
    files: 0
    free: None
    rse: BNL_PROD
    rse_id: f7594e2cb9304cdc8ee4130e2c3f1cc7
    source: rucio
    total: 0
    updated_at: 2022-02-09 09:47:52
    used: 0
RSE limits:
===========```


Modification
------------

**Comment by maatthias** [comment]
As a quick and dirty test I set hostname to empty string in database table rse_protocols and saw that the proper local path was returned on rucio download command.  This is of course not a fix but at least demonstrates that the fix in code for path construction could be trivial.

**Comment by bari12** [comment]
Just to get this right, instead of 
`file://localhost/sphenix/lustre01/sphnxpro/rucio...` you want `/sphenix/lustre01/sphnxpro/rucio...`
I think the best way to do this would be to add this as a subclass of the `Default` implementation. Similar to the `Symlink` one. Would obvious only work if this is locally mounted.

**Comment by dougbenjamin** [comment]
Hi,
   The mounts are “local” across all compute nodes. The lustre mount point on each machine is /sphenix/lustre01/…..

Doug

From: Martin Barisits ***@***.***>
Reply-To: rucio/rucio ***@***.***>
Date: Wednesday, November 23, 2022 at 10:52 AM
To: rucio/rucio ***@***.***>
Cc: Doug Benjamin ***@***.***>, Author ***@***.***>
Subject: Re: [rucio/rucio] lfn to pfn for file: protocol returns localhost in the path (Issue #5963)


Just to get this right, instead of
file://localhost/sphenix/lustre01/sphnxpro/rucio... you want /sphenix/lustre01/sphnxpro/rucio...
I think the best way to do this would be to add this as a subclass of the Default implementation. Similar to the Symlink one. Would obvious only work if this is locally mounted.

**Comment by dougbenjamin** [comment]
Any update on a solution for this issue? DUNE will also need this for its RSE's eventually.

**Comment by maatthias** [comment]
When the file is found on storage this line https://github.com/rucio/rucio/blob/c9545766c92b7c279cc1345fa656950c8f71557c/lib/rucio/rse/protocols/posix.py#L186 returns ```scheme://hostname/prefix```.  Can we just change this to return only the prefix ```/sphenix/lustre01/sphnxpro/rucio...``` ?  Or will that collide with others?

**Comment by bari12** [comment]
It might collide with others, so it should be done as a new subclass basically. Then instead of using
```
impl: rucio.rse.protocols.posix.Default
```
you use
```
impl: rucio.rse.protocols.posix.WithoutHostname
```
and this should work fine.

**Comment by bari12** [comment]
We discussed this in the Rucio meeting on [Feb-16](https://indico.cern.ch/event/1250017/); Opinion was to adapt the Default implementation if no external tool actually requires these `file://...` urls.
