### ISSUE TITLE
Automatix: Default value for set_metadata differs from documentation

### ISSUE THREAD

**Issue by d-ylee** [rucio/rucio#5965]
Motivation
----------
While deploying the `automatix` daemon for 1.29.8, I noticed that an error was occurring when the daemon tries to set metadata:
```
Traceback (most recent call last):
 File "/usr/local/lib/python3.6/site-packages/rucio/daemons/common.py", line 144, in run_daemon
  must_sleep = run_once_fnc(activity=activity, heartbeat_handler=heartbeat_handler)
 File "/usr/local/lib/python3.6/site-packages/rucio/daemons/automatix/automatix.py", line 228, in run_once
  scope=scope, name=dsn, meta=metadata, recursive=False
 File "/usr/local/lib/python3.6/site-packages/rucio/client/didclient.py", line 498, in set_metadata_bulk
  raise exc_cls(exc_msg)
rucio.common.exception.AccessDenied: Access to the requested resource denied.
```
This is expected because our deployment does not have the `perm_set_metadata` permission enabled.

This error occurs at these lines: https://github.com/rucio/rucio/blob/74c4da7bfc04cbe257ad9ab8717b4ac444240f8f/lib/rucio/daemons/automatix/automatix.py#L226-L232

In my configuration, I did not set the value `set_metadata` to anything. In the `run_once` function, `set_metadata` has defaulted to `True`: https://github.com/rucio/rucio/blob/74c4da7bfc04cbe257ad9ab8717b4ac444240f8f/lib/rucio/daemons/automatix/automatix.py#L156-L158

However, the documentation states that `set_metadata` should default to `False`: https://rucio.cern.ch/documentation/configuration_parameters/#rucio-configuration-table

A previous commit also has `set_metadata` default to `False`: https://github.com/rucio/rucio/blob/280249bf2e2d51936f59321841fa50a289d4a15b/lib/rucio/daemons/automatix/automatix.py#L48

Modification
------------
Should the default value of `set_metadata` be `True` or `False`?

**Comment by bari12** [comment]
Hi,
Sorry for the late reply. @cserf and myself just got to this in review. Better not change the current behaviour, but the documentation.

**Comment by bari12** [comment]
@d-ylee ping :-) any update on this?

**Comment by d-ylee** [comment]
@bari12 Sorry about that. I pushed changes in a PR (rucio/documentation#323)
