### ISSUE TITLE
RSE lfn2pfn attribute is ignored

### ISSUE THREAD

**Issue by jamesp-epcc** [rucio/rucio#5969]
Currently the lfn2pfn algorithm attribute for RSEs is ignored and the algorithm set in the configuration file is always used. Ideally the attribute should be able to override the config file setting for an individual RSE so that different RSEs can use different naming schemes.

**Comment by bari12** [comment]
Is this a regression @jamesp-epcc ? I thought this was working already.

**Comment by jamesp-epcc** [comment]
I have tested again and it is working now. I am not sure what happened when I tested previously. I will close this now. Sorry for the confusion.
