### ISSUE TITLE
Getting support links don't work

### ISSUE THREAD

**Issue by clelange** [rucio/rucio#5971]
I'm trying to get help with understanding stuck rucio rules (in particular the meaning of `RequestErrMsg.TRANSFER_FAILED:Unused hop in multi-hop` for which I cannot receive any support from within CMS nor can I find any pointers in the documentation) and it seems that the only way of getting support provided in the README is to write to a google group (rucio-users@googlegroups.com) or sign up to a slack chat.

- Using the slack link leads to a login page, but it doesn't allow me to create an account.
- Sending an email to the google group, I receive an error that I'm not allowed to send email to this group.

How can I ask for support? Are there any CERN-internal channels I can/should use?

**Comment by bari12** [comment]
Hi @clelange 
Sorry only reading this now. You should reach out to CMS to get this resolved. Transfer failures are highly deployment and configuration dependent, so we can't really generally help with these. Maybe @ericvaandering can point you to the right contact. (Transfer team?)
