### ISSUE TITLE
better handling of "archiving" transfers when destination exists

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#5975]
Motivation
----------

Rucio has specific logic to mark transfers successful when the destination file already exists and is correct:
https://github.com/rucio/rucio/blob/8eb35a3fb58a29208347050ab7052cd3c178c1ad/lib/rucio/transfertool/fts3.py#L467

However, this logic plays badly with the "archiving" requests. In those cases, FTS returns
```
dst_file['file_on_tape'] == False
```
So, the transfer is marked as failed and retried by rucio. As archival can take multiple days, Rucio will spend time submitting requests and retrying until the archival is complete. 

Modification
------------
FTS supports a specific type of transfers: "Archival monitoring". If the following condition is met:
```
src_url == dst_url AND archive_timeout > 0
```
FTS will monitor the archival to tape and only report completion when the archival is Done.

**Comment by mpatrascoiu** [comment]
I definitely encourage improving the archive `destination file exists` handling!

However, for the FTS condition of archive-monitoring only (`src_url == dst_url AND archive_timeout > 0`), you need us to implement and deploy a change. Here's the JIRA issue to track it: https://its.cern.ch/jira/browse/FTS-1865

Cheers,
Mihai

**Comment by rcarpa** [comment]
@mpatrascoiu , any ETA on the subject of the linked FTS ticket?

**Comment by KatyEllis** [comment]
@mpatrascoiu I have the same question as Radu :-)

**Comment by mpatrascoiu** [comment]
Hello both,

This would aid CMS in handling the `Destination file exists` retry loop.

We've been discussing this topic extensively with @dynamic-entropy the past weeks. At this moment, we're not fully sure [FTS-1865](https://its.cern.ch/jira/browse/FTS-1865) would help that much, which is why FTS progress is on standstill

**Comment by KatyEllis** [comment]
Ok thanks for the update, Mihai.

**Comment by rcarpa** [comment]
Any update ? @mpatrascoiu , @KatyEllis

**Comment by mpatrascoiu** [comment]
Hello Radu,

No progress on this and it's a low-priority item.

With the CMS data management team we are in the middle of a discussion concerning the `Destination file exists` when writing to tape endpoints. It looks like we will go in a `overwrite-when-only-on-disk` direction.

**Comment by rcarpa** [comment]
This is a question for CMS then: does it mean that nobody uses the `overwrite_corrupted_files` logic in rucio and we can drop support for it ?

**Comment by rcarpa** [comment]
@KatyEllis , @ericvaandering , is there any intent to use the `overwrite_corrupted_files` logic ? Or can we remove it from rucio ?

**Comment by ericvaandering** [comment]
Belated, but CMS is ok with removing this. We don't use it.

**Comment by bari12** [comment]
To be checked what code needs to be removed from FTS3 transfertool. 
https://github.com/rucio/rucio/blob/8eb35a3fb58a29208347050ab7052cd3c178c1ad/lib/rucio/transfertool/fts3.py#L449

**Comment by bari12** [comment]
Closing, followup in #6581
