### ISSUE TITLE
Webdav Protocol `stat` does not return data as specified

### ISSUE THREAD

**Issue by ThePhisch** [rucio/rucio#5977]
Motivation
----------
The docstring for `rse/protocols/webdav.py::Default::stat` states that a dict with two keys (filesize and adler32) are returned. This matches the implementations of `stat` in the SSH and xrootd protocols (although these protocols do not explicitly say that it is adler32 but any one of `GLOBALLY_SUPPORTED_CHECKSUMS`. At the moment, the implementation of webdav only returns the filesize.

Modification
------------
Add an entry to the dictionary containing the checksum.

**Comment by mohitsatr** [comment]
hi @kwaizer, have you solved this one ?

**Comment by Kwaizer** [comment]
hi @mohitsatr, I'm waiting for a review.
