### ISSUE TITLE
Add logging/debug callbacks to gfal implementation in rucio client

### ISSUE THREAD

**Issue by maatthias** [rucio/rucio#5980]
### Description

Add logging/debug callbacks to gfal implementation for rucio client.  Specifically the connect method in class rucio.rse.protocols.gfal.Default

### Motivation

At BNL we observed some timeout errors during gfal xrootd download. To get more information, would like to add logging/debug callbacks to the gfal implementation for rucio client.

### Change

Add logging/debug callbacks to gfal implementation for rucio client.  Specifically the connect method in class rucio.rse.protocols.gfal.Default at https://github.com/rucio/rucio/blob/master/lib/rucio/rse/protocols/gfal.py#L179-L184

### Additional Information

- [X] The `Core` needs to be changed.
- [ ] A `Daemon` needs to be changed.
- [ ] The `REST API` needs to be changed.
- [ ] The `API layer` needs to be changed.
- [ ] The `Client` needs to be changed.
- [ ] The change is incompatible with old Rucio versions.

**Comment by saumy-sh** [comment]
Hey @maatthias I would very much like to work on it with you but i am a newbie. Can you please help me get started with it?
