### ISSUE TITLE
BaseClient stops reauthenticating

### ISSUE THREAD

**Issue by d-ylee** [rucio/rucio#5986]
### Description

The `automatix` daemon cannot be authenticated after a few hours of working properly

### Steps to reproduce

1. Deploy rucio-server
2. Start `automatix` daemon
3. Let `automatix` run for a few hours
4. `automatix` reaches CannotAuthenticate and stops sending requests to `auth/x509_proxy` endpoint

### Rucio Version

1.29.8

### Additional Information

# Environment
* OKD4 @ Fermilab
* Authentication: `x509_proxy`

# Automatix Error Traceback
```
2022-11-18 20:52:08,397 root 1 CRITICAL automatix[e951f6c:0/1]: Exception
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/rucio/daemons/common.py", line 144, in run_daemon
must_sleep = run_once_fnc(activity=activity, heartbeat_handler=heartbeat_handler)
File "/usr/local/lib/python3.6/site-packages/rucio/daemons/automatix/automatix.py", line 223, in run_once
ret = upload_client.upload(files)
File "/usr/local/lib/python3.6/site-packages/rucio/client/uploadclient.py", line 121, in upload
rse = self.rse_expressions.setdefault(rse_expression, _pick_random_rse(rse_expression))
File "/usr/local/lib/python3.6/site-packages/rucio/client/uploadclient.py", line 103, in _pick_random_rse
rses = [r['rse'] for r in self.client.list_rses(rse_expression)] # can raise InvalidRSEExpression
File "/usr/local/lib/python3.6/site-packages/rucio/client/rseclient.py", line 132, in list_rses
raise exc_cls(exc_msg)
rucio.common.exception.CannotAuthenticate: Cannot authenticate.
```
This happens when the client is trying to access the `/rses/?expression=<rse>` endpoint on the server.

# Relevant Rucio Server Log
```
[2022-11-18 20:47:08] 10.103.3.229 10.100.3.178 - Y3fvTMqfNThlKqgvIkx43AAAAAA 500 860 80 26950 "GET /rses/?expression=DCACHE_BJWHITE_END HTTP/1.1" "automatix-/DC=org/DC=incommon/C=US/ST=Illinois/O=Fermi Research Alliance/CN=int-rucio.fnal.gov-unknown-7fa6d704e01e4f65a9ee9af70ba40cfb" "rucio-clients/1.29.8" rucio-automatix::--threads-per-process
```
# Rucio Server Traceback
I logged the traceback for the `RucioException` on Line 144:
https://github.com/rucio/rucio/blob/555ccaae224db3b54c63a4bd8898397ca501ef57/lib/rucio/web/rest/flaskapi/v1/common.py#L142-L148
```
[Fri Nov 18 20:52:08.392788 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] 2022-11-18 20:52:08,392\troot\t22\tERROR\tCannot authenticate.
[Fri Nov 18 20:52:08.392809 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] Details: NoneType: None
[Fri Nov 18 20:52:08.392810 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] Traceback (most recent call last):
[Fri Nov 18 20:52:08.392812 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] File "/usr/local/lib/python3.6/site-packages/rucio/web/rest/flaskapi/v1/common.py", line 121, in request_auth_env
[Fri Nov 18 20:52:08.392813 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] auth = validate_auth_token(auth_token)
[Fri Nov 18 20:52:08.392814 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 388, in new_funct
[Fri Nov 18 20:52:08.392815 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] result = function(*args, **kwargs)
[Fri Nov 18 20:52:08.392816 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] File "/usr/local/lib/python3.6/site-packages/rucio/api/authentication.py", line 294, in validate_auth_token
[Fri Nov 18 20:52:08.392817 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] auth = authentication.validate_auth_token(token, session=session)
[Fri Nov 18 20:52:08.392818 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 402, in new_funct
[Fri Nov 18 20:52:08.392819 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] result = function(*args, **kwargs)
[Fri Nov 18 20:52:08.392825 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] File "/usr/local/lib/python3.6/site-packages/rucio/core/authentication.py", line 437, in validate_auth_token
[Fri Nov 18 20:52:08.392826 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] value = validate_jwt(token, session=session)
[Fri Nov 18 20:52:08.392827 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] File "/usr/local/lib/python3.6/site-packages/rucio/db/sqla/session.py", line 402, in new_funct
[Fri Nov 18 20:52:08.392828 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] result = function(*args, **kwargs)
[Fri Nov 18 20:52:08.392829 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] File "/usr/local/lib/python3.6/site-packages/rucio/core/oidc.py", line 1193, in validate_jwt
[Fri Nov 18 20:52:08.392830 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] raise CannotAuthenticate(traceback.format_exc())
[Fri Nov 18 20:52:08.392831 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] rucio.common.exception.CannotAuthenticate: Cannot authenticate.
[Fri Nov 18 20:52:08.392833 2022] [wsgi:error] [pid 22] [remote 10.100.3.178:41072] Details: NoneType: None
```
# Other observations after the error occurs
* `automatix` stops uploading files
* Error repeats after each Heartbeat renewal
* `automatix` does not make any more requests to the `auth/x509_proxy` endpoint or other `auth` endpoints
* Redeploying rucio fixes the problem momentarily
* Above error is located at `rucio/core/oidc.py` but we use x509_proxy
* While the error was occuring, I checked the `x509` certificate expiration date. It had not yet not expired

# Potential Causes
Since tokens expire after 1 hour, I assume that the error is caused because automatix is trying to use an expired token, but for some reason, it isn’t getting renewed:
https://github.com/rucio/rucio/blob/555ccaae224db3b54c63a4bd8898397ca501ef57/lib/rucio/client/baseclient.py#L428-L431
Since the response error code is HTTP 500, which is not codes.unauthorized or HTTP 401, the client used in automatix does not call __get_token to get a new token

**Comment by d-ylee** [comment]
I was able to temporarily fix the problem by deleting the `auth_token_for_account_<account>` at the token path (in my case, `/tmp/<user>/.rucio_<user>`.

This makes me think that the client continues trying to use an expired token. In `baseclient.py`, the client checks to see if the file exists:
https://github.com/rucio/rucio/blob/555ccaae224db3b54c63a4bd8898397ca501ef57/lib/rucio/client/baseclient.py#L858
I think that since the file still exists, even after expiring, the `automatix` daemon's client tries to use this expired token, causing authentication to fail.

**Comment by bari12** [comment]
The underlying issue is that it is not an HTTP 401, so the code which triggers the renew is just never called. Your workaround works, but we should really look into why no 401 is sent there. Can you maybe track the call through the REST interface and see why this is just a 500?

**Comment by d-ylee** [comment]
Previously, the traceback on Rucio server leads to this location (see the Rucio Server Traceback section above): 
### First
https://github.com/rucio/rucio/blob/2934f30fef4ed051857ac992b703c7fb29915b2b/lib/rucio/web/rest/flaskapi/v1/common.py#L143

### Second

https://github.com/rucio/rucio/blob/2934f30fef4ed051857ac992b703c7fb29915b2b/lib/rucio/api/authentication.py#L299

### Third

https://github.com/rucio/rucio/blob/2934f30fef4ed051857ac992b703c7fb29915b2b/lib/rucio/core/authentication.py#L474

### Fourth

https://github.com/rucio/rucio/blob/2934f30fef4ed051857ac992b703c7fb29915b2b/lib/rucio/core/oidc.py#L1190-L1194

Since we are not using OIDC, there are no `OIDC_CLIENTS`, causing the RucioError here:
https://github.com/rucio/rucio/blob/2934f30fef4ed051857ac992b703c7fb29915b2b/lib/rucio/core/oidc.py#L1193-L1194
This is caught by this `try catch` statement.
https://github.com/rucio/rucio/blob/2934f30fef4ed051857ac992b703c7fb29915b2b/lib/rucio/web/rest/flaskapi/v1/common.py#L144-L145

which is what returns the error 500.

**Comment by bari12** [comment]
So isn't the issue then that it identifies the token as a JWT while it is a conventional Rucio token? (In Third)

**Comment by bari12** [comment]
Backport 1.29.11
