### ISSUE TITLE
Deletion broken on cloud storage

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#5997]
### Description

The following patch : https://github.com/rucio/rucio/commit/996493d6ab0b89ef3f62e4a7f21d4c4d7ad43e8f breaks the deletion on cloud storage. The signed URL that is created is only valid for the deletion. If it's used to check the existence of the file, it fails with a permission issue.

### Steps to reproduce

Really ???

### Rucio Version

1.29.0rc1 and after

**Comment by bari12** [comment]
How do we proceed with this? Rollback? Different workflow for cloud?

**Comment by bari12** [comment]
Is there any news on this @maany @cserf ?

**Comment by maany** [comment]
I have not looked into this yet. @cserf can I somehow verify this issue exists with Seal?
