### ISSUE TITLE
Listing replicas: Support storage that doesn't support multirange-byte requests

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#6006]
### Description

During a multi-range query, the client requests multiple contiguous chunks of a file. Not all servers support this, however. Some will understand the request and return a proper multi-chunk response, some will return the entire file, some will only give you the first range, and some will return an error.

If you know that a server does not support multi-range, you can instruct davix to jump straight to simulation by using a URL fragment parameter.

`https://example.org/somefile&#multirange=false`

Davix will try to lessen this performance impact by using multiple parallel HTTP connections. The default number is 10 connections, but you can override it with a URL fragment parameter. (Notice the weird `&#` construct.)

`https://example.org/somefile&#multirange=false&nconnections=30`

### Motivation

This is needed to support Google Cloud Storage for analysis with direct IO. We need to simulate the multirange byte request.

### Change

Extend `list_replicas()` (Client, REST, API, Core) to support an additional parameter, passing through the nr parallels, e.g.,

`rucio list-file-replicas .... --simulate-multirange=10`

`def list_replicas(....., simulate_multirange=10):`

(other name proposals welcome).

Such that the returned PFNs then look like:

`https://hostname:443/prefix/filename.txt&#multirange=false&nconnections=10`

(+ unit tests :-)

**Comment by bari12** [comment]
Do we need to store if an RSE supports multi-range responses? If not, why not just do this client-side?

**Comment by mlassnig** [comment]
Hmmm, yes, that's an RSE "feature", but the nr_connections are client-specific.

**Comment by bari12** [comment]
Then it's probably easier to do that client-sided.
Thus still have the `rucio list-file-replicas .... --simulate-multirange=10` command, but actually not pass this through to the server, but just append it client-sided for all `https://` urls?

**Comment by mlassnig** [comment]
Hmm, in addition the pilot calls `replicaclient.list_replicas(...)`.... are you suggesting that this should be done purely by the rucio copytool in the pilot?

**Comment by mlassnig** [comment]
After discussing with @PalNilsson we decided that giving clients the choice of the concurrency is maybe not the best idea.

So instead the implementation should look like this:

If an RSE has an RSE Attribute `multirange`:`<int>`, then apply the workaround when calling `list_replicas()`. No need for the API/client to change anything.

**Comment by bari12** [comment]
Just to confirm so everybody is on the same page:

We add an RSE attribute called `simulate_multirange:<int>` to RSEs which do not offer multirange. For these the generated PFN will be suffixed with `...#multirange=false&nconnections=<int>`

We do not add a way in the client to manually/overwrite this.

**Comment by mlassnig** [comment]
Yes, that's correct. I'm happy with `simulate_multirange` as the RSE attribute name. Thanks.
