### ISSUE TITLE
Define group/LFN correspondence check

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#6015]
### Description

We need to add additional checks for `group` scopes and lfns similar to what is done for `user` scopes. 

https://github.com/rucio/rucio/blob/9ae42908a0e188ece017bfec1b89cf2e354b383e/lib/rucio/common/schema/cms.py#L443-#L465

**Comment by dynamic-entropy** [comment]
Hi @bari12
I think a `CMS` tag would be more appropriate for the issue.
Or is it ok if I use the `enhancement` component in my commit message?

**Comment by bari12** [comment]
@dynamic-entropy we can also add the CMS tag. :-)
