### ISSUE TITLE
Extend /auth/x509 endpoint for browser-based clients

### ISSUE THREAD

**Issue by maany** [rucio/rucio#6048]
### Description

The existing `/auth/x509`  endpoint must be extended to work together with the new webui for converting `x509 certs -> rucio token`. 

In particular, it needs to return an HTTP 206 response with `X-RUCIO-AUTH-ACCOUNTS` header with a list of possible accounts in situations where the following conditions are all met: 
1. There was no account specified in the incoming request
2. The provided x509 identity was valid
3. The provided x509 identity was mapped to multiple accounts
4. There was no default account specified

After a valid authentication, it should return the `X-RUCIO-AUTH-ACCOUNT` header with the account that was ultimately used for the authentication process.

Additionally, the Apache config for rucio server in `rucio/containers` must be modified to explicitly force client certificate requests for the `/auth/x509` endpoint. This will display a pop-up in the browser for selecting a user certificate if a request is made from a browser-based client

### Motivation
The old web-ui completely bypassed this endpoint and implemented its own x509 authentication endpoint for which it required direct database access.

See the comment I have left below, which contains the old issue description, for details on how it was done in the old webui.

Since the new webui is a pure REST'ful client, the current apache config and rucio server endpoint need some tweaking to help avoid the workarounds done in the previous webui

### Change

The entire scope of work is:
-  Add a HTTP 206 response to the exiting `/auth/x509` endpoint, return more descriptive errors when x509 authentication fails ( this repo) 
- Modify httpd config to enable `SSL_CLIENT_VERIFY` for `/auth/x509` endpoint ( https://github.com/rucio/containers/issues/216 )
- Send request from the webui to '/auth/x509' endpoint (https://github.com/rucio/webui/issues/116)

For this issue, the new endpoint must handle MultiVO use-cases and situations where a x509 identity may be mapped to multiple accounts.

**Comment by rcarpa** [comment]
I don't understand why we need a new end-point for that. Why the current x509 end-point doesn't work ? it's a pure https. 

Edit: I mean this one: https://github.com/rucio/rucio/blob/2b23466beec4372ae6ae25b1e3e2a69501788a27/lib/rucio/web/rest/flaskapi/v1/auth.py#L1580-L1582

**Comment by maany** [comment]
Hey @rcarpa, you are correct that the existing x509 endpoint should work and I need to update the issue description as @bari12 mentioned in his review https://github.com/rucio/rucio/pull/6053#pullrequestreview-1267432994 

In the PR https://github.com/rucio/rucio/pull/6053, I have modified the existing x509 endpoint to handle cases where users do not explicitly specify a rucio account to be used for logging in.

Initially, I was unsure whether https://github.com/rucio/containers/pull/218 would break the CLI clients as I am not aware of exactly how apache requests client certificates. I, therefore, proposed adding a new endpoint as a precaution.

However, after some testing, I did come to the conclusion that a single endpoint with this apache config  https://github.com/rucio/containers/pull/218 works well for both CLI clients and browser-based clients.

 The PR for this issue just extends the existing x509 endpoint to handle requests from the new WebUI better, instead of creating a new endpoint as initially proposed. 

I will update the issue description now and below I have left a copy of the old issue description w.r.t which you have made the comment. Apologies about the confusion

---


### Description

A new endpoint must be introduced for handling `x509 cert -> rucio token` requests from browser-based clients.
This is required by the new WebUI, a pure REST'ful client of the Rucio server, to be able to swap an x509 certificate for a rucio token by making a request to the rucio auth server.

### Motivation

The previous WebUI circumvents the current /auth/x509 endpoint. Instead of utilizing the rucio auth server to acquire an auth token, it establishes its own /auth endpoint that directly interacts with the rucio core to obtain the rucio token.

https://github.com/rucio/rucio/blob/2b23466beec4372ae6ae25b1e3e2a69501788a27/lib/rucio/web/ui/flask/bp.py#L82

In short, the flask webui extracts the DN which was injected by apache into the incoming browser request

https://github.com/rucio/rucio/blob/2b23466beec4372ae6ae25b1e3e2a69501788a27/lib/rucio/web/ui/flask/common/utils.py#L200-L205

where, `token_method` is `get_auth_token_x509` method from `rucio.api.authentication`

Since the new webui is a pure REST client of the rucio auth server, the functionality of the old webui's `/auth` endpoint must be transferred to the rucio auth server.

At present, a `/auth/x509` endpoint exists on the rucio authserver
https://github.com/rucio/rucio/blob/2b23466beec4372ae6ae25b1e3e2a69501788a27/lib/rucio/web/rest/flaskapi/v1/auth.py#L1580-L1582

It is used by the rucio CLI clients. Unlike browser-based clients, CLI clients have access to x509 client certificate and can do the SSL handshake with the rucio authserver without the need of apache.


### Change

The entire scope of work is:
- Create a new `/auth/x509_web` endpoint ( this repo) 
- Modify httpd config to enable `SSL_CLIENT_VERIFY` for this endpoint ( https://github.com/rucio/containers/issues/216 )
- Send request from the webui to the new endpoint (https://github.com/rucio/webui/issues/116)

For this issue, the new endpoint must handle MultiVO use-cases and situations where a x509 identity may be mapped to multiple accounts.
