### ISSUE TITLE
Handle both legacy DN format and RFC 2253 format in x509 authentication

### ISSUE THREAD

**Issue by maany** [rucio/rucio#6052]
### Description

Apache HTTPD has been using the [RFC 2253](https://datatracker.ietf.org/doc/html/rfc2253) compatible format for x509 DNs (distinguished names) since version 2.3.11. This feature is over 11 years old. This format looks like 
```
CN=Steve Kille,O=Isode Limited,C=GB
```

However, some users may have their x509 certificates stored in the Rucio database in the `legacy` format that was more commonly used before. It looks like 

```
/C=GB/O=Isode Limited/CN=Steve Kille
``` 

In this case, if Apache is not configured to handle the legacy format (`LegacyDNStringFormat ` option of `mod_ssl`), the users will not be able to log in. 

To solve this issue, one possible solution is to check the format of the x509 certificate at the time of login, and if it is not in the correct format, try to convert it and check again. If the converted format works, then we can update the Rucio database with the new format.

From a quick discussion with @dchristidis, I understand this was probably how things were done earlier and that there were good reasons to stop doing them. 

However, it would be good to discuss what our plan for dealing with the different formats should be if any.

### Steps to reproduce

1. Add a rucio x509 identity in legacy format
   ```
   rucio-admin idenity add --account root --id "/DC=ch/OU=......" --email abc@xyz
   ```
2. Remove any existing rucio token from `/tmp`
3. Change `rucio.cfg` to use `x509` workflow
4. run `rucio whoami`

### Rucio Version

Server: 1.30.x

**Comment by dchristidis** [comment]
See https://github.com/rucio/rucio/issues/5842#issuecomment-1232840554 and the [release notes for 1.30](https://github.com/rucio/rucio/releases/tag/1.30.0). My opinion is that what you’re describing is not a bug.

**Comment by dchristidis** [comment]
Replaced with #6182.
