### ISSUE TITLE
The Reaper may work on the wrong set of RSEs

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6103]
### Description

Under some rather particular circumstances, it is possible for a Reaper instance to work an a different set of RSEs than the one specified through the command line arguments.

### Steps to reproduce

 1. Have an environment were multiple Reaper instances share the same Memcached instance.
 2. Start a new Reaper instance that works on a different set of RSEs that the already existing one.

### Additional Information

The issue come from the following part of the code and the fact that, in pods, the Reaper process is using PID 1.

https://github.com/rucio/rucio/blob/ea4d2c7e2702b85a86a8668b2d852971f42fceb4/lib/rucio/daemons/reaper/reaper.py#L98-L102

**Comment by cserf** [comment]
Do you think it would be enough to have a `cache_key` based on the hostname + pid ?

**Comment by dchristidis** [comment]
Just so that it isn’t forgotten: we discussed in person and we agreed that the key should probably come from some combination of the command-line arguments that affect the RSE selection (e.g. concatenate, then hash).
