### ISSUE TITLE
The transmogrifier updates the subscription history table everytime it runs

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#6109]
### Description

The subscription_history table is filled with entries without any updates to the subscription itself. 

The `transmogrifier` adds an entry to the subscription_history table on every run. 
https://github.com/rucio/rucio/blob/ea4d2c7e2702b85a86a8668b2d852971f42fceb4/lib/rucio/daemons/transmogrifier/transmogrifier.py#L694-L699

I believe the intention was just to update the `last_processed` value for the subscription. 
This also updated the `updated_at` value of subscriptions which eventually always match the `last_processed` value.

### Steps to reproduce

Set `subscriptions.keep_history` to `True` in the rucio configuration table and observe the `subscription_history` table.

`subscription_history` table after setting `keep_history` to `True`.
![image](https://user-images.githubusercontent.com/69708588/222174429-40a6b9e4-4ec1-4214-afc7-83d08bb3f1ce.png)

### Additional Information

Hi @cserf, 
Would you be able to find some time to help with this? This will help me get a sense of the code and would help with the implementation of the retroactive flag.

**Comment by cserf** [comment]
Good catch. The history must not be updated in case only `last_processed` is changed. Just need to change the test on this line : https://github.com/rucio/rucio/blob/ea4d2c7e2702b85a86a8668b2d852971f42fceb4/lib/rucio/core/subscription.py#L177  . Do you want to do it or should I do it ?

**Comment by dynamic-entropy** [comment]
I can try to do it.

**Comment by dynamic-entropy** [comment]
Hi @cserf 
Another thing, shouldn't the update_subscription call be only for subscriptions that run? i.e under this `if statement`. At the moment, subscriptions that are not evaluated get updated too. 
 https://github.com/rucio/rucio/blob/ea4d2c7e2702b85a86a8668b2d852971f42fceb4/lib/rucio/daemons/transmogrifier/transmogrifier.py#L512

**Comment by dynamic-entropy** [comment]
Also, another column indicating the date for `subscription_update` will be helpful for us.

**Comment by dynamic-entropy** [comment]
Hi @cserf 
Kindly let me know if this is enough and correct/a good way of checking.
