### ISSUE TITLE
SSH Auth Fails for Users Without Admin Rights

### ISSUE THREAD

**Issue by bjwhite-fnal** [rucio/rucio#6119]
### Description

The authentication API method `get_auth_token_ssh()` [checks ](https://github.com/rucio/rucio/blob/85492437ace81e6957a713d3d8895309703ded36/lib/rucio/api/authentication.py#L219) for a permission, `get_auth_token_ssh`, which is not present in the `perm` dictionary [defined](https://github.com/rucio/rucio/blob/release-1.29-LTS/lib/rucio/core/permission/generic.py#L25) in `core/permission/generic.py`. The result of this is that the default permission check function is [called](https://github.com/rucio/rucio/blob/85492437ace81e6957a713d3d8895309703ded36/lib/rucio/core/permission/generic.py#L123), and only users with admin rights are granted access. 

### Steps to reproduce

- Create an account
- Add an SSH pubkey to that account
- Add both `get_auth_token_ssh: 1` and `get_ssh_challenge_token: 1` attributes to account
- Try to `rucio whoami` using SSH authentication
    - Fail
- Add admin role
    - Success

### Rucio Version

Client/Server : 1.29.10/1.29.10

**Comment by bari12** [comment]
@bjwhite-fnal Can you perhaps submit a PR for this? As you pointed out, it should be sufficient to add a permission there. Must probably also be done for the challenge token.

Sidenote: You shouldn't need to add `get_auth_token_ssh` attributes to the account. The check should be identity based, similar to the other checks.

**Comment by bari12** [comment]
Backport 1.29.13
