### ISSUE TITLE
Transfer to cloud endpoints fail in case of multisource transfer

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#6137]
### Description

In case of a FTS transfer from a file with a single replica from GCS to a grid site, the conveyor use the source FTS instead of the destination one : https://github.com/rucio/rucio/blob/f1eabd11d22aef76d2c50f0ee152e1573eb19e0c/lib/rucio/transfertool/fts3.py#L807-L808
In case of multiple sources, it's not the case anymore (see example : https://fts3-atlas.cern.ch:8449/fts3/ftsmon/#/job/6b5599da-c3c7-11ed-9453-fa163eb580d6)

### Steps to reproduce

Create 2 replicas of a file : one on GCS (with `fts : fts1` that contains the GCS credentials) , the other on a grid site (with `fts: fts2`) and create a rule to a 3rd RSE  (with `fts: fts2`)

**Comment by rcarpa** [comment]
I don't have good ideas on how to handle this case. If we mix GCS and non-GCS sources, how can we pick the fts server if the destination server should always be picked for non-GCS sources, but the source server for the GCS source? 

I can think of two possible solutions:
- don't allow GCS sources in multi-sources: dirty solution, but easy to implement
- enforce that the FTS server used for submission is supported by all sources and destination via their 'fts' attribute: IMHO, the correct solution, but requires an incompatible change to the meaning of the 'fts' attribute for source selection. So this is something very difficult to make every community to adopt (can be hidden behind a configuration option; but this increases the technical debt and maintenance burden in rucio)

**Comment by bari12** [comment]
I think (2) is an overkill to make this work. It would also re-create this weird situation we had before, where you could listen multiple FTS servers and Rucio should fail-over if one doesn't work. This created all kinds of race conditions and we finally had to disable that feature, only allowing one server.

IMHO I would simply go for (1).

**Comment by rcarpa** [comment]
While I agree that (2) is overkill for this particular problem, I strongly believe that the initial design is very counter-intuitive for everybody starting with rucio. Having to set the fts=<something> attribute on both source and destination RSE; but only the destination one counts doesn't make any sense. Especially when you enter into the realm of multi-hopping. Why do you use the FTS server of the last hop to transfer everything? 

Implementing (2) fixes a bad design. Selecting an FTS server which is both supported by the source and the destination RSE for a transfer between the two RSEs makes perfect sense. This also allows to partition the topology by supported FTS server and multi-hopping using "border" RSEs which support both servers. 

On the other hand, implementing (1) commits on a bad design and adds even more tech debt and confusion for new users.

**Comment by bari12** [comment]
I agree with the sentiment, but practically, I think also with this solution, there will be confusion which can only be countered with proper documentation. E.g. multiple FTS servers, in different orders, used by all participant RSEs of a transfer. The question will also come up why FTS x is used over FTS y

**Comment by bari12** [comment]
I think we need to rather think about a better way for FTS to request GCS signed urls, when needed, from Rucio.
