### ISSUE TITLE
Rucio client lists replicas in wrong order

### ISSUE THREAD

**Issue by jamesp-epcc** [rucio/rucio#6141]
### Description

When using the `--sort` option with `rucio list-file-replicas`, the replicas are sorted correctly on the server, but the client does not preserve this ordering when printing the list of replicas. I think this is because the sorted replicas are in the `pfns` member of the JSON returned from the server, but the client iterates based on the `rses` member, which is not sorted. To fix this, the client should respect the ordering in the `pfns` member when displaying the list of replicas.

### Steps to reproduce

1. Create several replicas of a file.
2. Run `rucio list-file-replicas` and pass the `--sort` option to sort the replicas according to some criteria (it doesn't matter which as this affects all sorting algorithms).
3. Observe that the list printed by the client is not in the right order. (Inspecting the actual JSON returned from the server will confirm that this is a client problem).

### Rucio Version

1.30.0

**Comment by dsgeorge** [comment]
With rucio 1.31.5 I am still seeing replicas returned in the wrong order by the python client used in the ATLAS pilot. Is this expected to be fixed?
