### ISSUE TITLE
Make Virtual Placement return only complete dataset replicas

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6159]
### Description

https://github.com/rucio/rucio/blob/a86e74e9a3ee45bf8ffd2c040dd1e2eb4e28ea17/lib/rucio/core/replica.py#L3542-L3551

This checks that the dataset exists on a disk RSE which has a `root://` protocol for reading. It should also check that the dataset is fully replicated.

Reported by R. Walker.

**Comment by bari12** [comment]
@ivukotic are you available to implement this change?

**Comment by ivukotic** [comment]
I could do it if I would know how to ask if the replica is complete... can you please let me know?

**Comment by bari12** [comment]
Should be an easy change in principle. In the loop above, `list_dataset_replicas` should give you all the necessary information already, including a `state` entry (`AVAILABLE`/`UNAVAILABLE`)

**Comment by ivukotic** [comment]
ah OK. I will try to do it today.

**Comment by ivukotic** [comment]
solved by: https://github.com/rucio/rucio/pull/6162
