### ISSUE TITLE
Rule source replica expression not honoured

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#6186]
### Description

I've added a new rule to test the CTA recall:

`$ RUCIO_ACCOUNT=ddmadmin rucio add-rule --activity Express --lifetime 86400 --source-replica-expression CERN-PROD_TEST-CTA data22_13p6TeV:data22_13p6TeV.00436422.physics_Main.deriv.DAOD_PHYS.f1291_m2137_p5442_tid31137710_00 1 IN2P3-CC_SCRATCHDISK`
`b50a4ce18db74786b84f113a14486956`

However, the corresponding FTS jobs took the files from CERN DATADISK, ignoring the source replica expression, e.g.:

```
davs://eosatlas.cern.ch:443/eos/atlas/atlasdatadisk/rucio/data22_13p6TeV/d3/66/DAOD_PHYS.31137710._000006.pool.root.1?copy_mode=pull
-->
davs://ccdavatlas.in2p3.fr:2880/atlasscratchdisk/rucio/data22_13p6TeV/d3/66/DAOD_PHYS.31137710._000006.pool.root.1
```

### Steps to reproduce

See above.

**Comment by dchristidis** [comment]
I’m not sure this is a bug. It’s not possible to truly honour the source-replica expression when multi-hop transfers are involved. It’s even worse in this case where the replica already existed in the only-possible intermediate hop.

**Comment by bari12** [comment]
There is two ways where to source replica expression is not enforced. If there is already a transfer inflight, this will just be re-used, no matter the source replica expression. The second one is the one Dimitrios is describing. @rcarpa can comment, but I am pretty sure that the algorithm builds the path from CERN-PROD_TEST-CTA -> DATADISK -> IN2P3-CC_SCRATCHDISK correctly, but identifies that there is already a replica on the datadisk, and then just submits that transfer. This is also the right behaviour. Good catch.

**Comment by rcarpa** [comment]
Yes, Dimitrios is right. This is where it happens: 

https://github.com/rucio/rucio/blob/b5874bf02c0b1b8401593ef45991b9363cdd7fa4/lib/rucio/core/transfer.py#L727

**Comment by rcarpa** [comment]
@mlassnig . I believe there is nothing to be done here. Can I close the ticket?
