### ISSUE TITLE
rsemanager add domain to all method signatures

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#62]
The idea is to add the domain to all method signatures so that clients/conveyor can specify which domain should be used to create protocols/pathes.

- [x] First iteration: Add domain to method signature, without implementing any functionality yet.
- [x] Second iteration: The right output is generated depending on domain input. If no domain is given, wan is used, if wan does not exist, lan is used
- [x] Third iteration: Client / Conveyor have to call the methods with the right domain.

_Migrated from JIRA [RUCIO-2778](https://its.cern.ch/jira/browse/RUCIO-2778)_

**Comment by mlassnig** [comment]
this is starting to affect sites with different LAN/WAN protocol settings
