### ISSUE TITLE
Simplify the test pipeline

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#6212]
To run tests, we run a spaghetti of shell and python scripts with esoteric ways of passing parameters between them. It's very complex to actually run the tests locally. There is the donkeyrider, but it's just a wrapper to hide all the mess.

The goal of the ticket is to cleanup the test setup. Reduce the number of scripts. Make it possible to run the tests locally for every single database with minimal effort and using built-in capabilities rather than home-made wrappers. Idealy: be able to run one docker-compose command + one pytest command to execute tests for a selected database. All that without need for wrapper scripts.

**Comment by bari12** [comment]
Actually, I closed this most likely by mistake. In the release plan for 33 this is linked as the test-infrastructure simplifcation @rcarpa was planning. Or do we have another ticket for that?
