### ISSUE TITLE
Dynamic submission bulk size to FTS

### ISSUE THREAD

**Issue by ddavila0** [rucio/rucio#6228]
### Description

We would like rules to have a way to dynamically define the bulk size (number of file transfers per job/cycle) used when submitting to FTS. As far as I can tell, currently this parameter is statically configured and used for all rules.
This parameter should be modifiable during the lifetime of the rule so that the submission rate could be modified at any time. 

### Motivation

On the Rucio/SENSE integration context we foresee creating large bandwidth guaranteed paths for large transfer workflows. In order for the guaranteed bandwidth to be fully utilized, a certain number of active transfers is required. This number depends both on the bandwidth assigned and the latency between endpoints. 
Submitting fewer transfers to FTS will leave the path underutilized, on the other hand, submitting too many will leave less chance to make adjustments like moving the workflow back to the best-effort path which requires intervention before the submission to FTS.

Finally, the assigned bandwidth may change at anytime so it is necessary to be able to make adjustments on the submission bulk size 
  

### Change

A rule would have an editable parameter that can be modified at any time and that will define the submission bulk size to FTS

**Comment by bari12** [comment]
@rcarpa what do you think? Is this easily feasible for the conveyors?

I am not really sure where to best put this in a replication rule. There is the `meta` field which is a generic json, where this could be added. Normally this field is used to add some WFMS metadata to a rule. It wouldn't really apply to this, since it is not metadata, but possibly something similar could be done.

**Comment by rcarpa** [comment]
Conveyor doesn't work at a rule granularity. Each file is treated independently. Also, this "job/cycle" is mostly an implementation specifics on rucio side. If we put the throttler asides, rucio will submit absolutely all pending transfers in a short time window anyway. Adding complicated logic there will have absolutely no effect in terms of how many files will end queued in FTS. It will only impact how those files are grouped into jobs. And, on FTS side, if I'm not mistaken, they mostly work on file level again and there is little difference between submitting 1 job with 100 files and 100 jobs with one file. 

Now, if we go back to throttler, there are interesting things which can be done there for this use-case, but it's a component which only ATLAS uses and only at its most basic capabilities.

**Comment by bari12** [comment]
@ddavila0 is this still something needed by SENSE?
