### ISSUE TITLE
Restrict permissions for adding scopes or manipulating identities

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6267]
### Description

It has come to our attention that some permissions are not restrictive enough. Specifically:

* Adding new scopes (`perm_add_scope`)
* Adding new identities (`perm_add_account_identity`)
* Deleting existing identities (`perm_del_account_identity`)

For the latter two, they can only affect one’s own account, but it should probably be restricted nonetheless.

### Steps to reproduce

The snippet below, run as user `jdoe`, does not raise an error:
```console
$ rucio-admin scopes add --account jdoe --scope covfefe
```

### Additional Information

Affected policies are:

* `atlas.py`
* `cms.py`
* `escape.py`
* `generic.py`
* `generic_multi_vo.py`

We’ll certainly change it for ATLAS and the generic policies. @ericvaandering and @egazzarr, thoughts for CMS and ESCAPE respectively?

**Comment by ericvaandering** [comment]
We are now using a policy package, but it probably has these issue. @dynamic-entropy want to take a look?

**Comment by bari12** [comment]
Backport 1.29.14
