### ISSUE TITLE
x509 authentication fails for baseclient.py

### ISSUE THREAD

**Issue by maany** [rucio/rucio#6294]
### Description

Since https://github.com/rucio/containers/pull/218 , the apache config for the rucio server forces clients to explicitly provide Client Certificates when trying to reach the `/auth/x509` endpoint.
While this enables browser-based clients to request a client certificate from the user, the mechanism does not work for CLI clients as they are missing handling of TLS 1.3 Post Handshake Authentication workflow https://github.com/curl/curl/issues/3026 

 

### Steps to reproduce

1. Use x509 in the rucio.cfg client configuration, provide a valid cert and key
2. run any rucio command

### Rucio Version

32.0.0

**Comment by dchristidis** [comment]
Why ask me to submit an issue, then ignore it? :stuck_out_tongue:

**Comment by maany** [comment]
I took notice of your issue after I had created this one :P
