### ISSUE TITLE
Capital `I` in `Id` in REST API for Subscriptions

### ISSUE THREAD

**Issue by ThePhisch** [rucio/rucio#6316]
### Description

See https://github.com/rucio/rucio/blob/c4f4eb9902fe0be6ff52d22357f763769c8e9860/lib/rucio/web/rest/flaskapi/v1/subscriptions.py#L625

there is a capital `I` in `Id` which seems unintentional.

### Steps to reproduce

attempt a `GET` to `https://rucio.cern.ch/subscriptions/Id/{subscription_id}` and it will work, `GET` from `https://rucio.cern.ch/subscriptions/id/{subscription_id}` (note the lower-case `i` in `id`) will not.

### Rucio Version

v32

**Comment by mohitsatr** [comment]
Hi @ThePhisch , are you working on this one.

**Comment by ThePhisch** [comment]
> Hi @ThePhisch , are you working on this one.

no, you can go ahead and fix it

**Comment by mohitsatr** [comment]
Sorry for not being cleared in pre-edit version
I was asking whether `I`  in `ID` is just a typo and need to be changed to `i` or do we want it to return response no matter Capitalised `https://rucio.cern.ch/subscriptions/Id/{subscription_id}` or lowercased `https://rucio.cern.ch/subscriptions/id/{subscription_id}`

For example ,  `Rules`  in Below Url is also capitalised .
https://github.com/rucio/rucio/blob/c4f4eb9902fe0be6ff52d22357f763769c8e9860/lib/rucio/web/rest/flaskapi/v1/subscriptions.py#L625-L628

/

**Comment by voetberg** [comment]
`subscriptions` has the only endpoints with a capitalized urls, so that's almost certainly a mistake. 

As for handling the error, case-insensitive urls are not recommended by w3c, so I think we should follow that follow that convention. (We could set up redirects, but I think that's way more trouble than it's worth).
