### ISSUE TITLE
Introduce the RSE decommissioner daemon

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6321]
### Description

Introduce a new daemon that can assist in (or, hopefully, handle altogether) the RSE decommissioning process.

This is the result of an ATLAS Qualification Task, but can prove beneficial for other communities too.

### Motivation

Site decommissioning has been a repeating task because sites are retiring their storage or migrating to different technologies. The decommissioning process is very consuming, both in terms of duration and person effort. It frequently reveals various problems, like corrupted or missing files and inconsistencies between storage and the Rucio catalogue. The process happens in four stages: preventing new data from being sent to the site, migrating all stored data to other sites, cleaning up leftovers, and eventually disabling the site. Experience has shown that this process can negatively affect the throughput of data management tasks. Therefore, it is necessary for the actions to be adequately throttled with continuous non-invasive background operations.

**Comment by dynamic-entropy** [comment]
Hi @dchristidis 
Thank you for creating this. The decommissioning and/or site migrations are very tasking operations and we (CMS) tend to face the same issues you mention.
Kindly let us know if we can help by any means.

**Comment by yiiyama** [comment]
Currently worked on in #6066.
