### ISSUE TITLE
Configure slack notifications for travis

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#633]
Motivation
----------

https://docs.travis-ci.com/user/notifications/#Configuring-slack-notifications

**Comment by bari12** [comment]
Do we want this? I already had to turn off the slack github notifications, just too spammy :-)

**Comment by mlassnig** [comment]
I like our #github channel ;-)

**Comment by vingar** [comment]
I'm finding the github notifications quiet useful for me and having the report from travis will be also useful

**Comment by bari12** [comment]
Ok, maybe @tbeerman can have a look and add it to travis 😄

**Comment by tbeerman** [comment]
Sure

**Comment by vingar** [comment]
it doesn't look to hard https://docs.travis-ci.com/user/notifications/#Configuring-Slack-notifications

**Comment by vingar** [comment]
it looks quiet easy actually. just click click on slack.. I'm submitting a PR

**Comment by mlassnig** [comment]
Done!
