### ISSUE TITLE
List DID Rules will give 200 even if DID does not exist

### ISSUE THREAD

**Issue by ThePhisch** [rucio/rucio#6334]
### Description

Rucio will return a `200 OK` when querying DID Rules even when the scopename is invalid.

### Steps to reproduce

1. `GET /dids/<scope>/<name>/rules`
2. get a `200 OK` even if the scopename is not valid

### Rucio Version

32.3.0

### Additional Information

Discovered while developing the WebUI

**Comment by alexanderrichards** [comment]
Just for confirmation, when I look at the OpenAPI documentation for the REST interface I see an endpoint that is slightly different from the one you sepcify (see [/dids/{scope_name}/rules](https://rucio.cern.ch/documentation/html/rest_api_doc.html#tag/Data-Identifiers/paths/~1dids~1%7Bscope_name%7D~1rules/get) ). Notably the scope and name are combined into the single {scope_name} element. Is this the same endpoint that causing a problem?

--------------

**Edit:** Never mind, I see that there is a regex that is splitting the single scope_name into the two seperarte entities.
