### ISSUE TITLE
Search button for list of DIDs not responding (glitch)

### ISSUE THREAD

**Issue by stergios-kazakos** [rucio/rucio#6341]
### Description

The search button in the rucio GUI:
https://rucio-ui.cern.ch/r2d2/request
is not responding after providing a list of DIDs.
Tried already many browsers and the same is happening.

### Steps to reproduce

Enter the website: https://rucio-ui.cern.ch/r2d2/request
and try the search button

**Comment by dchristidis** [comment]
I’m afraid we’re unable to replicate the issue that you’re experiencing, based on the provided information. Could you be more precise?

### Example 1

1. Open https://rucio-ui.cern.ch/r2d2/request
2. In the ‘Data pattern’ field, enter `mc23_13p6TeV:mc23_13p6TeV.512452*`
3. Click ‘Search’
4. Results appear, as expected

### Example 2

 1. Open https://rucio-ui.cern.ch/r2d2/request
 2. Click on the ‘List of DIDs’ tab
 3. In the text area, enter `mc23_13p6TeV.512452.MGPy8EG_A14NNPDF23LO_HAHMggfZdZd2l2nu_110_30.deriv.DAOD_PHYS.e8548_e8528_s4159_s4114_r14799_r14811_p5855`
 4. Click ‘Search’
 5. A result appears, as expected

**Comment by stergios-kazakos** [comment]
Hi Dimitrios,

Thanks a lot for getting in touch and for looking into it!
Yes, now it works fine again for me as well, not sure what was the issue before.

Cheers,
Stergios

**Comment by dchristidis** [comment]
Very well. Don’t hesitate to re-open the issue should you run into it again, in a way that is reproducible.
