### ISSUE TITLE
implement the configuration option for source selection strategy

### ISSUE THREAD

**Issue by rcarpa** [rucio/rucio#6342]
In the context of configure the source selection strategy, we would like to implement a way for the administrator to change the ranking vector, 

https://github.com/rucio/rucio/blob/fc3973a83b9d658fba5ef9f645f5816a594d4586/lib/rucio/core/transfer.py#L753

via a configuration string. 

## STEP1 

The goal is to allow a pre-defined list of "strategies". 

Each of these strategies will take the form of a string token. For example: `highest_adjusted_source_ranking_first`, `prefer_disk_over_tape`, `path_distance`, `path_length`.

To explicitly set a strategy roughly similar to what's currently hard-coded in the code snippet linked above, the administrator will set the following configuration

```
[transfers]
source_selection_strategy=highest_adjusted_source_ranking_first, prefer_disk_over_tape, path_distance, path_length
```

As a first step, only the previous 4 strategies will have to be implemented. Each one will correspond to one of the operations in the tuple from the code snippet above. 

Each strategy will be backed by a function in python which takes a path (list[DirectTransferDefinition]) as parameter and returns a value comparably to a value of the same type.

On rucio startup, the strategy will be "compiled" into a dynamically generated function which takes a path and returns a tuple. This function will be used as `key` for comparison at runtime.

## STEP2

Once the previous goal is achieved, rework the code to allow a simple "calculator"-like gramar in each strategy. An example of such grammar: https://lark-parser.readthedocs.io/en/latest/examples/calc.html
Ideally, it's preffered to avoid using an external library for that. 

This will allow to simplify the strategies to more basic construction blocks. Something like `source_ranking`, `is_staging_required`, `path_distance`, `path_length`. So the configuration will become:

```
[transfers]
source_selection_strategy=-source_ranking + is_staging_required, is_staging_required, path_distance, path_length
```

Add a couple of other strategies. For example, `random`. An administrator who wants to always use path distances while randomly picking beween sources of equal distance will set:
```
[transfers]
source_selection_strategy=path_distance, random
```

## STEP3

Evaluate the use-case of a more complex grammar. It's up to you to propose a good grammar for that. A possible interesting options: implement parameters. For example to use an attribute from the source RSE (fallback to a default value): `bool_rse_attribute("oidc_support", False)`, `int_rse_attribute("outbound_speed", 0)`

**Comment by bari12** [comment]
👍 Sounds good to me!
