### ISSUE TITLE
Unused subscription name in `subscriptions/<account>/<name>/Rules/States` endpoint

### ISSUE THREAD

**Issue by maany** [rucio/rucio#6345]
### Description

The endpoint requires specifying a subscription name

https://github.com/rucio/rucio/blob/fc3973a83b9d658fba5ef9f645f5816a594d4586/lib/rucio/web/rest/flaskapi/v1/subscriptions.py#L626-L627

However, it returns rule states for all subscriptions for the provided account

https://github.com/rucio/rucio/blob/fc3973a83b9d658fba5ef9f645f5816a594d4586/lib/rucio/web/rest/flaskapi/v1/subscriptions.py#L532-L534

So technically, a request to `https://rucio-server.com/subscriptions/jdoe/HOLWAMJFDRSI/Rules/States` is a valid request

### Steps to reproduce

Make a request to 
`https://rucio-server.com/subscriptions/validAccount/invalidSubscription/Rules/Satetes`

### Rucio Version

32.x

### Additional Information

Depending on how this feature is fixed, we might have to make changes in the new webui. We also need to make sure that the change is backward compatible with older clients.

**Comment by bari12** [comment]
@cserf do you remember the reasoning here, or was this just a mistake?

**Comment by cserf** [comment]
That's a mistake.

**Comment by alexanderrichards** [comment]
Am I missing something or is this fix simply a matter of parsing the name to the api thusly:

```diff        
def generate(vo):
-    for row in list_subscription_rule_states(account=account, vo=vo):
+    for row in list_subscription_rule_states(name=name, account=account, vo=vo):
        yield dumps(row, cls=APIEncoder) + '\n'
 ```
 
 If so, I can do this right away
