### ISSUE TITLE
Make suspicious-replica-recoveror daemon VO-agnostic

### ISSUE THREAD

**Issue by haozturk** [rucio/rucio#6396]
### Description

We're evaluating this daemon for CMS use and I've realized that there is an RSE expression hard-coded [1] which appears to be ATLAS specific. Can we make it configurable?

There could be other parts to be changed in this regard that I didn't realize. Do the experts see any other change required in this context?

[1] https://github.com/rucio/rucio/blob/0290623118d0890e799b848d72f2c1a3b18b2b04/lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py#L294

### Motivation

To be adapted by CMS

### Change

Make all VO-specific parts of this daemon VO-agnostic.

@ericvaandering  @Panos512  FYI

**Comment by haozturk** [comment]
I've found another reason why this daemon wouldn't work for CMS out of the box: It requires dids to have `datatype` metadata and it ignores the files which don't have it [1]. CMS doesn't use this metadata field. I don't know what's the best strategy here: Use another metadata field to apply policies (fileName patterns?)

[1] https://github.com/rucio/rucio/blob/0290623118d0890e799b848d72f2c1a3b18b2b04/lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py#L367

**Comment by bari12** [comment]
Hi,

I think the rse_expression should be easy to adapt. For the fixed datatype field, I am not sure. @ChristophAmes and @cserf can comment.

**Comment by voetberg** [comment]
@haozturk and I talked about solutions for this - We agreed that the most straight forward solution is to make both [1] and [2] configurable via the config file, with defaults that don't impact ATLAS

[1] Would be something like 
Config: 
```
[replicarecoverer]
rse_expression = rse_expression
```
`suspicious_replica_recoverer.py`: 
```
rse_expression = config_get('replicarecoverer', 'rse_expression', raise_exception=False, default='type=SCRATCHDISK')
 add_rule(dids=dids_nattempts_1, account=InternalAccount('root', vo=vo), copies=nattempts, rse_expression=rse_expression, grouping=None, weight=None, lifetime=24 * 3600, locked=False, subscription_id=None) 
```

[2]
Config: 

```
[replicarecoverer] 
use_file_metadata = false 
datatype_expression = {matching regex}
```

`suspicious_replica_recoverer.py`: 
```
use_file_metadata = config_get_bool("replicarecoverer","use_file_metadata", raise_exception=False, default=True)
if use_file_metadata: 
    file_metadata_datatype = str(file_metadata["datatype"]) 
else: 
       name_regex = config_get('replicarecoverer', 'datatype_expression', raise_exception=True)
       file_metadata_datatype = re.compile(name_regex).match(file_name) 
```

[1]
https://github.com/rucio/rucio/blob/0290623118d0890e799b848d72f2c1a3b18b2b04/lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py#L294
[2]
https://github.com/rucio/rucio/blob/0290623118d0890e799b848d72f2c1a3b18b2b04/lib/rucio/daemons/replicarecoverer/suspicious_replica_recoverer.py#L367

**Comment by ericvaandering** [comment]
One minor comment. Maybe "did_name_expression" rather than "datatype_expression" so it's clear what we're proposing to act on. (Assuming that's right, we will just look at the DID name).

That leaves open the possibility for adding other types of selections for other use cases.

**Comment by voetberg** [comment]
@bari12 Is this proposed solution okay? 

@ChristophAmes has there been any work on this? If not I can gladly take it over.

**Comment by bari12** [comment]
For me this is ok, but @cserf or @ChristophAmes should really comment on this, as the experts. 🔔

**Comment by ChristophAmes** [comment]
The proposed solutions look fine to us. We haven't done any work on this topic yet.
