### ISSUE TITLE
Include the network domain (wan, lan) in list_replicas

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#64]
Motivation
-----------

For local usage, a combination of wan/lan attributes with rse_expressions will provide the local or remote replicas to a site.

Modification
-------------
added lan/wan in  list_replicas (clients/rest/server). default wan

**Comment by bari12** [comment]
Just to link this to #62 where I layed out the plan for this. In the first iteration I will add empty signatures for domain to all the RSEManager methods. At that point, the list_replicas call can basically already use them.

What we said today is, that list_replicas for the client in general should use domain='wan'. If an RSE is found witch matches with the client location, it should query again with domain='lan' for the RSE.

**Comment by mlassnig** [comment]
i will extend it to list_replicas(.. , domain='wan') once the signature for create_protocol is merged. then we can gradually start making the clients domain aware
