### ISSUE TITLE
Using Python client without configuration file

### ISSUE THREAD

**Issue by SergeyYakubov** [rucio/rucio#6410]
### Description

Currently, the Rucio client requires the presence of a configuration file to make it work properly. It would be very useful if that was not the case and the library worked properly without it.

### Motivation

We at Oak Ridge National Laboratory are trying to create a Rucio storage plugin for Galaxy (https://galaxyproject.org/). It works nicely, but we have to put a Rucio configuration file at a known location. This makes it hardly possible to use with dynamical parameters, in tests, etc. Even if the client allows to add some parameters during the constructor call, it still wants to read the config file and fails when it is not there. In some situations even `from rucio.client import Client` wants to read config file to get logging info (sometimes it works, though, I'm not sure what the difference is - probably depends on log configuration).

### Change

Add an option to get rid of the config file and use only constructor parameters. Get rid of using config file during import calls, pass config parameters used during client construction to inner functions/classes, ...

**Comment by bari12** [comment]
Hi @SergeyYakubov 

I believe we looked into that already once, but I cannot find the issue/reference now. In any way, I agree it is a good idea.
