### ISSUE TITLE
Use OpenID Connect Discovery

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6414]
### Description

The current new-style token support builds the token endpoint URL by concatenating the issuer from the configuration file with the hard-coded `/token` path. Instead, it should make use of OIDC Discovery (i.e. `/.well-known/openid-configuration`).

**Comment by tbeerman** [comment]
Hi @dchristidis,
fyi, we are currently running a Rucio deployment which is using the EGI AAI-demo instance (keycloak). With the current, hard-coded, implementation in 33 it's not working and we cannot get any tokens. So for the time being we will have to stay with 32 until this change has been implemented.

**Comment by dchristidis** [comment]
It is likely not just the endpoint; @rcarpa tested Keycloak and reported that the `audience` parameter is not taken into account.

Our current plan is for Rucio 33 to remain IAM-only.
