### ISSUE TITLE
Automatix only using 1st file type defined in automatix.json

### ISSUE THREAD

**Issue by thysk** [rucio/rucio#6418]
### Description

I have automatix running in the Multi-VO Rucio deployment with the following in automatix.json

When Automatix starts it states there are two test data set types and their probabilities.
But from running the daemon for several weeks now, I have never seen the "Type 2" job type be done, despite it stating and should be 66% of the time.

`{
"Type 1": {
                "probability": 5,
                "nbfiles": 20,
                "filesize" : 250000000,
                "metadata":
                {
                        "project": "user",
                        "prod_step": "LSST"
                }
        },
"Type 2": {
                "probability": 10,
                "nbfiles": 5,
                "filesize" : 20000000000,
                "metadata":
                {
                        "project": "user",
                        "prod_step": "ATLAS"
                }
        }
}`

### Steps to reproduce

1. Run Automatix
2. Have the automatix.json as in the description
3. watch as only "Type 1" data sets are created and uploaded

### Rucio Version

daemons-1.29, daemons-32, daemons-33

### Additional Information

I am running this on Multi-VO but the daemon is running fine

**Comment by cserf** [comment]
The algorithm that does the type selection works properly as shown below using the following test : 
```python
import random
from json import load
from rucio.daemons.automatix.automatix import get_data_distribution, choose_element

probabilities, data = get_data_distribution('policy.json')

probs = {5: 0, 10: 0}
for _ in range(20):
    dic = choose_element(probabilities, data)
    print(dic)
    probs[dic['probability']] += 1

print(probs)
```

Result :
```
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 5, 'nbfiles': 20, 'filesize': 250000000, 'metadata': {'project': 'user', 'prod_step': 'LSST'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 5, 'nbfiles': 20, 'filesize': 250000000, 'metadata': {'project': 'user', 'prod_step': 'LSST'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 5, 'nbfiles': 20, 'filesize': 250000000, 'metadata': {'project': 'user', 'prod_step': 'LSST'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 5, 'nbfiles': 20, 'filesize': 250000000, 'metadata': {'project': 'user', 'prod_step': 'LSST'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 5, 'nbfiles': 20, 'filesize': 250000000, 'metadata': {'project': 'user', 'prod_step': 'LSST'}}
{'probability': 5, 'nbfiles': 20, 'filesize': 250000000, 'metadata': {'project': 'user', 'prod_step': 'LSST'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 10, 'nbfiles': 5, 'filesize': 20000000000, 'metadata': {'project': 'user', 'prod_step': 'ATLAS'}}
{'probability': 5, 'nbfiles': 20, 'filesize': 250000000, 'metadata': {'project': 'user', 'prod_step': 'LSST'}}
{5: 7, 10: 13}
```

**Comment by thysk** [comment]
Over the winter holiday I have come back and still none of the type2 larger files have been generated by any of the three automatix.
I get the feeling I am missing something for the setup of automatix
As @cserf mentioned looking at `rucio-admin config get --section automatix` 
But I had nothing configured there
and I am not sure what needs to be configured

**Comment by cserf** [comment]
You probably have defined some options in `rucio.cfg` otherwise `automatix` whould raise an exception. Can you send all the options that are specified in the config file, as well as the parameters you pass to `automatix` ?
I still don't understand what can be the problem and I'm not able to reproduce.

**Comment by thysk** [comment]
All my config is specified in the values files

Automatix parameters - https://gitlab.com/ral-multi-vo-rucio/m-vo-rucio-deployment/-/blob/main/overlays/prod/rucio/values-rucio-daemons.yaml?ref_type=heads#L748

daemons rucio.cfg - https://gitlab.com/ral-multi-vo-rucio/m-vo-rucio-deployment/-/blob/main/overlays/prod/rucio/values-rucio-daemons.yaml?ref_type=heads#L748

Server config -https://gitlab.com/ral-multi-vo-rucio/m-vo-rucio-deployment/-/blob/main/overlays/prod/rucio/values-rucio-server.yaml?ref_type=heads#L310

**Comment by bari12** [comment]
@Thysk is this still a problem?
The config links above do not exist (anymore)
