### ISSUE TITLE
Possibility to add column/generic metadata in add_files method in dirac

### ISSUE THREAD

**Issue by panta-123** [rucio/rucio#6437]
### Description

When the add_files method of dirac is called , it does the  add_replicas and add_dids.
But then to register column/generic metadata for dids we need to make an extra call to set_metadata method.
Both add_replicas  and add_dids can take meta argument {key:value} .  Thus the did registration and metadata registration can be done in a single call of add_files method.

Tricky part will be that , add_files does the heirachial registration of did. The metadata can be associated with diffreent level of did in hierarchy.

**Comment by saumy-sh** [comment]
hey @panta-123 I would very much like to work on it with you. Can you please help me get started with it?

**Comment by panta-123** [comment]
Hi @saumy-sh , Thank you for your interest.
But for this issue, PR is already made and ready for merge.
https://github.com/rucio/rucio/pull/6438

For future we can work on different features together.

**Comment by saumy-sh** [comment]
okay no problem.
sure i am looking forward to working together.
