### ISSUE TITLE
Storm protocol wrongly used as failover from remote site

### ISSUE THREAD

**Issue by rodwalker** [rucio/rucio#6449]
### Description

"rucio get" fails over to the storm protocol for sources on storm RSEs, despite there being no chance of the sharedFS being mounted. The initial protocol is chosen based on the client locality in relation to the RSE, e.g. SITE_NAME etc, so the failovers should also respect this.

### Steps to reproduce

rucio get --rse UKI-NORTHGRID-LANCS-HEP-CEPH_DATADISK mc20_13TeV:DAOD_PHYS.34859811._000108.pool.root.1
after somehow breaking root and davs. Users can do this is many ways!

**Comment by dchristidis** [comment]
This is an unfortunate by-product of #5460. The configuration for this RSE is:

```
$ rucio-admin rse info UKI-NORTHGRID-LANCS-HEP-CEPH_DATADISK
…
Protocols:
==========
…
  file
    domains: '{"lan": {"read": 1, "write": 0, "delete": 0}, "wan": {"read": 3, "write": 0, "delete": 0, "third_party_copy_read": 0, "third_party_copy_write": 0}}'
    extended_attributes: None
    hostname: example.com
    impl: rucio.rse.protocols.posix.Symlink
    port: 0
    prefix: /cephfs/grid/atlas/atlasdatadisk/rucio/
    scheme: file
…
```

The `file` protocol is explicitly enabled for WAN. As such, there’s no bug in the Rucio client; it’s a ATLAS-specific ‘misconfiguration’. However, said misconfiguration was intentionally put there as a workaround to another bug. We agreed to close this issue and focus on addressing #5460.
