### ISSUE TITLE
Add Token based TPC tests to the CI

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#6451]
### Description

Add some transfer tests with Tokens

**Comment by saumy-sh** [comment]
Hey @bari12  I would very much like to work on it with you but i am a newbie. Can you please help me get started with it?

**Comment by rcarpa** [comment]
Hi, @saumy-sh. This is a very difficult ticket. And is already work in progress (https://github.com/rucio/rucio/pull/6443) . 

If you are motivated, I advise you to rather pick an issue from the following list as your first ticket: https://github.com/rucio/rucio/labels/good%20first%20issue

**Comment by saumy-sh** [comment]
Okay thanks a lot for responding. I will look into it!

**Comment by rcarpa** [comment]
Fixed in: https://github.com/rucio/rucio/pull/6443
