### ISSUE TITLE
ATLAS: Restrict access to activities

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#6486]
### Description

Rucio accounts without elevated privileges should only be allowed to create replication rules with the `User Subscriptions` activity. We should also envision the possibility of choosing other activities when there’s explicit request for approval.

### Motivation

`User Subscriptions` has a limited share and a Throttler limit. It has been made safe against a user creating a very large amount of requests (whether on purpose or on accident). When a user can switch to a different activity, they can bypass those protections, threatening production.

**Comment by rdimaio** [comment]
Closing in favour of tracking in policy package repository
