### ISSUE TITLE
Add an automatic formatter to the pre-commit hooks

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6488]
Right now, the pre-commit script (https://github.com/rucio/rucio/blob/master/.pre-commit-config.yaml) runs `flake8` as linter, warning of style issues. It might be worth also adding an automatic formatter like `black` (https://github.com/psf/black) to fix style issues automatically. 

- Using them together: https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#flake8

We could also consider using `isort` to sort the imports (https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#isort)

**Comment by bari12** [comment]
We have talked about this in the past, but could not agree.
Using a formatter now would somewhat complicate git history, but I don't think this is the primary issue, mostly it was that people just did not agree to use one specific formatter.
What we fell back on is that we will just enforce PEP8 rules, and on top of that people can somewhat freely choose how to format their contributions, as long as it is PEP8 compliant.
Re-formatting large parts of the code, without any functional changes, is generally frowned upon though.

**Comment by rdimaio** [comment]
Closing - discussed offline, we might discuss this at the retreat
