### ISSUE TITLE
Integrate probes/common/check_obsolete_replicas into rse_counter

### ISSUE THREAD

**Issue by voetberg** [rucio/rucio#6530]
### Description

Currently, cataloging the history of obsolete replicas is done by a monitoring probe.(found [here](https://github.com/rucio/probes/blob/master/common/check_obsolete_replicas)) This probe just queries and updates/inserts tables, and doesn't interact with probe architecture, nor does it need to be a probe. 

I propose we move this functionality to daemons/rse_counter, as it does very similar (if not mostly identical) work. 

cc: @ericvaandering 

### Motivation

This functionality is better suited to a daemon, as it does not need to interact with the rest of the probing code, and including it in the main repo would ensure it is better maintained. (The current probe isn't written using sql alchemy syntax or the data model.) 

### Change

Changes are as follows: 
- Move functionality of probes/common/check_obsolete_replicas to the RSE Counter daemon
- Move queries to core/rse_counter

**Comment by bari12** [comment]
This is a good idea I think. @dchristidis 
I think this concept should possibly also applied to other probes (or oracle procedures) but in the past we were not super successful doing that. Maybe we should re-start this activity

**Comment by voetberg** [comment]
Duplicate of [4261](https://github.com/rucio/rucio/issues/4261)
