### ISSUE TITLE
Introduce test coverage in PR reviews (and possibly in CI)

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6545]
Rucio used to have test coverage some time ago, but it was toggled off. I think it would be a good tool to have for PR review purposes; if there is a portion of code that is not covered, it might be a good indicator that some tests need to be written for that part of the code.

As we use pytest for testing, we can use https://github.com/pytest-dev/pytest-cov for coverage.

There are some criticisms for using coverage as a metric: the main reason behind this is that coverage only tells you whether code is covered or not, but it doesn't tell you much about the quality of the tests. I somewhat agree with this, and I would suggest only using coverage as a PR review tool, but we could also consider having a fairly achievable coverage threshold (60-70%) and aiming to always be over that threshold.

**Comment by bziemons** [comment]
The current coverage metric does not suffice for reviewing pull requests and it just creates noise. We have decided to roll back the coverage display and re-add this once it is properly implemented.
