### ISSUE TITLE
Send one email for approval request of multiple containers

### ISSUE THREAD

**Issue by bualust** [rucio/rucio#6566]
### Description

Hello,
I have just found out that when one opens a request of replication on an RSE containing many dataset containers this will trigger as many email as the number of dataset in the request. I understand (but I am not sure of this) that if I was to use a wildcard this would only trigger one email. I wonder if people would find it useful to trigger one single email with the list of the dataset in both cases.
Apologies if I am missing something that already allows this.

**Comment by bari12** [comment]
This is the case, but unfortunately not something easily change-able, since the approval is always per-rule. To change this requires probably quite some significant work.
