### ISSUE TITLE
Updates to overwrite configuration on tape

### ISSUE THREAD

**Issue by dynamic-entropy** [rucio/rucio#6581]
### Description

This is the current `overwrite` scenario as I understand it.

1.  Currently, rucio does not allow overwriting on `Tape` (By default)
https://github.com/rucio/rucio/blob/1117e15fdd373ba6a0c24b22b7bd564c13f77241/lib/rucio/transfertool/fts3.py#L333-L334

2. Overwrite  on DISKs  (By Default) https://github.com/rucio/rucio/blob/1117e15fdd373ba6a0c24b22b7bd564c13f77241/lib/rucio/transfertool/fts3.py#L328
 
 (Both of those can be overridden by setting it explicitly on the RSE, @dchristidis @bari12 , kindly correct me on this).
 https://github.com/rucio/rucio/blob/1117e15fdd373ba6a0c24b22b7bd564c13f77241/lib/rucio/transfertool/fts3.py#L354
 
3.  If the file is found corrupted on the first try and it can be affirmed from the returned contents that it is corrupted it can be overwritten (if this is configured in the transfers section)
https://github.com/rucio/rucio/blob/1117e15fdd373ba6a0c24b22b7bd564c13f77241/lib/rucio/transfertool/fts3.py#L705

We would like to have two things changed in this if it makes sense for the community too. 
1. Make the `overwrite_corrupted_files` a per RSE attribute as opposed to a global transfer configuration. 
     - We have had opinions and arguments from sites that strongly want us to enable it and sites that want otherwise
     
2. Add an `overwrite-when-only-on-disk` configuration to be sent with the job params, also configurable at an RSE level for tape RSEs. 
Here is the final proposal document agreed on by the FTS team for future developments. https://cmsdm.web.cern.ch/documents/FTS3_CMS_DM_Overwrite-when-only-on-disk_proposal.pdf

### Motivation

Have the ability to configure sites independently.

**Comment by bari12** [comment]
Hi Rahul,

1, 2, 3 is correct. 

Although I have to say we discussed 3 & 4(2nd 1) in #5975  and @ericvaandering said that this feature can be dropped from Rucio. Now you are saying that we should keep it and we should make it RSE specific 🤣 

The `overwrite-when-only-on-disk` shouldn't be too hard to add.

We should update the rucio documentation though to add these new workflows to the transfer documentation.

**Comment by dynamic-entropy** [comment]
Hello @bari12 
@ericvaandering  is correct. We do not use it. 

I intended to keep it for a just-in-case scenario,  we get different viewpoints when we try to pitch this to sites.
(We are otherwise okay if it is removed if no other experiment uses it either).

"Making it RSE specific" opinion stems from the fact that it helps to test this, instead of "we need it".

**Comment by bari12** [comment]
I don't mind keeping it, if it is being used (at least for testing); But if it is not being used by CMS (And right now nobody else uses it) we should aim to remove it.
