### ISSUE TITLE
Possible redundant util function

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6598]
It seems like `render_json_list` is exactly the same as `render_json`.

https://github.com/rucio/rucio/blob/bed3f050bc6ee12dc4e6a92637a628604b265725/lib/rucio/common/utils.py#L614-L623

 Is `render_json_list` actually needed? If not, it should be removed.

**Comment by Ban42** [comment]
Hi,
Since the PR I made is under review, could you assign the issue to me?
Many thanks
