### ISSUE TITLE
Create and populate common monitoring repository 

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#6641]
### Description
Create a easily deployable monitoring solution for Rucio for operators to deploy within the Kubernetes cluster to enable detailed transfer monitoring.
This will include:
Charts to deploy any needed components as a basic deployment to get started
dashboards created for grafana
Instructions for any setup required within the deployed components
Instructions on how to setup communication to the various components

This will most likely have various PRs across the Rucio, helm-charts, and documentation repos
@Thysk @bjwhite-fnal please fill information.

### Motivation

Many communities have requested monitoring solutions for Rucio outside of CERN, often after Mario has been shown the various dashboards that he uses. 
FTS monitoring for CERN deployments shows a great deal of information that is searchable and filterable to help identify issues with data flow, this can be re-created using the Hermes messages, elasticsearch and grafana.

Creating an easy to deploy monitoring solution should help communities get started with Rucio monitoring.

**Comment by ericvaandering** [comment]
I'd also be happy to share the prometheus setup I use in CMS which resides in the Rucio cluster but sends all of its info off to central monitoring. That's MONIT in our case but for Fermilab, I think Landscape with mimir as a prometheus endpoint satisfies exactly the same function.

**Comment by thysk** [comment]
Here is the start of my monitoring Repo: https://github.com/Thysk/Rucio-Monitoring
I am still working to include database based monitoring using logstash pipelines
