### ISSUE TITLE
Combine reset_database.py and destroy_database.py scripts

### ISSUE THREAD

**Issue by Geogouz** [rucio/rucio#6664]
In the tools directory, there are two scripts: `reset_database.py` and `destroy_database.py`, both offering overlapping functionality pertaining to purging the database. Would it be better to just merge those into a single one, introducing an additional argument?

For example:
```
parser.add_argument(
    '-r',
    '--reset', 
    action="store_true",
    default=False,
    help='Reset the database by rebuilding, creating a base VO, and creating a root account')
```

Also, unless such a change would call for considerable modifications to your established testing/debugging workflows (currently I don't see any usage of those within the project), renaming the resulted script to `purge_database.py` might be also a good idea (as reset becomes now optional).

**Comment by bari12** [comment]
Could be done, but I don't really see the benefit other than having one script, instead of two :-)
