### ISSUE TITLE
Creation of a rule for several DIDs does not work

### ISSUE THREAD

**Issue by valesark** [rucio/rucio#6676]
### Description

In the step of selection of data identifiers (DIDs), it works perfectly fine if I select the datasets through DID Pattern Search, but if I want to give a list of DIDs, then it gets stuck in the step of RSEs, while checking the quota. It gives an output of "Checking the DIDs", which is hanging and does not let you go to proceed to the next steps. 

### Steps to reproduce

One could reproduce the problem in the following way:

Step 1: Enter the dataset into the List of DIDs, f.g. " /EGamma0/Run2023B-22Sep2023-v1/NANOAOD " 
Step 2: Enter the RSE (expression) and click on "Check Quota"

This is the step where it hangs and does not let you to continue.  

### Additional Information

The problem is encountered via Rucio WebUI

**Comment by bari12** [comment]
@maany please check. This might be some issue with the CMS Rucio webui, or it might be a general issue.
