### ISSUE TITLE
Standardize SQLA model names to singular

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6717]
Most SQLA model names (https://github.com/rucio/rucio/blob/master/lib/rucio/db/sqla/models.py) represent a single entity and are correctly named as singular, e.g.:
- `RSE`
- `ReplicationRule`
- `ReplicaLock`
- `TransferHop`

The following two represent multiple entities and are correctly named as plural, and should not be changed:
- VirtualPlacements (this one has a column for multiple placements)
- TransferStats

However, there's a few models whose name is plural, but each entry represents a singular entity. For consistency with the other models, it would be a good idea to modify them to have a singular name too.
- [ ] BadReplicas -> BadReplica
- [ ] BadPFNs -> BadPFN
- [ ] DIDMetaConventionsConstraints -> DIDMetaConventionsConstraint
- [ ] Heartbeats -> Heartbeat
- [ ] LifetimeExceptions -> LifetimeException
- [ ] DidsFollowed -> DidFollowed
- [ ] FollowEvents -> FollowEvent
- [ ] RSEProtocols -> RSEProtocol

**Comment by dchristidis** [comment]
> RSEProtocols (for example, each entry of this model includes multiple RSE protocols)

I do not understand your conclusion. Each row in the database is exactly one RSE protocol.

**Comment by rdimaio** [comment]
> > RSEProtocols (for example, each entry of this model includes multiple RSE protocols)
> 
> I do not understand your conclusion. Each row in the database is exactly one RSE protocol.

true, I misunderstood the table; I thought that for a given `rse_id`, each `read`/`write` column represented a different 'protocol'. Edited the issue description now

**Comment by dchristidis** [comment]
I would suggest that such efforts be restricted to major releases, like other database changes. It may seem like a simple rename, but probes (thankfully none in this case, as far as I can tell) or other experiment-specific scripts may use the models for custom queries that are not possible through the core layer.

**Comment by rdimaio** [comment]
> I would suggest that such efforts be restricted to major releases, like other database changes. It may seem like a simple rename, but probes (thankfully none in this case, as far as I can tell) or other experiment-specific scripts may use the models for custom queries that are not possible through the core layer.

AFAIK, scripts / programs that use Rucio (e.g. those that use Rucio clients as a library) shouldn't need to interact with the SQLA models, since it'd mean that they are directly interacting with the DB rather than properly using the Rucio API. 

I don't think it's justified to postpone this change to the next major release, since:
-  we are not modifying the public API
- the only changes involved are internal, and if any user is directly using the internal Rucio logic rather than the public API, they should expect that that internal logic could change anytime.

I would prefer if these users opened feature requests for the custom queries they require, rather than us supporting an 'improper' use of Rucio

**Comment by dchristidis** [comment]
> AFAIK, scripts / programs that use Rucio (e.g. those that use Rucio clients as a library) shouldn't need to interact with the SQLA models

The probes must and do. There’s nothing improper about it.

**Comment by rdimaio** [comment]
> > AFAIK, scripts / programs that use Rucio (e.g. those that use Rucio clients as a library) shouldn't need to interact with the SQLA models
> 
> The probes must and do. There’s nothing improper about it.

Are the probes using the Rucio API to interact with the SQLA models?

If that's the case, then I agree that it's an external-facing breaking change and it should be only included in the next major release. 

If that's not the case, then we should consider extending the Rucio API to support the functionality of the probes, if possible. 
If this is not possible, then I can see why it would make sense to postpone until the next major release, but I think it is counterproductive for us to take scripts that are not part of the main Rucio code into consideration with regards to release management; where would we draw the line? If any internal methods are modified, should we always be checking the probes code to ensure the changes don't break anything in the probes?

In my opinion, this setup seems reasonable:
- The script developers/users open feature requests for any API changes/functionalities they need for their code
- If they need to perform any other function outside of the public API, they are free to do so, with the expectation that private interfaces might change during minor/patch releases

**Comment by dchristidis** [comment]
Here’s some historical context.

The probes used to be part of the main Rucio repository. They were split into https://github.com/rucio/probes/ to allow for more flexibility, mainly to allow changes without having to go through our usual review procedure and release schedule, but also to prevent very VO-specific code (which many probes are).

At the time, the recommendation was for the probes to use two layers: the Gateway (previously the API) and the Database. So, with that recommendation came the expectation that there will be no breaking changes to theses layers within a release.

We don’t want to have to reintroduce custom queries back into the main Rucio repository, because at that point we might as well merge all the probes back in.

**Comment by rdimaio** [comment]
> The probes used to be part of the main Rucio repository. They were split into https://github.com/rucio/probes/ to allow for more flexibility, mainly to allow changes without having to go through our usual review procedure and release schedule, but also to prevent very VO-specific code (which many probes are).
> 
> At the time, the recommendation was for the probes to use two layers: the Gateway (previously the API) and the Database. So, with that recommendation came the expectation that there will be no breaking changes to theses layers within a release.
> 
This expectation should be explicitly documented somewhere, either:
- as part of the release policy: https://rucio.github.io/documentation/started/releasepolicy/
- as part of the probes repository: https://github.com/rucio/probes

Until that's formalized, I think that the consideration of probes as part of release management is a grey area.

> We don’t want to have to reintroduce custom queries back into the main Rucio repository, because at that point we might as well merge all the probes back in.

I see a `common` folder in probes: https://github.com/rucio/probes/tree/master/common

I suggest this:
- We create a base Rucio probe, which we (Rucio dev team) support at the same level as the main Rucio code. This probe could possibly be re-integrated into the main repository, similarly to the `clients` and old `webui`.
- Each VO extends the base Rucio probe as needed.

This way: 
- We support VO-specific probes by providing functionality via the base Rucio probe.
- Breaking changes in the public probe API functionality are only included in major probe releases
- Breaking changes in the private functionality are treated in the same way as the rest of the Rucio source code
- We separate responsibilities for the VO-specific probes, so that each VO is responsible for their probe(s), rather than centralizing all of them in a single repository.

**Comment by dchristidis** [comment]
> This expectation should be explicitly documented somewhere

Agreed.

> Until that's formalized, I think that the consideration of probes as part of release management is a grey area.

Not agreed. :smile: The agreement predates the existence of the documentation.

> We create a base Rucio probe, which we (Rucio dev team) support at the same level as the main Rucio code.

I don’t comprehend what you mean. The probes are an official Rucio component, maintained by the Rucio development team. All the probes, not just the common ones. There is crucial core Rucio functionality that cannot work without them (e.g. Reaper, monitoring).

I find what you’re suggesting unnecessary complex. If one wishes to make a change to the database or the gateway, then the PR can be merged for the next major release or an additional PR has to be opened in the probes repository.

> We separate responsibilities for the VO-specific probes, so that each VO is responsible for their probe(s), rather than centralizing all of them in a single repository.

Using a single repository inside the Rucio organisation was a conscious decision. Though it is merely mentioned in https://github.com/rucio/probes/blob/master/CONTRIBUTING.md#motivation there was a discussion and common agreement about it.

**Comment by bari12** [comment]
I think there is merit to both points of view. 
In principle I do not like that the probes have that big of an impact on the development and lock us in a cage where we can't change things. We do distinguish between outer-facing APIs, which we only change for major releases, and inner-facing functionality (core) which we can change. To have this big asterix exception for the probes is not great. To me it puts an unnecessary burden on the development process.

On the other hand they are an important part of operating a Rucio deployment and we might say: Is it that big of a deal to wait for these changes for a major release?

I think we have a few options
A) Make db model changes only for major releases. Pros: Low effort, Cons: Weird to make that isolation exception for the probes
B) Probes should only run against the `X.0.0` rucio release, thus do not upgrade minor releases. Pros: Low effort, Cons: Hard to enforce, error prone
C) Bring back some probe functionality into the cores and have probes access clean through APIs. E.g. Queries inside the core, data manipulation outside. Pros: Clean separation, Cons: High effort, probably introduces some other versioning problems then

**Comment by rdimaio** [comment]
> > This expectation should be explicitly documented somewhere
> 
> Agreed.
> 
> > Until that's formalized, I think that the consideration of probes as part of release management is a grey area.
> 
> Not agreed. 😄 The agreement predates the existence of the documentation.
> 
I think it should have been included in the documentation, then. It's reasonable to expect that the release policy documentation should be the single source of truth for determining what should only be in major versions.

> > We create a base Rucio probe, which we (Rucio dev team) support at the same level as the main Rucio code.
> 
> I don’t comprehend what you mean. The probes are an official Rucio component, maintained by the Rucio development team. All the probes, not just the common ones. There is crucial core Rucio functionality that cannot work without them (e.g. Reaper, monitoring).
> 
I don't think VO-specific probes should be official Rucio components. I think an official Rucio component should be generic and VO-agnostic, so that it can actually be used by any community.

Why would the CMS probe, or the ATLAS probe, be an official Rucio component? If I'm in another community, what use can either of these probes be for me?

> There is crucial core Rucio functionality that cannot work without them (e.g. Reaper, monitoring).

Why is this specific functionality not in the core Rucio code, then? This seems like a 'soft' circular dependency: the probes depend on the Rucio code, but the proper functioning of the Rucio code depends on the probes.

> I find what you’re suggesting unnecessary complex. If one wishes to make a change to the database or the gateway, then the PR can be merged for the next major release or an additional PR has to be opened in the probes repository.
> 
> > We separate responsibilities for the VO-specific probes, so that each VO is responsible for their probe(s), rather than centralizing all of them in a single repository.
> 
> Using a single repository inside the Rucio organisation was a conscious decision. Though it is merely mentioned in https://github.com/rucio/probes/blob/master/CONTRIBUTING.md#motivation there was a discussion and common agreement about it.

Both of these ideas can coexist. We can:
- have the common probe logic be part of the Rucio main repository, and consider it as part of the Rucio source code, and
- have a single repository inside the Rucio organisation for all the community-specific probes.

**Comment by rdimaio** [comment]
> A) Make db model changes only for major releases. Pros: Low effort, Cons: Weird to make that isolation exception for the probes 

The DB models are not the only things from the Rucio core code that is being used in the probes. For example, some `core.rse` logic is being used here:

https://github.com/rucio/probes/blob/a7c055661f85b0363ec1aa7440ac5b470689d887/common/check_free_space#L18-L36

With this approach, I think we would have to make an exception not just for DB model changes, but for any core code that is used in the probes. Because probes lack unit testing (as mentioned here: https://github.com/rucio/probes/blob/master/CONTRIBUTING.md#motivation) and I assume there's not automated testing of other kinds (I don't see any GH actions), this seems like it would be a mostly manual effort of checking if a change could possibly affect the probe functionality.

> B) Probes should only run against the `X.0.0` rucio release, thus do not upgrade minor releases. Pros: Low effort, Cons: Hard to enforce, error prone

I think we should rule this out, as it could likely cause issues in Rucio deployments that are not `X.0.0`, e.g. in the case where:

- The Rucio probes are importing core functionality from Rucio x.0.0
- We modify that same core functionality and release it as part of Rucio x.1.0
- Rucio x.1.0 is deployed and used together with the Rucio probes that are depending on Rucio x.0.0

We'd end up with core functionality that works differently in probes and Rucio. Given that Rucio depends on probes to work properly (as mentioned here: https://github.com/rucio/rucio/issues/6717#issuecomment-2344960262), this could cause inconsistencies that would be very hard to debug. The only way to avoid this would be to implement approach A, but at that point it'd make sense to just go completely with approach A and avoid probe-related core functionality changes in minor/patch releases.

> C) Bring back some probe functionality into the cores and have probes access clean through APIs. E.g. Queries inside the core, data manipulation outside. Pros: Clean separation, Cons: High effort, probably introduces some other versioning problems then

I think this is the most reasonable approach. I am confused about the versioning problems con - what versioning problems would this introduce?

**Comment by dchristidis** [comment]
> I think it should have been included in the documentation, then. It's reasonable to expect that the release policy documentation should be the single source of truth for determining what should only be in major versions.

Again, I agree with you. But we have been historically deficient in our documentation, so it should not come as a surprise when something is missing.

> I don't think VO-specific probes should be official Rucio components. I think an official Rucio component should be generic and VO-agnostic, so that it can actually be used by any community.

I’m not sure how to respond to this. The leads of the probes component disagree with you.

> If I'm in another community, what use can either of these probes be for me?

It assists collaboration. If there’s a VO-specific probe that you can use outright, you can request to be moved to the common directory. Or you can start with it as a template and add your changes on top of it. Separate repositories hinder discoverability.

> Why is this specific functionality not in the core Rucio code, then?

For unfortunate but valid reasons. Let’s take a probe that implements monitoring. If part of the daemon itself, if that daemon misbehaves, then it monitoring stops working. We had discussed something like a cron daemon, but that too would mean that some misbehaviours take out the monitoring. Running it outside of your Rucio instance makes it more robust.

> With this approach, I think we would have to make an exception not just for DB model changes, but for any core code that is used in the probes.

Again, there’s some missing historical context. This probe was implemented prior to the split. When a similar breakage first occurred, we agreed that probes should use the gateway layer, and that layer should be expect to be more stable. The fact that the probe was actually not migrated does not mean that the core can’t be changed.

I think we should discuss in person. I didn’t expect my comment to create such a debate, and this GitHub issue is not the right place.

**Comment by rdimaio** [comment]
> > I don't think VO-specific probes should be official Rucio components. I think an official Rucio component should be generic and VO-agnostic, so that it can actually be used by any community.
> 
> I’m not sure how to respond to this. The leads of the probes component disagree with you.
> 
That's okay, but I would like to understand the arguments in favour of considering VO-specific probes as official Rucio components. 
Correct me if I'm wrong, but I don't see any other official Rucio components (from [this list](https://rucio.github.io/documentation/component_leads/)) that are VO-specific, except for the VO-specific probes;  every other component in the list can be used by any community. What are the arguments for having this big exception in our components, instead of having a clear separation between generic logic and VO-specific logic like it's done for the rest of the Rucio code?

> > If I'm in another community, what use can either of these probes be for me?
> 
> It assists collaboration. If there’s a VO-specific probe that you can use outright, you can request to be moved to the common directory. Or you can start with it as a template and add your changes on top of it. Separate repositories hinder discoverability.
> 

For the same reasons, should we also have a single repository for all VO-specific policy package plugins? I'm not against this idea, as I agree that it assists in collaboration; I'm just saying that these reasons also apply for policy package plugins, and I think we should use the same approach for both.

> > Why is this specific functionality not in the core Rucio code, then?
> 
> For unfortunate but valid reasons. Let’s take a probe that implements monitoring. If part of the daemon itself, if that daemon misbehaves, then it monitoring stops working. We had discussed something like a cron daemon, but that too would mean that some misbehaviours take out the monitoring. Running it outside of your Rucio instance makes it more robust.
> 

I think it makes sense to separate monitoring from a program's functionality in general, as we want the monitoring to keep working regardless of issues in the program. I am not sure about the other probes; do they all implement monitoring in some way?

In the context of the text I was responding to:

> There is crucial core Rucio functionality that cannot work without them (e.g. Reaper, monitoring).
> > Why is this specific functionality not in the core Rucio code, then?

- Regarding monitoring, as mentioned before, it should be separate to the main Rucio logic in order to be more robust. It might make sense to abstract out the Rucio monitoring logic into the probe so that it is all in one place.
- Regarding Reaper, does it depend on a probe that implements monitoring? If not, it could be safe to implement that probe's logic directly into Reaper

> > With this approach, I think we would have to make an exception not just for DB model changes, but for any core code that is used in the probes.
> 
> Again, there’s some missing historical context. This probe was implemented prior to the split. When a similar breakage first occurred, we agreed that probes should use the gateway layer, and that layer should be expect to be more stable. The fact that the probe was actually not migrated does not mean that the core can’t be changed.
> 
Thanks, I didn't know this. I opened this issue for tracking this: https://github.com/rucio/probes/issues/150

> I think we should discuss in person. I didn’t expect my comment to create such a debate, and this GitHub issue is not the right place.

I'm happy to discuss this in person, but I prefer having the overall considerations written down for future reference, otherwise this too would become historical context that future Rucio contributors would not be aware of. I agree that this issue is not the right place, so I created this GH discussion to continue the conversation:

**Comment by rdimaio** [comment]
GH discussion thread for continuing the conversation: https://github.com/rucio/rucio/discussions/7084
