### ISSUE TITLE
Remove deprecated `typing` imports

### ISSUE THREAD

**Issue by erlingstaff** [rucio/rucio#6720]
### Description

Several imports from `typing` are deprecated, and should be either:

1. Removed in favor of builtins, ex: `typing.Dict` -> `dict`
2. Re-imported from another module, ex: `from typing import Callable` ->
`from collections.abc import Callable`

The deprecations are relevant in Python versions ranging from 3.8 -> 3.12. This issue focuses on the imports deprecated in 3.8 or 3.9, as 3.9 is the minimum Python needed to run Rucio (as outlined in `setup_rucio.py`). When Rucio is updated, there might be new deprecations.

The following grep command finds all (i think) instances of deprecated imports:
```
grep -R --include="*.py" -E "from typing import.*(Callable|Iterator|Iterable|Sequence|AbstractSet|Dict|Tuple|List|Set|Type|FrozenSet|Tuple|DefaultDict|OrderedDict|ChainMap|Counter|Deque|AbstractSet|Collection|Container|ItemsView|KeysView|Mapping|MappingView|MutableMapping|MutableSet|MutableSequence|ValuesView|Corutine|AsyncGenerator|AsyncIterable|AsyncIterator|Awaitable|Generator|Reversible|ContextManager|AsyncContextManager|Match|Pattern)(,| )" .
```

This currently returns

![image](https://github.com/rucio/rucio/assets/38101463/96bfeeff-5d16-4c67-ae06-aef89a1c7f02)

More info:
https://docs.python.org/3/library/typing.html#deprecated-aliases
https://peps.python.org/pep-0585/#implementation

### Motivation

1. Standardize imports
2. Avoid DeprecationWarnings and larger changes in the future

### Change

1. Find all deprecated imports from `typing`, either manually or automatically using e.g. the aforementioned grep command
2. Change as appropriate

**Comment by dchristidis** [comment]
We’ve already had #6276 and I’m guessing that they may be accidentally reintroduced again in the future. Could you investigate the use of [Ruff](https://docs.astral.sh/ruff/settings/#lint_flake8-tidy-imports_banned-api)?

**Comment by rdimaio** [comment]
> We’ve already had #6276 and I’m guessing that they may be accidentally reintroduced again in the future. Could you investigate the use of [Ruff](https://docs.astral.sh/ruff/settings/#lint_flake8-tidy-imports_banned-api)?

Good catch on Ruff having this functionality - I'm configuring Ruff to include a few more features, I'll assign this issue to myself to look into adding this too
