### ISSUE TITLE
MySQL8 autotests are failing due to "Temporary failure in name resolution"

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6747]
```
(pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'mysql8' ([Errno -3] Temporary failure in name resolution)")
```

Example: https://github.com/rucio/rucio/actions/runs/8918099209/job/24492187039

Related issue: https://github.com/docker-library/mysql/issues/1048

**Comment by rdimaio** [comment]
> > Deprecation and Removal Notes
> > Important Change: The deprecated mysql_native_password authentication plugin is now disabled by default. It can be enabled by starting MySQL with the new [--mysql-native-password=ON](https://dev.mysql.com/doc/refman/8.4/en/server-options.html#option_mysqld_mysql-native-password) server option, or by adding mysql_native_password=ON to the [mysqld] section of your MySQL configuration file.
> > For more information, see [Native Pluggable Authentication](https://dev.mysqal.com/doc/refman/8.4/en/native-pluggable-authentication.html). (Bug #36337893)
> > - https://dev.mysql.com/doc/relnotes/mysql/8.4/en/news-8-4-0.html

**Comment by rdimaio** [comment]
I tried rolling back to MySQL 8.3 in this commit: https://github.com/rdimaio/rucio/commit/595afe90b3f2447510f953148b80599c9b4703cd

With this change, I get this error (which is likely related to me not having specified the MySQL version properly):
```
 rucio.common.exception.ConfigNotFound: Configuration not found.
Details: Could not load Rucio configuration file. Rucio looked in the following paths for a configuration file, in order:
	/opt/rucio/etc/rucio.cfg
```
(see: https://github.com/rdimaio/rucio/actions/runs/8925397636/job/24514035997)

Then I tried this https://github.com/rdimaio/rucio/commit/326fb8fffe284a4b166543bdcc41804641e0c4f7, and I get this error:
```
WARNING:root:Still waiting for database: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'mysql8' ([Errno 111] Connection refused)")
...
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (6125, "Failed to add the foreign key constraint. Missing unique key for constraint 'SOURCES_REPLICA_FK' in the referenced table 'replicas'")
[SQL: ALTER TABLE rucio.sources ADD CONSTRAINT `SOURCES_REPLICA_FK` FOREIGN KEY(scope, name, rse_id) REFERENCES rucio.replicas (scope, name, rse_id)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
Failed to run alembic migration!
``` 
(see https://github.com/rdimaio/rucio/actions/runs/8925833658/job/24515450220)

It's a bit unclear to me how we're defining the tests, specifically the versions for the DB systems in our tests. I think the changes that I made here https://github.com/rdimaio/rucio/commit/326fb8fffe284a4b166543bdcc41804641e0c4f7 should be correct, and it might be an issue that the test pulls the cached image?

**Comment by rdimaio** [comment]
By specifying MySQL 8.3 correctly, this way https://github.com/rdimaio/rucio/commit/61d00a3486e8b174bf58d7b867ebf8d4d1e2a6b6:

- The MySQL autotests pass: https://github.com/rdimaio/rucio/actions/runs/8929411714
- However, the integration tests fail at the conveyor stage: https://github.com/rdimaio/rucio/actions/runs/8929411712/job/24528778021 (this is the second test run, and multiple tests are failing, so I don't think this is due to flaky tests)

I think ideally we should use MySQL 8.4 in tests, and fix the deprecated command mentioned here https://github.com/rucio/rucio/issues/6747#issuecomment-2090594159 (like I attempted in this commit: https://github.com/rdimaio/rucio/commit/326fb8fffe284a4b166543bdcc41804641e0c4f7)

Edit: the conveyor stage tests for MySQL 8.3 are unrelated to this issue. See this issue for more: https://github.com/rucio/rucio/issues/6751

So we can fix this by pinning to MySQL8.3.

**Comment by rdimaio** [comment]
Discussed with @bari12 and we agreed to pin to `mysql:8.3` for now, and update in this follow-up issue: https://github.com/rucio/rucio/issues/6759.

**Comment by bari12** [comment]
Backport 32.8.3
