### ISSUE TITLE
Investigate `rclone` issue in integ tests

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6763]
https://github.com/rucio/rucio/actions/runs/8982006806/job/24668699045

```
 E   rucio.common.exception.RSEAccessDenied: Referenced RSE not reachable.
E   Details: Referenced RSE not reachable.
E   Details: 2024/05/07 08:30:44 Failed to create file system for "ssh_rclone_rse:": NewFs: couldn't connect SSH: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

See comments here for an initial investigation: https://github.com/rucio/rucio/pull/6761

**Comment by rdimaio** [comment]
## `rucio/containers`
- 34.2.0: https://github.com/rucio/containers/commits/34.2.0
- 34.3.0: https://github.com/rucio/containers/commits/34.3.0

Differing commits:
- https://github.com/rucio/containers/commit/d6b0281be9707dbc647c53b5b960f47288f37dd4: possibly the problem, as it's an `ssh`-related change; however, these [`ssh`-related integ tests pass](https://github.com/rucio/rucio/actions/runs/8982006806/job/24668699045#step:15:41), so `ssh` as a whole doesn't seem to be the problem
- https://github.com/rucio/containers/commit/f3db13fb5c104053c2689bef3ae3d74b32c537ac: likely unrelated
- https://github.com/rucio/containers/commit/5b317a4fcc35e3e456cc4f4e3bf0b907c67ea789: likely unrelated
- https://github.com/rucio/containers/commit/a97e975a0dad0c3fa18c782c5ca291997a593bf8: likely unrelated

**Comment by rdimaio** [comment]
## `rucio/rucio`
- 34.2.0: https://github.com/rucio/rucio/commits/34.2.0
- 34.3.0: https://github.com/rucio/rucio/commits/34.3.0

Diff: https://github.com/rucio/rucio/compare/34.2.0...34.3.0

I don't see any changes that could have caused this. I feel like the issue might likely be on the `rucio/containers` side - if the issue arose from any change in `rucio/rucio`, we would have probably seen some integ test failure at PR time

**Comment by rdimaio** [comment]
This seems sorta related: https://github.com/rclone/rclone/issues/5708#issuecomment-942459714

From [OpenSSH 8.8](https://www.openssh.com/txt/release-8.8): "This release disables RSA signatures using the SHA-1 hash algorithm by default."

Though the `openssh` version used in the tests (found [here](https://github.com/rucio/rucio/actions/runs/8982006806/job/24668699045#step:6:5299)) is `8.7p1-38.el9`, so it should still be enabled. It's also worth noting that this `openssh` version is different from the one found in the [last successful integ test run](https://github.com/rucio/rucio/actions/runs/8886731356/job/24400735656#step:6:5296), where it's `8.7p1-34.el9_3.3`.

The ssh key is generated here: https://github.com/rucio/rucio/blob/bc53dfc7d49f5e0e49de4b4e52adcd4eb28095da/etc/certs/generate.sh#L45

It's an RSA key with no hashing algorithm specified. From what I can see, it defaults to SHA256:
```
❯ ssh-keygen -lf ruciouser_sshkey.pub                                                                                                                                      
2048 SHA256:... ssh keys (RSA)
```

Though according to the manual (https://man.openbsd.org/ssh-keygen.1#rsa): "The available RSA signature variants are “ssh-rsa” (SHA1 signatures, not recommended)" - and the signature of the key seems to be `ssh-rsa` (at least the publickey starts with `ssh-rsa`, but I might be misunderstanding something here)

This is the `sshd_config` for the `ssh` container: https://github.com/rucio/containers/blob/master/ssh/sshd_config, and there's no `PubkeyAcceptedAlgorithms` line.

However, according to this: https://security.stackexchange.com/questions/270349/understanding-ssh-rsa-not-in-pubkeyacceptedalgorithms, the error we should likely see if this was actually the issue should be `key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`.


I think that adding a line about `PubkeyAcceptedAlgorithms` or `PubkeyAcceptedKeyTypes` in `sshd_config` might potentially fix this.

**Comment by rdimaio** [comment]
> This seems sorta related: [rclone/rclone#5708 (comment)](https://github.com/rclone/rclone/issues/5708#issuecomment-942459714)
> 
> From [OpenSSH 8.8](https://www.openssh.com/txt/release-8.8): "This release disables RSA signatures using the SHA-1 hash algorithm by default."
> 
> Though the `openssh` version used in the tests (found [here](https://github.com/rucio/rucio/actions/runs/8982006806/job/24668699045#step:6:5299)) is `8.7p1-38.el9`, so it should still be enabled. It's also worth noting that this `openssh` version is different from the one found in the [last successful integ test run](https://github.com/rucio/rucio/actions/runs/8886731356/job/24400735656#step:6:5296), where it's `8.7p1-34.el9_3.3`.
> 
> The ssh key is generated here:
> 
> https://github.com/rucio/rucio/blob/bc53dfc7d49f5e0e49de4b4e52adcd4eb28095da/etc/certs/generate.sh#L45
> 
> It's an RSA key with no hashing algorithm specified. From what I can see, it defaults to SHA256:
> 
> ```
> ❯ ssh-keygen -lf ruciouser_sshkey.pub                                                                                                                                      
> 2048 SHA256:... ssh keys (RSA)
> ```
> 
> Though according to the manual (https://man.openbsd.org/ssh-keygen.1#rsa): "The available RSA signature variants are “ssh-rsa” (SHA1 signatures, not recommended)" - and the signature of the key seems to be `ssh-rsa` (at least the publickey starts with `ssh-rsa`, but I might be misunderstanding something here)
> 
> This is the `sshd_config` for the `ssh` container: https://github.com/rucio/containers/blob/master/ssh/sshd_config, and there's no `PubkeyAcceptedAlgorithms` line.
> 
> However, according to this: https://security.stackexchange.com/questions/270349/understanding-ssh-rsa-not-in-pubkeyacceptedalgorithms, the error we should likely see if this was actually the issue should be `key type ssh-rsa not in PubkeyAcceptedAlgorithms [preauth]`.
> 
> I think that adding a line about `PubkeyAcceptedAlgorithms` or `PubkeyAcceptedKeyTypes` in `sshd_config` might potentially fix this.

https://github.com/appleboy/scp-action?tab=readme-ov-file#if-you-are-using-openssh this also seems to suggest doing something similar.

https://stackoverflow.com/questions/47102080/ssh-in-go-unable-to-authenticate-attempted-methods-none-no-supported-method - we can run `rclone` in verbose mode, and if that in turn runs `ssh` in verbose mode, we should be able to see the supported methods of authentication

**Comment by rdimaio** [comment]
Comparing these two runs:
- Latest successful `rclone` integ test: https://github.com/rucio/rucio/actions/runs/8886731356/job/24400735656
- Earliest failing `rclone` integ test: https://github.com/rucio/rucio/actions/runs/8969924190/job/24667799694

- `rclone` is `rclone-1.57.0-2.el9.x86_64` in both
- `libssh2` is `1.11.0-1.el9` in both
- `openssh-clients` is `8.7p1-34.el9_3.3` in the successful one, `8.7p1-38.el9` in the failing one
- `openssh` is `8.7p1-34.el9_3.3` in the successful one, `8.7p1-38.el9` in the failing one

**Comment by rdimaio** [comment]
Integ tests were previously passing because the version of `rucio/ssh` used in integ tests was fairly old (9+ months ago). I still have this image in my local dev environment. I'll list here the versions of the relevant dependencies so we can figure out what exactly was deprecated.

- `rclone`: `rclone v1.55.1-DEV` (`go/version: go1.15.5`)
- `openssh`: `OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017`

**Comment by rdimaio** [comment]
The major issue likely seems to be the jump from `openssh 7.4` to `openssh 8.7`. The breaking change that could be related seems to be:

- From [here](https://www.openssh.com/txt/release-8.0):
> sshd(8): Remove support for obsolete "host/port" syntax. Slash-
   separated host/port was added in 2001 as an alternative to
   host:port syntax for the benefit of IPv6 users. These days there
   are establised standards for this like [::1]:22 and the slash
   syntax is easily mistaken for CIDR notation, which OpenSSH
   supports for some things. Remove the slash notation from
   ListenAddress and PermitOpen; bz#2335

We don't use this syntax anywhere in the `sshd` config, though: https://github.com/rucio/containers/blob/a97e975a0dad0c3fa18c782c5ca291997a593bf8/ssh/sshd_config#L4

**Comment by rdimaio** [comment]
These seem to be the versions with relevant breaking changes:

## 7.5 (https://www.openssh.com/txt/release-7.5)

>  * This release deprecates the sshd_config UsePrivilegeSeparation
   option, thereby making privilege separation mandatory. Privilege
   separation has been on by default for almost 15 years and
   sandboxing has been on by default for almost the last five.

We have this in our config: https://github.com/rucio/containers/blob/a97e975a0dad0c3fa18c782c5ca291997a593bf8/ssh/sshd_config#L12-L13 - we need to remove it

## 7.6 (https://www.openssh.com/txt/release-7.6)

>  * Refuse RSA keys <1024 bits in length and improve reporting for keys
   that do not meet this requirement.

The key we use is 2048 bits, so this should not affect us:
```
❯ ssh-keygen -lf ruciouser_sshkey.pub
2048 SHA256:FMPVin8SPBPe8pzMTx6IvE2YMq+5141JRDV1HatVHhA ssh keys (RSA)
```

(and we use `2048` bits when generating it in `generate.sh`)

## 7.8 (https://www.openssh.com/txt/release-7.8)
```
 * ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. The OpenSSH format,
   supported in OpenSSH releases since 2014 and described in the
   PROTOCOL.key file in the source distribution, offers substantially
   better protection against offline password guessing and supports
   key comments in private keys. If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.
```

We use `-m PEM` in `generate.sh`, so this should be fine.

## 8.7 (https://www.openssh.com/txt/release-8.7)

```
 * ssh(1)/sshd(8): both the client and server are now using a
   stricter configuration file parser. The new parser uses more
   shell-like rules for quotes, space and escape characters. It is
   also more strict in rejecting configurations that include options
   lacking arguments. Previously some options (e.g. DenyUsers) could
   appear on a line with no subsequent arguments. This release will
   reject such configurations. The new parser will also reject
   configurations with unterminated quotes and multiple '='
   characters after the option name.
```

**Comment by maany** [comment]
rclone needs an upgrade :) 
https://github.com/rclone/rclone/issues/4177#issuecomment-1264039249

**Comment by rdimaio** [comment]
Re-ran integ tests and now `rclone` tests pass - thanks @maany!
