### ISSUE TITLE
Several ULegacy signal samples are no longer available! 

### ISSUE THREAD

**Issue by kjaffel** [rucio/rucio#6768]
Hello, 

I am encountering an issue with several ULegacy signal samples that were centrally produced. Previously, these files were available, but now I am noticing a concerning message indicating Dataset size: 0 (0.0) for many samples on [DAS](https://cmsweb.cern.ch/das/request?input=dataset%3D%2FHToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8%2FRunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1%2FNANOAODSIM&instance=prod/global). For instance, the files associated with this sample  were previously accessible on `T2_BE_UCL`, and I had been working with them until today.

````
/storage/data/cms/store/mc/RunIISummer20UL16NanoAODv9/HToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v1/40000/F54A9B20-4FF7-B443-A080-920AFAB8CEC2.root
/storage/data/cms/store/mc/RunIISummer20UL16NanoAODv9/HToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v1/40000/EDEFFFB4-298D-EB4B-AA8D-4B4D78CB4F26.root
/storage/data/cms/store/mc/RunIISummer20UL16NanoAODv9/HToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v1/2430000/76012D51-4B97-7A48-94B5-FA6EE27100F2.root
/storage/data/cms/store/mc/RunIISummer20UL16NanoAODv9/HToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v1/40000/4FCB119C-A81B-8844-8EBD-2E3C9292EC3E.root
/storage/data/cms/store/mc/RunIISummer20UL16NanoAODv9/HToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v1/40000/018EEDF7-989F-C344-A31A-61B7DBF51385.root
/storage/data/cms/store/mc/RunIISummer20UL16NanoAODv9/HToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8/NANOAODSIM/106X_mcRun2_asymptotic_v17-v1/40000/600622C3-0719-F745-B23A-BD86DE79F563.root
````

Here's the output from dasgoclient in a verbose mode if needed: `dasgoclient -query 'file dataset=/HToZATo2L2B_MH-379p00_MA-80p99_tb-20p00_TuneCP5_bbH4F_13TeV-madgraph-pythia8/RunIISummer20UL16NanoAODv9-106X_mcRun2_asymptotic_v17-v1/NANOAODSIM' --verbose 3`

[dasgo.log](https://github.com/rucio/rucio/files/15312817/dasgo.log)

I'm unclear why the files are disappearing! Any feedback would be greatly appreciated, this is really urgent, the signals samples are used for analysis going through unblinding.

**Comment by dchristidis** [comment]
I’m afraid we’re not the appropriate audience. This issue tracker is reserved for cross-community Rucio development. What you’re describing is a CMS-specific operational issue. Kindly seek support through the recommended CMS channels.
