### ISSUE TITLE
`DIDClient.add_containers()`: possible bug in function logic

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6803]
Regarding this line:

https://github.com/rucio/rucio/blob/ad19fb40f47f859c3c7f9e2786b4488f43f77ead/lib/rucio/client/didclient.py#L175

In `[dict(list(cnts.items()) + [('type', 'CONTAINER')]) for cnt in cnts]`, the `cnts.items()` seems suspicious - I think it should be `cnt.items()` instead. As it stands, `cnt` is unused in this loop. Is this intended?

**Comment by bari12** [comment]
Honestly, I think this isn't working at all. event with `cnt`?
