### ISSUE TITLE
Rucio LTS: fix MySQL 8 issue

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#6813]
### Description

LTS tests are failing (https://github.com/rucio/rucio/actions/runs/9193986146/job/25287900390 (https://github.com/rucio/rucio/actions?query=branch%3Arelease-32-LTS)) due to the same issue we saw here: https://github.com/rucio/rucio/issues/6747

We need to introduce that fix to the LTS branch

### Steps to reproduce

Run autotests

**Comment by bari12** [comment]
Fixed by cherry picking PR from #6747
