### ISSUE TITLE
permission policy "escape" outdated?

### ISSUE THREAD

**Issue by maxnoe** [rucio/rucio#6815]
### Description

The permission policy "escape" seems to be identical to "generic" but:

* Is missing some type annotations compared to generic
* Is missing a couple of methods (e.g. add_metadata_bulk)

This looks like "escape" is intedend to be identical to "generic" but was not updated after some changes were made to "generic"

### Steps to reproduce

```
nvim -d lib/rucio/core/permission/generic.py lib/rucio/core/permission/escape.py
```

**Comment by bari12** [comment]
It is outdated and will be removed in the process of #4798
