### ISSUE TITLE
rucio cli x509 options not working

### ISSUE THREAD

**Issue by maxnoe** [rucio/rucio#6822]
### Description

The `rucio` cli tool has 

- an option `--certificate` for the x509 certificate but doesn't use it
- has no option for the key

### Steps to reproduce

Look into `bin/rucio` or and `rucio --help`, observe that:

`args.certificate` is never used

there is no option to specify the key

### Rucio Version

current master and older

**Comment by voetberg** [comment]
Easy to fix - question about testing this though. The bin tests assume we have auth already set up when CLI is used, is this something we should change in the future? (They just use userpass if I remember correctly).
