### ISSUE TITLE
"no default delete protocol for QMUL"

### ISSUE THREAD

**Issue by StevenCTimm** [rucio/rucio#6837]
### Description

The Reaper currently refuses to delete anything on storage element QMUL, giving always the error message
No default delete protocol for QMUL. ( I also see this error on a couple other RSEs that are inactive).

### Steps to reproduce

Make a rule on storage element QMUL
rucio delete-rule <rule>
reaper will try to go get it and can't.
QMUL is configured as below.
I deleted the whole configuration and created it again from scratch, it had no effect, same error.

Below is pasted the mattermost thread with the configuration of the RSE.
---------------

Steven Timm
Update your status
[2 months ago](https://mattermost.web.cern.ch/rucio/pl/x86drwzy4in79fzytrsfkfaqze)
2024-04-26 16:47:27,919 root 1 DEBUG [0/8]: Working on QMUL. Percentage of the total space needed 0.00
280726
2024-04-26 16:47:27,924 root 1 WARNING [0/8]: No default delete protocol for QMUL
19 replies

	
Steven Timm
[today](https://mattermost.web.cern.ch/rucio/pl/3of6k8sgjffd3e8qu5k4p57azr)
OK so I went the next step and tried to dump the python dictionaries for this RSE and its protocols.
[today](https://mattermost.web.cern.ch/rucio/pl/uatdw8zacibfbeo843afiuno1y)
{'city': None, 'longitude': None, 'deleted_at': None, 'id': '1150f44263164a269d808e8d21e95a5b', 'region_code': None, 'latitude': None, 'created_at': datetime.datetime(2018, 9, 19, 14, 23, 59), 'rse': 'QMUL', 'country_name': 'UK', 'availability': 7, 'updated_at': datetime.datetime(2023, 4, 12, 20, 35, 52), 'vo': 'def', 'continent': None, 'availability_read': True, 'rse_type': 'DISK', 'time_zone': None, 'availability_write': True, 'deterministic': True, 'ISP': None, 'availability_delete': True, 'volatile': False, 'ASN': None, 'qos_class': None, 'staging_area': False, 'deleted': False}
[today](https://mattermost.web.cern.ch/rucio/pl/gadpbjq3nfnajy83t9h6496zzh)
That's the dump of the rse field
[today](https://mattermost.web.cern.ch/rucio/pl/7sudt59a7jfrtgwpdn9m5m8rce)
and here is the dump of the protocols
[today](https://mattermost.web.cern.ch/rucio/pl/e5szft3p5i8hugm8rn77uohodr)
myrseclient.get_protocols(rse="QMUL")
[{'domains': {'lan': {'delete': 1, 'read': 1, 'write': 1}, 'wan': {'delete': 2, 'read': 1, 'third_party_copy_read': 1, 'third_party_copy_write': 1, 'write': 1}}, 'extended_attributes': None, 'hostname': 'se03.esc.qmul.ac.uk', 'impl': 'rucio.rse.protocols.gfal.Default', 'port': 8443, 'prefix': '/dune/RSE', 'scheme': 'davs'}, {'domains': {'lan': {'delete': 0, 'read': 1, 'write': 0}, 'wan': {'delete': 0, 'read': 1, 'third_party_copy_read': 0, 'third_party_copy_write': 0, 'write': 0}}, 'extended_attributes': None, 'hostname': 'xrootd01.esc.qmul.ac.uk', 'impl': 'rucio.rse.protocols.gfal.Default', 'port': 1094, 'prefix': '/dune/RSE', 'scheme': 'root'}]
Show less
[today](https://mattermost.web.cern.ch/rucio/pl/7yij6e1tetd4m86y841ntosube)
There doesn't seem to be any thing in the python dictionaries that isn't also seen in the CLI.
[today](https://mattermost.web.cern.ch/rucio/pl/1i8gnxweo38g7raxdg7uocrdno)
now the puzzle:  you see from above that rucio-admin rse info QMUL also spews things out like:
[today](https://mattermost.web.cern.ch/rucio/pl/u833uenz43gq8j5u6jfpddaane)
  delete_protocol: 1
[today](https://mattermost.web.cern.ch/rucio/pl/fhr9zzyw7fymigdma7irfw7roc)
  read_protocol: 1
[today](https://mattermost.web.cern.ch/rucio/pl/jujzpb9cpfr8tmy5bb58odxska)
  third_party_copy_read_protocol: 1
  third_party_copy_write_protocol: 1
[today](https://mattermost.web.cern.ch/rucio/pl/x6kxpgw5cj8rpdozkagsdeorce)
  write_protocol: 1
[today](https://mattermost.web.cern.ch/rucio/pl/wuwatcx5ajfwfdg3tfxtxpcute)
Where are those coming from?
[today](https://mattermost.web.cern.ch/rucio/pl/jbujcpufx7njpftczizetz1znr)
I thought it might have been that there was some other protocol that had index "1" at some point which we deleted.
[today](https://mattermost.web.cern.ch/rucio/pl/ko3hzqnqybrfxd4kn8ng7wyrph)
So I deleted all the protocols from the RSE and started again.
[today](https://mattermost.web.cern.ch/rucio/pl/twn91rph6brs9bb46tbggh8iwr)
added them back the same way
[today](https://mattermost.web.cern.ch/rucio/pl/gymptntmiirr9m7qi6gwrxgooy)
This still gets the error "no default delete protocol for QMUL"
[today](https://mattermost.web.cern.ch/rucio/pl/snc96edjqfy8jdiajishtpdb3r)
The other puzzle is that there is no index field in that protocols dictionary so there's no way that "1" means anything.
[today](https://mattermost.web.cern.ch/rucio/pl/of5je14ah7n53r8aipu1dg6bbw)
So what does it take to get a default delete protocol set up?
[today](https://mattermost.web.cern.ch/rucio/pl/1e5yz8jha3r6mqc7ryg7ekz16h)
I really need to get some stuff deleted off of that RSE before it goes down for 3 months in 1 week.

### Rucio Version

34.4.3

### Additional Information

Alma9 client / python 3.9
Problem is on Server side , both client and server are rucio 34.4.3.

**Comment by dchristidis** [comment]
This version of Rucio expects that there’s a protocol with `delete_wan` priority equal to `1`. Alternatively, the Reaper instance must be run with the `--scheme` command-line option.

Future versions of Rucio will behave differently (with `None` meaning disabled and all non-negative integers meaning enabled, with `0` meaning top-priority).

Consequently, this may be considered a configuration error and not a bug.

https://github.com/rucio/rucio/blob/11509cf4750be0ff518588f9c7376d7b8a1106cd/lib/rucio/daemons/reaper/reaper.py#L239-L251

**Comment by StevenCTimm** [comment]
Agreed.. I made the change of my configuration to have a delete protocol of value 1 and it now works and things are being deleted.

Thank you, this can be closed,
