### ISSUE TITLE
Declare Datasets and parent Containers "Partially Available" when first replica gets removed from dataset

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#69]
- ~~Decide on Message format for ActiveMQ Message to AMI:~~ #70 
- ~~Schema change for database to add Partially Available(Imcomplete) to state column~~
- ~~Setting dataset/container state to PA and send message to AMI when first file gets deleted in Dataset~~ #71 

_Migrated from JIRA [RUCIO-2809](https://its.cern.ch/jira/browse/RUCIO-2809)_

**Comment by vingar** [comment]
I had a deep look in the code and it seems we overlooked the pros and cons:

When the last replica is removed, the file is also removed from the content.  Thus generating a INCOMPLETE state and message for a complete dataset from the system point of view is conceptually wrong. 
E.g. A dataset has 10000 files, when the reaper deletes the last replica, it removes it from the content. When listing all replicas, the 9999 files defined in the content are there which contradict the INCOMPLETE state.
Flagging the file as unavailable (and then set the dataset to incomplete) would have been more consistent. The counter part is that we will keep accumulating datasets with unavailable files. When all files are unavailable in the dataset this one is deleted by the reaper ? This will require more changes.

One scenario is to communicate datasets which have no rules anymore against them to AMI. The 'unlocked' datasets can be used by the event index but with the risk that they disappear.  Possible changes in the judge-cleaner ?

**Comment by bari12** [comment]
We discussed this in the meeting and I think conceptually this is fine. It really depends how you interpret the availability column of the did. For me this is not really a data-management related metadata but physics metadata, thus from a physics point of view the dataset is INCOMPLETE. As for data-management related things we do not need the availability column anyway.

The rule scenario would work, but it is really the same, as also in this case we need to store somewhere that the dataset is INCOMPLETE. From a workflow though it is better to do it in the reaper, as it is the last possible moment and the reaper needs to query anyway if this was the last replica, while for the judge this would be a completely new workflow.

**Comment by vingar** [comment]
incomplete is maybe not the correct semantic. 'unlocked' (or similar) makes more sense. message and flag can be generated from the reaper now and later we can think about moving it elsewhere.

**Comment by bari12** [comment]
Unlocked for me is a bit too confusing with lock/rule related things. Personally I feel "incomplete" is fine, but I agree there might be a better terminology for it. But as you said, we can move it later too.

**Comment by vingar** [comment]
I'm still fighting with the concept. 

availability: LOST/DELETED/AVAILABLE
A file is LOST if there are no known replicas of the file in Rucio, while at the same time at least one account requested a replica; a file is DELETED if no account requested a replica; otherwise the file is AVAILABLE. This is a derived attribute.

complete: True/False
A dataset/container where all files have replicas available is complete. Any dataset/container which contains files without replicas is incomplete. This is a derived attribute.

**Comment by bari12** [comment]
A dataset is INCOMPLETE if there is at least one LOST or DELETED file in the dataset.

The fact that this file is not in the main table (only in the deleted one) anymore is fine in my opinion. Don't get me wrong, I fully understand what you mean that conceptually the DELETED/LOST file should be kept in the table (dataset) - but from this workflow we walked away a long time ago. We do remove lost/deleted files in the table (dataset) and move it to the deleted one.
