### ISSUE TITLE
Regression in core/replica.py SQL migration

### ISSUE THREAD

**Issue by erlingstaff** [rucio/rucio#6983]
### Description

A query in core/replica.py is missing part of the base query, as discovered in https://github.com/rucio/rucio/pull/6591#discussion_r1695042752.

- [x] Fix the new queries (done in #6984)
- [ ] Write new tests to catch this regression in the future

### Motivation

The following query in `get_suspicious_reason()`

```
query = session.query(bad_replicas_alias.scope, bad_replicas_alias.name, bad_replicas_alias.reason, bad_replicas_alias.rse_id)\
                   .filter(bad_replicas_alias.rse_id == rse_id,
                           bad_replicas_alias.scope == scope,
                           bad_replicas_alias.name == name,
                           bad_replicas_alias.state == 'S',
                           ~exists(select(1).where(and_(bad_replicas_alias.rse_id == rse_id,
                                                        bad_replicas_alias.scope == scope,
                                                        bad_replicas_alias.name == name,
                                                        bad_replicas_alias.state != 'S',))))
    count = query.count()

    query_result = query.group_by(bad_replicas_alias.rse_id, bad_replicas_alias.scope, bad_replicas_alias.name, bad_replicas_alias.reason).having(func.count() > nattempts).all()
```

Was migrated to the following two subqueries:

```
    stmt = select(
        bad_replicas_alias.scope,
        bad_replicas_alias.name,
        bad_replicas_alias.reason,
        bad_replicas_alias.rse_id
    ).where(
        and_(bad_replicas_alias.rse_id == rse_id,
             bad_replicas_alias.scope == scope,
             bad_replicas_alias.state == 'S',
             bad_replicas_alias.name == name,
             ~exists(select(1).where(
                 and_(bad_replicas_alias.rse_id == rse_id,
                      bad_replicas_alias.name == name,
                      bad_replicas_alias.scope == scope,
                      bad_replicas_alias.state != 'S'))))
    ).subquery()

    count_query = select(
        func.count()
    ).select_from(
        stmt
    )
    count = session.execute(count_query).scalar_one()

    grouped_stmt = select(
        bad_replicas_alias.scope,
        bad_replicas_alias.name,
        bad_replicas_alias.reason,
        bad_replicas_alias.rse_id
    ).group_by(
        bad_replicas_alias.rse_id,
        bad_replicas_alias.scope,
        bad_replicas_alias.name,
        bad_replicas_alias.reason
    ).having(
        func.count() > nattempts
    )
```

These two implementations do not have the same functionality. Specifically, the new `grouped_stmt` does not implement the `where()`-clause

### Change

Refactor the second query in the new implementation to use the `where()`.

**Comment by rdimaio** [comment]
We should also consider why this regression did not cause any tests to fail - we don't necessarily need to do it under this issue, but I think it might be worth looking into fixing/expanding the related tests

**Comment by erlingstaff** [comment]
Good point @rdimaio, I'll change #6984 so that it does not auto-close this issue and open a new PR with some new tests to catch this regression. This way the fix can be merged immediately, and we do not need to wait for me to write the new tests

**Comment by rdimaio** [comment]
might want to reopen it so we don't forget about the "Write new tests to catch this regression in the future" bullet point (however, this was added to the 35.0.0 milestone, so I'm not sure if it's best to open a separate issue for this)
