### ISSUE TITLE
Decide on Message format for ActiveMQ Message to AMI

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#70]
Do we need two different messages? One for Dataset one for Container or is the same one sufficient?

_Migrated from JIRA [RUCIO-2810](https://its.cern.ch/jira/browse/RUCIO-2810)_

**Comment by vingar** [comment]
Is it related to the INCOMPLETE message ? Do we have another issue related to it ?

Motivation: 
When a dataset starts being deleted, If its state change to INCOMPLETE from a previous state != INCOMPLETE, then a message is produced:

            add_message('INCOMPLETE', {'scope': scope, 'name': name})

**Comment by bari12** [comment]
Yes, the epic issue for this is #69. I just noticed though, we added the INCOMPLETE state in the schema.sql, but not in models.py or constants.py yet.

**Comment by vingar** [comment]
I checked on next and could not find the constants change ? models.py is not necessary.

**Comment by bari12** [comment]
Yes, as I said, it's not there 😄

**Comment by vingar** [comment]
but I did the merge request (100% sure)...

**Comment by bari12** [comment]
It doesn't seem to be in there. Only schema.sql and the migrate_repo file.
https://github.com/rucio/rucio/commit/bf36f633622d469479074a15ecdaf28b91f86a9b

**Comment by bari12** [comment]
But just coming back to the original question. I think one message is enough, no need to have one for DATASET and one for CONTAINER.

**Comment by vingar** [comment]
did_type in the message ?

**Comment by bari12** [comment]
Yes, I think so. To some extent it is redundant, as e.g. AMI would know it anyway, but maybe this is consumed by other services too which do not necessarily know.

**Comment by vingar** [comment]
issue #68 is about 'Protect storage from too many requests ' ?

**Comment by bari12** [comment]
You mean about the epic issue link above? I accidentally linked #68 first, but then corrected to #69; Maybe in your eMail it still says the first version.
