### ISSUE TITLE
Postgres DID metadata plugin - is it being used in production?

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#7025]
Plugin in question:

https://github.com/rucio/rucio/blob/c0b58178c238556e553df0d7d200de5437bafaed/lib/rucio/core/did_meta_plugins/postgres_meta.py

I think we need some more information on these plugins (`postgres`, `mongo`) - they don't seem to be mentioned in the docs https://rucio.github.io/documentation/operator/did_meta/ and it's not clear whether they are being used in production (or if they are production ready). I spoke with Rob about them, and it seems like these were initially developed as proofs of concept.

If they're not being used in production yet and they should be refactored - is there any reason why we're not using SQLAlchemy for the queries here?

Related issue: https://github.com/rucio/rucio/issues/6669

**Comment by robbarnsley** [comment]
The postgres plugin is being used in "production" by us (SKAO). There are issues/prs outstanding blocked by https://github.com/rucio/rucio/issues/6669 that prevent it from being more production-ready (https://github.com/rucio/rucio/pull/6373, https://github.com/rucio/rucio/issues/6666).

Personally i'm not sure about the merit of transitioning to sqla here. From experience, the JSON support between the different dialects in sqla is a bit flaky, especially if structures are nested, and you end up with branching logic somewhere that can require quite hacky workarounds, e.g. https://github.com/rucio/rucio/blob/c0b58178c238556e553df0d7d200de5437bafaed/lib/rucio/core/did_meta_plugins/filter_engine.py#L479-L497 which is harder to track down bugs with/maintain imho.

Agree the docs need updating though.
