### ISSUE TITLE
Use `abstractmethod` decorator in place of `NotImplementedError` in instances where we're using `NotImplementedError` to mark an abstract method

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#7031]
e.g. for methods like https://github.com/rucio/rucio/blob/c0b58178c238556e553df0d7d200de5437bafaed/lib/rucio/rse/protocols/protocol.py#L493

we should be using: https://docs.python.org/3/library/abc.html#abc.abstractmethod

**Comment by bari12** [comment]
You mean defining the parent class methods as abstract, and then just not implementing them?
Just need to make sure that this is correctly caught then.

**Comment by rdimaio** [comment]
> You mean defining the parent class methods as abstract, and then just not implementing them? Just need to make sure that this is correctly caught then.

The `RSEProtocol` class should be marked as an abstract class (by deriving `ABC` https://docs.python.org/3/library/abc.html#abc.ABC), and the abstract methods (the ones currently raising `NotImplementedError`) should be marked with the `@abstractmethod` decorator
