### ISSUE TITLE
Conveyor receiver incorrectly handles multi_source jobs

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#704]
Motivation
----------
The conveyor receiver incorrectly handles multi source jobs. This is the case for jobs where the first source FAILS and the second one is a success.

The poller requests jobs via the transfer tool which does quite a bit of response formatting and checking. In the case of multi source jobs, it basically iterates the sources and if one of the sources is in state FTSState.FINISHED it returns the job as SUCCESS. The receiver however does not go via the transfertool as it gets the response directly from activemq. In the case of a job where the first source fails but the second one is a succes, the receiver only looks at the `t_final_transfer_state` which is FTSCompleteState.ERROR. However, what it actually should do is to iterate the sources like the conveyor poller. It seems that the `t_final_transfer_state` field can only be used for bulk-transfers, not multi-source transfers.

Modification
------------
Factorize the formatting used in the transfer tool and re-apply to conveyor receiver code.

**Comment by cserf** [comment]
Up
