### ISSUE TITLE
add_key broken on mySQL

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#705]
Motivation
----------

>>> from rucio.core.meta import add_key
>>> from rucio.db.sqla.constants import DIDType 
>>> add_key('datatype', DIDType.FILE)  
(_mysql_exceptions.DataError) (1265, "Data truncated for column 'key_type' at row 1") [SQL: u'INSERT INTO did_keys (`key`, key_type, value_type, value_regexp, updated_at, created_at) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: ('datatype', 'F', None, None, datetime.datetime(2018, 2, 19, 13, 41, 49, 985745), datetime.datetime(2018, 2, 19, 13, 41, 49, 985773))]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/rucio/db/sqla/session.py", line 358, in new_funct
    raise DatabaseException(str(error))
rucio.common.exception.DatabaseException: Database exception.
Details: (_mysql_exceptions.DataError) (1265, "Data truncated for column 'key_type' at row 1") [SQL: u'INSERT INTO did_keys (`key`, key_type, value_type, value_regexp, updated_at, created_at) VALUES (%s, %s, %s, %s, %s, %s)'] [parameters: ('datatype', 'F', None, None, datetime.datetime(2018, 2, 19, 13, 41, 49, 985745), datetime.datetime(2018, 2, 19, 13, 41, 49, 985773))]

Probably related to str vs unicode

Modification
------------

Fit it

**Comment by shreyanshk** [comment]
Hi,
I am working on this bug and have setup an instance in docker. I can identify that the key_type is actually an enum in the database and 'F' (which is being passed to the database) is not among valid values. Valid values are ('ALL','CONTAINER','DERIVED','COLLECTION','DATASET','FILE').
I'm not sure how the tuple ('F', 'FILE') as in constants.py is being turned into string 'F' when evaluated.
```
from rucio.db.sqla.constants import DIDType
DIDType.FILE.__dict__
>>> {'description': 'FILE', 'name': 'FILE', 'value': 'F', 'cls_': <class 'rucio.db.sqla.constants.DIDType'>}
```
I could use some context here.
Thank you.

**Comment by bari12** [comment]
This conversion is done by sqlalchemy I think. If you are preparing a patch, I am assigning the ticket to you 😄  Thanks a lot!

**Comment by shreyanshk** [comment]
Hi @bari12,
I decided to fire up a debugger and have identified the source of this conversion. It is being handled in DeclEnumType class in lib/rucio/db/sqla/enum.py
For some reason the migrations/create_all functions are creating this SQL statement
```
CREATE TABLE `did_keys` (
  `key` varchar(255) NOT NULL,
  `is_enum` tinyint(1) DEFAULT '0',
  `key_type` enum('ALL','CONTAINER','DERIVED','COLLECTION','DATASET','FILE') DEFAULT NULL,
  `value_type` varchar(255) DEFAULT NULL,
  `value_regexp` varchar(255) DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  PRIMARY KEY (`key`)
)
```
There is an inconsistency between the database and the application.
The database expected values: 'ALL','CONTAINER','DERIVED','COLLECTION','DATASET','FILE'
The application expected values: 'F', 'D', 'C', 'A', 'X', 'Y', 'Z'

In fact, manually executing below SQL statement brings the system in consistent state.
```
alter table did_keys modify column key_type enum('F', 'D', 'C', 'A', 'X', 'Y', 'Z') default null;
```
and then successfully allows running the following script.
```
from rucio.core.meta import add_key
from rucio.db.sqla.constants import DIDType

add_key('datatype', DIDType.FILE)
```

I think that either the SQLAlchemy's create_all function or Alembic's migrations are the issuing incorrect SQL. There is also possibility that DeclEnumType class is handling the conversions incorrectly but the code looks correct to me.
Also, I may be wrong as the codebase is big and I keep on finding surprises in it. Please let me know if that is the case.
Next, I'll try to find out what is issuing the incorrect SQL.
Thank you.

**Comment by vingar** [comment]
I  think it's just a specific dialect conversion missing somewhere. We need to have a test for this in `lib/rucio/tests/test_meta.py` to reproduce this. 

@shreyanshk Would it be fine for you to do a pull request with a test ? as such we can have a deeper look on this.

**Comment by shreyanshk** [comment]
@vingar, Please have a look at the opened pull requests and CI logs.
I added a test to test_meta.py and hopefully it is what was asked.
I was fully expecting tests on MySQL to fail but surprisingly all tests passed.
What is even more surprising is that tests on PostgreSQL failed (!).
I didn't touch application logic. So, I am having hard time following it.
What do you think?

**Comment by vingar** [comment]
The test error should be unrelated as we have some instabilities in the test with dbs. I've relaunched the failed tests manually in travis. Thanks for the PR !
