### ISSUE TITLE
Policy package version support: specifying each supported major version (current way of doing things) vs specifying a minimum valid version (proposal)

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#7082]
## Description

This is the way that Rucio currently checks that a policy package supports the current Rucio version:

https://github.com/rucio/rucio/blob/5d42f2c54bc60a213701bb6b77bf810835a280b4/lib/rucio/common/utils.py#L2115-L2119

This only works if the policy package's `SUPPORTED_VERSION` list specifies a major version. This is in line with the [policy package docs](https://rucio.github.io/documentation/operator/policy_packages/):

> `__init__.py` should include a `SUPPORTED_VERSION` field indicating the major version(s) of Rucio that your package supports. This is checked against the Rucio server version to ensure compatibility when loading the policy package.

The code parses the current version like this:

```
>>> components = 1
>>> versions = "35.0.0"
>>> ".".join(version.split(".")[:components])
'35'
```

and then just checks that the string `'35'` exists in `SUPPORTED_VERSION`. 

However, the latest version of the ATLAS policy package depends on `Rucio >= 35.1.0`:

https://gitlab.cern.ch/atlas-adc-ddm/rucio-policy-package/-/blob/master/src/atlas_rucio_policy_package/__init__.py?ref_type=heads#L1

This is because it depends on a fix that was added in Rucio `35.1.0.`

## Consideration
Right now, we specify each supported major version. With regards to the ATLAS policy package, this would mean that we should set the supported Rucio version to `36`. However, this:
1. is not completely correct (36 is not the only supported Rucio version for the policy package, since it supports some minor versions of Rucio 35, just not 35 as a whole)
2. delays deployment of the policy package to the next major release, even though it is already compatible with the current minor release

I think this sparks the discussion of whether it would be better to specify a minimum valid version instead. 

Considering that policy packages might depend on fixes and patches introduced in minor Rucio releases, I would propose to instead:
1. allow the operator to specify a minimum supported Rucio version in the policy package
2. allow the operator to optionally specify unsupported versions (this is akin to how Python requirements are specified, e.g. `pkg_name>2.0.0, !=2.2.0` allows the installation of any `pkg_name` version higher than `2.0.0` except `2.2.0`)
3. In the Rucio code, check `rucio_version not in UNSUPPORTED_VERSIONS` and `rucio_version >= minimum_supported_version`). To do this second comparison, we should use `packaging.version.Version` (https://stackoverflow.com/a/11887885)

**Comment by bari12** [comment]
I think this makes sense. When @jamesp-epcc and I originally discussed this, we were thinking to make it as easy as possible. But perhaps we need to refine this.

**Comment by jamesp-epcc** [comment]
The problem is that sometimes changes in the Rucio code break backwards compatibility with the policy packages (for example, changes to the signatures of permission functions), so a policy package that works with (for example) version 32 can't be guaranteed to work with version 33. So I'm not sure if this would be possible unless we mandate that the core code must not change in a way that breaks backward compatibility with policy packages.

**Comment by rdimaio** [comment]
> The problem is that sometimes changes in the Rucio code break backwards compatibility with the policy packages (for example, changes to the signatures of permission functions), so a policy package that works with (for example) version 32 can't be guaranteed to work with version 33. So I'm not sure if this would be possible unless we mandate that the core code must not change in a way that breaks backward compatibility with policy packages.

I think it comes down to a design decision where either option is valid:
- current method, allowlist-based version checking: operator specifies only the specific supported versions.
    - with this method, the assumption is that a new Rucio version is incompatible with the policy package unless it's explicitly specified to be compatible.
    - this currently only supports allowlisting major versions. If we want to keep this while adding more versatility for policy package operators, we could consider adding a feature to optionally specify minor/patch version (see https://github.com/rucio/rucio/issues/7083)
- blocklist-based version checking: operator specifies a minimum version, and adds a version to the blocklist if incompatible. 
    - with this method, the assumption is that a new Rucio version is compatible with the policy package unless it's explicitly specified to be incompatible.
    - I think for people familiar with Python versioning (policy package operators probably fit this description), they'd be more familiar with this range-based blocklist.

I assume that the likelihood of a new Rucio version having breaking changes for policy packages is lower than the likelihood of that version not having any breaking changes for policy packages - if this is the case, the blocklist-based assumption would seem more sensible. 

On the other hand, I can see why it would be better to play it safe and keep the current version checking (for the same reasons that e.g. we pin dependencies for the Rucio server)

**Comment by bari12** [comment]
Wouldn't be a middle way to define a minimum version, within the release range?
Thus if you define
* `35` -> `>=35.0,0;<36.0,0`
* `35.1` -> `>=35.1,0;<36.0,0`
* `35.4` -> `>=35.4.0;<36.0,0`
?

**Comment by jamesp-epcc** [comment]
So I guess we have (at least) three options:

1. Keep the current "allow list" based system
2. Keep the current system but interpret version numbers as a minimum version within the major release, as Martin suggests
3. Switch to a "block list" plus minimum version instead

I don't have strong feelings on what would be best here. 1 would ensure that we don't break existing policy packages, but 2 should also be relatively safe I think.

**Comment by rdimaio** [comment]
> Wouldn't be a middle way to define a minimum version, within the release range? Thus if you define
> 
>     * `35` -> `>=35.0,0;<36.0,0`
> 
>     * `35.1` -> `>=35.1,0;<36.0,0`
> 
>     * `35.4` -> `>=35.4.0;<36.0,0`
>       ?

We could do it this way as well, using the "compatible release" specifier: https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release

https://packaging.pypa.io/en/stable/specifiers.html

**Comment by bari12** [comment]
Let's do it as @rdimaio suggested and use the https://packaging.python.org/en/latest/specifications/version-specifiers/#compatible-release - this is easy to implement and gives the policy-package maker all tools to specify the compatibility.
