### ISSUE TITLE
Policy package version check: instead of parsing string manually, use `packaging.version.Version`

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#7083]
change should be done here https://github.com/rucio/rucio/blob/5d42f2c54bc60a213701bb6b77bf810835a280b4/lib/rucio/common/utils.py#L2115-L2119

according to https://stackoverflow.com/a/11887885

Note: this should be done regardless of what we decide to do here: https://github.com/rucio/rucio/issues/7082

**Comment by jamesp-epcc** [comment]
I think the only downside to this is that it would add an additional client dependency, which is something I know we were trying to minimise (server and dev already depend on `packaging`, but client does not). I don't have strong feelings on whether it's worth adding that dependency or not.
