### ISSUE TITLE
Clarify format of `filters` in `DIDClient.list_dids` for CLI usage

### ISSUE THREAD

**Issue by rdimaio** [rucio/rucio#7117]
This docstring:

https://github.com/rucio/rucio/blob/01bf2dd2bedf5da4201057351ce4e43643ec64ca/lib/rucio/client/didclient.py#L49

can cause a bit of confusion when using the CLI client, where the expected format of `filters` does not match the way it is written in the docstring, but it's rather written as `key=value`. 

A good idea could be to provide a CLI usage example within the docstring, e.g.:

```
rucio list-dids --filter key1=value test:*
```

**Comment by voetberg** [comment]
This documentation shouldn't be referenced when the user is using the CLI - what they'll look at is this 
https://github.com/rucio/rucio/blob/221dc03eb1ad208812c50073cdba49354f821553/bin/rucio#L2091

The nested dictionary format is correct for the py client.

**Comment by rdimaio** [comment]
> This documentation shouldn't be referenced when the user is using the CLI - what they'll look at is this
> 
> https://github.com/rucio/rucio/blob/221dc03eb1ad208812c50073cdba49354f821553/bin/rucio#L2091
> 
> The nested dictionary format is correct for the py client.

That's a good point, closing this issue; I think at most it might be nice to autogenerate the CLI client docs from the help messages in the CLI commands just to have them in the documentation website, but it's not really needed

**Comment by voetberg** [comment]
> That's a good point, closing this issue; I think at most it might be nice to autogenerate the CLI client docs from the help messages in the CLI commands just to have them in the documentation website, but it's not really needed

We do have that - view https://rucio.cern.ch/documentation/bin/rucio 

I think these should probably have their own tab though - putting an issue in for that
