### ISSUE TITLE
Ability to restrict archive metadata policy to certain RSEs

### ISSUE THREAD

**Issue by mlassnig** [rucio/rucio#7127]
### Description

It is unnecessary to send the archive metadata with all transfers, we should be able to restrict it to transfers to certain destination RSEs, maybe through a new RSE attribute (archive_metadata: true|false).

**Comment by mlassnig** [comment]
pinging @beer4duke

**Comment by rdimaio** [comment]
I think it might make sense to do this at the `FTS3TapeMetadataPlugin` level, rather than adding a new RSE attribute - we could add logic to `FTS3TapeMetadataPlugin` to only generate metadata for transfers where RSE matches certain attributes

**Comment by bari12** [comment]
Do we really need that? Is it that problematic to send it to tape systems which do not support the archive_metadata?

**Comment by beer4duke** [comment]
@bari12 archive_metadata is a specific header that sites should ignore if they do not support it: just another header.
Yet archive_metadata has to be stored in the underlying sheduler DB to be passed per file and depending on the DB sizing this could create some issues: 1kB per file to a tape destination.
This is more a possible mitigation/staged deployment in case of trouble with the selected FTS instance for the transfer: disable archive_metadata for tape RSEs close to problematic instance while not affecting other tape RSE.

The choice is yours: I just suggested this as a fine grained kill switch just in case.

**Comment by bari12** [comment]
Let's not do it for now and see if this is actually a problem.
