### ISSUE TITLE
Wrong sorting of list of rule in R2D2

### ISSUE THREAD

**Issue by tbeerman** [rucio/rucio#713]
Motivation
----------
When sorting the rules in R2D2 by creation date the result is wrong. Currently this is done using a simple string sorting which is wrong.

Modification
------------
Change the sorting to correctly sort the dates chronologically.

**Comment by rak108** [comment]
Is this still open? If so, can I take it up?

**Comment by mlassnig** [comment]
@rak108 yep!

**Comment by DhruvSondhi** [comment]
Hello, I had a query regarding the same ... I wish to know whether this sorting works with the DID filtering?

**Comment by dynamic-entropy** [comment]
Already fixed here, #4172

**Comment by DhruvSondhi** [comment]
To incorporate this we can also change the format directly where it is being created 🤔 or else we can convert it into a floating number & compare it that way leading to easier creation data type

**Comment by bari12** [comment]
@dynamic-entropy can you confirm that this is fixed now?

**Comment by dynamic-entropy** [comment]
Yes, earlier dates were converted to simple strings which were not Lexicographically sorted. However, [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) requires string representation to be Lexicographically sorted. Which was changed in #4172 for all places in web UI, at the initialisation stage itself.
