### ISSUE TITLE
json based import for RSEs, protocols, distances

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#716]
Motivation
----------
To have a structured way of importing RSEs, their protocols and even distances a json based importer would be beneficial.

**Comment by mlassnig** [comment]
JJ "volunteered", can you give him more details pls.

**Comment by jwackito** [comment]
Should this be a rucio-admin command? I was thinking about something like 
```
rucio-admin rse export RSE_NAME -o/--output rse.json (default to rse_name.json)
rucio-admin rse import rse_name.json
```
Which attributes should be mandatory, in order to make the method fail proof?
For distances, maybe an update method that support json files will do the trick.
`rucio-admin update-distances --from-json distances.json`
May also work for protocols.

**Comment by bari12** [comment]
The original idea of this came from Ale and what he had in mind was really a full importer. Thus essentially everything (rses, attributes, protocols, distances) can be represented as one big json and this can be imported by rucio to update/create/delete etc. I think we will need some further face2face discussion on this.

**Comment by hahahannes** [comment]
I would propose to add the endpoints /import and /export endpoints to the API where the admin can upload the full json file. Instead of different rucio-admin commands, there would been one command  like `rucio-admin import data.json`.

**Comment by mlassnig** [comment]
Other option, maybe as `/rse/configuration` with associated GET, POST, and DELETE?

**Comment by hahahannes** [comment]
I think a more general endpoint like `/configuration` is better if we want to add more export functionality in the future. For example with users or scopes if this would be useful later.

**Comment by bari12** [comment]
I think a separate endpoint might be better. It gives us more flexibility to widen the scope of the importer/exporter later on.

**Comment by hahahannes** [comment]
What endpoint name should we use in this case? Maybe `configuration` is a bit confusing as there already is an endpoint `config`.

Also I would like to reopen the PR [https://github.com/rucio/rucio/pull/1259](https://github.com/rucio/rucio/pull/1259) to use the export_distances() function.
