### ISSUE TITLE
conveyor-receiver uses name of policy package as vo name

### ISSUE THREAD

**Issue by maxnoe** [rucio/rucio#7207]
### Description

https://github.com/rucio/rucio/blob/3d5cbf5d8c0e37f793bbd6f01d1064e44cfe0b4f/lib/rucio/daemons/conveyor/receiver.py#L80-L82

This is a tad surprising... in our test setup, voname and name of the policy package are not identical

### Steps to reproduce

See above

### Rucio Version

Current and older

**Comment by maxnoe** [comment]
In our case, `get_policy()` even returns "generic", because we configured the policy package via the `RUCIO_POLICY_PACKAGE=bdms_rucio_policy` env variable

**Comment by maxnoe** [comment]
Looking at the code of `get_policy`, this is also linked to #7206

**Comment by jamesp-epcc** [comment]
I think this is related to (or possibly even the same issue as) https://github.com/rucio/rucio/issues/5764

**Comment by maxnoe** [comment]
Yes, same issue
