### ISSUE TITLE
New CLI: `--help` shows the old command structure

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#7245]
### Description

https://github.com/rucio/rucio/blob/46cc73438ba4042ac937fff1c5a0dfabc83e91f3/bin/rucio#L42
https://github.com/rucio/rucio/blob/46cc73438ba4042ac937fff1c5a0dfabc83e91f3/bin/rucio#L91

`-h` is included, but `--help` is not. Is this on purpose or accidental?

**Comment by voetberg** [comment]
Accidental 🤦
