### ISSUE TITLE
Admin interface in Rucio UI

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#78]
_Migrated from JIRA [RUCIO-2840](https://its.cern.ch/jira/browse/RUCIO-2840)_

**Comment by bari12** [comment]
I guess this is a duplicate for #80 and #81?

**Comment by mlassnig** [comment]
pinging @tbeerman

**Comment by tbeerman** [comment]
well, in JIRA it was the main task and #80 and #81 where the sub-tasks

**Comment by bari12** [comment]
Ah ok, what you can do in github which is a bit similar to epics in jira is create tasklist inside the ticket, which you could use as an epic.

- [ ] a
- [ ] b
- [ ] c

**Comment by cserf** [comment]
Closing as duplicate
