### ISSUE TITLE
Add Globus as Protocol and TransferTool

### ISSUE THREAD

**Issue by briedel** [rucio/rucio#805]
Motivation
----------

To be able to access storage at HPC centres (e.g. US leadership-class facilities) we will need to add Globus as an option to transfer files to/from the site

Modification
------------

Add `globus://` as protocol and supporting Globus as a `transfertool`

**Comment by bbockelm** [comment]
First, we'll also need to make sure that all the transfer logic is indeed in the transfer tool: last I checked, some FTS code had snuck into the conveyor itself.

**Comment by bari12** [comment]
Yes, there are some parts, especially related to activemq messages which are part of the conveyor directly. this needs to be properly disentangled and put into the transfertool.

**Comment by bari12** [comment]
#857 is related to this.

**Comment by bari12** [comment]
This has been implemented in #2905
