### ISSUE TITLE
Keyword parameters should always be used for instansiating datetime.timedelta

### ISSUE THREAD

**Issue by dchristidis** [rucio/rucio#807]
## Motivation

`datetime.timedelta(1)` is not as readable as `datetime.timedelta(days=1)`. Though there are only four such cases in the Rucio source code, two of those require additional discussion as they might reveal subtle bugs. What is implied and what is actually done differs.

 1. In `tools/probes/common/check_used_space`, the current time and the timestamp in the database are compared. If the range between the two is longer than `datetime.timedelta(1)`, the entry is considered stale. However, the message is ‘Used space has not been refreshed for more than 1 *hour*.’

 2. In `lib/rucio/tests/test_replica.py`, there is the following assignment: `tomorrow = datetime.utcnow() + timedelta(2)`. It feels like either the argument is wrong or the variable name is misleading.

## Modification

I intend to explicitly add the `days` keyword to all instances and, depending on the feedback, provide fixes for the two cases described above.

**Comment by cserf** [comment]
1. Should be indeed datetime.timedelta(hours=1)
2. Should be tomorrow = datetime.utcnow() + timedelta(1)
