### ISSUE TITLE
Client migration to Python3

### ISSUE THREAD

**Issue by jwackito** [rucio/rucio#819]
Motivation
----------
We need to make Rucio clients Python3 compatible

Modification
------------
Proposed incremental scenario (each step should be one or several pull requests):

- [x] Enable 2to3 in travis to report py3k incompatibility
- [x] change print by print()
- [x]  change xrange -> range
- [x] Fix dict.keys()/dict.values() to list()
- [x] Fixed  exception to be py3K compatible
- [x] compatible imports
- [x] float, Long, etc
- [x] Unicode vs byte string
- [x] having a py3K packaging +ping test in the test suite for the clients once the migration is complete (e.g. tox)
- [x] Check compatibility with different Python 3 versions; Currently works with 3.5 but not with 3.6

others maybe, python3 interpreter will tell...

**Comment by bari12** [comment]
There is a general ticket tracking the py3k migration.
https://github.com/rucio/rucio/issues/67
You can use this for general tracking.

**Comment by jwackito** [comment]
I should close this issue then?

**Comment by kreczko** [comment]
BTW: I found that the `six` python module makes these kinds of things easier during the transition period:
https://pythonhosted.org/six/#module-six.moves

It is also easier to find them later (searching for `six`) whenever the project is ready to go Python 3 only.

**Comment by cserf** [comment]
I think all the client files are now py3k compatible. @hahahannes can you confirm ?

**Comment by hahahannes** [comment]
The last ones missing are the didclient, fileclient, dq2client and the downloadclient. According to pylint there are just small changes needed. I can fix them.
