### ISSUE TITLE
Rucio Upload Should Respect verify_checksum Flag

### ISSUE THREAD

**Issue by berghaus** [rucio/rucio#847]
Motivation
----------
When uploading to `CERN-EXTENSION_GRIDDISK` the Rucio client fails because it attempts to verify the checksum. At the moment the `verify_checksum` flag is set for the RSE and not ask the storage for the checksum.

The suggested modification will then also skip the verification of the file size on storage. The stat call checking the file size should be OK, and in this scenario is even more important to be verified (in [rsemgr](https://github.com/rucio/rucio/blob/e708f55772d74c782d36f79cfda521570190111a/lib/rucio/rse/rsemanager.py#L398)).

I loathe to put this modification at the protocol level hence the suggested modification, please let me know if you have better ideas.

Modification
------------
- [x] copy `verify_checksum` RSE attribute to RSE info
- [x] get `verify_checksum` from RSE info in `rsemgr.upload`
- [x] always declare uploaded file as valid if `ignore_checksum` is True.

**Some notes**
On line [405](https://github.com/rucio/rucio/blob/e708f55772d74c782d36f79cfda521570190111a/lib/rucio/rse/rsemanager.py#L405) of the rsemgr add
```python
valid = True if ignore_checksum is True else False
```
After discussion with Martin we decided that `verify_checksum` should conceptually be RSE info and to copy it analagously to the `lfn2pfn_algorithm` attribute/info.

**Comment by berghaus** [comment]
No comment? Alright I'll try out what I am suggesting ;-)

The other option I was able to think of is to create a separate function in the protocols that get the checksum.

**Comment by bari12** [comment]
Hi Frank, sorry for the late reply. 👍 for the approach you are describing. Don't think we need the separate function in protocols.

**Comment by berghaus** [comment]
Thanks Martin, I'll get started with it :-)
