### ISSUE TITLE
Disentangle fts3 specific code from conveyor submitter and move to transfertool

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#857]
Motivation
----------
There are some fts3 specific parts in the conveyor, mostly job dictionary building and processing of activemq message results which needs to be disentangled from the code and moved to the tranfertool.

**Comment by bari12** [comment]
Part of #4499

**Comment by rcarpa** [comment]
I think this one is fixed. See https://github.com/rucio/rucio/issues/4873 for a follow-up in other parts of conveyor
