### ISSUE TITLE
Fixing grammatical errors in the documentation

### ISSUE THREAD

**Issue by tushar-97** [rucio/rucio#886]
Motivation
----------
To go through the documentation and submit my first patch.

Modification
------------
Fixed some grammatical errors in the documentation.

**Comment by tushar-97** [comment]
Is there anyway I can propose just one request with all changes across multiple files?

**Comment by mlassnig** [comment]
Sure, just add multiple changed files to the same pull request.

**Comment by tushar-97** [comment]
@mlassnig Done. Sorry for the mix up before
