### ISSUE TITLE
Add release notes to repository

### ISSUE THREAD

**Issue by bari12** [rucio/rucio#912]
Motivation
----------
Add the release notes to the repository, so that they are available on the documentation.

**Comment by tushar-97** [comment]
@bari12 I would like to take this up if possible. Where exactly do the release notes have to be added?

**Comment by vingar** [comment]
Part of the work is to replicate the changelog from here https://github.com/rucio/rucio/releases into individual rst files. I guess you can help on this but first @bari12 has to define the directory and file name conventions.

**Comment by bari12** [comment]
Hi, I have already started with this and prepared a structure and kind of template. (PR for that will come today) - If you would like to you could then fill all the missing release notes. I would be very thankful for that 😄

**Comment by tushar-97** [comment]
Sure @bari12  I will wait for your PR then to get started.

**Comment by bari12** [comment]
The PR is added now. Let's wait a bit of some people have comments to the general structure etc. Once it is merged I think you can go through the github releases and generate the releases notes similar to the 3 I already created. (You can use the `tools/generate-release-notes <release> --rst` script for the rst output) - Thanks

**Comment by tushar-97** [comment]
When I run the script, it asks for a Github token file. How am I supposed to get that? From what I understand it is needed for authentication to use the Github API.

**Comment by mlassnig** [comment]
Go here and create a new one, and put it in the .githubtoken file ;-)

https://github.com/settings/tokens

**Comment by tushar-97** [comment]
Thanks @mlassnig it's working now.
@everyone If I understand the task correctly, I am to create rst files for ALL releases on https://github.com/rucio/rucio/releases? If so I should also club clients & webui releases in the same file. And do I create files for each milestone number or separate files for hotfix releases as well?

**Comment by bari12** [comment]
Yes essentially create one file for each release (including webui-only, client-only and hotfix releases). If you want you can create a subset of the files first and submit the PR so we can comment them; so you won't have to change all your files if there are some repeating issues. 😄

**Comment by tushar-97** [comment]
@bari12 @mlassnig @vingar I have added a few files via PR #946. Is the formatting correct? I wrote a small script to create these files. Also I am unable to generate release notes for tags of type *.post1. How do I proceed? Also the release-notes tool is not returning anything for releases like 1.14.10. Do I skip these or enter them manually?

**Comment by bari12** [comment]
Hi @tushar-97 The formatting is fine 👍 
Let me check what's broken with the release notes script.

**Comment by bari12** [comment]
Ah I just realised. For the releases where there was a hotfix release afterwards there are two releases in the repository (two tags). A normal one such as 1.14.10 and a .post1. However, there is only one milestone (the 1.14.9) - that's why the generate-release-notes script is not returning anything. In this case just ignore the hotfix (.post1) ones and just create the notes for the normal ones.
For certain release (client releases) - such as 1.14.10 there is also no milestone, these you can also ignore.

**Comment by tushar-97** [comment]
I added all the files but the travis-ci test has failed. I have no clue why that happened as I only added 12 rst files.

**Comment by bari12** [comment]
This is a problem on the current master. Once solved, a rebase will solve the errors on your PR as well.
