### ISSUE TITLE
Error while setting up Rucio demo environment

### ISSUE THREAD

**Issue by kiryteo** [rucio/rucio#929]
Motivation
----------
**Setting up Rucio demo environment**

I am trying to set up Rucio demo environment and following - http://rucio.readthedocs.io/installing_demo.html
I have docker compose tool and running the command - 
sudo docker-compose --file etc/docker/demo/docker-compose.yml up -d
gives the following error:

demo_mysql_1 is up-to-date
Starting demo_rucio_1 ... error

ERROR: for demo_rucio_1  Cannot start service rucio: driver failed programming external connectivity on endpoint demo_rucio_1 (55028af47bd18fa8197d2a0a45913b9cd661237bf85fb06ed2e6c96504db5dfa): Bind for 0.0.0.0:443 failed: port is already allocated

ERROR: for rucio  Cannot start service rucio: driver failed programming external connectivity on endpoint demo_rucio_1 (55028af47bd18fa8197d2a0a45913b9cd661237bf85fb06ed2e6c96504db5dfa): Bind for 0.0.0.0:443 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

I have docker installed : following is the 'docker version' output
https://pastebin.com/LX3fcRFT

I tried 'sudo netstat -ntpl | grep 443' , here is the output :
tcp6       0      0 :::443                  :::*                    LISTEN      3806/docker-proxy

I also tried 'lsof -i:443' ,
output : https://pastebin.com/59NGu8mn

Any plausible way to work this out.?

**Comment by vingar** [comment]
The port 443 is taken by the docker-proxy application. I didn't see that before for me. This application might be the rucio one actually. If not, one naive comment should be to stop the application taking the port 443. Did you try to list the running docker containers `docker ps` ? Maybe the rucio one has been already started which explains this conflict.

**Comment by tbeerman** [comment]
You could try changing the exposed port. Just change line 15 of `etc/docker/demo/docker-compose.yml` to something like:
`- 6443:443`

**Comment by tushar-97** [comment]
I faced the same problem yesterday. A simple `sudo service docker restart` worked for me.

**Comment by kiryteo** [comment]
I  used ```docker ps``` and found that other application was using the port 443. Stopping that app and restarting docker service resolved the issue. I did not try the option given by @tbeerman, but I think that would work too.  
Thank you all.
