### ISSUE TITLE
section policy/support/rucio_support missing in rucio.cfg template and tests

### ISSUE THREAD

**Issue by vingar** [rucio/rucio#976]
Modification
------------
```
[policy]
support=https://github.com/rucio/rucio/issues/new
support_rucio=https://github.com/rucio/rucio/issues/new
```
?

**Comment by mlassnig** [comment]
It's in both?

https://github.com/rucio/rucio/blob/master/etc/rucio.cfg.atlas.client.template

https://github.com/rucio/rucio/blob/master/etc/rucio.cfg.template

**Comment by vingar** [comment]
[...] tests
